### ISSUE TITLE
BUG: Log in with authentication enabled not working

### ISSUE THREAD

**Issue by AndiMajore** [xorbitsai/inference#1006]
### Describe the bug
I like the idea of the authentication system around the Xinference framework. Whenever it is enabled and I hand over a config.json file, as described in the documentation validation through the UI or CLI are not working and resulting in a 500 response.

On the server side, the following errors occur:

```
2024-02-15 12:25:09,638 xinference.api.restful_api 9 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/opt/conda/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/opt/conda/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 945, in cluster_login
    restful_client.login(username, password)
  File "/opt/conda/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 684, in login
    raise RuntimeError(f"Failed to login, detail: {response.json()['detail']}")
  File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/opt/conda/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 622, in model_launch
    client._set_token(get_stored_token(endpoint, client))
  File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 83, in get_stored_token
    raise RuntimeError("Cannot find access token, please login first!")
RuntimeError: Cannot find access token, please login first!
```

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version´: `Python 3.10.13`
2. The version of xinference you use: `0.8.4` because `0.8.5` introduces new issues for pytorch inference
3. Versions of crucial packages.
```
requests==2.31.0
click==8.1.7
simplejson==3.19.2
```

4. Expected behaviour:

I start Xinference using the following command and config.json to have a working auth system:

```bash
xinference-local -H 0.0.0.0 --auth-config config.json
```

This is the config.json file:

```json
{
    "auth_config": {
        "algorithm": "RS256",
        "secret_key": "589bb1092b6831b87a068f1a45868c80c1752f1c0b4714f0ad3dcb2f3b8d42b9",
        "token_expire_in_minutes": 180
    },
    "user_config": [
        {
            "username": "admin",
            "password": "test",
            "permissions": [ 
                "admin"
            ]
        },
        { 
            "username": "student",
            "password": "second_key",
            "permissions": [
                "models:list",
                "models:read"
            ]
        }
    ]
}
```

I tried login through UI and CLI:

```bash
xinference login -e $SERVER_NAME --username $ADMIN_USER --password $ADMIN_PASSWORD
```

**Comment by ChengjieLi28** [comment]
Hi, @AndiMajore . I debug your situation one step by one step. I found that If you replace your `algorithm` config with `HS256`, then everything works. 
It seems that your generated secret key does not match the algorithm `RS256`. Could you please tell us that what's your OS and how did you generate the secret key?

**Comment by ChengjieLi28** [comment]
Hi, @AndiMajore . I have updated our document. The core reason is that the `secret_key` is not generated in the same way if different algorithms need to be used.

**Comment by AndiMajore** [comment]
Hey, @ChengjieLi28. Thank you very much for that response. I will make sure to generate the key properly again and let you know about the result!

**Comment by AndiMajore** [comment]
Hey, @ChengjieLi28. Generating a new key in the same way but changing to `HS256` helped making the login from commandline and for the Python client work, or at least not break. When I now try to launch a model directly after i logged in it works for Python and also authentication through the web UI. Through commandline, it does give me an error still:

```bash

(base) root@df6d69022608:/opt/conda/lib/python3.9# xinference login -e http://localhost:9997 --username $ADMIN_USER --password $ADMIN_PASSWORD
(base) root@df6d69022608:/opt/conda/lib/python3.9# xinference launch --model-name llama-2-chat --size-in-billions 13 --model-format pytorch --quantization none  --n-gpu 1
Traceback (most recent call last):
  File "/opt/conda/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 622, in model_launch
    client._set_token(get_stored_token(endpoint, client))
  File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 83, in get_stored_token
    raise RuntimeError("Cannot find access token, please login first!")
RuntimeError: Cannot find access token, please login first!

```

**Comment by ChengjieLi28** [comment]
> Hey, @ChengjieLi28. Generating a new key in the same way but changing to `HS256` helped making the login from commandline and for the Python client work, or at least not break. When I now try to launch a model directly after i logged in it works for Python and also authentication through the web UI. Through commandline, it does give me an error still:
> 
> ```shell
> (base) root@df6d69022608:/opt/conda/lib/python3.9# xinference login -e http://localhost:9997 --username $ADMIN_USER --password $ADMIN_PASSWORD
> (base) root@df6d69022608:/opt/conda/lib/python3.9# xinference launch --model-name llama-2-chat --size-in-billions 13 --model-format pytorch --quantization none  --n-gpu 1
> Traceback (most recent call last):
>   File "/opt/conda/bin/xinference", line 8, in <module>
>     sys.exit(cli())
>   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 622, in model_launch
>     client._set_token(get_stored_token(endpoint, client))
>   File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 83, in get_stored_token
>     raise RuntimeError("Cannot find access token, please login first!")
> RuntimeError: Cannot find access token, please login first!
> ```

Please try to launch model using this command:
```
xinference launch -e http://localhost:9997 ...
```
In the cli, xinference stores the needed credentials(token) locally, distinguished by endpoint. For now, we do not recognize `localhost` as `127.0.0.1`. If you do not specify `-e` option, xinference uses `http://127.0.0.1:9997` by default.In the future, we can improve this.

**Comment by AndiMajore** [comment]
Perfect, works now! 
Thank you!
