### ISSUE TITLE
Failed to generate chat completion

### ISSUE THREAD

**Issue by JTed1997** [xorbitsai/inference#1018]
Describe the bug
启动大模型后生成回答时报错

To Reproduce
电脑: macbookair m2芯片
Your Python version 3.11.7
The version of xinference you use 0.8.5

Expected behavior
恳请帮忙看一下是什么原因导致的要如何解决🙏

Additional context

(llm_test) apple@appledeAir ~ % xinference
/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/xinference/deploy/cmdline.py:160: DeprecationWarning: Starting a local 'xinference' cluster via the 'xinference' command line is deprecated and will be removed in a future release. Please use the new 'xinference-local' command.
  warnings.warn(
2024-02-20 22:31:43,681 xinference.core.supervisor 63817 INFO     Xinference supervisor 127.0.0.1:27115 started
2024-02-20 22:31:43,696 xinference.core.worker 63817 INFO     Xinference worker 127.0.0.1:27115 started
2024-02-20 22:31:43,697 xinference.core.worker 63817 INFO     Purge cache directory: /Users/apple/.xinference/cache
2024-02-20 22:31:48,326 xinference.api.restful_api 63812 INFO     Starting Xinference at endpoint: http://127.0.0.1:9997
2024-02-20 22:35:29,304 xinference.model.llm.llm_family 63817 INFO     Caching from Modelscope: Shanghai_AI_Laboratory/internlm-chat-7b
2024-02-20 22:35:29,375 - modelscope - INFO - PyTorch version 2.2.0 Found.
2024-02-20 22:35:29,376 - modelscope - INFO - Loading ast index from /Users/apple/.cache/modelscope/ast_indexer
2024-02-20 22:35:29,465 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 02c07dc1f8a5008e3143e15834d372c5 and a total number of 964 components indexed
2024-02-20 22:35:30,449 xinference.model.llm.llm_family 63817 INFO     Cache /Users/apple/.xinference/cache/internlm-chat-7b-pytorch-7b exists
100%|███████████████████████████████████████████████████████████████████████████| 8/8 [00:42<00:00,  5.36s/it]
Traceback (most recent call last):
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/blocks.py", line 1608, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/blocks.py", line 1188, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/utils.py", line 639, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/chat_interface.py", line 487, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/utils.py", line 506, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/gradio/utils.py", line 489, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/xinference/core/chat_interface.py", line 123, in generate_wrapper
    for chunk in model.chat(
                 ^^^^^^^^^^^
  File "/Users/apple/anaconda3/envs/llm_test/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 392, in chat
    raise RuntimeError(
RuntimeError: Failed to generate chat completion, detail: 500 Server Error: Internal Server Error for url: http://127.0.0.1:9997/v1/chat/completions

**Comment by aresnow1** [comment]
我们尝试复现下

**Comment by codingl2k1** [comment]
Fixed by: https://github.com/xorbitsai/inference/pull/1008
