### ISSUE TITLE
BUG：got error when launch model with vllm-v0.3.2  in multiple GPU mode

### ISSUE THREAD

**Issue by onionknightdd** [xorbitsai/inference#1028]
### Describe the bug
In order to use Qwen1.5 with vllm  in xinferrence， i upgrade vllm from v0.3.0 to v0.3.2, bug got the following error messsage when launch model with multiple GPU:

**AssertionError: [address=0.0.0.0:10725, pid=58281] daemonic processes are not allowed to have children**
![image](https://github.com/xorbitsai/inference/assets/49679672/0f229d9c-20f8-407f-a674-a875f26c4a12)

but when change the num of GPU to 1 , it works fine

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.  --> python3.11
2. The version of xinference you use. --> v0.8.5
3. Versions of crucial packages. -->  vllm 0.3.2
4. Full stack of the error. --> AssertionError: [address=0.0.0.0:10725, pid=58281] daemonic processes are not allowed to have children
5. Minimized code to reproduce the error.  --> enable vllm and launch xinferrence -> choose 'qwen1.5-chat' -> choose pytorch format and n_gpu > launch model 

![image](https://github.com/xorbitsai/inference/assets/49679672/a89d1e33-e7dc-4960-b55f-a2fe52840555)

Not suer this bug related to the xinferrence of vllm

**Comment by aresnow1** [comment]
Seems is not compatible with latest vllm, v0.3.0 has suppoerted qwen 1.5 series, you can fix version for now.

**Comment by codingl2k1** [comment]
Confirmed that vllm==0.3.2 has this issue, the full traceback:

``` python
2024-02-22 06:33:22,982 xinference.api.restful_api 155837 ERROR    [address=0.0.0.0:33063, pid=156010] daemonic processes are not allowed to have children
Traceback (most recent call last):
  File "/home/codingl2k1/inference/xinference/api/restful_api.py", line 674, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/codingl2k1/inference/xinference/core/supervisor.py", line 772, in launch_builtin_model
    await _launch_model()
  File "/home/codingl2k1/inference/xinference/core/supervisor.py", line 736, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/home/codingl2k1/inference/xinference/core/supervisor.py", line 720, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/home/codingl2k1/inference/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/codingl2k1/inference/xinference/core/worker.py", line 549, in launch_builtin_model
    await model_ref.load()
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/home/codingl2k1/inference/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/home/codingl2k1/inference/xinference/model/llm/vllm/core.py", line 139, in load
    self._engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 625, in from_engine_args
    engine = cls(parallel_config.worker_use_ray,
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 321, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/engine/async_llm_engine.py", line 366, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 118, in __init__
    self._init_workers_ray(placement_group)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 286, in _init_workers_ray
    self._run_workers("init_model", cupy_port=get_open_port())
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/engine/llm_engine.py", line 1014, in _run_workers
    driver_worker_output = getattr(self.driver_worker,
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/worker/worker.py", line 94, in init_model
    init_distributed_environment(self.parallel_config, self.rank,
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/worker/worker.py", line 275, in init_distributed_environment
    cupy_utils.init_process_group(
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/vllm/model_executor/parallel_utils/cupy_utils.py", line 90, in init_process_group
    _NCCL_BACKEND = NCCLBackendWithBFloat16(world_size, rank, host, port)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/cupyx/distributed/_nccl_comm.py", line 70, in __init__
    self._init_with_tcp_store(n_devices, rank, host, port)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/cupyx/distributed/_nccl_comm.py", line 88, in _init_with_tcp_store
    self._store.run(host, port)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/cupyx/distributed/_store.py", line 100, in run
    p.start()
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/multiprocessing/process.py", line 118, in start
    assert not _current_process._config.get('daemon'), \
AssertionError: [address=0.0.0.0:33063, pid=156010] daemonic processes are not allowed to have children
```

**Comment by ye7love7** [comment]
v0.3.0到v0.3.3都不行。
