### ISSUE TITLE
在聊天页面发起对话报错！

### ISSUE THREAD

**Issue by ZanePoe** [xorbitsai/inference#1030]
### Describe the bug
在聊天页面发起对话报错：
![image](https://github.com/xorbitsai/inference/assets/16047426/962b4e35-0961-4a87-b169-6ab11d2f065a)
页面错误信息：
![image](https://github.com/xorbitsai/inference/assets/16047426/34a7390c-edf0-4b70-8e6c-86e998245d73)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. conda env python 3.11.
2. xinference 0.9.0.
操作系统：ubuntu22.04.
启动命令：
`userroot@userroot-PowerEdge-R730:~/data/workspace/xinference$ conda activate xinference
(xinference) userroot@userroot-PowerEdge-R730:~/data/workspace/xinference$ export XINFERENCE_MODEL_SRC=modelscope
(xinference) userroot@userroot-PowerEdge-R730:~/data/workspace/xinference$ export HF_ENDPOINT=https://hf-mirror.com
(xinference) userroot@userroot-PowerEdge-R730:~/data/workspace/xinference$ export XINFERENCE_HOME=/home/userroot/data/workspace/xinference/data
(xinference) userroot@userroot-PowerEdge-R730:~/data/workspace/xinference$ xinference-local --host 0.0.0.0 --port 9997
`
完整控制台日志：
`2024-02-22 23:25:24,195 xinference.core.supervisor 598042 INFO     Xinference supervisor 0.0.0.0:36500 started
2024-02-22 23:25:24,280 xinference.core.worker 598042 INFO     Starting metrics export server at 0.0.0.0:None
2024-02-22 23:25:24,283 xinference.core.worker 598042 INFO     Checking metrics export server...
2024-02-22 23:25:27,139 xinference.core.worker 598042 INFO     Metrics server is started at: http://0.0.0.0:43471
2024-02-22 23:25:27,141 xinference.core.worker 598042 INFO     Xinference worker 0.0.0.0:36500 started
2024-02-22 23:25:27,142 xinference.core.worker 598042 INFO     Purge cache directory: /home/userroot/data/workspace/xinference/data/cache
2024-02-22 23:25:31,378 xinference.api.restful_api 597805 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997
2024-02-22 23:26:08,124 xinference.model.llm.llm_family 598042 INFO     Caching from Modelscope: Xorbits/chatglm3-ggml
2024-02-22 23:26:08,211 - modelscope - INFO - PyTorch version 2.1.2 Found.
2024-02-22 23:26:08,212 - modelscope - INFO - Loading ast index from /home/userroot/data/workspace/xinference/data/modelscope/ast_indexer
2024-02-22 23:26:08,212 - modelscope - INFO - No valid ast index found from /home/userroot/data/workspace/xinference/data/modelscope/ast_indexer, generating ast index from prebuilt!
2024-02-22 23:26:08,279 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 35760808910f8c7dd4891d7620d98abb and a total number of 964 components indexed
Traceback (most recent call last):
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/blocks.py", line 1608, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/blocks.py", line 1188, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 639, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/chat_interface.py", line 487, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 506, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 489, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/chat_interface.py", line 115, in generate_wrapper
    client = RESTfulClient(self.endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 651, in __init__
    self._check_cluster_authenticated()
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 674, in _check_cluster_authenticated
    f"Failed to get cluster information, detail: {response.json()['detail']}"
                                                  ^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/queueing.py", line 495, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/route_utils.py", line 233, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/blocks.py", line 1608, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/blocks.py", line 1188, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 639, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/chat_interface.py", line 487, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 513, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 506, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 489, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/chat_interface.py", line 115, in generate_wrapper
    client = RESTfulClient(self.endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 651, in __init__
    self._check_cluster_authenticated()
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 674, in _check_cluster_authenticated
    f"Failed to get cluster information, detail: {response.json()['detail']}"
                                                  ^^^^^^^^^^^^^^^
  File "/home/userroot/miniconda3/envs/xinference/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by aresnow1** [comment]
升级下 gradio, fastapi 试一下

**Comment by ZanePoe** [comment]
升级gradio, fastapi没有作用

**Comment by ZanePoe** [comment]
使用python=3.10创建虚拟环境重新安装后，问题解决。

**Comment by Yuchen-ge** [comment]
同样踩坑，把proxy unset就行了

**Comment by PiPiNam** [comment]
> 升级下 gradio, fastapi 试一下

可是我看到xinference强制要求 fastapi==0.110.3，每次升级fastapi后就提示不兼容，这个怎么办？

我同样在内置的聊天页面测试Qwen2-instruct的时候也报错：
packages/xinference/model/llm/transformers/core.py", line 738, in chat
    assert self.model_family.chat_template is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
