### ISSUE TITLE
BUG请问我在安装pip install "xinference[all]"时出错

### ISSUE THREAD

**Issue by cq134cq** [xorbitsai/inference#1050]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Additional context
Building wheels for collected packages: chatglm-cpp, llama-cpp-python
  Building wheel for chatglm-cpp (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for chatglm-cpp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [90 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\convert.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\langchain_api.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\openai_api.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      copying chatglm_cpp\__init__.py -> build\lib.win-amd64-cpython-310\chatglm_cpp
      running egg_info
      writing chatglm_cpp.egg-info\PKG-INFO
      writing dependency_links to chatglm_cpp.egg-info\dependency_links.txt
      writing requirements to chatglm_cpp.egg-info\requires.txt
      writing top-level names to chatglm_cpp.egg-info\top_level.txt
      reading manifest file 'chatglm_cpp.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'chatglm_cpp.egg-info\SOURCES.txt'
      copying chatglm_cpp\_C.pyi -> build\lib.win-amd64-cpython-310\chatglm_cpp
      running build_ext
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:2 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.

      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "c:\soft\xx\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "c:\soft\xx\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\soft\xx\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 128, in <module>
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\normal\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 89, in run
          _build_ext.run(self)
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\sync\AppData\Local\Temp\pip-build-env-hb4md33m\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 121, in build_extension
        File "c:\soft\xx\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\sync\\AppData\\Local\\Temp\\pip-install-g0pweghw\\chatglm-cpp_8d18dfbf569743e38cf0507f7a670894', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\sync\\AppData\\Local\\Temp\\pip-install-g0pweghw\\chatglm-cpp_8d18dfbf569743e38cf0507f7a670894\\build\\lib.win-amd64-cpython-310\\chatglm_cpp\\', '-DPYTHON_EXECUTABLE=c:\\soft\\xx\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DCHATGLM_ENABLE_PYBIND=ON', '-DCHATGLM_ENABLE_EXAMPLES=OFF', '-DBUILD_SHARED_LIBS=OFF', '-A', 'x64', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\sync\\AppData\\Local\\Temp\\pip-install-g0pweghw\\chatglm-cpp_8d18dfbf569743e38cf0507f7a670894\\build\\lib.win-amd64-cpython-310\\chatglm_cpp']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chatglm-cpp
  Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      *** scikit-build-core 0.8.1 using CMake 3.28.3 (wheel)
      *** Configuring CMake...
      2024-02-28 17:12:23,211 - scikit_build_core - WARNING - Can't find a Python library, got libdir=None, ldlibrary=None, multiarch=None, masd=None
      loading initial cache file C:\Users\sync\AppData\Local\Temp\tmp9rdzwi9a\build\CMakeInit.txt
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:3 (project):
        Running

         'nmake' '-?'

        failed with:

         绯荤粺鎵句笉鍒版寚瀹氱殑鏂囦欢銆\x82

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!

      *** CMake configuration failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build chatglm-cpp llama-cpp-python
ERROR: Could not build wheels for chatglm-cpp, llama-cpp-python, which is required to install pyproject.toml-based projects
请问这是什么错误，应如何解决，我在conda下安装的

**Comment by ChengjieLi28** [comment]
@cq134cq .安装chatglm-cpp 和 llama-cpp-python时报错了。这两个库在window上安装需要正确的CMake编译环境，可以到对应的github repo中查询解决方案。

**Comment by cq134cq** [comment]
> window上安装需要正确的CMake编译环境

我是一个小白，请问window上安装需要正确的CMake编译环境装什么

**Comment by ChengjieLi28** [comment]
> > window上安装需要正确的CMake编译环境
> 
> 我是一个小白，请问window上安装需要正确的CMake编译环境装什么

https://github.com/abetlen/llama-cpp-python 对于llama-cpp-python，参考这个仓库的readme看下windows环境下需要什么条件。他这里也给出来一些错误的解决方案：
<img width="1223" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/248e6244-7750-4028-9425-93482c9c4d6f">
参考这些信息先尝试单独安装llama-cpp-python。

**Comment by shyp88** [comment]
这两个包直接pip大概率出错，可以用下面链接里的，找到自己对应版本，手动pip安装就行了，win和linux都适用，不需要再去弄cmake啥的。

https://github.com/li-plus/chatglm.cpp/releases

https://github.com/abetlen/llama-cpp-python/releases

**Comment by cq134cq** [comment]
> 己



> 这两个包直接pip大概率出错，可以用下面链接里的，找到自己对应版本，手动pip安装就行了，win和linux都适用，不需要再去弄cmake啥的。
> 
> https://github.com/li-plus/chatglm.cpp/releases
> 
> https://github.com/abetlen/llama-cpp-python/releases

谢谢

**Comment by leomsn** [comment]
wsl2 ubuntu 22.0.4遇到了一样的错误，去google了一些，可以这样解决这两的编译错误：

激活进入到你的conda环境里面(我用的是python3.10)后：
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt update
sudo apt install gcc-11 g++-11
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11
pip install --upgrade pip
pip install --upgrade setuptools wheel
sudo apt-get install build-essential

跑完这些，中间install那一步gcc-11没见装新版本，然后再跑pip install "xinference[all]"就正常通过了：
Building wheels for collected packages: chatglm-cpp, llama-cpp-python
  Building wheel for chatglm-cpp (pyproject.toml) ... done
  Created wheel for chatglm-cpp: filename=chatglm_cpp-0.3.1-cp310-cp310-linux_x86_64.whl size=825124 sha256=d79a39e161ba40d61f3bffa10d4864aa2e1579f3a8a41e137ee16eebbe9d8a01
  Stored in directory: /home/leo/.cache/pip/wheels/c2/d5/b5/013d7e9b0893e485df77a9eabb231d54a0e803438550f0d75c
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.2.62-cp310-cp310-manylinux_2_35_x86_64.whl size=3127781 sha256=2da1cc274937e433aad637621c260716b0156d1f210f788cde73cea5b9a79f12
  Stored in directory: /home/leo/.cache/pip/wheels/c0/81/de/d4cc8f152d89865379dbf28ca672358c667192ee55deaca7cb
Successfully built chatglm-cpp llama-cpp-python

**Comment by Zhenyi-Wang** [comment]
> wsl2 ubuntu 22.0.4遇到了一样的错误，去google了一些，可以这样解决这两的编译错误：
> 
> 激活进入到你的conda环境里面(我用的是python3.10)后： sudo add-apt-repository ppa:ubuntu-toolchain-r/test sudo apt update sudo apt install gcc-11 g++-11 sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 60 --slave /usr/bin/g++ g++ /usr/bin/g++-11 pip install --upgrade pip pip install --upgrade setuptools wheel sudo apt-get install build-essential
> 
> 跑完这些，中间install那一步gcc-11没见装新版本，然后再跑pip install "xinference[all]"就正常通过了： Building wheels for collected packages: chatglm-cpp, llama-cpp-python Building wheel for chatglm-cpp (pyproject.toml) ... done Created wheel for chatglm-cpp: filename=chatglm_cpp-0.3.1-cp310-cp310-linux_x86_64.whl size=825124 sha256=d79a39e161ba40d61f3bffa10d4864aa2e1579f3a8a41e137ee16eebbe9d8a01 Stored in directory: /home/leo/.cache/pip/wheels/c2/d5/b5/013d7e9b0893e485df77a9eabb231d54a0e803438550f0d75c Building wheel for llama-cpp-python (pyproject.toml) ... done Created wheel for llama-cpp-python: filename=llama_cpp_python-0.2.62-cp310-cp310-manylinux_2_35_x86_64.whl size=3127781 sha256=2da1cc274937e433aad637621c260716b0156d1f210f788cde73cea5b9a79f12 Stored in directory: /home/leo/.cache/pip/wheels/c0/81/de/d4cc8f152d89865379dbf28ca672358c667192ee55deaca7cb Successfully built chatglm-cpp llama-cpp-python

补充一下，我是同样的环境，按照这个操作之后还是报错，pip install llama-cpp-python --verbose打印出明细日志，发现是因为找不到 libgomp.so.1 库。解决方法如下：
```
# 安装
sudo apt-get update
sudo apt-get install libgomp1

# 添加环境变量（临时，永久的话加到~/.bashrc里）
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
```
再执行  pip install llama-cpp-python 测试，成功
