### ISSUE TITLE
Fail to launch built-in chatglm3-6b in 8bit.

### ISSUE THREAD

**Issue by FalconIA** [xorbitsai/inference#1108]
### Describe the bug
Fail to launch built-in chatglm3-6b in 8bit from ModelScope.

### To Reproduce
Deploy xinference by docker image under WSL2 and Docker Desktop v4.27.2.
Launch chatglm3-6b without quantization works well.
Launch qwen1.5-chat-7b in 8bit works well.

1. Python in docker image: `Python 3.10.13`
2. Docker Images version: `xprobe/xinference:v0.9.1`
3. GPU Info in docker image: 
```
root@485ab37eee38:/workspace# nvidia-smi
Sat Mar  9 10:42:15 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.10              Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        On  |   00000000:0B:00.0  On |                  N/A |
| 30%   39C    P8             32W /  350W |    1111MiB /  24576MiB |     18%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        On  |   00000000:0C:00.0 Off |                  N/A |
| 30%   39C    P8             26W /  350W |    1111MiB /  24576MiB |      9%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
root@485ab37eee38:/workspace# nvidia-smi nvlink -s
GPU 0: NVIDIA GeForce RTX 3090 (UUID: GPU-3d761d93-e4be-fdaf-f314-b3da9c94b7b8)
         Link 0: 14.062 GB/s
         Link 1: 14.062 GB/s
         Link 2: 14.062 GB/s
         Link 3: 14.062 GB/s
GPU 1: NVIDIA GeForce RTX 3090 (UUID: GPU-907b5464-99e5-7ae6-4317-1778bff7d577)
         Link 0: 14.062 GB/s
         Link 1: 14.062 GB/s
         Link 2: 14.062 GB/s
         Link 3: 14.062 GB/s
```
4. Full stack of the error.
```
2024-03-09 10:27:36,605 xinference.core.supervisor 53 DEBUG    Enter launch_builtin_model, model_uid: chatglm3-6b, model_name: chatglm3, model_size: 6, model_format: pytorch, quantization: 8-bit, replica: 1
2024-03-09 10:27:36,606 xinference.core.worker 53 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7f7deb5acb80>,), kwargs: {}
2024-03-09 10:27:36,606 xinference.core.worker 53 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-03-09 10:27:36,606 xinference.core.worker 53 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7f7deb5acb80>,), kwargs: {'model_uid': 'chatglm3-6b-1-0', 'model_name': 'chatglm3', 'model_size_in_billions': 6, 'model_format': 'pytorch', 'quantization': '8-bit', 'model_type': 'LLM', 'n_gpu': 'auto', 'request_limits': None}
2024-03-09 10:27:36,607 xinference.core.worker 53 DEBUG    GPU selected: [0] for model chatglm3-6b-1-0
2024-03-09 10:27:42,456 xinference.model.llm.llm_family 53 INFO     Caching from Modelscope: ZhipuAI/chatglm3-6b
2024-03-09 10:27:42,462 xinference.model.llm.llm_family 53 INFO     Cache /root/.xinference/cache/chatglm3-pytorch-6b exists
2024-03-09 10:27:42,462 xinference.model.llm.core 53 DEBUG    Launching chatglm3-6b-1-0 with ChatglmPytorchChatModel
The `load_in_4bit` and `load_in_8bit` arguments are deprecated and will be removed in the future versions. Please, pass a `BitsAndBytesConfig` object in `quantization_config` argument instead.
Loading checkpoint shards:   0%|                         | 0/7 [00:00<?, ?it/s]/opt/conda/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards:   0%|                         | 0/7 [00:19<?, ?it/s]
2024-03-09 10:28:05,472 xinference.core.worker 53 ERROR    Failed to load model chatglm3-6b-1-0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 553, in launch_builtin_model
    await model_ref.load()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 202, in load
    self._model, self._tokenizer = self._load_model(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/chatglm.py", line 70, in _load_model
    model = AutoModel.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3926, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 802, in _load_state_dict_into_meta_model
    or (not hf_quantizer.check_quantized_param(model, param, param_name, state_dict))
  File "/opt/conda/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_8bit.py", line 142, in check_quantized_param
    if isinstance(module._parameters[tensor_name], bnb.nn.Int8Params):
KeyError: [address=0.0.0.0:41195, pid=380] 'inv_freq'
2024-03-09 10:28:05,599 xinference.core.supervisor 53 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f7deb5acbd0>, 'chatglm3-6b'), kwargs: {'suppress_exception': True}
2024-03-09 10:28:05,599 xinference.core.supervisor 53 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-03-09 10:28:05,603 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:41195, pid=380] 'inv_freq'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py", line 678, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 797, in launch_builtin_model
    await _launch_model()
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 761, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 745, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 553, in launch_builtin_model
    await model_ref.load()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 202, in load
    self._model, self._tokenizer = self._load_model(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/chatglm.py", line 70, in _load_model
    model = AutoModel.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3502, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3926, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/opt/conda/lib/python3.10/site-packages/transformers/modeling_utils.py", line 802, in _load_state_dict_into_meta_model
    or (not hf_quantizer.check_quantized_param(model, param, param_name, state_dict))
  File "/opt/conda/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_8bit.py", line 142, in check_quantized_param
    if isinstance(module._parameters[tensor_name], bnb.nn.Int8Params):
KeyError: [address=0.0.0.0:41195, pid=380] 'inv_freq'
```

### Expected behavior
Expect to launch chatglm3-6b in 8bit.

**Comment by ChengjieLi28** [comment]
@FalconIA Refer to https://github.com/hiyouga/LLaMA-Factory/issues/2554. You need to downgrade your `transformers` version to `4.37.2`.

**Comment by FalconIA** [comment]
@ChengjieLi28 Thanks a lot.

However, I am using a Docker Image (`xprobe/xinference:v0.9.1`), and it is troublesome to downgrade `transformers` to `4.37.2` using pip.
I should make a new Docker Image manually to solve this issue, thank you any way.
