### ISSUE TITLE
BUG：中止流式对话后，后段报错：parallel generation is not supported by ggml

### ISSUE THREAD

**Issue by linhao622** [xorbitsai/inference#1123]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. python 3.10.12
2. xinference 0.9.1
3. 报错模块：llama_cpp
4.报错信息
 2024-03-11 16:48:57,966 xinference.api.restful_api 82169 ERROR    Chat completion stream got an error: [address=127.0.0.1:59145, pid=82249] Parallel generation is not supported by ggml.
Traceback (most recent call last):
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1267, in stream_results
    iterator = await model.chat(
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/model.py", line 79, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/model.py", line 370, in chat
    response = await self._call_wrapper(
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/model.py", line 103, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/model.py", line 336, in _call_wrapper
    raise Exception("Parallel generation is not supported by ggml.")
Exception: [address=127.0.0.1:59145, pid=82249] Parallel generation is not supported by ggml.
5. Minimized code to reproduce the error.

### Additional context
复现步骤：
1、启动一个使用llama-cpp推理的gguf模型（本例：qwen1.5-14b-chat-gguf）
2、使用curl或者python来调用对话（stream=True）
3、在生成过程中中止（ctrl+C）
4、后续再发一个新请求报错：parallel generation is not supported by ggml
导致无法处理后续的请求

**Comment by qinxuye** [comment]
关于支持中断，我开了个 issue #1124 .
