### ISSUE TITLE
在启动bge-reranker-bas时出错

### ISSUE THREAD

**Issue by cq134cq** [xorbitsai/inference#1133]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.   3.10
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Additional context
(c:\soft\xx) C:\soft\xx>xinference-local --host 10.0.100.100 --port 9997
2024-03-12 15:22:26,368 xinference.core.supervisor 1544 INFO     Xinference supervisor 10.0.100.100:35701 started
2024-03-12 15:22:26,414 xinference.core.worker 1544 INFO     Starting metrics export server at 10.0.100.100:None
2024-03-12 15:22:26,429 xinference.core.worker 1544 INFO     Checking metrics export server...
2024-03-12 15:22:31,851 xinference.core.worker 1544 INFO     Metrics server is started at: http://10.0.100.100:50596
2024-03-12 15:22:31,851 xinference.core.worker 1544 INFO     Xinference worker 10.0.100.100:35701 started
2024-03-12 15:22:31,851 xinference.core.worker 1544 INFO     Purge cache directory: C:\Users\vip\.xinference\cache
2024-03-12 15:22:34,306 xinference.api.restful_api 10272 INFO     Starting Xinference at endpoint: http://10.0.100.100:9997
2024-03-12 15:23:43,152 xinference.model.utils 1544 INFO     Use model cache from a different hub.
2024-03-12 15:23:45,742 xinference.core.worker 1544 ERROR    Failed to load model bge-reranker-base-1-0
Traceback (most recent call last):
  File "c:\soft\xx\lib\site-packages\xinference\core\worker.py", line 569, in launch_builtin_model
    await model_ref.load()
  File "c:\soft\xx\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "c:\soft\xx\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "c:\soft\xx\lib\site-packages\xoscar\backends\pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "c:\soft\xx\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "c:\soft\xx\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "c:\soft\xx\lib\site-packages\xinference\core\model.py", line 239, in load
    self._model.load()
  File "c:\soft\xx\lib\site-packages\xinference\model\rerank\core.py", line 124, in load
    self._model = CrossEncoder(
  File "c:\soft\xx\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 77, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name, revision=revision, **tokenizer_args)
  File "c:\soft\xx\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 825, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "c:\soft\xx\lib\site-packages\transformers\tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "c:\soft\xx\lib\site-packages\transformers\tokenization_utils_base.py", line 2287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "c:\soft\xx\lib\site-packages\transformers\models\xlm_roberta\tokenization_xlm_roberta_fast.py", line 155, in __init__
    super().__init__(
  File "c:\soft\xx\lib\site-packages\transformers\tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "c:\soft\xx\lib\site-packages\transformers\convert_slow_tokenizer.py", line 1510, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "c:\soft\xx\lib\site-packages\transformers\convert_slow_tokenizer.py", line 536, in __init__
    requires_backends(self, "protobuf")
  File "c:\soft\xx\lib\site-packages\transformers\utils\import_utils.py", line 1318, in requires_backends
    raise ImportError("".join(failed))
ImportError: [address=10.0.100.100:50614, pid=11864]
XLMRobertaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.

2024-03-12 15:23:45,898 xinference.api.restful_api 10272 ERROR    [address=10.0.100.100:50614, pid=11864]
XLMRobertaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.
Traceback (most recent call last):
  File "c:\soft\xx\lib\site-packages\xinference\api\restful_api.py", line 689, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "c:\soft\xx\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "c:\soft\xx\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "c:\soft\xx\lib\site-packages\xoscar\backends\pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "c:\soft\xx\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "c:\soft\xx\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "c:\soft\xx\lib\site-packages\xinference\core\supervisor.py", line 803, in launch_builtin_model
    await _launch_model()
  File "c:\soft\xx\lib\site-packages\xinference\core\supervisor.py", line 767, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "c:\soft\xx\lib\site-packages\xinference\core\supervisor.py", line 748, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "c:\soft\xx\lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "c:\soft\xx\lib\site-packages\xinference\core\worker.py", line 569, in launch_builtin_model
    await model_ref.load()
  File "c:\soft\xx\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "c:\soft\xx\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "c:\soft\xx\lib\site-packages\xoscar\backends\pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "c:\soft\xx\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "c:\soft\xx\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "c:\soft\xx\lib\site-packages\xinference\core\model.py", line 239, in load
    self._model.load()
  File "c:\soft\xx\lib\site-packages\xinference\model\rerank\core.py", line 124, in load
    self._model = CrossEncoder(
  File "c:\soft\xx\lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 77, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(model_name, revision=revision, **tokenizer_args)
  File "c:\soft\xx\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 825, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "c:\soft\xx\lib\site-packages\transformers\tokenization_utils_base.py", line 2048, in from_pretrained
    return cls._from_pretrained(
  File "c:\soft\xx\lib\site-packages\transformers\tokenization_utils_base.py", line 2287, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "c:\soft\xx\lib\site-packages\transformers\models\xlm_roberta\tokenization_xlm_roberta_fast.py", line 155, in __init__
    super().__init__(
  File "c:\soft\xx\lib\site-packages\transformers\tokenization_utils_fast.py", line 114, in __init__
    fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)
  File "c:\soft\xx\lib\site-packages\transformers\convert_slow_tokenizer.py", line 1510, in convert_slow_tokenizer
    return converter_class(transformer_tokenizer).converted()
  File "c:\soft\xx\lib\site-packages\transformers\convert_slow_tokenizer.py", line 536, in __init__
    requires_backends(self, "protobuf")
  File "c:\soft\xx\lib\site-packages\transformers\utils\import_utils.py", line 1318, in requires_backends
    raise ImportError("".join(failed))
ImportError: [address=10.0.100.100:50614, pid=11864]
XLMRobertaConverter requires the protobuf library but it was not found in your environment. Checkout the instructions on the
installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
that match your environment. Please note that you may need to restart your runtime after installation.

**Comment by qinxuye** [comment]
你这个是依赖问题吧，XLMRobertaConverter 要求 protobuf，但没找到。

**Comment by cq134cq** [comment]
> 你这个是依赖问题吧，XLMRobertaConverter 要求 protobuf，但没找到。

那就当如何安装？
