### ISSUE TITLE
BUG:运行bge-large-zh-v1.5报错

### ISSUE THREAD

**Issue by HelloEveryonehh** [xorbitsai/inference#1139]
### Describe the bug
运行bge-large-zh-v1.5报错

### To Reproduce
To help us to reproduce this bug, please provide information below:
1. Your Python version:3.10.8
3. The version of xinference you use:latest
4. Versions of crucial packages:
5. Full stack of the error
```
2024-03-13 10:33:29,398 xinference.api.restful_api 2580 ERROR    [address=0.0.0.0:41333, pid=2762] 'EmbeddingModel' object has no attribute 'model_spec'
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1288, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/model.py", line 79, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/model.py", line 379, in chat
    raise AttributeError(f"Model {self._model.model_spec} is not for chat.")
AttributeError: [address=0.0.0.0:41333, pid=2762] 'EmbeddingModel' object has no attribute 'model_spec'
```
7. Minimized code to reproduce the error.
直接运行bge-large-zh-v1.5，然后请求就会报错

**Comment by qinxuye** [comment]
你是如何运行的？

**Comment by HelloEveryonehh** [comment]
> 你是如何运行的？

你好，我是使用xinference的UI来运行的，然后在one-api上自定义模型，然后调用one-api去请求这个向量模型，然后就报错了

**Comment by qinxuye** [comment]
我看你走到了 chat 的接口，embedding 模型不能走 chat。

**Comment by HelloEveryonehh** [comment]
好的，经过排查是下游调用的问题，感谢

**Comment by LIKEGAKKI** [comment]
> 好的，经过排查是下游调用的问题，感谢

你好，请问你是怎么解决的？

**Comment by HelloEveryonehh** [comment]
我卸载以后，重装这个库



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月23日(周二) 上午9:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [xorbitsai/inference] BUG:运行bge-large-zh-v1.5报错 (Issue #1139)




  
好的，经过排查是下游调用的问题，感谢
  
你好，请问你是怎么解决的？

**Comment by seanzhang-zhichen** [comment]
> 好的，经过排查是下游调用的问题，感谢

我也碰到了这个问题，请问是重装xinference吗？

**Comment by xiusidunhuren** [comment]
请问怎么弄好的，重装了哪个库啊？

**Comment by HelloEveryonehh** [comment]
就是重装了这个项目，你用pip卸载再重装试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月24日(周五) 上午8:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [xorbitsai/inference] BUG:运行bge-large-zh-v1.5报错 (Issue #1139)




 
请问怎么弄好的，重装了哪个库啊？

**Comment by xiyao23** [comment]
我和你一样的问题，但是我重装了xinference还是不行，难道不是oneapi调错接口了吗，能帮忙详细说说怎么解决的吗，谢谢

**Comment by xiyao23** [comment]
你的意思是可以接入正常用，但是不能测试对吗，我上游用的fastgpt



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年09月25日 15:50 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xorbitsai/inference] BUG:运行bge-large-zh-v1.5报错 (Issue #1139) |

one-api不能对embeding模型进行测试，测试就报错，智能对chat模型测试，不用管就好
