### ISSUE TITLE
BUG vllm加载Yi-34B-Chat-4bits对接fastgpt对话出错（单轮对话）

### ISSUE THREAD

**Issue by leoterry-ulrica** [xorbitsai/inference#1153]
启动：
`xinference launch --model-name Yi-34B-Chat-4bits --model-uid Yi-34B-Chat-4bits --endpoint "http://127.0.0.1:6006" --quantization Int4 --model-format awq --size-in-billions 34 --gpu_memory_utilization 0.85 --max_model_len 4096`

问题：
```
原问题: 你是谁\n检索词: <|im_end|>\n<|im_start|>assistant\n', prefix_pos: None,sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.01, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|endoftext|>', '<|im_start|>', '<|im_end|>', '<|im_sep|>'], stop_token_ids=[2, 6, 7, 8], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: None, lora_request: None.
INFO 03-17 00:26:10 async_llm_engine.py:133] Aborted request e555ba2a-e3b1-11ee-8bbb-0242ac11000d.
2024-03-17 00:26:10,030 xinference.api.restful_api 4088 ERROR    [address=0.0.0.0:36103, pid=4435] Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.
Traceback (most recent call last):
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1389, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/core/model.py", line 79, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/core/model.py", line 375, in chat
    response = await self._call_wrapper(
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/core/model.py", line 103, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/core/model.py", line 325, in _call_wrapper
    ret = await fn(*args, **kwargs)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 426, in async_chat
    c = await self.async_generate(full_prompt, generate_config)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 338, in async_generate
    async for request_output in results_generator:
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 577, in generate
    raise e
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 571, in generate
    async for request_output in stream:
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 69, in __anext__
    raise result
  File "/root/miniconda3/envs/xin/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 38, in _raise_exception_on_finish
    raise exc
  File "/root/miniconda3/envs/xin/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 33, in _raise_exception_on_finish
    raise AsyncEngineDeadError(
vllm.engine.async_llm_engine.AsyncEngineDeadError: [address=0.0.0.0:36103, pid=4435] Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.

```

**Comment by leoterry-ulrica** [comment]
> 我觉得这应该是vllm的问题，是不是显存不够了

但单独用vLLM来启动模型，它是可以的。

**Comment by qinxuye** [comment]
> > 我觉得这应该是vllm的问题，是不是显存不够了
> 
> 显存不够，应该会抛OOM之类的错误，单纯从这个错误信息看不出是OOM。单独用vLLM来启动模型，它是可以的。

选项一致吗？

**Comment by leoterry-ulrica** [comment]
> > 我觉得这应该是vllm的问题，是不是显存不够了
> 
> 显存不够，应该会抛OOM之类的错误，单纯从这个错误信息看不出是OOM。单独用vLLM来启动模型，它是可以的。

```
docker run -d --restart always --gpus all -v ./llm/models:/root/.cache/huggingface -e MODEL=/root/.cache/huggingface -p 6006:8000 --name vllm vllm/vllm-openai:latest --model /root/.cache/huggingface/Yi-34B-Chat-4bits --gpu-memory-utilization 0.85 --max-model-len 8192 --quantization awq --served-model-name Yi-34B-Chat-4bits
```

**Comment by leoterry-ulrica** [comment]
> > > 我觉得这应该是vllm的问题，是不是显存不够了
> > 
> > 
> > 显存不够，应该会抛OOM之类的错误，单纯从这个错误信息看不出是OOM。单独用vLLM来启动模型，它是可以的。
> 
> 选项一致吗？

一样的
```
docker run -d --restart always --gpus all -v ./llm/models:/root/.cache/huggingface -e MODEL=/root/.cache/huggingface -p 6006:8000 --name vllm vllm/vllm-openai:latest --model /root/.cache/huggingface/Yi-34B-Chat-4bits --gpu-memory-utilization 0.85 --max-model-len 8192 --quantization awq --served-model-name Yi-34B-Chat-4bits
```

**Comment by qinxuye** [comment]
有没有可能是 vllm 版本问题，比如比较新加入的 cuda graph 会更吃显存之类的。
