### ISSUE TITLE
'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence

### ISSUE THREAD

**Issue by xxch** [xorbitsai/inference#1163]
` File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
     File "D:\Anconda\envs\xinfTrans\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence`
启动的时候报错。环境：window11、cuda12、

**Comment by xxch** [comment]
我只能修改pathlib.py中的代码，with self.open(mode='r', encoding='utf-8', errors=errors) as f:
            return f.read()   但是不应该直接修改，还是哪里应该有问题

**Comment by qinxuye** [comment]
完整的栈有么？看上去是 Gradio 报出来的错误。

**Comment by xxch** [comment]
`2024-03-20 14:11:08,211 xinference.core.worker 19820 INFO     Purge cache directory: E:\bigModel\cache
Traceback (most recent call last):
  File "D:\Anconda\envs\xinfTrans\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anconda\envs\xinfTrans\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Anconda\envs\xinfTrans\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\xinference\deploy\cmdline.py", line 225, in local
    start_local_cluster(
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\xinference\deploy\cmdline.py", line 112, in start_local_cluster
    main(
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\xinference\deploy\local.py", line 125, in main
    from ..api import restful_api
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\xinference\api\restful_api.py", line 27, in <module>
    import gradio as gr
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\_simple_templates\__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\_simple_templates\simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\components\__init__.py", line 40, in <module>
    from gradio.components.multimodal_textbox import MultimodalTextbox
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\components\multimodal_textbox.py", line 28, in <module>
    class MultimodalTextbox(FormComponent):
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\component_meta.py", line 198, in __new__
    create_or_modify_pyi(component_class, name, events)
  File "D:\Anconda\envs\xinfTrans\lib\site-packages\gradio\component_meta.py", line 92, in create_or_modify_pyi
    source_code = source_file.read_text()
  File "D:\Anconda\envs\xinfTrans\lib\pathlib.py", line 1135, in read_text
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb2 in position 1972: illegal multibyte sequence`

**Comment by yhfgyyf** [comment]
原因是4.22版本gradio的multimodal_textbox.py 和multimodal_textbox.pyi两个文件的编码格式为MacRoman，不是ascii，把文件编码格式转下后bug修复 。
可以用以下代码转：
source_file 填multimodal_textbox.py 和multimodal_textbox.pyi的文件路径。
```
source_file = 'path to multimodal_textbox.py /multimodal_textbox.pyi'
with open(source_file, 'r', encoding='mac_roman') as source_file:
    content = source_file.read()

ascii_content = content.encode('ascii', errors='replace').decode('ascii')

with open(source_file, 'w', encoding='ascii') as target_file:
    target_file.write(ascii_content)
```

**Comment by knightcn1983** [comment]
根据官方维护群“yang”网友的解答，问题出在“4.22版本gradio的multimodal_textbox.py 和multimodal_textbox.pyi两个文件的编码格式为MacRoman，不是ascii，把文件编码格式转下后bug修复”，安装完xinference后，直接输入“ pip install gradio==4.21.0",把gradio降级后，程序运行正常

**Comment by yhfgyyf** [comment]
> 根据官方维护群“yang”网友的解答，问题出在“4.22版本gradio的multimodal_textbox.py 和multimodal_textbox.pyi两个文件的编码格式为MacRoman，不是ascii，把文件编码格式转下后bug修复”，安装完xinference后，直接输入“ pip install gradio==4.21.0",把gradio降级后，程序运行正常
~~~~

那就是我，最近写代码正好用到gradio库，我自己的4.19.2版本没问题，另一个人的4.22版本就有问题，开始也是换了版本后解决问题。
Windows上xinference也出现问题，就查了下代码，发现组件目录中就这两个新文件的编码不一样。
