### ISSUE TITLE
在创建一个新的本地模型到xinference  web Ui 界面进行启动的时候会报错误启动不了

### ISSUE THREAD

**Issue by Joker-sad** [xorbitsai/inference#1172]
Note that the issue tracker is NOT the place for general support.
 File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/deploy/cmdline.py", line 692, in model_launch
    model_uid = client.launch_model(
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 863, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:38951, pid=2310079] 'list' object has no attribute 'as_dict'

**Comment by hainaweiben** [comment]
可以发一下完整的日志文件吗？

**Comment by Joker-sad** [comment]
Traceback (most recent call last):
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/api/restful_api.py", line 722, in launch_model
    try:
         
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 796, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 760, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 741, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/worker.py", line 569, in launch_builtin_model
    await model_ref.load()
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 239, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 222, in load
    self._model, self._tokenizer = self._load_model(**kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 110, in _load_model
    model = AutoModelForCausalLM.from_pretrained(
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 556, in from_pretrained
    return model_class.from_pretrained(
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/.cache/huggingface/modules/transformers_modules/Baichuan2-13B-Chat-4bits/modeling_baichuan.py", line 666, in from_pretrained
    dispatch_model(model, device_map=device_map)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/accelerate/big_modeling.py", line 349, in dispatch_model
    check_device_map(model, device_map)
      ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 1283, in check_device_map
    all_model_tensors = [name for name, _ in model.state_dict().items()]
      ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1897, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1897, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1897, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
    ^^^^^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1894, in state_dict
    self._save_to_state_dict(destination, prefix, keep_vars)
    ^^^^^^^^^^^^^^^^^
  File "/home/ps/anaconda3/envs/xinference/lib/python3.11/site-packages/bitsandbytes/nn/modules.py", line 237, in _save_to_state_dict
    for k, v in self.weight.quant_state.as_dict(packed=True).items():
    ^^^^^^^^^^^^^^^^^
AttributeError: [address=0.0.0.0:38951, pid=2310079] 'list' object has no attribute 'as_dict'

完整的日志

**Comment by hainaweiben** [comment]
#275 你可以参考这个回答

**Comment by hainaweiben** [comment]
[参考这个链接](https://github.com/baichuan-inc/Baichuan2/issues/275)

**Comment by Joker-sad** [comment]
谢谢哥

**Comment by hainaweiben** [comment]
close issue

**Comment by zhangfhe** [comment]
How can this problem be solved?
the Engine core initialization failed. See root cause above. Failed core proc(s): {}
