### ISSUE TITLE
Download bge-reranker-large always failure in docker container 

### ISSUE THREAD

**Issue by jackleeforce** [xorbitsai/inference#1185]
### Describe the bug
I try download `bge-reranker-large` in the latest version of docker, but it always failure.

### To Reproduce
To help us to reproduce this bug, please provide information below:

- docker image: xprobe/xinference           
- docker tag: latest-cpu   
- image id: 0c26a84a9d0f

### Expected behavior
Model download successful.

### Additional context
```log
2024-03-25 06:56:57,598 xinference.core.supervisor 72 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f9e8c8ae7b0>, 'LLM'), kwargs: {'detailed': True}
2024-03-25 06:56:57,638 xinference.core.supervisor 72 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-03-25 06:56:59,402 xinference.core.supervisor 72 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f9e8c8ae7b0>, 'rerank'), kwargs: {'detailed': True}
2024-03-25 06:56:59,403 xinference.core.supervisor 72 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-03-25 06:57:01,519 xinference.core.supervisor 72 DEBUG    Enter launch_builtin_model, model_uid: bge-reranker-large, model_name: bge-reranker-large, model_size: , model_format: None, quantization: None, replica: 1
2024-03-25 06:57:01,520 xinference.core.worker 72 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7f9f538f85f0>,), kwargs: {}
2024-03-25 06:57:01,520 xinference.core.worker 72 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-03-25 06:57:01,520 xinference.core.worker 72 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7f9f538f85f0>,), kwargs: {'model_uid': 'bge-reranker-large-1-0', 'model_name': 'bge-reranker-large', 'model_size_in_billions': None, 'model_format': None, 'quantization': None, 'model_type': 'rerank', 'n_gpu': 'auto', 'request_limits': None, 'peft_model_path': None, 'image_lora_load_kwargs': None, 'image_lora_fuse_kwargs': None}
Fetching 8 files:  38%|███▊      | 3/8 [00:05<00:09,  1.86s/it]
2024-03-25 06:57:10,611 xinference.model.utils 72 DEBUG    Download failed: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 8c0dbd58-6e67-4bca-aff7-1fadbacdc18c)'), download func: <function snapshot_download at 0x7f9f52f0ca40>, download args: ('BAAI/bge-reranker-large',), kwargs: {'revision': '27c9168d479987529781de8474dff94d69beca11', 'local_dir': '/xinference/cache/bge-reranker-large', 'local_dir_use_symlinks': True}
2024-03-25 06:57:10,611 xinference.model.utils 72 WARNING  Attempt 1 failed. Remaining attempts: 2
Fetching 8 files:  38%|███▊      | 3/8 [00:21<00:36,  7.22s/it]
2024-03-25 06:57:32,892 xinference.model.utils 72 DEBUG    Download failed: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: 0e4553a4-07d8-4f1d-be37-d2eafa9ac8a5)'), download func: <function snapshot_download at 0x7f9f52f0ca40>, download args: ('BAAI/bge-reranker-large',), kwargs: {'revision': '27c9168d479987529781de8474dff94d69beca11', 'local_dir': '/xinference/cache/bge-reranker-large', 'local_dir_use_symlinks': True}
2024-03-25 06:57:32,892 xinference.model.utils 72 WARNING  Attempt 2 failed. Remaining attempts: 1
Fetching 8 files:  38%|███▊      | 3/8 [00:00<00:00,  5.02it/s]
2024-03-25 06:57:48,012 xinference.model.utils 72 DEBUG    Download failed: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: b3c9a531-55bc-43cc-9acb-688d1fd9e257)'), download func: <function snapshot_download at 0x7f9f52f0ca40>, download args: ('BAAI/bge-reranker-large',), kwargs: {'revision': '27c9168d479987529781de8474dff94d69beca11', 'local_dir': '/xinference/cache/bge-reranker-large', 'local_dir_use_symlinks': True}
2024-03-25 06:57:48,012 xinference.model.utils 72 WARNING  Attempt 3 failed. Remaining attempts: 0
2024-03-25 06:57:48,012 xinference.core.worker 72 ERROR    Failed to load model bge-reranker-large-1-0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/opt/conda/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/opt/conda/lib/python3.11/ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 89, in retry_download
    return download_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 308, in snapshot_download
    thread_map(
  File "/opt/conda/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 69, in thread_map
    return _executor_map(ThreadPoolExecutor, fn, *iterables, **tqdm_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/tqdm/contrib/concurrent.py", line 51, in _executor_map
    return list(tqdm_class(ex.map(fn, *iterables, chunksize=chunksize), **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 283, in _inner_hf_hub_download
    return hf_hub_download(
           ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1492, in hf_hub_download
    http_get(
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 471, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), '(Request ID: b3c9a531-55bc-43cc-9acb-688d1fd9e257)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 543, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 100, in create_model_instance
    return create_rerank_model_instance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/rerank/core.py", line 222, in create_rerank_model_instance
    model_path = cache(model_spec)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/rerank/core.py", line 180, in cache
    return cache(model_spec, RerankModelDescription)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 316, in cache
    retry_download(
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 118, in retry_download
    raise RuntimeError(
RuntimeError: Failed to download model 'bge-reranker-large' after multiple retries
2024-03-25 06:57:48,035 xinference.core.supervisor 72 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f9e8c8ae7b0>, 'bge-reranker-large'), kwargs: {'suppress_exception': True}
2024-03-25 06:57:48,035 xinference.core.supervisor 72 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-03-25 06:57:48,038 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:17215, pid=72] Failed to download model 'bge-reranker-large' after multiple retries
requests.exceptions.ConnectionError: [Errno ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))] (Request ID: b3c9a531-55bc-43cc-9acb-688d1fd9e257)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/api/restful_api.py", line 723, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 796, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 760, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 741, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 543, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 100, in create_model_instance
    return create_rerank_model_instance(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/rerank/core.py", line 222, in create_rerank_model_instance
    model_path = cache(model_spec)
      ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/rerank/core.py", line 180, in cache
    return cache(model_spec, RerankModelDescription)
      ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 316, in cache
    retry_download(
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 118, in retry_download
    raise RuntimeError(
    ^^^^^^^^^^^^^^^^^
RuntimeError: [address=0.0.0.0:17215, pid=72] Failed to download model 'bge-reranker-large' after multiple retries
```

**Comment by qinxuye** [comment]
Looks like network issue.

**Comment by jackleeforce** [comment]
seems this cause by network issue indeed, issue close.
