### ISSUE TITLE
RuntimeError: [address=172.31.76.184:9999, pid=15] No available worker found

### ISSUE THREAD

**Issue by JoshuaAndrew** [xorbitsai/inference#1193]
### Describe the bug
```
2024-03-27 05:11:36,541 xinference.api.restful_api 1 ERROR    [address=172.31.76.184:9999, pid=15] No available worker found
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/api/restful_api.py", line 591, in _get_devices_count
    data = await (await self._get_supervisor_ref()).get_devices_count()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 261, in get_devices_count
    worker_ref = await self._choose_worker()
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 282, in _choose_worker
    raise RuntimeError("No available worker found")
    ^^^^^^^^^^^^^^^^^
RuntimeError: [address=172.31.76.184:9999, pid=15] No available worker found
```

![image](https://github.com/xorbitsai/inference/assets/12997509/3f006f97-ee24-4cf4-a5c0-ee1c451a06f6)

### To Reproduce
`
curl  http://10.97.207.212:9997/v1/cluster/devices 
`

![image](https://github.com/xorbitsai/inference/assets/12997509/51680cb3-216b-4311-b603-c3194eee05f7)

xinference-supervisor:
![image](https://github.com/xorbitsai/inference/assets/12997509/038f11e1-78cc-41ec-bc10-8035145464dc)

xinference-worker:
![image](https://github.com/xorbitsai/inference/assets/12997509/07d4d71c-f0d2-4687-b143-84f9b395a918)

k8s service: 
```
apiVersion: v1
kind: Service
metadata:
  name: xinference
  namespace: xinference
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9997
      protocol: TCP
      targetPort: web
    - name: http
      port: 9999
      protocol: TCP
      targetPort: http
  selector:
    inference.io/component: xinference-server
```

**Comment by ChengjieLi28** [comment]
How do you start xinference in K8s?
This seems that xinference worker does not connect to supervisor.
Could you please show me the K8s config? You may need to config service for network between supervisor and worker.

**Comment by JoshuaAndrew** [comment]
@ChengjieLi28 
```
apiVersion: v1
kind: Service
metadata:
  name: xinference
  namespace: xinference
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9997
      protocol: TCP
      targetPort: web
    - name: http
      port: 9999
      protocol: TCP
      targetPort: http
  selector:
    inference.io/component: xinference-server
```

**Comment by ChengjieLi28** [comment]
Paste the supervisor and worker pod logs.

**Comment by JoshuaAndrew** [comment]
@ChengjieLi28 
why **worker port** should be configured in k8s service ?

**Comment by ChengjieLi28** [comment]
> @ChengjieLi28 why **worker port** should be configured in k8s service ?

Not being a K8s expert here, all I can tell you is that supervisor and worker access each other via ip and port. There's no reason why.
Your issue should be that when the cluster starts, the supervisor doesn't receive the registration request from the worker, causing the supervisor to think that there is no worker. this registration is a network packet that the worker sends directly to the supervisor through the ip port.

**Comment by JoshuaAndrew** [comment]
@ChengjieLi28    

Can you use Tencent Meeting to discuss this issue for 5 minutes?

#腾讯会议：876-668-7773
