### ISSUE TITLE
BUG: 请求频率过快，后端会崩掉

### ISSUE THREAD

**Issue by Hjiassen** [xorbitsai/inference#1206]
我在使用qwen1.5-14b-chat迭代input是就会出现请求失败，一般来说迭代20次以后就会出现这个问题，但是模型依然在占用显存

**Comment by qinxuye** [comment]
有服务端的出错日志吗？

**Comment by Hjiassen** [comment]
2024-03-28 13:48:14,325 xinference.api.restful_api 69002 ERROR    Chat completion stream got an error: invalid state
Traceback (most recent call last):
  File "/home/xinference/venv/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1359, in stream_results
    async for item in iterator:
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 106, in _wait
    await asyncio.shield(future)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/core.py", line 88, in _listen
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state
2024-03-28 13:48:14,326 xinference.api.restful_api 69002 ERROR    Chat completion stream got an error: invalid state
Traceback (most recent call last):
  File "/home/xinference/venv/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1359, in stream_results
    async for item in iterator:
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 106, in _wait
    await asyncio.shield(future)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/core.py", line 88, in _listen
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state

**Comment by Hjiassen** [comment]
> 有服务端的出错日志吗？

2024-03-28 13:48:14,325 xinference.api.restful_api 69002 ERROR    Chat completion stream got an error: invalid state
Traceback (most recent call last):
  File "/home/xinference/venv/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1359, in stream_results
    async for item in iterator:
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 106, in _wait
    await asyncio.shield(future)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/core.py", line 88, in _listen
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state
2024-03-28 13:48:14,326 xinference.api.restful_api 69002 ERROR    Chat completion stream got an error: invalid state
Traceback (most recent call last):
  File "/home/xinference/venv/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1359, in stream_results
    async for item in iterator:
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 106, in _wait
    await asyncio.shield(future)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/core.py", line 88, in _listen
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state

**Comment by Hjiassen** [comment]
> 有服务端的出错日志吗？

2024-03-28 13:48:14,325 xinference.api.restful_api 69002 ERROR    Chat completion stream got an error: invalid state
Traceback (most recent call last):
  File "/home/xinference/venv/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1359, in stream_results
    async for item in iterator:
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 106, in _wait
    await asyncio.shield(future)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/core.py", line 88, in _listen
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state
2024-03-28 13:48:14,326 xinference.api.restful_api 69002 ERROR    Chat completion stream got an error: invalid state
Traceback (most recent call last):
  File "/home/xinference/venv/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1359, in stream_results
    async for item in iterator:
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/context.py", line 106, in _wait
    await asyncio.shield(future)
  File "/home/xinference/venv/lib/python3.10/site-packages/xoscar/backends/core.py", line 88, in _listen
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state

**Comment by qinxuye** [comment]
有中断生成过吗？

**Comment by Hjiassen** [comment]
> 有中断生成过吗？

有中断生成过

**Comment by qinxuye** [comment]
是最新的 0.9.4 吗？

**Comment by Hjiassen** [comment]
是的，之前0.9.1也出现了这个问题，升级到0.9.4依然出现了这个问题

**Comment by qinxuye** [comment]
嗯，和中断执可能是有关的，这个我们还得想办法复现才能解决问题。

**Comment by Hjiassen** [comment]
好的，谢谢解答，复现的时候可以使用流式然后打断再请求，反复几次就会出现

**Comment by qinxuye** [comment]
用的是什么后端，有用 vllm 吗？

**Comment by Hjiassen** [comment]
用的是vllm，用的qwen-agent的工具调用模块

**Comment by Hjiassen** [comment]
用的是vllm，用的qwen-agent的工具调用模块

**Comment by beardog6** [comment]
同样的问题，流式请求异常中断后，推理服务完全挂死，xinference list也无响应。日志如下：
2024-04-24 10:07:35,017 xinference.api.restful_api 1435 ERROR    Chat completion stream got an error: invalid state
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1386, in stream_results
    async for item in iterator:
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/core.py", line 88, in _listen
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state

**Comment by carloszhang999** [comment]
流式输出短时间内中断2次以上的请求，就会出现这个问题

### 触发代码
import openai
import concurrent.futures

def send_request(prompt):
    try:
        client = openai.Client(api_key="Empty", base_url="http://10.18.4.190:9997/v1")
        completion = client.chat.completions.create(
            model="chatglm3",
            messages=[
                {
                    "content": prompt,
                    "role": "user",
                }
            ],
            stream=True
        )
        # for chunk in completion:
        #     print(chunk.choices[0].delta.content)
        # print(completion.choices[0].message.content)
        # return completion.choices[0].message.content
        # time.sleep(1)
        # client.close()
        return True
    except Exception as e:
        return str(e)
 

prompts = [
    "写一段7000字的文档，以雪为主题",
    "写一段7000字的文档，以雪为主题",
]

# 使用ThreadPoolExecutor来并发发送请求
with concurrent.futures.ThreadPoolExecutor() as executor:
    # 使用map函数来并行执行send_request函数
    results = list(executor.map(send_request, prompts))

# 打印结果
# for prompt, result in zip(prompts, results):
#     print(f"Prompt: {prompt}\nResponse: {result}\n")

**Comment by qinxuye** [comment]
这个问题应该被 #1663 解决了，如果还有问题，请 reopen 这个 issue。
