### ISSUE TITLE
BUG - error: ggml-metal.metal ... 'ggml-common.h' file not found

### ISSUE THREAD

**Issue by weipienlee** [xorbitsai/inference#1222]
### Describe the bug
error: ggml-metal.metal ... 'ggml-common.h' file not found

### To Reproduce
2023 Macbook M2
isolated python 3.10.12 env, unable to find docker image for mac that the docker works in 
```
CMAKE_ARGS="-DGGML_METAL=ON -DLLAMA_METAL=ON" FORCE_CMAKE=1 pip install "xinference[all]"(got 0.10.0)
xinference-local --host 0.0.0.0 --port 9997
```
use ui to launch qwen1.5-chat, ggufv2, 0.5B, q4_0, N GPU L -1, repl 1
=>  error 'ggml-common.h' file not found (see complete trace below)

### Expected behavior
Model will launch

### Additional context
Only unquantized pytorch models work.
chatglm-cpp                   0.3.1
llama_cpp_python              0.2.57

```
2024-03-31 06:02:14,651 xinference.model.llm.llm_family 58368 INFO     Caching from Hugging Face: Qwen/Qwen1.5-0.5B-Chat-GGUF
llama_model_loader: loaded meta data with 21 key-value pairs and 291 tensors from /Users/weipienlee/.xinference/cache/qwen1.5-chat-ggufv2-0_5b/qwen1_5-0_5b-chat-q4_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = qwen2
llama_model_loader: - kv   1:                               general.name str              = Qwen1.5-0.5B-Chat-AWQ-fp16
llama_model_loader: - kv   2:                          qwen2.block_count u32              = 24
llama_model_loader: - kv   3:                       qwen2.context_length u32              = 32768
llama_model_loader: - kv   4:                     qwen2.embedding_length u32              = 1024
llama_model_loader: - kv   5:                  qwen2.feed_forward_length u32              = 2816
llama_model_loader: - kv   6:                 qwen2.attention.head_count u32              = 16
llama_model_loader: - kv   7:              qwen2.attention.head_count_kv u32              = 16
llama_model_loader: - kv   8:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
llama_model_loader: - kv   9:                       qwen2.rope.freq_base f32              = 1000000.000000
llama_model_loader: - kv  10:                qwen2.use_parallel_residual bool             = true
llama_model_loader: - kv  11:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  12:                      tokenizer.ggml.tokens arr[str,151936]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  13:                  tokenizer.ggml.token_type arr[i32,151936]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  14:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
llama_model_loader: - kv  15:                tokenizer.ggml.eos_token_id u32              = 151645
llama_model_loader: - kv  16:            tokenizer.ggml.padding_token_id u32              = 151643
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 151643
llama_model_loader: - kv  18:                    tokenizer.chat_template str              = {% for message in messages %}{{'<|im_...
llama_model_loader: - kv  19:               general.quantization_version u32              = 2
llama_model_loader: - kv  20:                          general.file_type u32              = 2
llama_model_loader: - type  f32:  121 tensors
llama_model_loader: - type q4_0:  169 tensors
llama_model_loader: - type q6_K:    1 tensors
llm_load_vocab: special tokens definition check successful ( 293/151936 ).
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = qwen2
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 151936
llm_load_print_meta: n_merges         = 151387
llm_load_print_meta: n_ctx_train      = 32768
llm_load_print_meta: n_embd           = 1024
llm_load_print_meta: n_head           = 16
llm_load_print_meta: n_head_kv        = 16
llm_load_print_meta: n_layer          = 24
llm_load_print_meta: n_rot            = 64
llm_load_print_meta: n_embd_head_k    = 64
llm_load_print_meta: n_embd_head_v    = 64
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 2816
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 2
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 1000000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 32768
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 0.5B
llm_load_print_meta: model ftype      = Q4_0
llm_load_print_meta: model params     = 619.57 M
llm_load_print_meta: model size       = 371.02 MiB (5.02 BPW) 
llm_load_print_meta: general.name     = Qwen1.5-0.5B-Chat-AWQ-fp16
llm_load_print_meta: BOS token        = 151643 '<|endoftext|>'
llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
llm_load_print_meta: PAD token        = 151643 '<|endoftext|>'
llm_load_print_meta: LF token         = 148848 'ÄĬ'
llm_load_tensors: ggml ctx size =    0.22 MiB
ggml_backend_metal_buffer_type_alloc_buffer: allocated buffer, size =   287.56 MiB, (  287.62 / 73728.00)
llm_load_tensors: offloading 24 repeating layers to GPU
llm_load_tensors: offloading non-repeating layers to GPU
llm_load_tensors: offloaded 25/25 layers to GPU
llm_load_tensors:        CPU buffer size =    83.46 MiB
llm_load_tensors:      Metal buffer size =   287.56 MiB
...............................................
llama_new_context_with_model: n_ctx      = 32768
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: freq_base  = 1000000.0
llama_new_context_with_model: freq_scale = 1
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M2 Max
ggml_metal_init: picking default device: Apple M2 Max
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: loading '/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/llama_cpp/ggml-metal.metal'
ggml_metal_init: error: Error Domain=MTLLibraryErrorDomain Code=3 "program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:3:10: fatal error: 'ggml-common.h' file not found
#include "ggml-common.h"
         ^~~~~~~~~~~~~~~
}
llama_new_context_with_model: failed to initialize Metal backend
2024-03-31 06:02:15,084 xinference.core.worker 58368 ERROR    Failed to load model qwen1.5-chat-1-0
Traceback (most recent call last):
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/worker.py", line 688, in launch_builtin_model
    await model_ref.load()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/model/llm/ggml/llamacpp.py", line 171, in load
    self._llm = Llama(
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/llama_cpp/llama.py", line 328, in __init__
    self._ctx = _LlamaContext(
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/llama_cpp/_internals.py", line 265, in __init__
    raise ValueError("Failed to create llama_context")
ValueError: [address=0.0.0.0:55942, pid=58484] Failed to create llama_context
2024-03-31 06:02:15,114 xinference.api.restful_api 58330 ERROR    [address=0.0.0.0:55942, pid=58484] Failed to create llama_context
Traceback (most recent call last):
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/api/restful_api.py", line 729, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/supervisor.py", line 827, in launch_builtin_model
    await _launch_model()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/supervisor.py", line 791, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/supervisor.py", line 771, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/worker.py", line 688, in launch_builtin_model
    await model_ref.load()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/xinference/model/llm/ggml/llamacpp.py", line 171, in load
    self._llm = Llama(
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/llama_cpp/llama.py", line 328, in __init__
    self._ctx = _LlamaContext(
  File "/Users/weipienlee/.pyenv/versions/3.10.12/envs/xorbits-inference_3.10/lib/python3.10/site-packages/llama_cpp/_internals.py", line 265, in __init__
    raise ValueError("Failed to create llama_context")
ValueError: [address=0.0.0.0:55942, pid=58484] Failed to create llama_context
```

**Comment by qinxuye** [comment]
Refer to: https://github.com/abetlen/llama-cpp-python/issues/1285

Uninstall llama-cpp-python, then install with

```
CMAKE_ARGS="-DLLAMA_METAL_EMBED_LIBRARY=ON -DLLAMA_METAL=on" pip install -U llama-cpp-python --no-cache-dir
```

**Comment by qinxuye** [comment]
Since it's solved, close it first.

**Comment by weipienlee** [comment]
Just to be sure, I can't close my own submitted issues, right @qinxuye?
