### ISSUE TITLE
chatglm3-6b 无法实现工具调用

### ISSUE THREAD

**Issue by lordk911** [xorbitsai/inference#1230]
### Describe the bug
**我通过xinference分别部署了chatglm3-6b 和 qwen1.5-chat-7b, 使用同样的代码测试工具调用，chatglm3-6b会失败**

![image](https://github.com/xorbitsai/inference/assets/19989300/8affc4b3-81b6-4840-8f65-309d3f78cabb)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.   
    3.10.0
2. The version of xinference you use.
    0.10.0
3. Versions of crucial packages.
    ```
    client conda env : 
        langchain                0.1.14
        langchain-community      0.0.30
        langchain-core           0.1.37
        langchain-experimental   0.0.56
        langchain-openai         0.1.1
        langchain-text-splitters 0.0.1
        langsmith                0.1.38
        openai                   1.14.3
     ```
4. Full stack of the error.
```
    Traceback (most recent call last):
  File "/Users/shin/ideaProjects/langchain_learn/functioncall2.py", line 31, in <module>
    completion = client.chat.completions.create(
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_base_client.py", line 973, in _request
    return self._retry_request(
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_base_client.py", line 1021, in _retry_request
    return self._request(
  File "/Users/shin/miniconda3/envs/langchain_official/lib/python3.10/site-packages/openai/_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'detail': '[address=0.0.0.0:43987, pid=28005] 0'}
```
5. Minimized code to reproduce the error.

```
tools = [
    {
        "type": "function",
        "function": {
            "name": "get_lucky_lottery",
            "description": "生成双色球彩票号码",
            "parameters": {
                "type": "int",
                "properties": {"num": {"description": "生成的彩票号码组数"}},
                "required": ["num"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "lottery_draw",
            "description": "开奖双色球",
            "parameters": {
                "type": "object",
                "properties": {},
            },
        },
    },
]

import openai

client = openai.Client(api_key="not empty", base_url=f"http://10.9.123.456:9997/v1")
completion = client.chat.completions.create(
    model="chatglm3",   #qwen1.5-chat # chatglm3
    messages=[{"role": "user", "content": "帮我生成5组双色球号码"}],
    tools=tools,
)
print(f"Lottery numbers: {completion}")
```

**Comment by qinxuye** [comment]
Do you have the log from the server side?

**Comment by mujin2** [comment]
@lordk911 I tried to reproduce your issue, but I got a normal return: 

> Lottery numbers: ChatCompletion(id='chatcmpl-6926d221-a91a-48a8-b95f-7f4ca9849a4b', choices=[Choice(finish_reason='tool_calls', index=0, logprobs=None, message=ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_6926d221-a91a-48a8-b95f-7f4ca9849a4b', function=Function(arguments='{"num": 5}', name='get_lucky_lottery'), type='function')]))], created=1712644860, model='chatglm3', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=-1, prompt_tokens=-1, total_tokens=-1))

**Comment by qinxuye** [comment]
@mujin2 Did you use vllm backend?

**Comment by qinxuye** [comment]
@codingl2k1 能看下这个问题么？

**Comment by codingl2k1** [comment]
> @codingl2k1 能看下这个问题么？

好的，在看。

**Comment by codingl2k1** [comment]
我这里测试也是调用正常
```python
@pytest.mark.parametrize(
    "model_format, quantization", [("ggmlv3", "q4_0"), ("pytorch", None)]
)
# @pytest.mark.skip(reason="Cost too many resources.")
def test_restful_api_for_tool_calls(setup, model_format, quantization):
    model_name = "chatglm3"

    endpoint, _ = setup
    url = f"{endpoint}/v1/models"

    # list
    response = requests.get(url)
    response_data = response.json()
    assert len(response_data["data"]) == 0

    # launch
    payload = {
        "model_uid": "test_tool",
        "model_name": model_name,
        "model_size_in_billions": 6,
        "model_format": model_format,
        "quantization": quantization,
    }

    response = requests.post(url, json=payload)
    response_data = response.json()
    model_uid_res = response_data["model_uid"]
    assert model_uid_res == "test_tool"

    response = requests.get(url)
    response_data = response.json()
    assert len(response_data["data"]) == 1

    tools = [{
        "type": "function",
        "function": {
            "name": "get_current_weather",
            "description": "获取当前天气",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "城市，例如北京"
                    },
                    "format": {
                        "type": "string",
                        "enum": ["celsius", "fahrenheit"],
                        "description": "使用的温度单位。从所在的城市进行推断。"
                    }
                },
                "required": ["location", "format"]
            }
        }
    }]

    url = f"{endpoint}/v1/chat/completions"
    payload = {
        "model": model_uid_res,
        "messages": [
            {"role": "system", "content": "你是一个有用的助手。不要对要函数调用的值做出假设。"},
            {"role": "user", "content": "上海现在的天气怎么样？"}
        ],
        "temperature": 0.7,
        "tools": tools,
        "stop": ["\n"],
    }
    response = requests.post(url, json=payload)
    completion = response.json()
    print(completion)

    assert (
        "get_current_weather"
        == completion["choices"][0]["message"]["tool_calls"][0]["function"]["name"]
    )
    arguments = completion["choices"][0]["message"]["tool_calls"][0]["function"][
        "arguments"
    ]
    arg = json.loads(arguments)
    assert arg == {'location': '上海', 'format': 'celsius'}
```

**Comment by codingl2k1** [comment]
> ```json
>     {"role": "system", "content": "你是一个有用的助手。不要对要函数调用的值做出假设。"},
>     {"role": "user", "content": "上海现在的天气怎么样？"}
> ```

一样的配置，我用这个测试正常：
```python
import openai

tools = [{
    "type": "function",
    "function": {
        "name": "get_current_weather",
        "description": "获取当前天气",
        "parameters": {
            "type": "object",
            "properties": {
                "location": {
                    "type": "string",
                    "description": "城市，例如北京"
                },
                "format": {
                    "type": "string",
                    "enum": ["celsius", "fahrenheit"],
                    "description": "使用的温度单位。从所在的城市进行推断。"
                }
            },
            "required": ["location", "format"]
        }
    }
}]

client = openai.Client(api_key="not empty", base_url="http://127.0.0.1:9997/v1")
completion = client.chat.completions.create(
    model="chatglm3",  # qwen1.5-chat # chatglm3
    messages=[{"role": "system", "content": "你是一个有用的助手。不要对要函数调用的值做出假设。"},
              {"role": "user", "content": "上海现在的天气怎么样？"}
              ],
    tools=tools,
)
print(completion)
```
output
```
ChatCompletion(id='chatcmpl-ffa65b01-fe57-4209-888d-11000445e228', choices=[Choice(finish_reason='tool_calls', index=0, message=ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_ffa65b01-fe57-4209-888d-11000445e228', function=Function(arguments='{"location": "\\u4e0a\\u6d77", "format": "celsius"}', name='get get_current_weather'), type='function')]))], created=1714307582, model='chatglm3', object='chat.completion', system_fingerprint=None, usage=CompletionUsage(completion_tokens=-1, prompt_tokens=-1, total_tokens=-1))

```

```python
json.loads('{"location": "\\u4e0a\\u6d77", "format": "celsius"}')
Out[4]: {'location': '上海', 'format': 'celsius'}
```

**Comment by jiaolongxue** [comment]
```
r = await func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 375, in chat
response = await self._call_wrapper(
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 104, in _asy
nc_wrapper
    return await fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 325, in _cal
l_wrapper
    ret = await fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 504
, in async_chat
    return self._tool_calls_completion(
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/utils.py", line 672, in
_tool_calls_completion
    content, func, args = cls._eval_tool_arguments(model_family, c, tools)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/utils.py", line 630, in
_eval_tool_arguments
    content, func, args = cls._eval_chatglm3_arguments(c, tools)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/utils.py", line 578, in
_eval_chatglm3_arguments
    if isinstance(c[0], str):
```
