### ISSUE TITLE
BUG：用源码本地部署，启动报错：typer 0.12.0 has no such extra feature 'all'

### ISSUE THREAD

**Issue by lm970585581** [xorbitsai/inference#1237]
### Describe the bug
我想在本地用源码部署，按照官网提供的文档，部署后无法正确使用启动

### To Reproduce
已经使用python3.10.13和python3.11两个版本进行了测试，
执行命令xinference-local --host 0.0.0.0 --port 9997后会报错
报错完整信息如下：
Traceback (most recent call last):
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2760, in requires
    deps.extend(dm[safe_extra(ext)])
                ~~^^^^^^^^^^^^^^^^^
KeyError: 'all'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jqxxuser/venv/xinfer-dev/bin/xinference-local", line 33, in <module>
    sys.exit(load_entry_point('xinference', 'console_scripts', 'xinference-local')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jqxxuser/venv/xinfer-dev/bin/xinference-local", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jqxxuser/miniconda3/envs/llm/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jqxxuser/miniconda3/envs/llm/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jqxxuser/inference/xinference/__init__.py", line 38, in <module>
    _install()
  File "/home/jqxxuser/inference/xinference/__init__.py", line 28, in _install
    from xoscar.backends.router import Router
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/xoscar/__init__.py", line 63, in <module>
    init_extension_entrypoints()
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/xoscar/entrypoints.py", line 29, in init_extension_entrypoints
    from pkg_resources import iter_entry_points  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    @_call_aside
     ^^^^^^^^^^^
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 803, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jqxxuser/venv/xinfer-dev/lib/python3.11/site-packages/pkg_resources/__init__.py", line 2762, in requires
    raise UnknownExtra(
pkg_resources.UnknownExtra: typer 0.12.0 has no such extra feature 'all'

**Comment by qinxuye** [comment]
typer 降到 0.12 以下。

```
pip install "typer<0.12"
```

**Comment by lm970585581** [comment]
> typer 降到 0.12 以下。
> 
> ```
> pip install "typer<0.12"
> ```

试了一下还是会报错：
`Traceback (most recent call last):
  File "/home/jqxxuser/miniconda3/envs/xinf/bin/xinference-local", line 33, in <module>
    sys.exit(load_entry_point('xinference', 'console_scripts', 'xinference-local')())
  File "/home/jqxxuser/miniconda3/envs/xinf/bin/xinference-local", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jqxxuser/inference-dev/xinference/__init__.py", line 38, in <module>
    _install()
  File "/home/jqxxuser/inference-dev/xinference/__init__.py", line 28, in _install
    from xoscar.backends.router import Router
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/__init__.py", line 63, in <module>
    init_extension_entrypoints()
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/entrypoints.py", line 29, in init_extension_entrypoints
    from pkg_resources import iter_entry_points  # type: ignore
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3328, in <module>
    def _initialize_master_working_set():
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3302, in _call_aside
    f(*args, **kwargs)
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3340, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    ws.require(__requires__)
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/home/jqxxuser/miniconda3/envs/xinf/lib/python3.10/site-packages/pkg_resources/__init__.py", line 870, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'colorama<0.5.0,>=0.4.3; extra == "all"' distribution was not found and is required by typer
`

**Comment by mikeshi80** [comment]
请使用：
```shell
pip install "typer[all]<0.12"
```

注意后面的`[all]`

**Comment by lm970585581** [comment]
> 请使用：
> 
> ```shell
> pip install "typer[all]<0.12"
> ```
> 
> 注意后面的`[all]`

果然可以，感谢解答
