### ISSUE TITLE
音频文件无法transcriptions,报错找不到音频文件

### ISSUE THREAD

**Issue by Songjiadong** [xorbitsai/inference#1240]
```py
from churchill.config import ( XINFERENCE_URL,
                              SPEECH_2_TEXT_MODEL_NAME)
from xinference.client import Client
from xinference.client.restful.restful_client import RESTfulAudioModelHandle,RESTfulRerankModelHandle
if __name__ == '__main__':

    client = Client(XINFERENCE_URL)
    speech_model:RESTfulAudioModelHandle = client.get_model(SPEECH_2_TEXT_MODEL_NAME)
    file_path="/usr/local/churchill/churchill/files/audios/1.mp3"#f"{APP_FILE_PATH}/audios/1.mp3"
    print(file_path)
    content=""
    with open(file_path, "rb") as audio_file:
        content=speech_model.transcriptions(audio_file.read())
    print(content)
```
```
Traceback (most recent call last):
  File "/usr/local/churchill/churchill/test/audio.py", line 17, in <module>
    content=speech_model.transcriptions(audio_file.read())
  File "/usr/local/churchill/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 597, in transcriptions
    raise RuntimeError(
RuntimeError: Failed to transcribe the audio, detail: [address=0.0.0.0:42973, pid=15339] ffmpeg was not found but is required to load audio files from filename
```

**Comment by Songjiadong** [comment]
xinference launch --model-name whisper-large-v3 --model-type audio  -e "http://127.0.0.1:8888"

**Comment by qinxuye** [comment]
需要安装 ffmpeg

**Comment by Songjiadong** [comment]
@qinxuye `pip install ffmpeg` 依然报这个错误，需要重启服务么？

**Comment by qinxuye** [comment]
只是包是不够的，应该要安装 ffmpeg 软件。

**Comment by DoItEric** [comment]
@Songjiadong 你是怎么解决的啊？
