### ISSUE TITLE
xinference.core.worker 50 ERROR    Failed to load model baichuan-2-1-0

### ISSUE THREAD

**Issue by fengyingbanbo** [xorbitsai/inference#1260]
### Describe the bug
 Failed to load model baichuan-2-1-0

### To Reproduce
[[ docker latest](xinference:latest)[xinference:latest](https://github.com/xorbitsai/inference/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=BUG#)](xinference:latest)

Traceback (most recent call last):
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 688, in launch_builtin_model
2024-04-08 18:03:46     await model_ref.load()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
2024-04-08 18:03:46     return self._process_result_message(result)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
2024-04-08 18:03:46     raise message.as_instanceof_cause()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
2024-04-08 18:03:46     result = await self._run_coro(message.message_id, coro)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
2024-04-08 18:03:46     return await coro
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
2024-04-08 18:03:46     return await super().__on_receive__(message)  # type: ignore
2024-04-08 18:03:46   File "xoscar/core.pyx", line 558, in __on_receive__
2024-04-08 18:03:46     raise ex
2024-04-08 18:03:46   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     async with self._lock:
2024-04-08 18:03:46   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     with debug_async_timeout('actor_lock_timeout',
2024-04-08 18:03:46   File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     result = func(*args, **kwargs)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
2024-04-08 18:03:46     self._model.load()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 222, in load
2024-04-08 18:03:46     self._model, self._tokenizer = self._load_model(**kwargs)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 104, in _load_model
2024-04-08 18:03:46     tokenizer = AutoTokenizer.from_pretrained(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 822, in from_pretrained
2024-04-08 18:03:46     return tokenizer_class.from_pretrained(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2086, in from_pretrained
2024-04-08 18:03:46     return cls._from_pretrained(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2325, in _from_pretrained
2024-04-08 18:03:46     tokenizer = cls(*init_inputs, **init_kwargs)
2024-04-08 18:03:46   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-pytorch-13b/tokenization_baichuan.py", line 71, in __init__
2024-04-08 18:03:46     super().__init__(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 367, in __init__
2024-04-08 18:03:46     self._add_tokens(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
2024-04-08 18:03:46     current_vocab = self.get_vocab().copy()
2024-04-08 18:03:46   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-pytorch-13b/tokenization_baichuan.py", line 105, in get_vocab
2024-04-08 18:03:46     vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
2024-04-08 18:03:46   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-pytorch-13b/tokenization_baichuan.py", line 101, in vocab_size
2024-04-08 18:03:46     return self.sp_model.get_piece_size()
2024-04-08 18:03:46 AttributeError: [address=0.0.0.0:35355, pid=436] 'BaichuanTokenizer' object has no attribute 'sp_model'
2024-04-08 18:03:46 2024-04-08 10:03:46,178 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:35355, pid=436] 'BaichuanTokenizer' object has no attribute 'sp_model'
2024-04-08 18:03:46 Traceback (most recent call last):
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py", line 729, in launch_model
2024-04-08 18:03:46     model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
2024-04-08 18:03:46     return self._process_result_message(result)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
2024-04-08 18:03:46     raise message.as_instanceof_cause()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
2024-04-08 18:03:46     result = await self._run_coro(message.message_id, coro)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
2024-04-08 18:03:46     return await coro
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
2024-04-08 18:03:46     return await super().__on_receive__(message)  # type: ignore
2024-04-08 18:03:46   File "xoscar/core.pyx", line 558, in __on_receive__
2024-04-08 18:03:46     raise ex
2024-04-08 18:03:46   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     async with self._lock:
2024-04-08 18:03:46   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     with debug_async_timeout('actor_lock_timeout',
2024-04-08 18:03:46   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     result = await result
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 827, in launch_builtin_model
2024-04-08 18:03:46     await _launch_model()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 791, in _launch_model
2024-04-08 18:03:46     await _launch_one_model(rep_model_uid)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 771, in _launch_one_model
2024-04-08 18:03:46     await worker_ref.launch_builtin_model(
2024-04-08 18:03:46   File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
2024-04-08 18:03:46     async with lock:
2024-04-08 18:03:46   File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
2024-04-08 18:03:46     result = await result
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
2024-04-08 18:03:46     ret = await func(*args, **kwargs)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 688, in launch_builtin_model
2024-04-08 18:03:46     await model_ref.load()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
2024-04-08 18:03:46     return self._process_result_message(result)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
2024-04-08 18:03:46     raise message.as_instanceof_cause()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
2024-04-08 18:03:46     result = await self._run_coro(message.message_id, coro)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
2024-04-08 18:03:46     return await coro
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
2024-04-08 18:03:46     return await super().__on_receive__(message)  # type: ignore
2024-04-08 18:03:46   File "xoscar/core.pyx", line 558, in __on_receive__
2024-04-08 18:03:46     raise ex
2024-04-08 18:03:46   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     async with self._lock:
2024-04-08 18:03:46   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     with debug_async_timeout('actor_lock_timeout',
2024-04-08 18:03:46   File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
2024-04-08 18:03:46     result = func(*args, **kwargs)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
2024-04-08 18:03:46     self._model.load()
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 222, in load
2024-04-08 18:03:46     self._model, self._tokenizer = self._load_model(**kwargs)
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 104, in _load_model
2024-04-08 18:03:46     tokenizer = AutoTokenizer.from_pretrained(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 822, in from_pretrained
2024-04-08 18:03:46     return tokenizer_class.from_pretrained(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2086, in from_pretrained
2024-04-08 18:03:46     return cls._from_pretrained(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2325, in _from_pretrained
2024-04-08 18:03:46     tokenizer = cls(*init_inputs, **init_kwargs)
2024-04-08 18:03:46   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-pytorch-13b/tokenization_baichuan.py", line 71, in __init__
2024-04-08 18:03:46     super().__init__(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 367, in __init__
2024-04-08 18:03:46     self._add_tokens(
2024-04-08 18:03:46   File "/opt/conda/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
2024-04-08 18:03:46     current_vocab = self.get_vocab().copy()
2024-04-08 18:03:46   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-pytorch-13b/tokenization_baichuan.py", line 105, in get_vocab
2024-04-08 18:03:46     vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
2024-04-08 18:03:46   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-pytorch-13b/tokenization_baichuan.py", line 101, in vocab_size
2024-04-08 18:03:46     return self.sp_model.get_piece_size()
2024-04-08 18:03:46 AttributeError: [address=0.0.0.0:35355, pid=436] 'BaichuanTokenizer' object has no attribute 'sp_model'

**Comment by qinxuye** [comment]
Which version of `transformers` are you using?

**Comment by ChengjieLi28** [comment]
@fengyingbanbo baichuan is an old LLM model. You need to downgrade you transformers version to `4.33.1`.
See : https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/discussions/18
