### ISSUE TITLE
 Model not supported, name: Llama2-Chinese-13b-Chat, format: pytorch, size: 13, quantization: 4-bit

### ISSUE THREAD

**Issue by jacklee-ingenico** [xorbitsai/inference#1309]
### Describe the bug
After upgrade from `0.10.0` to `0.10.1`, the LLM that could be loaded normally before but now cannot be loaded anymore.
model provider:
URL: https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. The version of xinference you use： Docker image with latest tag(version should be 0.10.1)

### Expected behavior
Model can be loaded normally as before.

### Additional context
```
2024-04-16 07:17:07,483 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:30714, pid=63] Model not supported, name: Llama2-Chinese-13b-Chat, format: pytorch, size: 13, quantization: 4-bit
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py", line 729, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 827, in launch_builtin_model
    await _launch_model()
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 791, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/supervisor.py", line 771, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 662, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/core.py", line 68, in create_model_instance
    return create_llm_model_instance(
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/core.py", line 211, in create_llm_model_instance
    raise ValueError(
ValueError: [address=0.0.0.0:30714, pid=63] Model not supported, name: Llama2-Chinese-13b-Chat, format: pytorch, size: 13, quantization: 4-bit
```

**Comment by amumu96** [comment]
Is that your custom LLM?
Maybe you can try to register it again...

**Comment by jacklee-ingenico** [comment]
> Is that your custom LLM? Maybe you can try to register it again...

yes,this is my customize LLM, i already try re-register it, but still got same issue.

**Comment by jacklee-ingenico** [comment]
> > > Is that your custom LLM? Maybe you can try to register it again...
> > 
> > 
> > yes,this is my customize LLM, i already try re-register it, but still got same issue.
> 
> it seems you didn't register successful，please check this path whether there have your model json file
> 
> ```
> /Users/username/.xinference/model
> ```

i deploy it with docker, i don't understanding  which excactly path should be for ` /Users/username/.xinference/model` ?
i entry the running container, can't find such a path.
