### ISSUE TITLE
v10.2.post1,模型限流后会处于假死状态

### ISSUE THREAD

**Issue by michaelxu1107** [xorbitsai/inference#1344]
1、launch model时配置request limit参数
2、使用locust发起性能测试
3、触发限流后，应用假死，登录ui页面，点击Launch Model->CUSTOM MODELS显示为空，点击Running Models无法查看到模型，但是执行nvidia-smi能够看到显存仍被占用

**Comment by ChengjieLi28** [comment]
@michaelxu1107 完整的debug日志贴一下

**Comment by michaelxu1107** [comment]
2024-04-22 15:30:35,490 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:35,490 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 0, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:35,491 xinference.model.llm.vllm.core 15754 DEBUG    Enter generate, prompt: <|system|>
 You are a helpful assistant.
<|user|>
 你好
<|assistant|>, generate config: {'temperature': 0.0, 'stop': ['<|user|>', '<|observation|>'], 'stop_token_ids': [64795, 64797, 2]}
INFO 04-22 15:30:35 async_llm_engine.py:508] Received request 35791152-007a-11ef-9f30-bc2411d63360: prompt: '<|system|>\n You are a helpful assistant.\n<|user|>\n 你好\n<|assistant|>', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|user|>', '<|observation|>'], stop_token_ids=[64795, 64797, 2], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: None, lora_request: None.
INFO 04-22 15:30:35 metrics.py:218] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 04-22 15:30:35 async_llm_engine.py:120] Finished request 35791152-007a-11ef-9f30-bc2411d63360.
2024-04-22 15:30:35,843 xinference.core.model 15754 DEBUG    After request chat, current serve request count: 0 for the model chatglm3-6b-32k
2024-04-22 15:30:35,843 xinference.core.model 15754 DEBUG    Leave wrapped_func, elapsed time: 0 s
2024-04-22 15:30:35,848 xinference.core.supervisor 15570 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:35,848 xinference.core.worker 15570 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:35,848 xinference.core.worker 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:35,848 xinference.core.supervisor 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:35,849 xinference.core.supervisor 15570 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:35,849 xinference.core.worker 15570 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:35,849 xinference.core.worker 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:35,849 xinference.core.supervisor 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:35,850 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:35,850 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 0, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:35,850 xinference.model.llm.vllm.core 15754 DEBUG    Enter generate, prompt: <|system|>
 You are a helpful assistant.
<|user|>
 你好
<|assistant|>, generate config: {'temperature': 0.0, 'stop': ['<|user|>', '<|observation|>'], 'stop_token_ids': [64795, 64797, 2]}
INFO 04-22 15:30:35 async_llm_engine.py:508] Received request 35afe722-007a-11ef-9f30-bc2411d63360: prompt: '<|system|>\n You are a helpful assistant.\n<|user|>\n 你好\n<|assistant|>', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|user|>', '<|observation|>'], stop_token_ids=[64795, 64797, 2], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: None, lora_request: None.
INFO 04-22 15:30:36 async_llm_engine.py:120] Finished request 35afe722-007a-11ef-9f30-bc2411d63360.
2024-04-22 15:30:36,172 xinference.core.model 15754 DEBUG    After request chat, current serve request count: 0 for the model chatglm3-6b-32k
2024-04-22 15:30:36,172 xinference.core.model 15754 DEBUG    Leave wrapped_func, elapsed time: 0 s
2024-04-22 15:30:36,175 xinference.core.supervisor 15570 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,175 xinference.core.worker 15570 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,175 xinference.core.worker 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,175 xinference.core.supervisor 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,176 xinference.core.supervisor 15570 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,176 xinference.core.worker 15570 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,176 xinference.core.worker 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,176 xinference.core.supervisor 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,177 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:36,177 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 0, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:36,177 xinference.model.llm.vllm.core 15754 DEBUG    Enter generate, prompt: <|system|>
 You are a helpful assistant.
<|user|>
 你好
<|assistant|>, generate config: {'temperature': 0.0, 'stop': ['<|user|>', '<|observation|>'], 'stop_token_ids': [64795, 64797, 2]}
INFO 04-22 15:30:36 async_llm_engine.py:508] Received request 35e1e164-007a-11ef-9f30-bc2411d63360: prompt: '<|system|>\n You are a helpful assistant.\n<|user|>\n 你好\n<|assistant|>', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|user|>', '<|observation|>'], stop_token_ids=[64795, 64797, 2], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: None, lora_request: None.
2024-04-22 15:30:36,486 xinference.core.supervisor 15570 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,487 xinference.core.worker 15570 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,487 xinference.core.worker 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,487 xinference.core.supervisor 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,487 xinference.core.supervisor 15570 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,487 xinference.core.worker 15570 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,488 xinference.core.worker 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,488 xinference.core.supervisor 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,488 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:36,489 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 1, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:36,490 xinference.api.restful_api 15365 ERROR    [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k
Traceback (most recent call last):
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1413, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/model.py", line 75, in wrapped_func
    raise RuntimeError(
RuntimeError: [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k
2024-04-22 15:30:36,495 xinference.core.supervisor 15570 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,496 xinference.core.worker 15570 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,496 xinference.core.worker 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,496 xinference.core.supervisor 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,496 xinference.core.supervisor 15570 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,497 xinference.core.worker 15570 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,497 xinference.core.worker 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,497 xinference.core.supervisor 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,497 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:36,497 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 1, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:36,499 xinference.api.restful_api 15365 ERROR    [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k
Traceback (most recent call last):
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1413, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/model.py", line 75, in wrapped_func
    raise RuntimeError(
RuntimeError: [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k
INFO 04-22 15:30:36 async_llm_engine.py:120] Finished request 35e1e164-007a-11ef-9f30-bc2411d63360.
2024-04-22 15:30:36,500 xinference.core.model 15754 DEBUG    After request chat, current serve request count: 0 for the model chatglm3-6b-32k
2024-04-22 15:30:36,500 xinference.core.model 15754 DEBUG    Leave wrapped_func, elapsed time: 0 s
2024-04-22 15:30:36,502 xinference.core.supervisor 15570 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,502 xinference.core.worker 15570 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,502 xinference.core.worker 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,502 xinference.core.supervisor 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,503 xinference.core.supervisor 15570 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,503 xinference.core.worker 15570 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,503 xinference.core.worker 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,503 xinference.core.supervisor 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,503 xinference.core.supervisor 15570 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,503 xinference.core.worker 15570 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,504 xinference.core.worker 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,504 xinference.core.supervisor 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,504 xinference.core.supervisor 15570 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,504 xinference.core.worker 15570 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,504 xinference.core.worker 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,504 xinference.core.supervisor 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,504 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:36,504 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 0, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:36,504 xinference.model.llm.vllm.core 15754 DEBUG    Enter generate, prompt: <|system|>
 You are a helpful assistant.
<|user|>
 你好
<|assistant|>, generate config: {'temperature': 0.0, 'stop': ['<|user|>', '<|observation|>'], 'stop_token_ids': [64795, 64797, 2]}
INFO 04-22 15:30:36 async_llm_engine.py:508] Received request 3613c77e-007a-11ef-9f30-bc2411d63360: prompt: '<|system|>\n You are a helpful assistant.\n<|user|>\n 你好\n<|assistant|>', sampling_params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|user|>', '<|observation|>'], stop_token_ids=[64795, 64797, 2], include_stop_str_in_output=False, ignore_eos=False, max_tokens=1024, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt_token_ids: None, lora_request: None.
2024-04-22 15:30:36,505 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:36,506 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 1, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:36,507 xinference.api.restful_api 15365 ERROR    [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k
Traceback (most recent call last):
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1413, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/model.py", line 75, in wrapped_func
    raise RuntimeError(
RuntimeError: [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k
2024-04-22 15:30:36,510 xinference.core.supervisor 15570 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,510 xinference.core.worker 15570 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,510 xinference.core.worker 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,510 xinference.core.supervisor 15570 DEBUG    Leave get_model, elapsed time: 0 s
2024-04-22 15:30:36,511 xinference.core.supervisor 15570 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb94e7aa930>, 'chatglm3-6b-32k'), kwargs: {}
2024-04-22 15:30:36,511 xinference.core.worker 15570 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb94e7aa8e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0'}
2024-04-22 15:30:36,511 xinference.core.worker 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,511 xinference.core.supervisor 15570 DEBUG    Leave describe_model, elapsed time: 0 s
2024-04-22 15:30:36,512 xinference.core.model 15754 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f0440252de0>, '你好', 'You are a helpful assistant.', [], {'temperature': 0.0}), kwargs: {}
2024-04-22 15:30:36,512 xinference.core.model 15754 DEBUG    Request chat, current serve request count: 1, request limit: 1 for the model chatglm3-6b-32k
2024-04-22 15:30:36,513 xinference.api.restful_api 15365 ERROR    [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k
Traceback (most recent call last):
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1413, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/model.py", line 75, in wrapped_func
    raise RuntimeError(
RuntimeError: [address=IP:PORT, pid=15754] Rate limit reached for the model. Request limit 1 for the model: chatglm3-6b-32k

**Comment by ChengjieLi28** [comment]
@michaelxu1107 从服务端日志看，没什么问题，超过request_limit的请求是会报错。
你说的假死是什么现象？页面上有任何错误提示吗？可以打开页面F12看下console或者network有什么错误，并给出截图。

**Comment by michaelxu1107** [comment]
假死现象如下：
1、Launch Model->CUSTOM MODELS显示为空
2、点击Running Models无法查看到模型，但是执行nvidia-smi能够看到显存仍被占用
3、调用模型接口无反应
4、页面上没有提示，查看console发现调用v1/models为pending状态

**Comment by michaelxu1107** [comment]
感觉像哪个地方锁没释放

**Comment by ChengjieLi28** [comment]
> 假死现象如下： 1、Launch Model->CUSTOM MODELS显示为空 2、点击Running Models无法查看到模型，但是执行nvidia-smi能够看到显存仍被占用 3、调用模型接口无反应 4、页面上没有提示，查看console发现调用v1/models为pending状态

3. 调用接口没反应是调用接口后，后端也不会新生成任何日志吗？完全没响应？

**Comment by michaelxu1107** [comment]
后端没有生成新的日志，感觉像哪个地方锁没释放

**Comment by ChengjieLi28** [comment]
> 后端没有生成新的日志，感觉像哪个地方锁没释放

launch模型过程的日志也贴一下

**Comment by michaelxu1107** [comment]
> > 后端没有生成新的日志，感觉像哪个地方锁没释放
> 
> 你的设置request_limit是1，超过1个会报错，那么原来那个有返回吗？你是怎么调用的？

有返回，我是通过locust发起性能测试，配置number of users=2,ramp up=1

**Comment by jingyaogong** [comment]
> > > 后端没有生成新的日志，感觉像哪个地方锁没释放
> > 
> > 
> > 你的设置request_limit是1，超过1个会报错，那么原来那个有返回吗？你是怎么调用的？
> 
> 有返回，我是通过locust发起性能测试，配置number of users=2,ramp up=1

我在之前版本上都遇到了假死现象，不是10.2之后限流才有的

**Comment by ChengjieLi28** [comment]
@michaelxu1107 @jingyaogong 
我没有复现出来，以下是复现代码：
launch qwen1.5-chat 4b 在 vllm上，launch时指定request_limits为1
复现代码：
```
import threading
from xinference.client import Client

client = Client('http://127.0.0.1:12306')
model = client.get_model("qwen1.5-chat")


class myThread(threading.Thread):
    def __init__(self, prompt):
        threading.Thread.__init__(self)
        self._prompt = prompt

    def run(self):
        print_time(self._prompt)


def print_time(prompt):
    res = model.chat(prompt)
    print(res)


thread1 = myThread("What's the difference between dog and cat?")
thread2 = myThread("Tell me about history of basketball.")

thread1.start()
thread2.start()

thread1.join()
thread2.join()
```
运行结果：
<img width="1714" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/75bcd489-f4df-4a69-8987-b8870afdd131">
一个收到报错，一个正常有结果，并没有出现什么假死的现象，前端页面也正常。

**Comment by michaelxu1107** [comment]
@ChengjieLi28 
我这边测试代码如下:
from locust import HttpUser, task
import json

class WebsiteUser(HttpUser):
    host = "http://127.0.0.1:9999"

    @task
    def task(self):
        h = {
            "accept": "application/json",
            "Content-Type": "application/json"
        }
        body = {
            "model": "chatglm3-6b-32k",
            "messages": [
                {
                    "role": "system",
                    "content": "You are a helpful assistant."
                },
                {
                    "role": "user",
                    "content": "你好"
                }
            ],
            "temperature": 0.0
        }
        r = self.client.post("/v1/chat/completions", headers=h, data=json.dumps(body))
        print(str(r.json()))

**Comment by michaelxu1107** [comment]
@ChengjieLi28 
我这边测试代码如下：

from locust import HttpUser, task
import json
class WebsiteUser(HttpUser):
    host = "http://127.0.0.1:9999"

    @task
    def task(self):
        h = {
            "accept": "application/json",
            "Content-Type": "application/json"
        }
        body = {
            "model": "chatglm3-6b-32k",
            "messages": [
                {
                    "role": "system",
                    "content": "You are a helpful assistant."
                },
                {
                    "role": "user",
                    "content": "你好"
                }
            ],
            "temperature": 0.0
        }
        r = self.client.post("/v1/chat/completions", headers=h, data=json.dumps(body))
        print(str(r.json()))
