### ISSUE TITLE
BUG：The embedding model has been used for a while and is no longer available.

### ISSUE THREAD

**Issue by JasonFlyBeauty** [xorbitsai/inference#1345]
### Describe the bug
The embedding model has been used for a while and is no longer available.

The actual situation is: I use the embedding model for some time, I can't find the embedding model in the webui interface, and the API can't be used, but I can still find the uid in the terminal, and if I use the ui web to create the model again, the uid is no longer bge-m3-1-0, so I need to delete the model in the terminal, and then create the model again in the ui. I need to delete the previous model in terminal and create the model in ui again.

Translated with DeepL.com (free version)

### To Reproduce
docker：xprobe/xinference:latest

```
2024-04-22 03:16:25,220 xinference.core.worker 95 DEBUG    Enter terminate_model, args: (<xinference.core.worker.WorkerActor object at 0x7d960864b380>, 'bge-m3-1-0'), kwargs: {}
2024-04-22 03:16:25,221 xinference.core.worker 95 DEBUG    Destroy model actor failed, model uid: bge-m3-1-0, error: [Errno 111] Connection refused
2024-04-22 03:16:25,221 xinference.core.worker 95 DEBUG    Remove sub pool failed, model uid: bge-m3-1-0, error: '0.0.0.0:33245'
2024-04-22 03:16:25,221 xinference.core.worker 95 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-04-22 03:16:25,222 xinference.core.worker 95 WARNING  Recreating model actor bge-m3-1-0 ...
2024-04-22 03:16:25,222 xinference.core.worker 95 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7d960864b380>,), kwargs: {'model_uid': 'bge-m3-1-0', 'model_name': 'bge-m3', 'model_size_in_billions': None, 'model_format': None, 'quantization': None, 'model_type': 'embedding', 'n_gpu': 'auto', 'peft_model_path': None, 'image_lora_load_kwargs': None, 'image_lora_fuse_kwargs': None, 'request_limits': None, 'gpu_idx': None, 'event_model_uid': 'bge-m3', '_': 1, '__': 0}
2024-04-22 03:16:25,223 xinference.core.worker 95 DEBUG    GPU selected: [0] for model bge-m3-1-0
2024-04-22 03:16:28,479 xinference.model.embedding.core 95 DEBUG    Embedding model bge-m3 found in ModelScope.
2024-04-22 03:16:28,480 xinference.model.utils 95 INFO     Use model cache from a different hub.
2024-04-22 03:16:28,481 xinference.core.worker 95 ERROR    Failed to load model bge-m3-1-0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 662, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/core.py", line 83, in create_model_instance
    return create_embedding_model_instance(
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/embedding/core.py", line 329, in create_embedding_model_instance
    model = EmbeddingModel(model_uid, model_path, **kwargs)
TypeError: EmbeddingModel.__init__() got an unexpected keyword argument 'event_model_uid'
2024-04-22 03:20:29,113 xinference.core.worker 95 ERROR    Report status got error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 781, in report_status
    status = await asyncio.to_thread(gather_node_info)
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
asyncio.exceptions.CancelledError
```

**Comment by ChengjieLi28** [comment]
@JasonFlyBeauty Could you please show me the complete debug logs from the start of the xinference?

**Comment by ChengjieLi28** [comment]
@JasonFlyBeauty Thanks for reporting. This is a bug. We will fix it ASAP.
By the way, the reason you are facing this problem is that, you have triggered a CUDA OOM while using embedding. This error is an error in the auto-recovery process. 
Please check the status of your GPU memory while using the embedding model.

**Comment by JasonFlyBeauty** [comment]
Thank you very much for your help.

> @JasonFlyBeauty Thanks for reporting. This is a bug. We will fix it ASAP. By the way, the reason you are facing this problem is that, you have triggered a CUDA OOM while using embedding. This error is an error in the auto-recovery process. Please check the status of your GPU memory while using the embedding model.

**Comment by JasonFlyBeauty** [comment]
Also, I would like to know how to specify the GPU card for the embedding model and if it supports multi-card running


> @JasonFlyBeauty Thanks for reporting. This is a bug. We will fix it ASAP. By the way, the reason you are facing this problem is that, you have triggered a CUDA OOM while using embedding. This error is an error in the auto-recovery process. Please check the status of your GPU memory while using the embedding model.

**Comment by ChengjieLi28** [comment]
> Also, I would like to know how to specify the GPU card for the embedding model and if it supports multi-card running
> 
> > @JasonFlyBeauty Thanks for reporting. This is a bug. We will fix it ASAP. By the way, the reason you are facing this problem is that, you have triggered a CUDA OOM while using embedding. This error is an error in the auto-recovery process. Please check the status of your GPU memory while using the embedding model.

Use --gpu-idx option when launching models. See https://inference.readthedocs.io/en/latest/reference/generated/xinference.client.Client.launch_model.html
```
xinference launch <other_options> --gpu-idx <your_specific_gpu_index>
```

**Comment by JasonFlyBeauty** [comment]
Thanks again for your help!

> > 另外，我想知道如何指定嵌入模型的GPU卡以及是否支持多卡运行
> > > @JasonFlyBeauty感谢您的报告。这是一个错误。我们会加速修复它。顺便说一句，您遇到此问题的原因是，您在使用嵌入时触发了 CUDA OOM。该错误是自动恢复过程中的错误。使用嵌入模型时请检查GPU内存的状态。
> 
> 启动模型时使用 --gpu-idx 选项。请参考[https://inference.readthedocs.io/en/latest/reference/ generated /xinference.client.Client.launch_model.html](https://inference.readthedocs.io/en/latest/reference/generated/xinference.client.Client.launch_model.html)
> 
> ```
> xinference launch <other_options> --gpu-idx <your_specific_gpu_index>
> ```
