### ISSUE TITLE
Lanch rerank bge-reranker-large false

### ISSUE THREAD

**Issue by nikhe** [xorbitsai/inference#1352]
### Describe the bug
master branch
run：xinference launch -e http://192.168.1.55:9997 -n bge-reranker-large -t rerank --n-gpu 1 --worker-ip 192.168.1.55 --gpu-idx 1 -u bge-reranker-large
then fail：
Launch model name: bge-reranker-large with kwargs: {}
Traceback (most recent call last):
  File "/home/gpu/anaconda3/envs/xinference/bin/xinference", line 33, in <module>
    sys.exit(load_entry_point('xinference', 'console_scripts', 'xinference')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/aidata/inference/xinference/deploy/cmdline.py", line 765, in model_launch
    model_uid = client.launch_model(
                ^^^^^^^^^^^^^^^^^^^^
  File "/aidata/inference/xinference/client/restful/restful_client.py", line 892, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=192.168.20.25:36739, pid=2155786] CUDA call failed lazily at initialization with error: device >= 0 && device < num_gpus INTERNAL ASSERT FAILED at "../aten/src/ATen/cuda/CUDAContext.cpp":50, please report a bug to PyTorch. device=1, num_gpus=

CUDA call was originally invoked at:

  File "<string>", line 1, in <module>
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/multiprocessing/spawn.py", line 135, in _main
    return self._bootstrap(parent_sentinel)
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/indigen/pool.py", line 258, in _start_sub_pool
    logging.config.dictConfig(logging_conf["dict"])
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/logging/config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/logging/config.py", line 561, in configure
    filters[name] = self.configure_filter(filters[name])
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/logging/config.py", line 698, in configure_filter
    result = self.configure_custom(config)
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/logging/config.py", line 479, in configure_custom
    c = self.resolve(c)
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/logging/config.py", line 396, in resolve
    found = self.importer(used)
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/aidata/inference/xinference/__init__.py", line 38, in <module>
    _install()
  File "/aidata/inference/xinference/__init__.py", line 35, in _install
    install_model()
  File "/aidata/inference/xinference/model/__init__.py", line 17, in _install
    from .llm import _install as llm_install
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/aidata/inference/xinference/model/llm/__init__.py", line 19, in <module>
    from .core import (
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/aidata/inference/xinference/model/llm/core.py", line 23, in <module>
    from ...core.utils import parse_replica_model_uid
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/aidata/inference/xinference/core/__init__.py", line 15, in <module>
    from .model import ModelActor
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/aidata/inference/xinference/core/model.py", line 47, in <module>
    from ..device_utils import empty_cache
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/aidata/inference/xinference/device_utils.py", line 17, in <module>
    import torch
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/__init__.py", line 1332, in <module>
    _C._initExtension(manager_path())
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/cuda/__init__.py", line 244, in <module>
    _lazy_call(_check_capability)
  File "/home/gpu/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/cuda/__init__.py", line 241, in _lazy_call
    _queued_calls.append((callable, traceback.format_stack()))

### To Reproduce
Cluster model 
lanch rerank bge-reranker-large by bash or web page then look worker log
(xinference launch -e http://192.168.1.55:9997 -n bge-reranker-large -t rerank --n-gpu 1 --worker-ip 192.168.1.55 --gpu-idx 1 -u bge-reranker-large)
To help us to reproduce this bug, please provide information below:

1. Your Python version: 3.11
2. The version of xinference you use: xinference, version 0.10.2.post1+2.g9602061
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by ChengjieLi28** [comment]
@nikhe try `v0.10.3` and then close this issue if it works.

**Comment by nikhe** [comment]
> @nikhe try `v0.10.3` and then close this issue if it works.

Ok I'll try it later
