### ISSUE TITLE
部署Embedding模型时报错got an unexpected keyword argument 'peft_model_path'

### ISSUE THREAD

**Issue by LivingXu** [xorbitsai/inference#1357]
使用WebUI启动Embedding模型时报错如下，同时无法从前端将peft_model_path设为None

2024-04-23 07:10:37,454 - modelscope - INFO - Use user-specified model revision: v0.0.1
Downloading: 100%|██████████| 201/201 [00:00<00:00, 709kB/s]
Downloading: 100%|██████████| 690/690 [00:00<00:00, 2.23MB/s]
Downloading: 100%|██████████| 688/688 [00:00<00:00, 2.60MB/s]
Downloading: 100%|██████████| 196/196 [00:00<00:00, 614kB/s]
Downloading: 100%|██████████| 533k/533k [00:00<00:00, 3.15MB/s]
Downloading: 100%|█████████▉| 2.08G/2.08G [00:44<00:00, 49.9MB/s]
Downloading: 100%|█████████▉| 2.09G/2.09G [00:42<00:00, 52.8MB/s]
Downloading: 100%|██████████| 387/387 [00:00<00:00, 933kB/s]
Downloading: 100%|█████████▉| 2.09G/2.09G [00:39<00:00, 57.2MB/s]
Downloading: 100%|██████████| 433/433 [00:00<00:00, 1.72MB/s]
Downloading: 100%|██████████| 57.0/57.0 [00:00<00:00, 263kB/s]
Downloading: 100%|██████████| 4.83M/4.83M [00:00<00:00, 7.67MB/s]
Downloading: 100%|██████████| 4.83M/4.83M [00:00<00:00, 14.5MB/s]
Downloading: 100%|██████████| 280/280 [00:00<00:00, 1.20MB/s]
Downloading: 100%|██████████| 280/280 [00:00<00:00, 1.26MB/s]
Downloading:   0%|          | 0.00/16.3M [00:00<?, ?B/s]2024-04-23 07:13:07,865 xinference.model.utils 11174 INFO     Use model cache from a different hub.
2024-04-23 07:13:07,866 xinference.core.worker 11174 ERROR    Failed to load model bge-large-zh-v1.5-1-0
Traceback (most recent call last):
  File "/mnt/External/xuliwen/anaconda3/envs/LLM/lib/python3.10/site-packages/xinference/core/worker.py", line 669, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
  File "/mnt/External/xuliwen/anaconda3/envs/LLM/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/mnt/External/xuliwen/anaconda3/envs/LLM/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/External/xuliwen/anaconda3/envs/LLM/lib/python3.10/site-packages/xinference/model/core.py", line 82, in create_model_instance
    return create_embedding_model_instance(
  File "/mnt/External/xuliwen/anaconda3/envs/LLM/lib/python3.10/site-packages/xinference/model/embedding/core.py", line 329, in create_embedding_model_instance
    model = EmbeddingModel(model_uid, model_path, **kwargs)
TypeError: EmbeddingModel.__init__() got an unexpected keyword argument 'peft_model_path'

**Comment by qinxuye** [comment]
目前 0.10.2 命令行加载会有这个报错，UI加载没有这个问题。主分支已经修复，会随 0.10.3 发布。这个问题和 #1333 重复
