### ISSUE TITLE
0.10.2.post1版本同时起多个模型会报CUDA out of memory,0.9.4版本可以同时起多个模型

### ISSUE THREAD

**Issue by michaelxu1107** [xorbitsai/inference#1361]
**起第一个模型日志如下：**
2024-04-24 10:32:08,785 xinference.core.supervisor 34829 DEBUG    Enter launch_builtin_model, model_uid: chatglm3-6b-32k, model_name: chatglm3-6b-32k, model_size: 6, model_format: pytorch, quantization: none, replica: 1
2024-04-24 10:32:08,785 xinference.core.worker 34829 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7fe6545137e0>,), kwargs: {}
2024-04-24 10:32:08,785 xinference.core.worker 34829 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-04-24 10:32:08,785 xinference.core.worker 34829 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7fe6545137e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-1-0', 'model_name': 'chatglm3-6b-32k', 'model_size_in_billions': 6, 'model_format': 'pytorch', 'quantization': 'none', 'model_type': 'LLM', 'n_gpu': 1, 'request_limits': None, 'peft_model_config': None, 'gpu_idx': None}
2024-04-24 10:32:08,786 xinference.core.worker 34829 DEBUG    GPU selected: [0] for model chatglm3-6b-32k-1-0
2024-04-24 10:32:12,822 xinference.model.llm.llm_family 34829 INFO     Caching from URI: /home/iqas/models/THUDM/chatglm3-6b-32k
2024-04-24 10:32:12,823 xinference.model.llm.llm_family 34829 INFO     Cache /home/iqas/models/THUDM/chatglm3-6b-32k exists
2024-04-24 10:32:12,823 xinference.model.llm.core 34829 DEBUG    Launching chatglm3-6b-32k-1-0 with VLLMChatModel
2024-04-24 10:32:12,828 xinference.model.llm.vllm.core 35156 INFO     Loading chatglm3-6b-32k with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 1, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None, 'max_model_len': 4096}
INFO 04-24 10:32:12 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='/home/iqas/models/THUDM/chatglm3-6b-32k', tokenizer='/home/iqas/models/THUDM/chatglm3-6b-32k', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
WARNING 04-24 10:32:12 tokenizer.py:104] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 04-24 10:32:13 pynccl.py:39] Loading nccl from environment variable VLLM_NCCL_SO_PATH=/home/iqas/model_env_new/lib/python3.10/site-packages/nvidia/nccl/lib/libnccl.so.2
INFO 04-24 10:32:15 selector.py:16] Using FlashAttention backend.
INFO 04-24 10:32:24 model_runner.py:104] Loading model weights took 11.6608 GB
INFO 04-24 10:32:26 gpu_executor.py:94] # GPU blocks: 19161, # CPU blocks: 9362
INFO 04-24 10:32:29 model_runner.py:791] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 04-24 10:32:29 model_runner.py:795] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.
INFO 04-24 10:32:36 model_runner.py:867] Graph capturing finished in 7 secs.

**起第二个相同模型日志日下：**
2024-04-24 10:33:33,663 xinference.core.worker 34829 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7fe6545137e0>,), kwargs: {'model_uid': 'chatglm3-6b-32k-e82uAQYC-1-0', 'model_name': 'chatglm3-6b-32k', 'model_size_in_billions': 6, 'model_format': 'pytorch', 'quantization': 'none', 'model_type': 'LLM', 'n_gpu': 1, 'request_limits': None, 'peft_model_config': None, 'gpu_idx': None}
2024-04-24 10:33:33,664 xinference.core.worker 34829 DEBUG    GPU selected: [1] for model chatglm3-6b-32k-e82uAQYC-1-0
2024-04-24 10:33:37,771 xinference.model.llm.llm_family 34829 INFO     Caching from URI: /home/iqas/models/THUDM/chatglm3-6b-32k
2024-04-24 10:33:37,772 xinference.model.llm.llm_family 34829 INFO     Cache /home/iqas/models/THUDM/chatglm3-6b-32k exists
2024-04-24 10:33:37,772 xinference.model.llm.core 34829 DEBUG    Launching chatglm3-6b-32k-e82uAQYC-1-0 with VLLMChatModel
2024-04-24 10:33:37,776 xinference.model.llm.vllm.core 35678 INFO     Loading chatglm3-6b-32k-e82uAQYC with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 1, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None, 'max_model_len': 4096}
INFO 04-24 10:33:37 llm_engine.py:74] Initializing an LLM engine (v0.4.0.post1) with config: model='/home/iqas/models/THUDM/chatglm3-6b-32k', tokenizer='/home/iqas/models/THUDM/chatglm3-6b-32k', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, seed=0)
WARNING 04-24 10:33:37 tokenizer.py:104] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 04-24 10:33:38 pynccl.py:39] Loading nccl from environment variable VLLM_NCCL_SO_PATH=/home/iqas/model_env_new/lib/python3.10/site-packages/nvidia/nccl/lib/libnccl.so.2
INFO 04-24 10:33:40 selector.py:16] Using FlashAttention backend.
2024-04-24 10:33:43,099 xinference.core.worker 34829 ERROR    Failed to load model chatglm3-6b-32k-e82uAQYC-1-0
Traceback (most recent call last):
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/worker.py", line 693, in launch_builtin_model
    await model_ref.load()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 176, in load
    self._engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 348, in from_engine_args
    engine = cls(
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 311, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 422, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 37, in __init__
    self._init_worker()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 66, in _init_worker
    self.driver_worker.load_model()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/worker/worker.py", line 107, in load_model
    self.model_runner.load_model()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 95, in load_model
    self.model = get_model(
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 81, in get_model
    model = model_class(model_config.hf_config, linear_method,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 344, in __init__
    self.transformer = ChatGLMModel(config, linear_method)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 290, in __init__
    self.embedding = VocabParallelEmbedding(config.padded_vocab_size,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 76, in __init__
    torch.empty(self.num_embeddings_per_partition,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
torch.cuda.OutOfMemoryError: [address=IP:PORT, pid=35678] CUDA out of memory. Tried to allocate 508.00 MiB. GPU 0 has a total capacty of 23.53 GiB of which 329.44 MiB is free. Process 35156 has 22.14 GiB memory in use. Including non-PyTorch memory, this process has 1.05 GiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2024-04-24 10:33:43,377 xinference.core.supervisor 34829 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fe653d0e750>, 'chatglm3-6b-32k-e82uAQYC'), kwargs: {'suppress_exception': True}
2024-04-24 10:33:43,377 xinference.core.supervisor 34829 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-04-24 10:33:43,381 xinference.api.restful_api 34648 ERROR    [address=IP:PORT, pid=35678] CUDA out of memory. Tried to allocate 508.00 MiB. GPU 0 has a total capacty of 23.53 GiB of which 329.44 MiB is free. Process 35156 has 22.14 GiB memory in use. Including non-PyTorch memory, this process has 1.05 GiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/api/restful_api.py", line 731, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/supervisor.py", line 850, in launch_builtin_model
    await _launch_model()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/supervisor.py", line 814, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/supervisor.py", line 796, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/worker.py", line 693, in launch_builtin_model
    await model_ref.load()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/core/model.py", line 239, in load
    self._model.load()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 176, in load
    self._engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 348, in from_engine_args
    engine = cls(
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 311, in __init__
    self.engine = self._init_engine(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/async_llm_engine.py", line 422, in _init_engine
    return engine_class(*args, **kwargs)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 110, in __init__
    self.model_executor = executor_class(model_config, cache_config,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 37, in __init__
    self._init_worker()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/executor/gpu_executor.py", line 66, in _init_worker
    self.driver_worker.load_model()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/worker/worker.py", line 107, in load_model
    self.model_runner.load_model()
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/worker/model_runner.py", line 95, in load_model
    self.model = get_model(
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/model_loader.py", line 81, in get_model
    model = model_class(model_config.hf_config, linear_method,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 344, in __init__
    self.transformer = ChatGLMModel(config, linear_method)
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/models/chatglm.py", line 290, in __init__
    self.embedding = VocabParallelEmbedding(config.padded_vocab_size,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/vllm/model_executor/layers/vocab_parallel_embedding.py", line 76, in __init__
    torch.empty(self.num_embeddings_per_partition,
  File "/home/iqas/model_env_new/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
torch.cuda.OutOfMemoryError: [address=IP:PORT, pid=35678] CUDA out of memory. Tried to allocate 508.00 MiB. GPU 0 has a total capacty of 23.53 GiB of which 329.44 MiB is free. Process 35156 has 22.14 GiB memory in use. Including non-PyTorch memory, this process has 1.05 GiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

日志中可以发现第二个模型先选择了GPU【1】这张显卡，但后面不知为什么会去使用GPU【0】这张显卡，导致CUDA out of memory

**Comment by qinxuye** [comment]
升级下 accelerate 这个包看下还有没有这个问题。

**Comment by michaelxu1107** [comment]
> 升级下 accelerate 这个包看下还有没有这个问题。

升级accelerate后，发现还是不行

**Comment by michaelxu1107** [comment]
我发现当Using FlashAttention backend时就会Cuda out of memory,而我把flash_attn卸载后，使用Using XFormers backend则不会出现Cuda out of memory

**Comment by qinxuye** [comment]
> 我发现当Using FlashAttention backend时就会Cuda out of memory,而我把flash_attn卸载后，使用Using XFormers backend则不会出现Cuda out of memory

flash_attn 的 block size 比较大，会有比较多的显存占用。

**Comment by qinxuye** [comment]
建议不要用 flash_attn，显存占用更多，实际上性能提升不明显。

**Comment by michaelxu1107** [comment]
> 建议不要用 flash_attn，显存占用更多，实际上性能提升不明显。

是的，性能几乎没啥提升

**Comment by qinxuye** [comment]
那这个问题主要是 flash_attn 导致的，可以 close 了？

**Comment by qinxuye** [comment]
ps 实际上我测试下来，flash_attn 比 xformers 还要慢，后续可以期待 flashinfer。

**Comment by michaelxu1107** [comment]
> 那这个问题主要是 flash_attn 导致的，可以 close 了？

是的，可以close了
