### ISSUE TITLE
BUG- xinference list cmdline run error

### ISSUE THREAD

**Issue by miracletiger** [xorbitsai/inference#1383]
### Describe the bug
 xinference list
Traceback (most recent call last):
  File "/data/anaconda3/envs/xinfer/bin/xinference", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/data/personal/zonghu.wang/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/personal/zonghu.wang/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/data/personal/zonghu.wang/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/personal/zonghu.wang/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/personal/zonghu.wang/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/xinfer/lib/python3.11/site-packages/xinference/deploy/cmdline.py", line 679, in model_list
    if model_spec["model_type"] == "LLM":
       ~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
### To Reproduce
python3.11 
xinference, version 0.9.1

**Comment by ChengjieLi28** [comment]
@miracletiger Uprade xinference to `v0.10.3`, then try your command.
