### ISSUE TITLE
The Chinese username path is incorrectly identified as a unicode character

### ISSUE THREAD

**Issue by 1542305589** [xorbitsai/inference#1549]
xinference-local
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\logging\config.py", line 573, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\logging\config.py", line 757, in configure_handler
    result = factory(**kwargs)
             ^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\logging\handlers.py", line 155, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "D:\Anaconda3\Lib\logging\handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "D:\Anaconda3\Lib\logging\__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\logging\__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ********************'C:\\Users\\u502a\\u6ca3\\.xinference\\logs\\local_1716925863388\\xinference.log'**********************

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Anaconda3\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda3\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\site-packages\xinference\deploy\cmdline.py", line 225, in local
    start_local_cluster(
  File "D:\Anaconda3\Lib\site-packages\xinference\deploy\cmdline.py", line 110, in start_local_cluster
    logging.config.dictConfig(dict_config)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda3\Lib\logging\config.py", line 823, in dictConfig
    dictConfigClass(config).configure()
  File "D:\Anaconda3\Lib\logging\config.py", line 580, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file_handler'

**Comment by 1542305589** [comment]
I think I've solved it myself, by adding the XINFERENCE_HOME environment variable

**Comment by kfchandsome** [comment]
> I think I've solved it myself, by adding the XINFERENCE_HOME environment variable

hi, whai is the XINFERENCE_HOME path?
