### ISSUE TITLE
fastGPT调用EmbeddingModel出错后Xinference挂起，其他所有运行模型都不能使用

### ISSUE THREAD

**Issue by zhapi1780** [xorbitsai/inference#1560]
### Describe the bug
fastGPT调用EmbeddingModel出错后Xinference挂起，其他所有运行模型都不能使用，xinference后台进程反复kill都不能结束进程，不得已重启服务器

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. conda py3.11.
2. xinference Release: v0.11.2.post1
3. 运行qwen1.5-chat、m3e-large、bge-reranker-v2-m3、Belle-distilwhisper-large-v2-zh.
4. 2024-05-30 01:41:31,630 xinference.core.model 14479 DEBUG    Request create_embedding, current serve request count: 0, request limit: None for the model m3e-large-66-1-0
2024-05-30 01:41:31,630 xinference.core.model 14479 DEBUG    After request create_embedding, current serve request count: 0 for the model m3e-large-66-1-0
2024-05-30 01:41:31,634 xinference.core.model 14479 DEBUG    After request create_embedding, current serve request count: 0 for the model m3e-large-66-1-0
2024-05-30 01:41:31,632 xinference.api.restful_api 3266 ERROR    [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1021, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 80, in wrapped_func
    ret = await fn(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 402, in create_embedding
    return await self._call_wrapper(
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 104, in _async_wrapper
    return await fn(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 333, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 284, in create_embedding
    all_embeddings, all_token_nums = encode(
    ^^^^^^^^^^^^^^^^^
TypeError: [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
2024-05-30 01:41:31,638 xinference.core.model 14479 DEBUG    After request create_embedding, current serve request count: 0 for the model m3e-large-66-1-0
2024-05-30 01:41:31,642 xinference.core.model 14479 DEBUG    After request create_embedding, current serve request count: 0 for the model m3e-large-66-1-0
2024-05-30 01:41:31,645 xinference.api.restful_api 3266 ERROR    [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1021, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 80, in wrapped_func
    ret = await fn(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 402, in create_embedding
    return await self._call_wrapper(
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 104, in _async_wrapper
    return await fn(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 333, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 284, in create_embedding
    all_embeddings, all_token_nums = encode(
    ^^^^^^^^^^^^^^^^^
TypeError: [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
2024-05-30 01:41:31,653 xinference.api.restful_api 3266 ERROR    [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1021, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 80, in wrapped_func
    ret = await fn(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 402, in create_embedding
    return await self._call_wrapper(
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 104, in _async_wrapper
    return await fn(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 333, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 284, in create_embedding
    all_embeddings, all_token_nums = encode(
    ^^^^^^^^^^^^^^^^^
TypeError: [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
2024-05-30 01:41:31,662 xinference.api.restful_api 3266 ERROR    [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1021, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 80, in wrapped_func
    ret = await fn(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 402, in create_embedding
    return await self._call_wrapper(
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 104, in _async_wrapper
    return await fn(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 333, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 284, in create_embedding
    all_embeddings, all_token_nums = encode(
    ^^^^^^^^^^^^^^^^^
TypeError: [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
2024-05-30 01:41:31,665 xinference.api.restful_api 3266 ERROR    [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1021, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 80, in wrapped_func
    ret = await fn(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 402, in create_embedding
    return await self._call_wrapper(
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 104, in _async_wrapper
    return await fn(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/core/model.py", line 333, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/py3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 284, in create_embedding
    all_embeddings, all_token_nums = encode(
    ^^^^^^^^^^^^^^^^^
TypeError: [address=0.0.0.0:46677, pid=14479] EmbeddingModel.create_embedding.<locals>.encode() got an unexpected keyword argument 'dimensions'
.
5. Minimized code to reproduce the error.
fastGPT config.json 配置
"vectorModels": [
    {
      "model": "m3e-large-66",
      "name": "m3e-large-66",
      "avatar": "/imgs/model/openai.svg",
      "charsPointsPrice": 0,
      "defaultToken": 512,
      "maxToken": 3000,
      "weight": 100,
      "dbConfig": {},
      "queryConfig": {},
      "defaultConfig": {
        "dimensions": 1024
      }
    },

**Comment by MecPan** [comment]
同样的错误，我是用的fastgpt + one-api + xinference

**Comment by Acc1143** [comment]
一样的错误不明白怎么回事

**Comment by Acc1143** [comment]
解决了，把这玩意删掉
![Uploading Snipaste_2024-06-07_09-52-22.png…]()

**Comment by Acc1143** [comment]
![Uploading Snipaste_2024-06-07_09-52-22.png…]()

**Comment by Acc1143** [comment]
![Uploading Snipaste_2024-06-07_09-52-22.png…]()
