### ISSUE TITLE
Install failed: AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by MountainGG** [xorbitsai/inference#1574]
### Describe the bug
(base) root@930221811a20:~# pip install xinference[all]
Collecting xinference[all]
  Using cached xinference-0.11.3-py3-none-any.whl.metadata (15 kB)
Collecting xoscar>=0.3.0 (from xinference[all])
  Using cached xoscar-0.3.0.tar.gz (125 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/root/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/miniconda3/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-82k9lqyl/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-82k9lqyl/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-82k9lqyl/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### To Reproduce
1. Python3.12.
2. The version of xinference, latest may be.

**Comment by MountainGG** [comment]
(base) root@930221811a20:~# pip list
Package                  Version
------------------------ -----------
aifs                     0.0.15
aiohttp                  3.9.5
aiosignal                1.3.1
anaconda-anon-usage      0.4.4
annotated-types          0.7.0
anyio                    4.4.0
archspec                 0.2.3
astor                    0.8.1
asttokens                2.4.1
attrs                    23.2.0
backoff                  2.2.1
blessed                  1.20.0
boltons                  23.0.0
Brotli                   1.0.9
certifi                  2024.2.2
cffi                     1.16.0
charset-normalizer       2.0.4
click                    8.1.7
comm                     0.2.2
conda                    24.4.0
conda-content-trust      0.2.0
conda-libmamba-solver    24.1.0
conda-package-handling   2.2.0
conda_package_streaming  0.9.0
contourpy                1.2.1
cryptography             42.0.5
cycler                   0.12.1
debugpy                  1.8.1
decorator                5.1.1
distro                   1.9.0
editor                   1.6.6
executing                2.0.1
fastapi                  0.110.3
filelock                 3.14.0
fonttools                4.53.0
frozenlist               1.4.1
fsspec                   2024.5.0
git-python               1.0.3
gitdb                    4.0.11
GitPython                3.1.43
h11                      0.14.0
html2image               2.0.4.3
httpcore                 1.0.5
httpx                    0.27.0
huggingface-hub          0.23.2
idna                     3.7
importlib_metadata       7.1.0
inquirer                 3.2.4
ipykernel                6.29.4
ipython                  8.25.0
jedi                     0.19.1
Jinja2                   3.1.4
joblib                   1.4.2
jsonpatch                1.33
jsonpointer              2.1
jupyter_client           8.6.2
jupyter_core             5.7.2
kiwisolver               1.4.5
libmambapy               1.5.8
litellm                  1.39.6
markdown-it-py           3.0.0
MarkupSafe               2.1.5
matplotlib               3.9.0
matplotlib-inline        0.1.7
mdurl                    0.1.2
menuinst                 2.0.2
monotonic                1.6
mpmath                   1.3.0
multidict                6.0.5
nest-asyncio             1.6.0
networkx                 3.3
nltk                     3.8.1
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.5.40
nvidia-nvtx-cu12         12.1.105
open-interpreter         0.2.5
openai                   1.30.5
packaging                23.2
parso                    0.8.4
pexpect                  4.9.0
pillow                   10.3.0
pip                      24.0
platformdirs             4.2.2
pluggy                   1.0.0
posthog                  3.5.0
prompt_toolkit           3.0.45
psutil                   5.9.8
ptyprocess               0.7.0
pure-eval                0.2.2
pycosat                  0.6.6
pycparser                2.21
pydantic                 2.7.2
pydantic_core            2.18.3
Pygments                 2.18.0
pyparsing                3.1.2
PySocks                  1.7.1
python-dateutil          2.9.0.post0
python-dotenv            1.0.1
PyYAML                   6.0.1
pyzmq                    26.0.3
readchar                 4.1.0
regex                    2024.5.15
requests                 2.31.0
rich                     13.7.1
ruamel.yaml              0.17.21
runs                     1.2.2
screeninfo               0.8.1
Send2Trash               1.8.3
setuptools               70.0.0
six                      1.16.0
smmap                    5.0.1
sniffio                  1.3.1
stack-data               0.6.3
starlette                0.37.2
sympy                    1.12.1
tiktoken                 0.6.0
tokenizers               0.19.1
tokentrim                0.1.13
toml                     0.10.2
torch                    2.3.0
tornado                  6.4
tqdm                     4.66.2
traitlets                5.14.3
truststore               0.8.0
typing_extensions        4.12.0
urllib3                  2.1.0
uvicorn                  0.27.1
wcwidth                  0.2.13
websocket-client         1.8.0
wget                     3.2
wheel                    0.43.0
xmod                     1.8.1
yarl                     1.9.4
zipp                     3.19.1
zstandard                0.22.0

**Comment by qinxuye** [comment]
Python 3.12 is not supported yet.

**Comment by Jalen-Zhong** [comment]
Same promlem at 2024/7/29. Still not be fixed

**Comment by jerryjedi** [comment]
At first [xoscar](https://github.com/xorbitsai/xoscar) need to support python 3.12. I met the same problem.

**Comment by qinxuye** [comment]
Yes, Xoscar has not supported Python 3.12.
