### ISSUE TITLE
QUESTION：GLM-4V-9B为什么没有4bit量化版本，我看官方性能测试里面是有的

### ISSUE THREAD

**Issue by gmaimmortal** [xorbitsai/inference#1609]
我是docker运行的nightly-main版本，今天早上刚刚pull的
可以运行glm4-chat 4bit版本和glm-4v，但是glm-4v的4bit量化版本运行时报错，提示模型不存在
以下是运行日志：
```shell
# xinference launch --model-engine Transformers --model-name glm-4v --size-in-billions 9 --model-format pytorch --quantization 4-bit
Launch model name: glm-4v with kwargs: {}
Traceback (most recent call last):
  File "/opt/conda/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 814, in model_launch
    model_uid = client.launch_model(
  File "/opt/conda/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 907, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:47447, pid=63] Model not found, name: glm-4v, format: pytorch, size: 9, quantization: 4-bit
```

官方性能测试报告：
![image](https://github.com/xorbitsai/inference/assets/47653038/45f0e9b4-685b-47be-be33-24c9ff01c7ab)

**Comment by gmaimmortal** [comment]
我是docker运行的nightly-main版本，今天早上刚刚pull的

**Comment by okwinds** [comment]
直接推就行了
