### ISSUE TITLE
机器上有两张卡，启动一直报错

### ISSUE THREAD

**Issue by kangkang721** [xorbitsai/inference#1633]
Note that the issue tracker is NOT the place for general support.
2024-06-13 06:06:31,034 xinference.core.supervisor 63 INFO     Xinference supervisor 0.0.0.0:13602 started
2024-06-13 06:06:35,130 xinference.core.worker 63 INFO     Starting metrics export server at 0.0.0.0:None
2024-06-13 06:06:35,133 xinference.core.worker 63 INFO     Checking metrics export server...
2024-06-13 06:06:36,778 xinference.core.worker 63 INFO     Metrics server is started at: http://0.0.0.0:40018
2024-06-13 06:06:36,779 xinference.core.worker 63 INFO     Xinference worker 0.0.0.0:13602 started
2024-06-13 06:06:36,780 xinference.core.worker 63 INFO     Purge cache directory: /root/.xinference/cache
2024-06-13 06:06:38,294 xinference.api.restful_api 1 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997
2024-06-13 06:06:38,782 xinference.core.worker 63 ERROR    Report status got error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/worker.py", line 762, in report_status
    status = await asyncio.to_thread(gather_node_info)
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

**Comment by codingl2k1** [comment]
一张卡时没问题吗？你用的什么版本xinference？

**Comment by Modas-Li** [comment]
same issue, did you solve it?

**Comment by Charmnut** [comment]
same issue, did you solve it?
