### ISSUE TITLE
[QUESTION]  Failed to import module 'SentenceTransformer'

### ISSUE THREAD

**Issue by MichaelYang1995** [xorbitsai/inference#1703]
Note that the issue tracker is NOT the place for general support.
I install xinference[transformers]

use Embedding Model "bge-large-zh-v1.5"
but there are some error.

**Error log**:
2024-06-23 13:15:22,898 xinference.core.supervisor 40682 INFO     Xinference supervisor 10.1.154.242:38235 started
2024-06-23 13:15:22,915 xinference.core.worker 40682 INFO     Starting metrics export server at 10.1.154.242:None
2024-06-23 13:15:22,915 xinference.core.worker 40682 INFO     Checking metrics export server...
2024-06-23 13:15:24,973 xinference.core.worker 40682 INFO     Metrics server is started at: http://10.1.154.242:54246
2024-06-23 13:15:24,975 xinference.core.worker 40682 INFO     Xinference worker 10.1.154.242:38235 started
2024-06-23 13:15:24,975 xinference.core.worker 40682 INFO     Purge cache directory: /Users/yangqingyuan/.xinference/cache
2024-06-23 13:15:27,278 xinference.api.restful_api 40660 INFO     Starting Xinference at endpoint: http://10.1.154.242:9997
.gitattributes: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.52k/1.52k [00:00<00:00, 8.35MB/s]
config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.00k/1.00k [00:00<00:00, 7.35MB/s]
modules.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 349/349 [00:00<00:00, 2.84MB/s]
config_sentence_transformers.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 124/124 [00:00<00:00, 268kB/s]
1_Pooling/config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 191/191 [00:00<00:00, 1.23MB/s]
README.md: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26.4k/26.4k [00:00<00:00, 55.0MB/s]
special_tokens_map.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 125/125 [00:00<00:00, 762kB/s]
sentence_bert_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 52.0/52.0 [00:00<00:00, 289kB/s]
tokenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 394/394 [00:00<00:00, 8.35MB/s]
vocab.txt: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 110k/110k [00:00<00:00, 113kB/s]
tokenizer.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 439k/439k [00:04<00:00, 95.0kB/s]
pytorch_model.bin: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.30G/1.30G [03:37<00:00, 5.98MB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.30G/1.30G [03:50<00:00, 5.65MB/s]
Fetching 13 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [03:51<00:00, 17.82s/it]
2024-06-23 13:19:36,344 xinference.core.worker 40682 ERROR    Failed to load model bge-large-zh-v1.5-1-0██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.30G/1.30G [03:50<00:00, 12.1MB/s]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 130, in load
    from sentence_transformers import SentenceTransformer
    ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sentence_transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/worker.py", line 665, in launch_builtin_model
    await model_ref.load()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/model.py", line 278, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 138, in load
    raise ImportError(f"{error_message}\n\n{''.join(installation_guide)}")
    ^^^^^^^^^^^^^^^^^
ImportError: [address=10.1.154.242:54350, pid=40745] Failed to import module 'SentenceTransformer'

Please make sure 'sentence-transformers' is installed. You can install it by `pip install sentence-transformers`

2024-06-23 13:19:36,361 xinference.api.restful_api 40660 ERROR    [address=10.1.154.242:54350, pid=40745] Failed to import module 'SentenceTransformer'

Please make sure 'sentence-transformers' is installed. You can install it by `pip install sentence-transformers`
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 130, in load
    from sentence_transformers import SentenceTransformer
    ^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'sentence_transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/api/restful_api.py", line 771, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/supervisor.py", line 837, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/supervisor.py", line 801, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/supervisor.py", line 782, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/worker.py", line 665, in launch_builtin_model
    await model_ref.load()
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/core/model.py", line 278, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 138, in load
    raise ImportError(f"{error_message}\n\n{''.join(installation_guide)}")
    ^^^^^^^^^^^^^^^^^
ImportError: [address=10.1.154.242:54350, pid=40745] Failed to import module 'SentenceTransformer'

Please make sure 'sentence-transformers' is installed. You can install it by `pip install sentence-transformers`

=================================================================================================

**But I'm sure I installed `sentence-transformers         3.0.1`
Someone could help me?**

**env**:
`python: 3.11`
`os: macOS-14.4-arm64-arm-64bit.`
`venv: Poetry`

**pip list**:
Package                       Version
----------------------------- ------------
accelerate                    0.31.0
addict                        2.4.0
aiobotocore                   2.7.0
aiofiles                      23.2.1
aiohttp                       3.9.5
aioitertools                  0.11.0
aioprometheus                 23.12.0
aiosignal                     1.3.1
aliyun-python-sdk-core        2.15.1
aliyun-python-sdk-kms         2.16.3
altair                        5.3.0
annotated-types               0.7.0
anyio                         4.4.0
async-timeout                 4.0.3
attrdict                      2.0.1
attrs                         23.2.0
bcrypt                        4.1.3
bitsandbytes                  0.42.0
botocore                      1.31.64
certifi                       2024.6.2
cffi                          1.16.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpickle                   3.0.0
colorama                      0.4.6
coloredlogs                   15.0.1
contourpy                     1.2.1
crcmod                        1.7
cryptography                  42.0.8
cycler                        0.12.1
Cython                        3.0.10
datasets                      2.18.0
dill                          0.3.8
distro                        1.9.0
ecdsa                         0.19.0
einops                        0.8.0
fastapi                       0.110.3
ffmpy                         0.3.2
filelock                      3.15.4
fonttools                     4.53.0
frozenlist                    1.4.1
fsspec                        2023.10.0
gast                          0.5.4
gradio                        4.26.0
gradio_client                 0.15.1
h11                           0.14.0
httpcore                      1.0.5
httpx                         0.27.0
huggingface-hub               0.23.4
humanfriendly                 10.0
idna                          3.7
importlib_metadata            7.2.0
importlib_resources           6.4.0
Jinja2                        3.1.4
jmespath                      0.10.0
joblib                        1.4.2
jsonschema                    4.22.0
jsonschema-specifications     2023.12.1
kiwisolver                    1.4.5
markdown-it-py                3.0.0
MarkupSafe                    2.1.5
matplotlib                    3.9.0
mdurl                         0.1.2
modelscope                    1.15.0
mpmath                        1.3.0
multidict                     6.0.5
multiprocess                  0.70.16
networkx                      3.3
numpy                         1.26.4
openai                        1.35.3
opencv-contrib-python         4.10.0.84
optimum                       1.20.0
orjson                        3.10.5
oss2                          2.18.6
packaging                     24.1
pandas                        2.2.2
passlib                       1.7.4
peft                          0.11.1
pillow                        10.3.0
pip                           24.1
platformdirs                  4.2.2
protobuf                      5.27.1
psutil                        6.0.0
pyarrow                       16.1.0
pyarrow-hotfix                0.6
pyasn1                        0.6.0
pycparser                     2.22
pycryptodome                  3.20.0
pydantic                      2.7.4
pydantic_core                 2.18.4
pydub                         0.25.1
Pygments                      2.18.0
pynvml                        11.5.0
pyparsing                     3.1.2
python-dateutil               2.9.0.post0
python-jose                   3.3.0
python-multipart              0.0.9
pytz                          2024.1
PyYAML                        6.0.1
quantile-python               1.1
referencing                   0.35.1
regex                         2024.5.15
requests                      2.32.3
rich                          13.7.1
rpds-py                       0.18.1
rsa                           4.9
ruff                          0.4.10
s3fs                          2023.10.0
safetensors                   0.4.3
scikit-learn                  1.5.0
scipy                         1.13.1
semantic-version              2.10.0
sentence-transformers         3.0.1
sentencepiece                 0.2.0
setuptools                    70.1.0
shellingham                   1.5.4
simplejson                    3.19.2
six                           1.16.0
sniffio                       1.3.1
sortedcontainers              2.4.0
sse-starlette                 2.1.2
starlette                     0.37.2
sympy                         1.12.1
tabulate                      0.9.0
tblib                         3.0.0
threadpoolctl                 3.5.0
tiktoken                      0.7.0
timm                          1.0.7
tokenizers                    0.19.1
tomli                         2.0.1
tomlkit                       0.12.0
toolz                         0.12.1
torch                         2.3.1
torchvision                   0.18.1
tqdm                          4.66.4
transformers                  4.41.2
transformers-stream-generator 0.0.5
typer                         0.11.1
typing_extensions             4.12.2
tzdata                        2024.1
urllib3                       2.0.7
uvicorn                       0.30.1
uvloop                        0.19.0
websockets                    11.0.3
wheel                         0.43.0
wrapt                         1.16.0
xinference                    0.12.2.post1
xoscar                        0.3.0
xxhash                        3.4.1
yapf                          0.40.2
yarl                          1.9.4
zipp                          3.19.2

**Comment by MichaelYang1995** [comment]
Okay, I pip install sentence-transformers in my local env is deal this question.

**Comment by doing-cr7** [comment]
hi i have a question,ValueError: [address=0.0.0.0:31149, pid=20] Model bge-large-zh-v1.5 cannot be run on engine sentence_transformers ,could you help me ,How to launch xinfrence use docker !

**Comment by xiaoli-white** [comment]
Run pip install -U accelerate in your container.
