### ISSUE TITLE
[Bug] TypeError: [address=0.0.0.0:35683, pid=711500] CrossEncoder.init() got an unexpected keyword argument 'peft_model_path'

### ISSUE THREAD

**Issue by Shengshenlan** [xorbitsai/inference#1727]
### Describe the bug
Traceback (most recent call last):
  File "/dd/inference/xinference/api/restful_api.py", line 771, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/dd/inference/xinference/core/supervisor.py", line 837, in launch_builtin_model
    await _launch_model()
  File "/dd/inference/xinference/core/supervisor.py", line 801, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/dd/inference/xinference/core/supervisor.py", line 782, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/dd/inference/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/dd/inference/xinference/core/worker.py", line 665, in launch_builtin_model
    await model_ref.load()
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/llama3/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/dd/inference/xinference/core/model.py", line 278, in load
    self._model.load()
  File "/dd/inference/xinference/model/rerank/core.py", line 164, in load
    self._model = CrossEncoder(
TypeError: [address=0.0.0.0:35683, pid=711500] CrossEncoder.__init__() got an unexpected keyword argument 'peft_model_path'

### To Reproduce
from xinference.client import Client

client = Client("http://192.168.1.115:9997")
model_uid = client.launch_model(model_name="bge-reranker-base", model_type="rerank")
model = client.get_model(model_uid)

query = "A man is eating pasta."
corpus = [
    "A man is eating food.",
    "A man is eating a piece of bread.",
    "The girl is carrying a baby.",
    "A man is riding a horse.",
    "A woman is playing violin."
]
print(model.rerank(corpus, query))

### Expected behavior
调用失败

**Comment by ChengjieLi28** [comment]
@Shengshenlan 哪个版本的xinference？无法复现。我这边是最新的代码：
<img width="1666" alt="image" src="https://github.com/xorbitsai/inference/assets/109656400/a67048a0-4187-483a-b949-3c286eec37c6">
