### ISSUE TITLE
chatglm3 使用agent报错 unhashable type: 'slice'

### ISSUE THREAD

**Issue by zmh2000829** [xorbitsai/inference#1729]
### Describe the bug
使用langchain-chatchat基于xinference chatglm3调用开启Agent能力，问答报错 unhashable type: 'slice'

### To Reproduce
python 3.10
xinference 0.12.1
langchain-chatchat 0.3.0

2024-06-27 15:12:01,255 xinference.api.restful_api 3874224 ERROR    Chat completion stream got an error: [address=0.0.0.0:36809, pid=3905684] unhashable type: 'slice'
Traceback (most recent call last):
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1476, in stream_results
    async for item in iterator:
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/api.py", line 431, in __xoscar_next__
    raise e
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/api.py", line 417, in __xoscar_next__
    r = await asyncio.to_thread(_wrapper, gen)
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xoscar/api.py", line 402, in _wrapper
    return next(_gen)
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xinference/core/model.py", line 300, in _to_json_generator
    for v in gen:
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xinference/model/llm/utils.py", line 544, in _to_chat_completion_chunks
    for i, chunk in enumerate(chunks):
  File "/home/xx/miniconda3/envs/LLM_x/lib/python3.10/site-packages/xinference/model/llm/pytorch/chatglm.py", line 177, in _stream_generator
    chunk_text = chunk_text[last_chunk_text_length:]
TypeError: [address=0.0.0.0:36809, pid=3905684] unhashable type: 'slice'

**Comment by zmh2000829** [comment]
> This error is weird,

已使用Xinference-0.12.3，报错相同，增加如下打印，请帮忙查看问题原因
![image](https://github.com/xorbitsai/inference/assets/44742019/4c839d6f-ff52-4905-8264-9e70c60d299d)
![image](https://github.com/xorbitsai/inference/assets/44742019/2ec10d0e-b3b8-49ff-90fd-a61395cf8fba)

**Comment by moyangjiayou** [comment]
遇到同样的问题了~ 求解决

**Comment by moyangjiayou** [comment]
您好！我是莫洋，我已经收到您的来信了！

**Comment by moyangjiayou** [comment]
您好！我是莫洋，我已经收到您的来信了！
