### ISSUE TITLE
运行GLM-4v报错参数不符合

### ISSUE THREAD

**Issue by a914356887** [xorbitsai/inference#1789]
1. 版本: xinference==0.12.3, GPU==AD102 48G,  CUAA==cuda_12.2.r12.2
2. 启动方式: xinference-local --host 0.0.0.0 --port 9997
3. 模型启动: xinference launch --model-engine Transformers --model-name glm-4v --size-in-billions 9 --model-format pytorch --quantization none
4. 报错
2024-07-05 08:56:46,554 xinference.api.restful_api 1659 ERROR    [address=0.0.0.0:37429, pid=1758] too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1477, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 87, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 473, in chat
    response = await self._call_wrapper(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 111, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 369, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/miniconda3/envs/xinf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/llm/pytorch/glm4v.py", line 199, in chat
    outputs = self._model.generate(**generate_kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 1188, in forward
    transformer_outputs = self.transformer(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 1056, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 790, in forward
    layer_ret = layer(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 693, in forward
    attention_output, kv_cache = self.self_attention(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 562, in forward
    cache_k, cache_v = kv_cache
ValueError: [address=0.0.0.0:37429, pid=1758] too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/utils.py", line 583, in async_iteration
    return await iterator.__anext__()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/gradio/utils.py", line 742, in gen_wrapper
    response = next(iterator)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/chat_interface.py", line 229, in predict
    response = model.chat(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 421, in chat
    raise RuntimeError(
RuntimeError: Failed to generate chat completion, detail: [address=0.0.0.0:37429, pid=1758] too many values to unpack (expected 2)

**Comment by a914356887** [comment]
已经找到问题, 需要把transformers降低到4.40.2

**Comment by zachary-zheng** [comment]
@a914356887 @ChengjieLi28 xinference==0.13.2   transformers==4.40.2 
仍然报这个错误

**Comment by a914356887** [comment]
> @a914356887 @ChengjieLi28xinference==0.13.2 Transformers==4.40.2 仍然报这个错误

这个得看你的版本了
