### ISSUE TITLE
cogvlm2 交互界面失败

### ISSUE THREAD

**Issue by menkeyi001** [xorbitsai/inference#1799]
Note that the issue tracker is NOT the place for general support.

上传完文件+提示问题 提交就报这个错误  

AttributeError: [address=0.0.0.0:44421, pid=128985] 'str' object has no attribute 'shape'
Traceback (most recent call last):
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/utils.py", line 583, in async_iteration
    return await iterator.__anext__()
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/gradio/utils.py", line 742, in gen_wrapper
    response = next(iterator)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/chat_interface.py", line 229, in predict
    response = model.chat(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 423, in chat
    raise RuntimeError(
RuntimeError: Failed to generate chat completion, detail: [address=0.0.0.0:44421, pid=128985] 'str' object has no attribute 'shape'

**Comment by qinxuye** [comment]
升级到 0.13.0 依然有这个问题吗？

**Comment by GarrickLin** [comment]
pip install transformer==4.40  https://github.com/THUDM/CogVLM2/issues/134

**Comment by ZG688** [comment]
> pip install transformer==4.40 [THUDM/CogVLM2#134](https://github.com/THUDM/CogVLM2/issues/134)

我装到4.4还是不行，报错是RuntimeError: Failed to generate completion, detail: [address=127.0.0.1:50477, pid=1780] 'str' object has no attribute 'get'
