### ISSUE TITLE
BUG 无法加载ChatTTS模型

### ISSUE THREAD

**Issue by NTLx** [xorbitsai/inference#1820]
### Describe the bug
加载ChatTTS模型时报错。

### To Reproduce
To help us to reproduce this bug, please provide information below:

我使用的是 `xprobe/xinference:latest-cpu` docker部署，MANIFEST DIGEST sha256:7660c8485d36dd75fcea87768f6073f0b86d77e458b968a7b843f1167d9a3d05

### Expected behavior
正常加载ChatTTS模型。

### Additional context
docker容器日志（docekr-compose）：
```
xinference    | 2024-07-09 14:51:11,100 xinference.core.supervisor 39 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f1b0966e390>, 'LLM'), kwargs: {'detailed': True}
xinference    | 2024-07-09 14:51:11,169 xinference.core.supervisor 39 DEBUG    Leave list_model_registrations, elapsed time: 0 s
xinference    | 2024-07-09 14:51:12,396 xinference.core.supervisor 39 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f1b0966e390>, 'audio'), kwargs: {'detailed': True}
xinference    | 2024-07-09 14:51:12,400 xinference.core.supervisor 39 DEBUG    Leave list_model_registrations, elapsed time: 0 s
xinference    | 2024-07-09 14:51:30,489 xinference.core.supervisor 39 DEBUG    Enter launch_builtin_model, model_uid: ChatTTS, model_name: ChatTTS, model_size: , model_format: None, quantization: None, replica: 1, kwargs: {}
xinference    | 2024-07-09 14:51:30,490 xinference.core.worker 39 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7f1b096db5f0>,), kwargs: {}
xinference    | 2024-07-09 14:51:30,490 xinference.core.worker 39 DEBUG    Leave get_model_count, elapsed time: 0 s
xinference    | 2024-07-09 14:51:30,490 xinference.core.worker 39 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7f1b096db5f0>,), kwargs: {'model_uid': 'ChatTTS-1-0', 'model_name': 'ChatTTS', 'model_size_in_billions': None, 'model_format': None, 'quantization': None, 'model_engine': None, 'model_type': 'audio', 'n_gpu': 'auto', 'request_limits': None, 'peft_model_config': None, 'gpu_idx': None}
xinference    | 2024-07-09 14:51:33,983 xinference.core.worker 39 ERROR    Failed to load model ChatTTS-1-0
xinference    | Traceback (most recent call last):
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 673, in launch_builtin_model
xinference    |     await model_ref.load()
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
xinference    |     return self._process_result_message(result)
xinference    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
xinference    |     raise message.as_instanceof_cause()
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
xinference    |     result = await self._run_coro(message.message_id, coro)
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
xinference    |     return await coro
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
xinference    |     return await super().__on_receive__(message)  # type: ignore
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 558, in __on_receive__
xinference    |     raise ex
xinference    |   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
xinference    |     async with self._lock:
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
xinference    |     with debug_async_timeout('actor_lock_timeout',
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
xinference    |     result = await result
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/model.py", line 278, in load
xinference    |     self._model.load()
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/chattts.py", line 43, in load
xinference    |     from xinference.thirdparty import ChatTTS
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/thirdparty/ChatTTS/__init__.py", line 1, in <module>
xinference    |     from .core import Chat
xinference    |           ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/thirdparty/ChatTTS/core.py", line 5, in <module>
xinference    |     from omegaconf import OmegaConf
xinference    |           ^^^^^^^^^^^^^^^^^
xinference    | ModuleNotFoundError: [address=0.0.0.0:35749, pid=723] No module named 'omegaconf'
xinference    | 2024-07-09 14:51:34,015 xinference.core.supervisor 39 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f1b0966e390>, 'ChatTTS'), kwargs: {'suppress_exception': True}
xinference    | 2024-07-09 14:51:34,015 xinference.core.supervisor 39 DEBUG    Leave terminate_model, elapsed time: 0 s
xinference    | 2024-07-09 14:51:34,019 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:35749, pid=723] No module named 'omegaconf'
xinference    | Traceback (most recent call last):
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/api/restful_api.py", line 822, in launch_model
xinference    |     model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
xinference    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
xinference    |     return self._process_result_message(result)
xinference    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
xinference    |     raise message.as_instanceof_cause()
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
xinference    |     result = await self._run_coro(message.message_id, coro)
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
xinference    |     return await coro
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
xinference    |     return await super().__on_receive__(message)  # type: ignore
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 558, in __on_receive__
xinference    |     raise ex
xinference    |   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
xinference    |     async with self._lock:
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
xinference    |     with debug_async_timeout('actor_lock_timeout',
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
xinference    |     result = await result
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 871, in launch_builtin_model
xinference    |     await _launch_model()
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 835, in _launch_model
xinference    |     await _launch_one_model(rep_model_uid)
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 816, in _launch_one_model
xinference    |     await worker_ref.launch_builtin_model(
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
xinference    |     async with lock:
xinference    |   File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
xinference    |     result = await result
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
xinference    |     ret = await func(*args, **kwargs)
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 673, in launch_builtin_model
xinference    |     await model_ref.load()
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
xinference    |     return self._process_result_message(result)
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
xinference    |     raise message.as_instanceof_cause()
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 659, in send
xinference    |     result = await self._run_coro(message.message_id, coro)
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
xinference    |     return await coro
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
xinference    |     return await super().__on_receive__(message)  # type: ignore
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 558, in __on_receive__
xinference    |     raise ex
xinference    |   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
xinference    |     async with self._lock:
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
xinference    |     with debug_async_timeout('actor_lock_timeout',
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
xinference    |     result = await result
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/core/model.py", line 278, in load
xinference    |     self._model.load()
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/chattts.py", line 43, in load
xinference    |     from xinference.thirdparty import ChatTTS
xinference    |     ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/thirdparty/ChatTTS/__init__.py", line 1, in <module>
xinference    |     from .core import Chat
xinference    |           ^^^^^^^^^^^^^^^^^
xinference    |   File "/opt/conda/lib/python3.11/site-packages/xinference/thirdparty/ChatTTS/core.py", line 5, in <module>
xinference    |     from omegaconf import OmegaConf
xinference    |           ^^^^^^^^^^^^^^^^^
xinference    | ModuleNotFoundError: [address=0.0.0.0:35749, pid=723] No module named 'omegaconf'
```

**Comment by NTLx** [comment]
This problem was solved.

**Comment by lu598110900** [comment]
how to do slove this issue?

> 这个问题已经解决。
