### ISSUE TITLE
BUG: ChatTTS voice NoneType error

### ISSUE THREAD

**Issue by halexan** [xorbitsai/inference#1826]
### Describe the bug

When using the ChatTTS model, if 'voice' is None, a NoneType ERROR reported.

It is recommended to allow 'input' and 'voice' to be null values. So it is easier integrated with Dify.

The error log:

``` python
2024-07-09 23:49:49,688 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:36309, pid=285] a bytes-like object is required, not 'NoneType'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1302, in create_speech
    out = await model.speech(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 637, in speech
    return await self._call_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 394, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/chattts.py", line 61, in speech
    seed = xxhash.xxh32_intdigest(voice)
TypeError: [address=0.0.0.0:36309, pid=285] a bytes-like object is required, not 'NoneType'
```

### To Reproduce

using docker image xprobe/xinference:v0.13.0

### Expected behavior

HttpResponse '20X'

**Comment by qinxuye** [comment]
According to OpenAI doc, https://platform.openai.com/docs/api-reference/audio/createSpeech

`input` and `voice` are required arguments.
