### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by silver0919** [xorbitsai/inference#1828]
### Describe the bug
运行 pip install "xinference[all]" 命令安装xinference全部依赖
运行 XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 9997 启动服务
在网页端选择bce-embedding-base_v1模型，点击launch后报错
![image](https://github.com/xorbitsai/inference/assets/170061902/a437ca68-6d66-4ed9-92ce-58a0547d0c72)
![image](https://github.com/xorbitsai/inference/assets/170061902/c1af158c-a054-41f2-a1c0-1b28dcb7b122)

2024-07-10 15:16:15,833 xinference.core.worker 809038 ERROR    Failed to load model bce-embedding-base_v1-1-0
Traceback (most recent call last):
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1560, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/trainer.py", line 214, in <module>
    from peft import PeftModel
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/mapping.py", line 22, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/mixed_model.py", line 26, in <module>
    from peft.tuners.mixed import COMPATIBLE_TUNER_TYPES
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/tuners/__init__.py", line 26, in <module>
    from .boft import BOFTConfig, BOFTModel
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/tuners/boft/__init__.py", line 16, in <module>
    from .layer import BOFTLayer
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/tuners/boft/layer.py", line 30, in <module>
    from torch.utils.cpp_extension import load
  File "/home/cloud01/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 28, in <module>
    from pkg_resources import packaging  # type: ignore[attr-defined]
ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/cloud01/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/worker.py", line 684, in launch_builtin_model
    await model_ref.load()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/model/embedding/core.py", line 130, in load
    from sentence_transformers import SentenceTransformer
  File "/home/cloud01/.local/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 15, in <module>
    from sentence_transformers.trainer import SentenceTransformerTrainer
  File "/home/cloud01/.local/lib/python3.10/site-packages/sentence_transformers/trainer.py", line 10, in <module>
    from transformers import EvalPrediction, PreTrainedTokenizerBase, Trainer, TrainerCallback
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1550, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1562, in _get_module
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:36301, pid=845922] Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'packaging' from 'pkg_resources' (/home/cloud01/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)
2024-07-10 15:16:15,887 xinference.api.restful_api 808614 ERROR    [address=0.0.0.0:36301, pid=845922] Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'packaging' from 'pkg_resources' (/home/cloud01/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)
Traceback (most recent call last):
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1560, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/trainer.py", line 214, in <module>
    from peft import PeftModel
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/mapping.py", line 22, in <module>
    from .mixed_model import PeftMixedModel
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/mixed_model.py", line 26, in <module>
    from peft.tuners.mixed import COMPATIBLE_TUNER_TYPES
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/tuners/__init__.py", line 26, in <module>
    from .boft import BOFTConfig, BOFTModel
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/tuners/boft/__init__.py", line 16, in <module>
    from .layer import BOFTLayer
  File "/home/cloud01/.local/lib/python3.10/site-packages/peft/tuners/boft/layer.py", line 30, in <module>
    from torch.utils.cpp_extension import load
  File "/home/cloud01/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 28, in <module>
    from pkg_resources import packaging  # type: ignore[attr-defined]
ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/cloud01/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/api/restful_api.py", line 822, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/supervisor.py", line 871, in launch_builtin_model
    await _launch_model()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/supervisor.py", line 835, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/supervisor.py", line 816, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/worker.py", line 684, in launch_builtin_model
    await model_ref.load()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/cloud01/.local/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
  File "/home/cloud01/.local/lib/python3.10/site-packages/xinference/model/embedding/core.py", line 130, in load
    from sentence_transformers import SentenceTransformer
  File "/home/cloud01/.local/lib/python3.10/site-packages/sentence_transformers/__init__.py", line 15, in <module>
    from sentence_transformers.trainer import SentenceTransformerTrainer
  File "/home/cloud01/.local/lib/python3.10/site-packages/sentence_transformers/trainer.py", line 10, in <module>
    from transformers import EvalPrediction, PreTrainedTokenizerBase, Trainer, TrainerCallback
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1550, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/cloud01/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1562, in _get_module
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:36301, pid=845922] Failed to import transformers.trainer because of the following error (look up to see its traceback):
cannot import name 'packaging' from 'pkg_resources' (/home/cloud01/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version: 3.12.4
2. The version of xinference you use: 0.13.0
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Expected behavior
完成本地部署bce-embedding-base_v1模型

**Comment by qinxuye** [comment]
`pip install 'setuptools==69.5.1'`
