### ISSUE TITLE
cogvlm2 推理异常

### ISSUE THREAD

**Issue by atlasroben** [xorbitsai/inference#1836]
### System Info / 系統信息

linux 系统
最新版本xinference
2卡A100 40G

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Name: xinference
Version: 0.13.0
Summary: Model Serving Made Easy
Home-page: https://github.com/xorbitsai/inference
Author: Qin Xuye
Author-email: qinxuye@xprobe.io
License: Apache License 2.0
Location: /home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages
Requires: aioprometheus, async-timeout, click, fastapi, fsspec, gradio, huggingface-hub, modelscope, openai, opencv-contrib-python, passlib, peft, pillow, pydantic, pynvml, python-jose, requests, s3fs, sse-starlette, tabulate, timm, torch, tqdm, typer, typing-extensions, uvicorn, xoscar

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 8801

### Reproduction / 复现过程

2024-07-10 21:49:54,812 xinference.api.restful_api 5163 ERROR [address=0.0.0.0:46525, pid=5215] 'str' object has no attribute 'shape'
Traceback (most recent call last):
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1566, in create_chat_completion
data = await model.chat(
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
return self._process_result_message(result)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
raise message.as_instanceof_cause()
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
result = await self._run_coro(message.message_id, coro)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
return await coro
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xoscar/api.py", line 384, in on_receive
return await super().on_receive(message) # type: ignore
^^^^^^^^^^^^^^^^^
File "xoscar/core.pyx", line 558, in on_receive
raise ex
File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.on_receive
async with self._lock:
^^^^^^^^^^^^^^^^^
File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.on_receive
with debug_async_timeout('actor_lock_timeout',
^^^^^^^^^^^^^^^^^
File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.on_receive
result = await result
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
ret = await func(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/core/model.py", line 90, in wrapped_func
ret = await fn(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xoscar/api.py", line 462, in _wrapper
r = await func(self, *args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/core/model.py", line 505, in chat
response = await self._call_wrapper(
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/core/model.py", line 114, in _async_wrapper
return await fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/core/model.py", line 388, in _call_wrapper
ret = await asyncio.to_thread(fn, *args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/asyncio/threads.py", line 25, in to_thread
return await loop.run_in_executor(None, func_call)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/model/llm/pytorch/cogvlm2.py", line 275, in chat
outputs = self._model.generate(**inputs, **sanitized_config)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/transformers/generation/utils.py", line 1914, in generate
result = self._sample(
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/transformers/generation/utils.py", line 2651, in _sample
outputs = self(
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/accelerate/hooks.py", line 169, in new_forward
output = module._old_forward(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-pytorch-20b/modeling_cogvlm.py", line 649, in forward
outputs = self.model(
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^
File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-pytorch-20b/modeling_cogvlm.py", line 403, in forward
return self.llm_forward(
^^^^^^^^^^^^^^^^^
File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-pytorch-20b/modeling_cogvlm.py", line 452, in llm_forward
past_key_values_length = past_key_values[0][0].shape[2]
^^^^^^^^^^^^^^^^^
AttributeError: [address=0.0.0.0:46525, pid=5215] 'str' object has no attribute 'shape'
Traceback (most recent call last):
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
response = await route_utils.call_process_api(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/route_utils.py", line 261, in call_process_api
output = await app.get_blocks().process_api(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/blocks.py", line 1786, in process_api
result = await self.call_function(
^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/blocks.py", line 1350, in call_function
prediction = await utils.async_iteration(iterator)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/utils.py", line 583, in async_iteration
return await iterator.anext()
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/utils.py", line 576, in anext
return await anyio.to_thread.run_sync(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
return await get_async_backend().run_sync_in_worker_thread(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
return await future
^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
result = context.run(func, *args)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/utils.py", line 559, in run_sync_iterator_async
return next(iterator)
^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/gradio/utils.py", line 742, in gen_wrapper
response = next(iterator)
^^^^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/core/chat_interface.py", line 229, in predict
response = model.chat(
^^^^^^^^^^^
File "/home/vipuser/anaconda3/envs/xi/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 423, in chat
raise RuntimeError(
RuntimeError: Failed to generate chat completion, detail: [address=0.0.0.0:46525, pid=5215] 'str' object has no attribute 'shape'
您好,,所有配置均为默认并未变更代码,加载正常,但是一推理就异常了,

### Expected behavior / 期待表现

期待回复,谢谢

**Comment by ChengjieLi28** [comment]
@atlasroben 
看错误像是cogvlm2自己的报错，你是怎么下载的，从huggingface还是modelscope？

**Comment by ChengjieLi28** [comment]
@atlasroben 他们官方issue有回复：参考https://github.com/THUDM/CogVLM2/issues/134

**Comment by atlasroben** [comment]
> @atlasroben 他们官方issue有回复：参考[THUDM/CogVLM2#134](https://github.com/THUDM/CogVLM2/issues/134)

谢谢您的回复
