### ISSUE TITLE
BUG: chatglm fails on windows

### ISSUE THREAD

**Issue by ZanePoe** [xorbitsai/inference#185]
### Describe the bug
install failed ,windows10,llama-cpp-python build success,but chatglm-cpp Failed.
`raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\poe\\AppData\\Local\\Temp\\pip-install-8ojg5xz6\\chatglm-cpp_95dbb1a09d8847a9a99b093924e8b201', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\poe\\AppData\\Local\\Temp\\pip-install-8ojg5xz6\\chatglm-cpp_95dbb1a09d8847a9a99b093924e8b201\\build\\lib.win-amd64-cpython-310\\chatglm_cpp\\', '-DPYTHON_EXECUTABLE=C:\\ProgramData\\miniconda3\\envs\\gpt_server\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DCHATGLM_ENABLE_PYBIND=ON']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chatglm-cpp
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.1.72-cp310-cp310-win_amd64.whl size=467775 sha256=0ba40707b425386a1a38f8865daa63000c0e8beb6e6789d60a561dfc2f38c04b
  Stored in directory: c:\users\poe\appdata\local\pip\cache\wheels\ed\50\66\f44b417fb8ed7860836157dd767c73d0890c337ead374562c4
  Building wheel for ffmpy (setup.py) ... done
  Created wheel for ffmpy: filename=ffmpy-0.3.0-py3-none-any.whl size=4712 sha256=6ac06e14bf3a3231e638b961ba4b3a330b91bd010c6395b63aff97855ba9814b
  Stored in directory: c:\users\poe\appdata\local\pip\cache\wheels\0c\c2\0e\3b9c6845c6a4e35beb90910cc70d9ac9ab5d47402bd62af0df
Successfully built llama-cpp-python ffmpy
Failed to build chatglm-cpp
ERROR: Could not build wheels for chatglm-cpp, which is required to install pyproject.toml-based projects`

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Python version 3.10.
2. The version of xinference 0.04.
3. Versions of crucial packages.
![image](https://github.com/xorbitsai/inference/assets/16047426/2a9f233c-16e8-4b56-bb29-c6591b1fc034)

4. Full stack of the error:
`CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:2 (project)

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\ProgramData\miniconda3\envs\gpt_server\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\miniconda3\envs\gpt_server\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\ProgramData\miniconda3\envs\gpt_server\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 46, in <module>
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\normal\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 84, in run
          _build_ext.run(self)
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
          self._build_extensions_serial()
        File "C:\Users\poe\AppData\Local\Temp\pip-build-env-q5ml330t\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 39, in build_extension
        File "C:\ProgramData\miniconda3\envs\gpt_server\lib\subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\poe\\AppData\\Local\\Temp\\pip-install-8ojg5xz6\\chatglm-cpp_95dbb1a09d8847a9a99b093924e8b201', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\poe\\AppData\\Local\\Temp\\pip-install-8ojg5xz6\\chatglm-cpp_95dbb1a09d8847a9a99b093924e8b201\\build\\lib.win-amd64-cpython-310\\chatglm_cpp\\', '-DPYTHON_EXECUTABLE=C:\\ProgramData\\miniconda3\\envs\\gpt_server\\python.exe', '-DCMAKE_BUILD_TYPE=Release', '-DCHATGLM_ENABLE_PYBIND=ON']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for chatglm-cpp
  Building wheel for llama-cpp-python (pyproject.toml) ... done
  Created wheel for llama-cpp-python: filename=llama_cpp_python-0.1.72-cp310-cp310-win_amd64.whl size=467775 sha256=0ba40707b425386a1a38f8865daa63000c0e8beb6e6789d60a561dfc2f38c04b
  Stored in directory: c:\users\poe\appdata\local\pip\cache\wheels\ed\50\66\f44b417fb8ed7860836157dd767c73d0890c337ead374562c4
  Building wheel for ffmpy (setup.py) ... done
  Created wheel for ffmpy: filename=ffmpy-0.3.0-py3-none-any.whl size=4712 sha256=6ac06e14bf3a3231e638b961ba4b3a330b91bd010c6395b63aff97855ba9814b
  Stored in directory: c:\users\poe\appdata\local\pip\cache\wheels\0c\c2\0e\3b9c6845c6a4e35beb90910cc70d9ac9ab5d47402bd62af0df
Successfully built llama-cpp-python ffmpy
Failed to build chatglm-cpp
ERROR: Could not build wheels for chatglm-cpp, which is required to install pyproject.toml-based projects`
5. Minimized code to reproduce the error:
`pip install "xinference[all]"`

**Comment by UranusSeven** [comment]
Thanks for reporting this problem! We'll try to reproduce this problem ASAP.

**Comment by lonngxiang** [comment]
same error

Failed to build chatglm-cpp
ERROR: Could not build wheels for chatglm-cpp, which is required to install pyproject.toml-based projects

**Comment by roachsinai** [comment]
Same error again.

**Comment by aresnow1** [comment]
@lonngxiang @roachsinai Seems like it failed when installing `chatglm-cpp`, you can get more information from https://github.com/li-plus/chatglm.cpp .

**Comment by UranusSeven** [comment]
This issue is due to an external dependency `chatglm-cpp` and it has been removed from xinference's dependency list.
