### ISSUE TITLE
 No module named 'ChatTTS'

### ISSUE THREAD

**Issue by menkeyi001** [xorbitsai/inference#1854]
### System Info / 系統信息

ubuntu22.04  cuda 12.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

0.31.1

### The command used to start Xinference / 用以启动 xinference 的命令

 XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

chatts 选择 modelscope 下载后台提示错误

  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 816, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
  File "/root/anaconda3/envs/xinference/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/anaconda3/envs/xinference/lib/python3.10/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/core.py", line 106, in create_model_instance
    return create_audio_model_instance(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/audio/core.py", line 155, in create_audio_model_instance
    model_path = cache(model_spec)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/audio/core.py", line 131, in cache
    return cache(model_spec, AudioModelDescription)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/utils.py", line 331, in cache
    download_dir = retry_download(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/utils.py", line 133, in retry_download
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:14043, pid=959084] Failed to download model 'ChatTTS' after multiple retries

### Expected behavior / 期待表现

如何手动下载modelscope

**Comment by qinxuye** [comment]
You need to run pip install chattts now.

**Comment by menkeyi001** [comment]
> You need to run pip install chattts now.
安装完了  运行后报这个错误
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/audio/whisper.py", line 56, in load
    model = AutoModelForSpeechSeq2Seq.from_pretrained(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 524, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 965, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/transformers/configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/transformers/utils/hub.py", line 373, in cached_file
    raise EnvironmentError(
OSError: [address=0.0.0.0:45877, pid=1157028] /models/chatTTS does not appear to have a file named config.json. Checkout 'https://huggingface.co//models/chatTTS/tree/None' for available files.

**Comment by sullamago** [comment]
i have same question

`
Downloading: 100%|██████████| 47.0/47.0 [00:00<00:00, 149B/s]
Downloading: 100%|██████████| 98.9M/98.9M [00:04<00:00, 23.6MB/s]
Downloading: 100%|██████████| 117/117 [00:00<00:00, 427B/s]
Downloading: 100%|██████████| 26.5M/26.5M [00:01<00:00, 15.1MB/s]
Downloading: 100%|██████████| 143/143 [00:00<00:00, 359B/s]
Downloading: 100%|██████████| 859M/859M [00:29<00:00, 30.3MB/s]
Downloading: 100%|██████████| 346/346 [00:00<00:00, 933B/s]
Downloading: 100%|██████████| 309/309 [00:00<00:00, 1.08kB/s]
Downloading: 100%|██████████| 1.36k/1.36k [00:00<00:00, 3.56kB/s]
Downloading: 100%|██████████| 4.16k/4.16k [00:00<00:00, 5.28kB/s]
Downloading: 100%|██████████| 329k/329k [00:00<00:00, 789kB/s]
Downloading: 100%|██████████| 51.8M/51.8M [00:02<00:00, 20.9MB/s]
Downloading: 100%|██████████| 460/460 [00:00<00:00, 1.20kB/s]
2024-07-17 11:03:25,005 xinference.core.worker 36 ERROR    Failed to load model ChatTTS-1-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 295, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/chattts.py", line 41, in load
    import ChatTTS
ModuleNotFoundError: [address=0.0.0.0:37749, pid=162] No module named 'ChatTTS'
2024-07-17 11:03:25,030 xinference.core.supervisor 36 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ab17305cf90>, 'ChatTTS'), kwargs: {'suppress_exception': True}
2024-07-17 11:03:25,030 xinference.core.supervisor 36 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-07-17 11:03:25,032 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:37749, pid=162] No module named 'ChatTTS'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 835, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 295, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/chattts.py", line 41, in load
    import ChatTTS
ModuleNotFoundError: [address=0.0.0.0:37749, pid=162] No module named 'ChatTTS'
`
[Failed to load model ChatTTS-1-0.txt](https://github.com/user-attachments/files/16264460/Failed.to.load.model.ChatTTS-1-0.txt)

**Comment by qinxuye** [comment]
It's fixed in #1812 , and will be included in next release.
