### ISSUE TITLE
Unable to Initiate Chat with glm4v Model Using xinference v0.13.1 - Error: Too Many Values to Unpack

### ISSUE THREAD

**Issue by zhanghx0905** [xorbitsai/inference#1855]
### System Info / 系統信息

registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.13.1
V100

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [x] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

```
services:
  xinference:
    image: registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.13.1
    environment:
     - XINFERENCE_MODEL_SRC=modelscope
     - HF_ENDPOINT=https://hf-mirror.com
     - XINFERENCE_DISABLE_METRICS=1
    command: xinference-local --host 0.0.0.0 --port 8080
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: all
    shm_size: "10gb"
```

### Reproduction / 复现过程

1. Pull the latest xinference v0.13.1 Docker image.
2. Start the Docker container.
3. Deploy glm4v. Attempt to initiate a chat session with the glm4v model.
4. Observe the error message in the logs.

```
2024-07-13 01:41:42,093 xinference.core.worker 140 INFO     You specify to launch the model: glm-4v on GPU index: [3] of the worker: 0.0.0.0:32089, xinference will automatically ignore the `n_gpu` option.
2024-07-13 01:41:47,502 xinference.model.llm.llm_family 140 INFO     Caching from Modelscope: ZhipuAI/glm-4v-9b
2024-07-13 01:41:47,503 xinference.model.llm.llm_family 140 INFO     Cache /root/.xinference/cache/glm-4v-pytorch-9b exists
2024-07-13 01:41:47,547 transformers.configuration_utils 567 INFO     loading configuration file /root/.xinference/cache/glm-4v-pytorch-9b/config.json
2024-07-13 01:41:47,549 transformers.configuration_utils 567 INFO     loading configuration file /root/.xinference/cache/glm-4v-pytorch-9b/config.json
2024-07-13 01:41:47,550 transformers.configuration_utils 567 INFO     Model config ChatGLMConfig {
  "_name_or_path": "/root/.xinference/cache/glm-4v-pytorch-9b",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMModel"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
  },
  "bias_dropout_fusion": true,
  "boi_token_id": 151339,
  "classifier_dropout": null,
  "eoi_token_id": 151340,
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1.5625e-07,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_layers": 40,
  "original_rope": true,
  "pad_token_id": 151329,
  "padded_vocab_size": 151552,
  "post_layer_norm": true,
  "pre_seq_len": null,
  "prefix_projection": false,
  "rmsnorm": true,
  "rope_ratio": 1,
  "seq_length": 8192,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.42.3",
  "use_cache": true,
  "vision_config": {
    "dropout_prob": 0.0,
    "hidden_act": "gelu",
    "hidden_size": 1792,
    "image_size": 1120,
    "in_channels": 3,
    "intermediate_size": 15360,
    "layer_norm_eps": 1e-06,
    "num_heads": 16,
    "num_hidden_layers": 63,
    "num_positions": 6401,
    "patch_size": 14,
    "scaling_factor": 8
  },
  "vocab_size": 151552
}

2024-07-13 01:41:48,032 transformers.modeling_utils 567 INFO     loading weights file /root/.xinference/cache/glm-4v-pytorch-9b/model.safetensors.index.json
2024-07-13 01:41:48,033 transformers.modeling_utils 567 INFO     Instantiating ChatGLMForConditionalGeneration model under default dtype torch.float16.
2024-07-13 01:41:48,034 transformers.generation.configuration_utils 567 INFO     Generate config GenerationConfig {
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "pad_token_id": 151329
}

Loading checkpoint shards: 100%|███████████████| 15/15 [00:11<00:00,  1.26it/s]
2024-07-13 01:42:00,371 transformers.modeling_utils 567 INFO     All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

2024-07-13 01:42:00,371 transformers.modeling_utils 567 INFO     All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at /root/.xinference/cache/glm-4v-pytorch-9b.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
2024-07-13 01:42:00,382 transformers.generation.configuration_utils 567 INFO     loading configuration file /root/.xinference/cache/glm-4v-pytorch-9b/generation_config.json
2024-07-13 01:42:00,382 transformers.generation.configuration_utils 567 INFO     Generate config GenerationConfig {
  "do_sample": true,
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "max_length": 8000,
  "pad_token_id": 151329,
  "temperature": 0.8,
  "top_p": 0.8
}

2024-07-13 01:42:01,176 transformers.tokenization_utils_base 567 INFO     loading file tokenizer.model
2024-07-13 01:42:01,176 transformers.tokenization_utils_base 567 INFO     loading file added_tokens.json
2024-07-13 01:42:01,176 transformers.tokenization_utils_base 567 INFO     loading file special_tokens_map.json
2024-07-13 01:42:01,176 transformers.tokenization_utils_base 567 INFO     loading file tokenizer_config.json
2024-07-13 01:42:01,177 transformers.tokenization_utils_base 567 INFO     loading file tokenizer.json
2024-07-13 01:42:01,868 transformers.tokenization_utils_base 567 WARNING  Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-07-13 01:42:45,271 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:34361, pid=567] too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1613, in create_chat_completion
    data = await model.chat(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 505, in chat
    response = await self._call_wrapper(
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 388, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/pytorch/glm4v.py", line 232, in chat
    outputs = self._model.generate(**generate_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 1063, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 931, in forward
    hidden_states, presents, all_hidden_states, all_self_attentions = self.encoder(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 668, in forward
    layer_ret = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 571, in forward
    attention_output, kv_cache = self.self_attention(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/glm-4v-pytorch-9b/modeling_chatglm.py", line 440, in forward
    cache_k, cache_v = kv_cache
ValueError: [address=0.0.0.0:34361, pid=567] too many values to unpack (expected 2)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 583, in async_iteration
    return await iterator.__anext__()
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 742, in gen_wrapper
    response = next(iterator)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/chat_interface.py", line 229, in predict
    response = model.chat(
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 423, in chat
    raise RuntimeError(
RuntimeError: Failed to generate chat completion, detail: [address=0.0.0.0:34361, pid=567] too many values to unpack (expected 2)
```

### Expected behavior / 期待表现

This issue did not occur in v0.13.0.
Please investigate this issue, considering the potential dependency version change between v0.13.0 and v0.13.1, and provide a resolution or a workaround to enable successful chat initiation with the glm4v model using the latest xinference version.

**Comment by zhanghx0905** [comment]
https://github.com/xorbitsai/inference/issues/1789
