### ISSUE TITLE
'chatglm_cpp._C.ChatGLM3Tokenizer' object has no attribute 'encode_messages'

### ISSUE THREAD

**Issue by dylanm199009** [xorbitsai/inference#1857]
### System Info / 系統信息

Name: chatglm-cpp
Version: 0.4.0
Name: llama_cpp_python
Version: 0.2.82
python3.10
Name: transformers
Version: 4.41.2
cuda12.5

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

V0.13.0

### The command used to start Xinference / 用以启动 xinference 的命令

 docker run --name xinference -d --restart always -p 9997:9997  --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0 

### Reproduction / 复现过程

web ui提交对话出现报错。
2024-07-13 17:04:23 2024-07-13 09:04:23,682 xinference.api.restful_api 1 ERROR    Chat completion stream got an error: [address=0.0.0.0:35185, pid=77] 'chatglm_cpp._C.ChatGLM3Tokenizer' object has no attribute 'encode_messages'
2024-07-13 17:04:23 Traceback (most recent call last):
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1527, in stream_results
2024-07-13 17:04:23     iterator = await model.chat(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 227, in send
2024-07-13 17:04:23     return self._process_result_message(result)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
2024-07-13 17:04:23     raise message.as_instanceof_cause()
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 659, in send
2024-07-13 17:04:23     result = await self._run_coro(message.message_id, coro)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 370, in _run_coro
2024-07-13 17:04:23     return await coro
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
2024-07-13 17:04:23     return await super().__on_receive__(message)  # type: ignore
2024-07-13 17:04:23   File "xoscar/core.pyx", line 558, in __on_receive__
2024-07-13 17:04:23     raise ex
2024-07-13 17:04:23   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
2024-07-13 17:04:23     async with self._lock:
2024-07-13 17:04:23   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
2024-07-13 17:04:23     with debug_async_timeout('actor_lock_timeout',
2024-07-13 17:04:23   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
2024-07-13 17:04:23     result = await result
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
2024-07-13 17:04:23     ret = await func(*args, **kwargs)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 90, in wrapped_func
2024-07-13 17:04:23     ret = await fn(self, *args, **kwargs)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 462, in _wrapper
2024-07-13 17:04:23     r = await func(self, *args, **kwargs)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 505, in chat
2024-07-13 17:04:23     response = await self._call_wrapper(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 114, in _async_wrapper
2024-07-13 17:04:23     return await fn(*args, **kwargs)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 394, in _call_wrapper
2024-07-13 17:04:23     ret = await asyncio.to_thread(fn, *args, **kwargs)
2024-07-13 17:04:23   File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
2024-07-13 17:04:23     return await loop.run_in_executor(None, func_call)
2024-07-13 17:04:23   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-07-13 17:04:23     result = self.fn(*self.args, **self.kwargs)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/ggml/chatglm.py", line 337, in chat
2024-07-13 17:04:23     input_ids = self._llm.tokenizer.encode_messages(
2024-07-13 17:04:23 AttributeError: [address=0.0.0.0:35185, pid=77] 'chatglm_cpp._C.ChatGLM3Tokenizer' object has no attribute 'encode_messages'
2024-07-13 17:04:23 Traceback (most recent call last):
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 527, in process_events
2024-07-13 17:04:23     response = await route_utils.call_process_api(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 261, in call_process_api
2024-07-13 17:04:23     output = await app.get_blocks().process_api(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1786, in process_api
2024-07-13 17:04:23     result = await self.call_function(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1350, in call_function
2024-07-13 17:04:23     prediction = await utils.async_iteration(iterator)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 583, in async_iteration
2024-07-13 17:04:23     return await iterator.__anext__()
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 709, in asyncgen_wrapper
2024-07-13 17:04:23     response = await iterator.__anext__()
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/chat_interface.py", line 545, in _stream_fn
2024-07-13 17:04:23     first_response = await async_iteration(generator)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 583, in async_iteration
2024-07-13 17:04:23     return await iterator.__anext__()
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 576, in __anext__
2024-07-13 17:04:23     return await anyio.to_thread.run_sync(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
2024-07-13 17:04:23     return await get_async_backend().run_sync_in_worker_thread(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
2024-07-13 17:04:23     return await future
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
2024-07-13 17:04:23     result = context.run(func, *args)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 559, in run_sync_iterator_async
2024-07-13 17:04:23     return next(iterator)
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/core/chat_interface.py", line 124, in generate_wrapper
2024-07-13 17:04:23     for chunk in model.chat(
2024-07-13 17:04:23   File "/usr/local/lib/python3.10/dist-packages/xinference/client/common.py", line 51, in streaming_response_iterator
2024-07-13 17:04:23     raise Exception(str(error))
2024-07-13 17:04:23 Exception: [address=0.0.0.0:35185, pid=77] 'chatglm_cpp._C.ChatGLM3Tokenizer' object has no attribute 'encode_messages'

### Expected behavior / 期待表现

无法进行对话，返回错误，这种如何解决呢？可以帮忙看下吗？

**Comment by dylanm199009** [comment]
2024-07-14 10:04:37 2024-07-14 02:04:37,628 xinference.core.worker 58 DEBUG    Leave launch_builtin_model, elapsed time: 81 s
2024-07-14 10:04:38 2024-07-14 02:04:38,813 xinference.core.supervisor 58 DEBUG    Enter list_models, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f8eaab80270>,), kwargs: {}
2024-07-14 10:04:38 2024-07-14 02:04:38,814 xinference.core.worker 58 DEBUG    Enter list_models, args: (<xinference.core.worker.WorkerActor object at 0x7f8eaabf1580>,), kwargs: {}
2024-07-14 10:04:38 2024-07-14 02:04:38,814 xinference.core.worker 58 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-14 10:04:38 2024-07-14 02:04:38,815 xinference.core.supervisor 58 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-14 10:04:41 2024-07-14 02:04:41,883 xinference.core.supervisor 58 DEBUG    Enter list_models, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f8eaab80270>,), kwargs: {}
2024-07-14 10:04:41 2024-07-14 02:04:41,884 xinference.core.worker 58 DEBUG    Enter list_models, args: (<xinference.core.worker.WorkerActor object at 0x7f8eaabf1580>,), kwargs: {}
2024-07-14 10:04:41 2024-07-14 02:04:41,884 xinference.core.worker 58 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-14 10:04:41 2024-07-14 02:04:41,885 xinference.core.supervisor 58 DEBUG    Leave list_models, elapsed time: 0 s
2024-07-14 10:04:45 2024-07-14 02:04:45,378 xinference.core.supervisor 58 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f8eaab80270>, 'chatglm3b'), kwargs: {}
2024-07-14 10:04:45 2024-07-14 02:04:45,378 xinference.core.worker 58 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7f8eaabf1580>,), kwargs: {'model_uid': 'chatglm3b-1-0'}
2024-07-14 10:04:45 2024-07-14 02:04:45,379 xinference.core.worker 58 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-14 10:04:45 2024-07-14 02:04:45,379 xinference.core.supervisor 58 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-14 10:04:45 2024-07-14 02:04:45,382 xinference.core.supervisor 58 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f8eaab80270>, 'chatglm3b'), kwargs: {}
2024-07-14 10:04:45 2024-07-14 02:04:45,383 xinference.core.worker 58 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7f8eaabf1580>,), kwargs: {'model_uid': 'chatglm3b-1-0'}
2024-07-14 10:04:45 2024-07-14 02:04:45,383 xinference.core.worker 58 DEBUG    Leave get_model, elapsed time: 0 s
2024-07-14 10:04:45 2024-07-14 02:04:45,384 xinference.core.supervisor 58 DEBUG    Leave get_model, elapsed time: 0 s
2024-07-14 10:04:45 2024-07-14 02:04:45,385 xinference.core.supervisor 58 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f8eaab80270>, 'chatglm3b'), kwargs: {}
2024-07-14 10:04:45 2024-07-14 02:04:45,385 xinference.core.worker 58 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7f8eaabf1580>,), kwargs: {'model_uid': 'chatglm3b-1-0'}
2024-07-14 10:04:45 2024-07-14 02:04:45,386 xinference.core.worker 58 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-14 10:04:45 2024-07-14 02:04:45,386 xinference.core.supervisor 58 DEBUG    Leave describe_model, elapsed time: 0 s
2024-07-14 10:04:45 2024-07-14 02:04:45,388 xinference.core.model 272 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7fba1ed76110>, '3', '', [], {'max_tokens': 512, 'temperature': 1.0, 'stream': True, 'lora_name': ''}), kwargs: {'raw_params': {'max_tokens': 512, 'temperature': 1, 'stream': True, 'lora_name': ''}}
2024-07-14 10:04:45 2024-07-14 02:04:45,389 xinference.core.model 272 DEBUG    Request chat, current serve request count: 0, request limit: None for the model chatglm3b
2024-07-14 10:04:45 2024-07-14 02:04:45,390 xinference.model.llm.ggml.chatglm 272 DEBUG    Full conversation history:
2024-07-14 10:04:45 [{'role': 'system', 'content': ''}, {'role': 'user', 'content': '3'}]
2024-07-14 10:04:45 2024-07-14 02:04:45,391 xinference.core.model 272 DEBUG    After request chat, current serve request count: 0 for the model chatglm3b
2024-07-14 10:04:45 2024-07-14 02:04:45,393 xinference.api.restful_api 1 ERROR    Chat completion stream got an error: [address=0.0.0.0:37685, pid=272] 'chatglm_cpp._C.ChatGLM3Tokenizer' object has no attribute 'encode_messages'
2024-07-14 10:04:45 Traceback (most recent call last):
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1527, in stream_results
2024-07-14 10:04:45     iterator = await model.chat(
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 227, in send
2024-07-14 10:04:45     return self._process_result_message(result)
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
2024-07-14 10:04:45     raise message.as_instanceof_cause()
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 659, in send
2024-07-14 10:04:45     result = await self._run_coro(message.message_id, coro)
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 370, in _run_coro
2024-07-14 10:04:45     return await coro
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
2024-07-14 10:04:45     return await super().__on_receive__(message)  # type: ignore
2024-07-14 10:04:45   File "xoscar/core.pyx", line 558, in __on_receive__
2024-07-14 10:04:45     raise ex
2024-07-14 10:04:45   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
2024-07-14 10:04:45     async with self._lock:
2024-07-14 10:04:45   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
2024-07-14 10:04:45     with debug_async_timeout('actor_lock_timeout',
2024-07-14 10:04:45   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
2024-07-14 10:04:45     result = await result
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
2024-07-14 10:04:45     ret = await func(*args, **kwargs)
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 90, in wrapped_func
2024-07-14 10:04:45     ret = await fn(self, *args, **kwargs)
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 462, in _wrapper
2024-07-14 10:04:45     r = await func(self, *args, **kwargs)
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 505, in chat
2024-07-14 10:04:45     response = await self._call_wrapper(
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 114, in _async_wrapper
2024-07-14 10:04:45     return await fn(*args, **kwargs)
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 394, in _call_wrapper
2024-07-14 10:04:45     ret = await asyncio.to_thread(fn, *args, **kwargs)
2024-07-14 10:04:45   File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
2024-07-14 10:04:45     return await loop.run_in_executor(None, func_call)
2024-07-14 10:04:45   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-07-14 10:04:45     result = self.fn(*self.args, **self.kwargs)
2024-07-14 10:04:45   File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/ggml/chatglm.py", line 337, in chat
2024-07-14 10:04:45     input_ids = self._llm.tokenizer.encode_messages(
2024-07-14 10:04:45 AttributeError: [address=0.0.0.0:37685, pid=272] 'chatglm_cpp._C.ChatGLM3Tokenizer' object has no attribute 'encode_messages'

**Comment by ChengjieLi28** [comment]
@dylanm199009 
最新版本已经不再支持`chatglm-cpp`, 不再支持glm系列的ggml格式的老版本模型。
GPU docker升级到最新版，直接走`llama-cpp-python`逻辑。
