### ISSUE TITLE
'system_message' is undefined

### ISSUE THREAD

**Issue by Silenceang** [xorbitsai/inference#1862]
### System Info / 系統信息

注册glm4启动后聊天报错

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

ubuntu22.04  xinference 13.1   

### The command used to start Xinference / 用以启动 xinference 的命令

UI注册私有glm4微调模型成功，launch后聊天报错，

### Reproduction / 复现过程

UI注册私有glm4微调模型成功，launch后聊天报错，Exception: [address=0.0.0.0:39181, pid=17737] 'system_message' is undefined

### Expected behavior / 期待表现

同步骤glm3没问题，为什么glm4报错呢

**Comment by qinxuye** [comment]
贴下如何注册私有模型。如果是 JSON 贴下。

**Comment by Silenceang** [comment]
{
    "version": 1,
    "context_length": 2048,
    "model_name": "custom-glm4",
    "model_lang": [
        "zh"
    ],
    "model_ability": [
        "chat"
    ],
    "model_description": "This is a custom model description.",
    "model_family": "glm4-chat",
    "model_specs": [
        {
            "model_format": "pytorch",
            "model_size_in_billions": 9,
            "quantizations": [
                "none"
            ],
            "model_id": null,
            "model_hub": "huggingface",
            "model_uri": "/home/yang/LLM/LLaMA-Factory/models/sft_1300",
            "model_revision": null
        }
    ],
    "prompt_style": {
        "style_name": "CHATGLM3",
        "system_prompt": "",
        "roles": [
            "user",
            "assistant"
        ],
        "intra_message_sep": "",
        "inter_message_sep": "",
        "stop": [
            "&lt;|endoftext|&gt;",
            "&lt;|user|&gt;",
            "&lt;|observation|&gt;"
        ],
        "stop_token_ids": [
            151329,
            151336,
            151338
        ]
    },
    "is_builtin": false
}


用的UI注册

**Comment by qinxuye** [comment]
完整报错信息能再贴下吗？

**Comment by Silenceang** [comment]
以下是我从launch到报错的完整复现log

(xinference) yang@yag:~$ xinference-local --host 0.0.0.0 --port 9997
2024-07-15 14:56:29,859 xinference.core.supervisor 27742 INFO     Xinference supervisor 0.0.0.0:47194 started
2024-07-15 14:56:30,156 xinference.core.worker 27742 INFO     Starting metrics export server at 0.0.0.0:None
2024-07-15 14:56:30,158 xinference.core.worker 27742 INFO     Checking metrics export server...
2024-07-15 14:56:31,300 xinference.core.worker 27742 INFO     Metrics server is started at: http://0.0.0.0:34489
2024-07-15 14:56:31,300 xinference.core.worker 27742 INFO     Xinference worker 0.0.0.0:47194 started
2024-07-15 14:56:31,301 xinference.core.worker 27742 INFO     Purge cache directory: /home/yang/.xinference/cache
2024-07-15 14:56:35,372 xinference.api.restful_api 27672 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997
2024-07-15 14:56:35,414 uvicorn.error 27672 INFO     Uvicorn running on http://0.0.0.0:9997 (Press CTRL+C to quit)
2024-07-15 14:57:06,962 xinference.model.llm.llm_family 27742 INFO     Caching from URI: /home/yang/LLM/LLaMA-Factory/models/sft_1300
2024-07-15 14:57:06,962 xinference.model.llm.llm_family 27742 INFO     Cache /home/yang/LLM/LLaMA-Factory/models/sft_1300 exists
2024-07-15 14:57:07,024 transformers.tokenization_utils_base 27862 INFO     loading file tokenizer.model
2024-07-15 14:57:07,024 transformers.tokenization_utils_base 27862 INFO     loading file added_tokens.json
2024-07-15 14:57:07,024 transformers.tokenization_utils_base 27862 INFO     loading file special_tokens_map.json
2024-07-15 14:57:07,024 transformers.tokenization_utils_base 27862 INFO     loading file tokenizer_config.json
2024-07-15 14:57:07,024 transformers.tokenization_utils_base 27862 INFO     loading file tokenizer.json
2024-07-15 14:57:07,221 transformers.tokenization_utils_base 27862 WARNING  Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-07-15 14:57:07,222 transformers.configuration_utils 27862 INFO     loading configuration file /home/yang/LLM/LLaMA-Factory/models/sft_1300/config.json
2024-07-15 14:57:07,222 transformers.configuration_utils 27862 INFO     loading configuration file /home/yang/LLM/LLaMA-Factory/models/sft_1300/config.json
2024-07-15 14:57:07,223 transformers.configuration_utils 27862 INFO     Model config ChatGLMConfig {
  "_name_or_path": "/home/yang/LLM/LLaMA-Factory/models/sft_1300",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMForConditionalGeneration"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
  },
  "bias_dropout_fusion": true,
  "classifier_dropout": null,
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1.5625e-07,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_hidden_layers": 40,
  "num_layers": 40,
  "original_rope": true,
  "pad_token_id": 151329,
  "padded_vocab_size": 151552,
  "post_layer_norm": true,
  "rmsnorm": true,
  "rope_ratio": 500,
  "seq_length": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "float16",
  "transformers_version": "4.41.2",
  "use_cache": true,
  "vocab_size": 151552
}


2024-07-15 14:57:07,413 transformers.modeling_utils 27862 INFO     loading weights file /home/yang/LLM/LLaMA-Factory/models/sft_1300/model.safetensors.index.json
2024-07-15 14:57:07,414 transformers.modeling_utils 27862 INFO     Instantiating ChatGLMForConditionalGeneration model under default dtype torch.float16.
2024-07-15 14:57:07,414 transformers.generation.configuration_utils 27862 INFO     Generate config GenerationConfig {
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "pad_token_id": 151329
}

Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 10/10 [00:16<00:00,  1.70s/it]
2024-07-15 14:57:24,522 transformers.modeling_utils 27862 INFO     All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.

2024-07-15 14:57:24,522 transformers.modeling_utils 27862 INFO     All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at /home/yang/LLM/LLaMA-Factory/models/sft_1300.
If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
2024-07-15 14:57:24,524 transformers.generation.configuration_utils 27862 INFO     loading configuration file /home/yang/LLM/LLaMA-Factory/models/sft_1300/generation_config.json
2024-07-15 14:57:24,524 transformers.generation.configuration_utils 27862 INFO     Generate config GenerationConfig {
  "do_sample": true,
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "max_length": 128000,
  "pad_token_id": 151329,
  "temperature": 0.1,
  "top_p": 0.5
}

2024-07-15 14:57:47,522 xinference.model.utils 27742 INFO     Use model cache from a different hub.
2024-07-15 14:57:48,204 transformers.configuration_utils 28006 INFO     loading configuration file /home/yang/.xinference/cache/bge-large-zh-v1.5/config.json
2024-07-15 14:57:48,204 transformers.dynamic_module_utils 28006 INFO     Patched resolve_trust_remote_code: (False, '/home/yang/.xinference/cache/bge-large-zh-v1.5', True, False) {}
2024-07-15 14:57:48,204 transformers.configuration_utils 28006 INFO     Model config BertConfig {
  "_name_or_path": "/home/yang/.xinference/cache/bge-large-zh-v1.5",
  "architectures": [
    "BertModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "directionality": "bidi",
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "id2label": {
    "0": "LABEL_0"
  },
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "label2id": {
    "LABEL_0": 0
  },
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.41.2",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}


2024-07-15 14:57:48,225 transformers.dynamic_module_utils 28006 INFO     Patched resolve_trust_remote_code: (False, '/home/yang/.xinference/cache/bge-large-zh-v1.5', True, False) {}
2024-07-15 14:57:48,227 transformers.modeling_utils 28006 INFO     loading weights file /home/yang/.xinference/cache/bge-large-zh-v1.5/model.safetensors
2024-07-15 14:57:48,319 transformers.modeling_utils 28006 INFO     All model checkpoint weights were used when initializing BertModel.

2024-07-15 14:57:48,319 transformers.modeling_utils 28006 INFO     All the weights of BertModel were initialized from the model checkpoint at /home/yang/.xinference/cache/bge-large-zh-v1.5.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertModel for predictions without further training.
2024-07-15 14:57:48,337 transformers.dynamic_module_utils 28006 INFO     Patched resolve_trust_remote_code: (False, '/home/yang/.xinference/cache/bge-large-zh-v1.5', True, False) {}
2024-07-15 14:57:48,338 transformers.tokenization_utils_base 28006 INFO     loading file vocab.txt
2024-07-15 14:57:48,338 transformers.tokenization_utils_base 28006 INFO     loading file tokenizer.json
2024-07-15 14:57:48,338 transformers.tokenization_utils_base 28006 INFO     loading file added_tokens.json
2024-07-15 14:57:48,338 transformers.tokenization_utils_base 28006 INFO     loading file special_tokens_map.json
2024-07-15 14:57:48,338 transformers.tokenization_utils_base 28006 INFO     loading file tokenizer_config.json
2024-07-15 14:58:06,171 xinference.api.restful_api 27672 ERROR    Chat completion stream got an error: [address=0.0.0.0:45607, pid=27862] 'system_message' is undefined
Traceback (most recent call last):
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1584, in stream_results
    async for item in iterator:
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 431, in __xoscar_next__
    raise e
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 417, in __xoscar_next__
    r = await asyncio.to_thread(_wrapper, gen)
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 402, in _wrapper
    return next(_gen)
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 318, in _to_json_generator
    for v in gen:
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/utils.py", line 558, in _to_chat_completion_chunks
    for i, chunk in enumerate(chunks):
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/pytorch/chatglm.py", line 259, in _stream_generator
    for chunk_text, _ in self._model.stream_chat(
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/.cache/huggingface/modules/transformers_modules/sft_1300/modeling_chatglm.py", line 1124, in stream_chat
    inputs = tokenizer.apply_chat_template(history + [{"role": role, "content": query}],
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1812, in apply_chat_template
    rendered_chat = compiled_template.render(
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
    ^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
    ^^^^^^^^^^^^^^^^^
  File "<template>", line 1, in top-level template code
jinja2.exceptions.UndefinedError: [address=0.0.0.0:45607, pid=27862] 'system_message' is undefined
Traceback (most recent call last):
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/blocks.py", line 1786, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/blocks.py", line 1350, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 583, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 709, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/chat_interface.py", line 545, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 583, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 576, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/gradio/utils.py", line 559, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/chat_interface.py", line 124, in generate_wrapper
    for chunk in model.chat(
  File "/home/yang/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/client/common.py", line 51, in streaming_response_iterator
    raise Exception(str(error))
Exception: [address=0.0.0.0:45607, pid=27862] 'system_message' is undefined

**Comment by Silenceang** [comment]
是模型微调到注册出了错误，不是xinference的问题
