### ISSUE TITLE
Upgrade vllm and sglang to new version and support gemma model correctly

### ISSUE THREAD

**Issue by vikrantrathore** [xorbitsai/inference#1869]
### Feature request / 功能建议

At present the vllm and sglang used in xinference are older. New sglang supports gemma-2 models out of the box, but in xinference engine sglang it does not support. Same is the case with vllm, at present vllm is 0.5.1 also supports gemma-2 out of the box. The current implementation of gemma in xinference is giving error and do not stop the token generation probably due to new 4096 token sliding window in gemma 2.

### Motivation / 动机

Upgrade to new version fo sglang and vllm

### Your contribution / 您的贡献

No PR yet but can create one.

**Comment by qinxuye** [comment]
OK, thanks, we will support it, actually it's not easy to add a model, do you have interest to contribute?

Refer to code blow to add new models to vLLM.

https://github.com/xorbitsai/inference/blob/e80910d9ec159b04c950a47910c6630c3f16e27c/xinference/model/llm/vllm/core.py#L133-L149

**Comment by vikrantrathore** [comment]
I tried to add the code for sglang for gemma 2 model, but the system still gives error most likely need to check how model_family in custom LLM is handled, in Fastchat works without any errors using fastchat.serve.sglang_worker and do not need to provide some prompt style as it automatically picks for it.

Gemma is registered with xinference as custom model as its already on my server and wanted to use it.

Following are the details of changes and custom LLM file.

https://github.com/xorbitsai/inference/blob/e80910d9ec159b04c950a47910c6630c3f16e27c/xinference/model/llm/sglang/core.py#L65-L75

to 

```
SGLANG_SUPPORTED_MODELS = ["llama-2", "mistral-v0.1", "mixtral-v0.1"] 
SGLANG_SUPPORTED_CHAT_MODELS = [ 
     "llama-2-chat", 
     "qwen-chat", 
     "qwen1.5-chat", 
     "mistral-instruct-v0.1", 
     "mistral-instruct-v0.2", 
     "mixtral-instruct-v0.1", 
     "gemma-it",
     "gemma-2-it",
    #"test-gemma-2-it" # commented out as it is not working 
 ] 
```

Custom model registration file named gemma.json:

```
{ 
    "version": 1,
    "context_length": 8192,
    "model_name": "test-gemma-2-it",
    "model_lang": [
	"en",
	"zh"
    ],
    "model_ability": [
      "chat"
    ],
    "model_description": "Gemma is a family of lightweight, state-of-the-art open models from Google, built from the same research and technology used to create the Gemini models.",
    "model_family": "gemma-2-it",
    "model_specs": [
      {
        "model_format": "pytorch",
        "model_size_in_billions": 9,
        "quantizations": [
          "none",
          "4-bit",
          "8-bit"
        ],
          "model_id": "gemma-2-9b-it",
	  "model_uri": "file:///home/ubuntu/projects/llm_models/gemma/gemma-2-9b-it"
      },
      {
        "model_format": "pytorch",
        "model_size_in_billions": 27,
        "quantizations": [
          "none",
          "4-bit",
          "8-bit"
        ],
          "model_id": "gemma-2-27b-it",
	  "model_uri": "file:///home/ubuntu/projects/llm_models/gemma/gemma-2-27b-it"
      }
    ],
    "prompt_style": {
	"style_name": "gemma",
	"roles": [
	    "user",
	    "model"
	],
        "stop": [
	    "<end_of_turn>",
	    "<start_of_turn>"
	]
    }
  }
```

Errors encountered while trying to launch after successfull registration.

```
xinference launch --model-engine sglang -n test-gemma-2-it -u gemma-2-9b-it --max_model_len 8192 --gpu_memory_utilization 0.90 -e http://127.0.0.1:18888 --api-key "sk-testapikey"

2024-07-16 13:36:54,197 xinference.api.restful_api 205487 ERROR    [address=0.0.0.0:60601, pid=205563] Model test-gemma-2-it cannot be run on engine sglang.
Traceback (most recent call last):
  File "/home/ubuntu/projects/inference/xinference/api/restful_api.py", line 835, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai_inference/.venv/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai_inference/.venv/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/ubuntu/projects/testai_inference/.venv/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in
  File "/home/ubuntu/projects/inference/xinference/core/supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/inference/xinference/core/supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/inference/xinference/core/supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/inference/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/inference/xinference/core/worker.py", line 816, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.2/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.pyenv/versions/3.11.2/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/inference/xinference/model/core.py", line 69, in create_model_instance
    return create_llm_model_instance(
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/inference/xinference/model/llm/core.py", line 215, in create_llm_model_instance
    llm_cls = check_engine_by_spec_parameters(
      ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/inference/xinference/model/llm/llm_family.py", line 1193, in check_engine_by_spec_parameters
    raise ValueError(f"Model {model_name} cannot be run on engine {model_engine}.")
    ^^^^^^^^^^^^^^^^^
ValueError: [address=0.0.0.0:60601, pid=205563] Model test-gemma-2-it cannot be run on engine sglang.
```

**Comment by qinxuye** [comment]
Now environment variable XINFERENCE_ENABLE_SGLANG=1 should be added to enable sglang, did you add it?

**Comment by qinxuye** [comment]
@wxiwnd Can you take a look to see this? why the `include_usage` gives some error?

**Comment by qinxuye** [comment]
Hi @vikrantrathore , can you try to merge the main branch to see if you can move forward?

**Comment by vikrantrathore** [comment]
> Hi @vikrantrathore , can you try to merge the main branch to see if you can move forward?

Yes the changes you made now works for sglang and tokens/s is 2x vllm even though both are using flashinfer-0.0.8. But still face few smaller issues:

1. I am using sglang==0.1.21, vllm==0.5.2, these results in upgrade of other packages to torch-2.3.1, torchvision-0.18.1, triton-2.3.1, vllm-flash-attn-2.5.9.post1, xformers-0.0.27, lm-format-enforcer-0.10.3. This means torch-2.3.1 is incompatible with torchaudio-2.3.0 (which requires torch 2.3.0).
2. Face issue with parallel generation as its using some ggml code for streams processing. My thinking is making sglang code similar to fastchat's sglang_worker will solve this problem. 

```
return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai/.venv/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai/.venv/lib/python3.11/site-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai/.venv/lib/python3.11/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai/.venv/lib/python3.11/site-packages/xinference/core/model.py", line 528, in chat
    response = await self._call_wrapper_json(
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai/.venv/lib/python3.11/site-packages/xinference/core/model.py", line 393, in _call_wrapper_json
    return await self._call_wrapper("json", fn, *args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai/.venv/lib/python3.11/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/testai/.venv/lib/python3.11/site-packages/xinference/core/model.py", line 413, in _call_wrapper
    raise Exception("Parallel generation is not supported by ggml.")
    ^^^^^^^^^^^^^^^^^
Exception: [address=0.0.0.0:43267, pid=33178] Parallel generation is not supported by ggml.
```

**Comment by qinxuye** [comment]
Do you have any update?
