### ISSUE TITLE
[ maybe a bug ] Occasional exceptions occurred when reasoning with the mlx model yi-1.5-9b-chat

### ISSUE THREAD

**Issue by okwinds** [xorbitsai/inference#1873]
I am certain that the occasional issues occurred during the Inference of the mlx model, and without restarting the model, it was able to self-heal.

FYI, stack info:

2024-07-16 11:51:17,019 xinference.api.restful_api 58629 ERROR    Chat completion stream got an error: [address=0.0.0.0:54223, pid=58650] Parallel generation is not supported by ggml.
Traceback (most recent call last):
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1574, in stream_results
    iterator = await model.chat(
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/model.py", line 505, in chat
    response = await self._call_wrapper(
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/Users/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/model.py", line 397, in _call_wrapper
    raise Exception("Parallel generation is not supported by ggml.")
Exception: [address=0.0.0.0:54223, pid=58650] Parallel generation is not supported by ggml.

**Comment by ChengjieLi28** [comment]
Please fill the complete information for the issue. 
Why did you delete the place where you were required to fill in the information?
How do you start xinference? How do you launch the model and how do you do the inference? 
We will not process this issue unless you open another one and fill in the full information.
