### ISSUE TITLE
Failed to register model, Invalid model URI D:/Pretrainedmodels3/ZhipuAI/chat4/glm-4-9b-chat.

### ISSUE THREAD

**Issue by fengchezhendexiatian** [xorbitsai/inference#1885]
### System Info / 系統信息

Wed Jul 17 18:01:29 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.12                 Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090      WDDM  |   00000000:01:00.0  On |                  N/A |
| 34%   54C    P0            125W /  350W |    1479MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |

Python 3.11.9

transformers                  4.37.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

2024-07-17 09:56:28,551 xinference.core.supervisor 52 DEBUG    Enter unregister_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f7169dd9300>, 'LLM', 'custom-glm4-chat'), kwargs: {}
2024-07-17 09:56:28,552 xinference.core.supervisor 52 DEBUG    Leave unregister_model, elapsed time: 0 s
2024-07-17 09:56:35,722 xinference.core.supervisor 52 DEBUG    Enter register_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f7169dd9300>, 'LLM', '{\n  "version": 1,\n  "context_length": 131072,\n  "model_name": "custom-glm4-chat",\n  "model_lang": [\n    "en",\n    "zh"\n  ],\n  "model_ability": [\n    "chat",\n    "tools"\n  ],\n  "model_family": "glm4-chat",\n  "model_specs": [\n    {\n      "model_format": "pytorch",\n      "model_size_in_billions": 9,\n      "quantizations": [\n        "4-bit",\n        "8-bit",\n        "none"\n      ],\n      "model_id": "THUDM/glm-4-9b-chat",\n      "model_uri": "D:/Pretrainedmodels3/ZhipuAI/chat4/glm-4-9b-chat"\n      \n    }\n  ]\n}\n', True, None), kwargs: {}
2024-07-17 09:56:35,724 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:50159, pid=52] Invalid model URI D:/Pretrainedmodels3/ZhipuAI/chat4/glm-4-9b-chat.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1647, in register_model
    await (await self._get_supervisor_ref()).register_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 775, in register_model
    raise e
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 770, in register_model
    register_fn(model_spec, persist)
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/llm_family.py", line 1125, in register_llm
    raise ValueError(f"Invalid model URI {model_uri}.")
ValueError: [address=0.0.0.0:50159, pid=52] Invalid model URI D:/Pretrainedmodels3/ZhipuAI/chat4/glm-4-9b-chat.

### The command used to start Xinference / 用以启动 xinference 的命令

docker run  -p 9997:9997 --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0 --log-level debug
xinference register --model-type LLM --file custom-glm4-chat.json --persist

### Reproduction / 复现过程

2024-07-17 09:56:28,551 xinference.core.supervisor 52 DEBUG    Enter unregister_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f7169dd9300>, 'LLM', 'custom-glm4-chat'), kwargs: {}
2024-07-17 09:56:28,552 xinference.core.supervisor 52 DEBUG    Leave unregister_model, elapsed time: 0 s
2024-07-17 09:56:35,722 xinference.core.supervisor 52 DEBUG    Enter register_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f7169dd9300>, 'LLM', '{\n  "version": 1,\n  "context_length": 131072,\n  "model_name": "custom-glm4-chat",\n  "model_lang": [\n    "en",\n    "zh"\n  ],\n  "model_ability": [\n    "chat",\n    "tools"\n  ],\n  "model_family": "glm4-chat",\n  "model_specs": [\n    {\n      "model_format": "pytorch",\n      "model_size_in_billions": 9,\n      "quantizations": [\n        "4-bit",\n        "8-bit",\n        "none"\n      ],\n      "model_id": "THUDM/glm-4-9b-chat",\n      "model_uri": "D:/Pretrainedmodels3/ZhipuAI/chat4/glm-4-9b-chat"\n      \n    }\n  ]\n}\n', True, None), kwargs: {}
2024-07-17 09:56:35,724 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:50159, pid=52] Invalid model URI D:/Pretrainedmodels3/ZhipuAI/chat4/glm-4-9b-chat.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1647, in register_model
    await (await self._get_supervisor_ref()).register_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 775, in register_model
    raise e
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 770, in register_model
    register_fn(model_spec, persist)
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/llm_family.py", line 1125, in register_llm
    raise ValueError(f"Invalid model URI {model_uri}.")
ValueError: [address=0.0.0.0:50159, pid=52] Invalid model URI D:/Pretrainedmodels3/ZhipuAI/chat4/glm-4-9b-chat.

### Expected behavior / 期待表现

如何指向正确URI

**Comment by qinxuye** [comment]
确保你的写法用 os.path.exists 能返回 True。

**Comment by Andyszl** [comment]
请问这个解决了吗

**Comment by tigflanker** [comment]
![微信截图_20240910140522](https://github.com/user-attachments/assets/2b328c13-e630-4515-9f36-b7d6bb8d6fea)
同样的问题

**Comment by tigflanker** [comment]
我找到原因了！
如果你也用的是docker版，别忘了一开始挂载外部路径的时候，内外是不一致的，所以docker内部能看到的路径是以 /data开头的

**Comment by Andyszl** [comment]
> 我找到原因了！ 如果你也用的是docker版，别忘了一开始挂载外部路径的时候，内外是不一致的，所以docker内部能看到的路径是以 /data开头的

这个要怎么修改，自己建立一个data文件夹吗？

**Comment by tigflanker** [comment]
> > 我找到原因了！ 如果你也用的是docker版，别忘了一开始挂载外部路径的时候，内外是不一致的，所以docker内部能看到的路径是以 /data开头的
> 
> 这个要怎么修改，自己建立一个data文件夹吗？

不是这个意思，例如你启动docker的时候是这个命令：
s docker run --name xinference -d -p 9997:9997 -e XINFERENCE_HOME=/data -v /data/llm:/data --gpus all --restart always xinference:latest xinference-local -H 0.0.0.0
你就需要注意一下，在xinference中填写模型路径的时候，应该映射一下，
例如你的模型在这个位置（容器外）：/data/llm/modelscope/...，你在容器内就应该填：/data/modelscope/...
