### ISSUE TITLE
llama.cpp引擎加载qwen2-72b会报错

### ISSUE THREAD

**Issue by jingle009** [xorbitsai/inference#1912]
### System Info / 系統信息

cuda:11.8
python:3.11.9
llama-cpp-python:0.2.77
ubuntu:20.04

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.13.2

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

使用xinference界面启动llama.cpp引擎的qwen2-72b，会报错。
服务器使用的两张A6000，并且在界面配置使用两个GPU，排除显存问题。
![2024-07-22 10-51-11 的屏幕截图](https://github.com/user-attachments/assets/796d2cb1-9e48-4461-9cb3-eefd8e236115)

下面是报错信息。
```
2024-07-22 10:19:15,458 xinference.api.restful_api 3159671 ERROR    [address=0.0.0.0:44725, pid=3166302] Failed to load model from file: xinference/cache/qwen2-instruct-ggufv2-72b/qwen2-72b-instruct-q5_0.gguf
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/api/restful_api.py", line 847, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/ggml/llamacpp.py", line 172, in load
    self._llm = Llama(
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/llama_cpp/llama.py", line 341, in __init__
    self._model = _LlamaModel(
    ^^^^^^^^^^^^^^^^^
  File "/home/user/anaconda3/envs/xinference/lib/python3.11/site-packages/llama_cpp/_internals.py", line 57, in __init__
    raise ValueError(f"Failed to load model from file: {path_model}")
    ^^^^^^^^^^^^^^^^^
ValueError: [address=0.0.0.0:44725, pid=3166302] Failed to load model from file: xinference/xinference/cache/
```

### Expected behavior / 期待表现

查看后台，发现qwen2-72b-instruct-q5_0模型下载下来是两个部分，后台会先merge模型，再加载，是在加载模型期间报的错。
尝试使用qwe2-7b的模型，其gguf是一个文件，此时不会报错。

使用./llama-gguf-split --merge命令进行gguf合并模型，再将转换后的模型替换到cach目录下，此时加载模型不会报错了。用此方法尝试了qwen2-72b-instruct-q5_0和qwen2-72b-instruct-q5_k_m，均成功加载。

怀疑是xinference merge的qwen2模型有问题。

**Comment by qinxuye** [comment]
ok，了解，xinf 这部分 merge 多个 gguf 的功能是社区提供的，我们需要检查下是否存在问题。

**Comment by qinxuye** [comment]
查证了一下，应该是 llamacpp 改变了 merge 的行为，和当时社区提供的时候不同了。

目前 llamacpp 可以通过提供第 0 个 part，它就能识别其他的 part，已经在 #1987 解决，等本周版本发布，请帮忙测试是否起作用。
