### ISSUE TITLE
Xinference 接入glm4-chat模型报错 KeyError: [address=127.0.0.1:63143, pid=32360] 'transformer.embedding.word_embeddings.weight'

### ISSUE THREAD

**Issue by wangsen1110** [xorbitsai/inference#1967]
### System Info / 系統信息

在win11系统下，python版本3.10.9，cuda版本12.1，
transformers                  4.41.0
xinference                    0.13.1
torch                         2.3.1+cu121
torchaudio                    2.3.1+cu121
chatglm-cpp                   0.4.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference                    0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

<img width="790" alt="微信图片_20240729153040" src="https://github.com/user-attachments/assets/e7d56d2c-1758-4074-ae54-d1f78bda0682">

<img width="1115" alt="微信图片_20240729153047" src="https://github.com/user-attachments/assets/69a09ccc-479d-430b-8280-bad1e92684df">

### Reproduction / 复现过程

在xinference启动glm4后，xinference后端报错如下：
2024-07-29 12:19:00,729 xinference.api.restful_api 32296 ERROR    [address=127.0.0.1:63143, pid=32360] 'transformer.embedding.word_embeddings.weight'
Traceback (most recent call last):
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xinference\api\restful_api.py", line 835, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    result = await result
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xinference\core\worker.py", line 841, in launch_builtin_model
    await model_ref.load()
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xinference\core\model.py", line 295, in load
    self._model.load()
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xinference\model\llm\pytorch\core.py", line 768, in load
    super().load()
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xinference\model\llm\pytorch\core.py", line 309, in load
    ) = load_compress_model(
  File "D:\soft\deves\python\anaconda3\envs\xin\lib\site-packages\xinference\model\llm\pytorch\compression.py", line 163, in load_compress_model
    model, name, device, value=compressed_state_dict[name]
KeyError: [address=127.0.0.1:63143, pid=32360] 'transformer.embedding.word_embeddings.weight'

### Expected behavior / 期待表现

在win11系统下，Xinference 接入glm4-chat模型报错 KeyError: [address=127.0.0.1:63143, pid=32360] 'transformer.embedding.word_embeddings.weight'

Xinference 里面选择chatglm3 是可以正常启动。
glm4-chat 是通过 Xinference 进行安装的，启动方式和chatglm3一样。  在参数界面glm4-chat的 quantization只能选择8-bit，4-bit是提示不支持。 但是选择8-bit，启动报错：'transformer.embedding.word_embeddings.weight

**Comment by qinxuye** [comment]
<img width="1522" alt="image" src="https://github.com/user-attachments/assets/a66e27db-b35c-4dc4-850f-4a9e1b7101dc">

测试没有问题。看下如下两个包对齐有没有问题

```
$ pip show transformers
Name: transformers
Version: 4.43.2
Summary: State-of-the-art Machine Learning for JAX, PyTorch and TensorFlow
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: /new_data3/xuyeqin/miniconda3/lib/python3.11/site-packages
Requires: filelock, huggingface-hub, numpy, packaging, pyyaml, regex, requests, safetensors, tokenizers, tqdm
Required-by: auto_gptq, autoawq, chattts, FlagEmbedding, nemo_text_processing, optimum, peft, sentence-transformers, transformers-stream-generator, vllm

$ pip show bitsandbytes
Name: bitsandbytes
Version: 0.43.0
Summary: k-bit optimizers and matrix multiplication routines.
Home-page: https://github.com/TimDettmers/bitsandbytes
Author: Tim Dettmers
Author-email: dettmers@cs.washington.edu
License: MIT
Location: /new_data3/xuyeqin/miniconda3/lib/python3.11/site-packages
Requires: numpy, torch
Required-by: 

```

**Comment by Shuming-Cheng** [comment]
我也遇到了相同的问题，也是glm4-chat 8bit量化启动时出现该问题，已经按照上文中对齐两个包版本，但还是报错KeyError: [address=127.0.0.1:3019, pid=20040] 'transformer.embedding.word_embeddings.weight'这个问题。

**Comment by qinxuye** [comment]
glm4-chat 用最新的 transformers，且 xinference 也是最新，模型权重文件更新到最新。

**Comment by zkbaba** [comment]
> 我也遇到了相同的问题，也是glm4-chat 8bit量化启动时出现该问题，已经按照上文中对齐两个包版本，但还是报错KeyError: [address=127.0.0.1:3019, pid=20040] 'transformer.embedding.word_embeddings.weight'这个问题。
你好，你是怎么解决的？我尝试把transformers和bitsandbytes分别降级到4.43.2和0.43.0，但是依旧会报这个错误。

**Comment by radishlee** [comment]
遇到同样问题，求解？
