### ISSUE TITLE
[BUG] An error occurred when inferring the downloaded 'bge-large-zh-v1.5' embedding model

### ISSUE THREAD

**Issue by okwinds** [xorbitsai/inference#2010]
### System Info 

env info:

CUDA
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0
```

transformers `Version: 4.42.4`

system: `Ubuntu 22.04 ` 

python `3.10`

### Running Xinference with Docker? 

- [ ] docker / docker
- [X] pip install 
- [ ] installation from source 

### Version info 

xinference = 0.14.0

### The command used to start Xinference 

`xinference-local -H 0.0.0.0 -p 8000`

### Reproduction 

Download the model `"bge-large-zh-v1.5"` to the customized path.
Register the model name as `“bge-large-zh-v1.5-Torch”`.

JSON Configuration :
```
{
    "model_name": "bge-large-zh-v1.5-Torch",
    "model_id": null,
    "model_revision": null,
    "model_hub": "huggingface",
    "dimensions": 1024,
    "max_tokens": 2048,
    "language": [
        "zh"
    ],
    "model_uri": "/home/gavin/llm/embeddings/bge-large-zh-v1.5",
    "is_builtin": false
}
```
![image](https://github.com/user-attachments/assets/be48597f-c77d-4ad0-a6d6-3fefbaa94b95)

Inference Error :

```
2024-08-04 10:39:22,905 xinference.api.restful_api 85519 ERROR    [address=0.0.0.0:37339, pid=86038] argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/api/restful_api.py", line 850, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/supervisor.py", line 990, in launch_builtin_model
    await _launch_model()
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/supervisor.py", line 954, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/supervisor.py", line 933, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/worker.py", line 848, in launch_builtin_model
    await model_ref.load()
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
  File "/home/gavin/miniconda3/envs/xinf_cp310/lib/python3.10/site-packages/xinference/model/embedding/core.py", line 154, in load
    "gte-Qwen2" in self._model_spec.model_id
TypeError: [address=0.0.0.0:37339, pid=86038] argument of type 'NoneType' is not iterable
```

### Expected behavior

Restore Normal Inference Capability

**Comment by qinxuye** [comment]
This is a known issue, we will fix it ASAP.
