### ISSUE TITLE
启动时报RuntimeError: Cluster is not available after multiple attempts

### ISSUE THREAD

**Issue by sunyankui** [xorbitsai/inference#2023]
### System Info / 系統信息

Python 3.11.9
windows11

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local -H 0.0.0.0

### Reproduction / 复现过程

C:\Users\Administrator>xinference-local -H 0.0.0.0
2024-08-06 10:32:37,372 xinference.core.supervisor 3216 INFO     Xinference supervisor 0.0.0.0:39084 started
2024-08-06 10:32:37,403 xinference.model.image.core 3216 WARNING  Cannot find builtin image model spec: stable-diffusion-inpainting
2024-08-06 10:32:37,404 xinference.model.image.core 3216 WARNING  Cannot find builtin image model spec: stable-diffusion-2-inpainting
2024-08-06 10:32:37,405 xinference.model.image.core 3216 WARNING  Cannot find builtin image model spec: stable-diffusion-xl-inpainting
2024-08-06 10:32:37,416 xinference.core.worker 3216 INFO     Starting metrics export server at 0.0.0.0:None
2024-08-06 10:32:37,421 xinference.core.worker 3216 INFO     Checking metrics export server...
2024-08-06 10:32:42,412 xinference.core.worker 3216 INFO     Metrics server is started at: http://0.0.0.0:51174
2024-08-06 10:32:42,413 xinference.core.worker 3216 INFO     Xinference worker 0.0.0.0:39084 started
2024-08-06 10:32:42,418 xinference.core.worker 3216 INFO     Purge cache directory: C:\Users\Administrator\.xinference\cache
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\xinference\deploy\cmdline.py", line 225, in local
    start_local_cluster(
  File "C:\Python311\Lib\site-packages\xinference\deploy\cmdline.py", line 112, in start_local_cluster
    main(
  File "C:\Python311\Lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts

### Expected behavior / 期待表现

xinference-local -H 127.0.0.1 可以正常启动，但是修改为0.0.0.0就报错，这是什么问题

**Comment by Alex-Zuo-One** [comment]
xinference-local -H 0.0.0.0
把这个 0.0.0.0 换成机器的ip试试

**Comment by sunyankui** [comment]
> xinference-local -H 0.0.0.0 把这个 0.0.0.0 换成机器的ip试试

可以用本机ip，但是我本地有chatchat他会请求127.0.0.1的地址，改chatchat的配置也不好使，所以看怎么能让xinference绑定0.0.0.0算根本决绝问题

**Comment by wangsen1110** [comment]
windows 下不能用0.0.0.0    换成 127.0.0.1 就可以了

**Comment by lhs0627** [comment]
@wangsen1110 我用127.0.0.1也报错是为什么呢xinference-local --host 127.0.0.1 --port 9997

**Comment by 824562329** [comment]
(xinference) F:\pyth\Langchain-Chatchat>xinference-local --host 127.0.0.1 --port 9997
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\xinference\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\.conda\envs\xinference\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\.conda\envs\xinference\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 224, in local
    start_local_cluster(
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 111, in start_local_cluster
    main(
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts
2024-09-05 17:02:54,223 xinference.core.supervisor 10808 INFO     Xinference supervisor 127.0.0.1:57814 started
2024-09-05 17:02:57,533 xinference.core.worker 10808 INFO     Starting metrics export server at 127.0.0.1:None
2024-09-05 17:02:57,533 xinference.core.worker 10808 INFO     Checking metrics export server...

**Comment by ddyzq** [comment]
一样的问题，和0.0.0.0的地址无关，对gradio库进行降级也没有解决。环境为WINDOWS 2022+CONDA

**Comment by fg2501** [comment]
解决了吗？我也碰到了这个问题。

**Comment by fg2501** [comment]
我也是换成本地地址就不会报错，但是换成0.0.0.0就会报错，但是如果改成本地地址的话，用其他软件就打不开这个地址的模型，直接用端口号，也打不开地址。

**Comment by qinxuye** [comment]
> 我也是换成本地地址就不会报错，但是换成0.0.0.0就会报错，但是如果改成本地地址的话，用其他软件就打不开这个地址的模型，直接用端口号，也打不开地址。

可以直接用机器的 IP。

**Comment by qinxuye** [comment]
先关闭。
