### ISSUE TITLE
模型下载,自定义模型启动: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Alex-Zuo-One** [xorbitsai/inference#2026]
### System Info / 系統信息

Linux fvm4 4.15.0-197-generic #208-Ubuntu   x86_64 
Python 3.11.9 (3.10也有尝试,一样浮现)
NVIDIA GeForce RTX 4090
NVIDIA-SMI 550.78                 Driver Version: 550.78         CUDA Version: 12.4 
vllm Version: 0.5.4
transformers Version: 4.43.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 172.16.2.174 --port 3997

### Reproduction / 复现过程

点击模型下载,启动自定义本地glm4-chat模型(vllm or transformers),均可复现
报错如下:
```
Process IndigenActorPool2984116224:
Traceback (most recent call last):
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/indigen/pool.py", line 278, in _start_sub_pool
    asyncio.run(coro)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/indigen/pool.py", line 294, in _create_sub_pool
    pool = await SubActorPool.create(
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/pool.py", line 803, in create
    servers = await cls._create_servers(
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/pool.py", line 771, in _create_servers
    await asyncio.gather(*create_server_tasks)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/communication/socket.py", line 226, in create
    aio_server = await asyncio.start_server(
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/asyncio/streams.py", line 85, in start_server
    return await loop.create_server(factory, host, port, **kwds)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('172.16.2.174', 0): address already in use
2024-08-06 19:03:58,213 xinference.api.restful_api 22685 ERROR    [address=172.16.2.174:31533, pid=22767] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xinference/api/restful_api.py", line 857, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xinference/core/supervisor.py", line 990, in launch_builtin_model
    await _launch_model()
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xinference/core/supervisor.py", line 954, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xinference/core/supervisor.py", line 933, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xinference/core/worker.py", line 819, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xinference/core/worker.py", line 540, in _create_subpool
    subpool_address = await self._main_pool.append_sub_pool(
  File "/fastdfs/sinhon/miniconda3/envs/xinfc/lib/python3.10/site-packages/xoscar/backends/indigen/pool.py", line 385, in append_sub_pool
    process_index, process_status.external_addresses[0]
TypeError: [address=172.16.2.174:31533, pid=22767] 'NoneType' object is not subscriptable

```

### Expected behavior / 期待表现

normal startup

**Comment by qinxuye** [comment]
OSError: [Errno 98] error while attempting to bind on address ('172.16.2.174', 0): address already in use

看起来是不能绑定到这个地址。

**Comment by Alex-Zuo-One** [comment]
> OSError: [Errno 98] error while attempting to bind on address ('172.16.2.174', 0): address already in use
> 
> 看起来是不能绑定到这个地址。

绑定0.0.0.0会失败
