### ISSUE TITLE
failed to register

### ISSUE THREAD

**Issue by zhaozhizhuo** [xorbitsai/inference#2036]
### System Info / 系統信息

cuda 12.2 
python3.11

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference=0.13.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local -H 0.0.0.0     

### Reproduction / 复现过程

1.xinference-local -H 0.0.0.0     
2.使用xinference register --model-type LLM --file qwen2.json --persist进行挂载模型的时候报错无法挂载模型。
下面是全部报错信息：
(vllm) root@liuyzhost:/tmp/deploy/llm/qwen2-7b-instruct# xinference register --model-type LLM --file qwen-vllm.json --persist
WARNING 08-07 15:49:27 _custom_ops.py:14] Failed to import from vllm._C with ImportError("/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/vllm/_C.abi3.so)")
Traceback (most recent call last):
  File "/tmp/deploy/anaconda/envs/vllm/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 404, in register_model
    client.register_model(
  File "/tmp/deploy/anaconda/envs/vllm/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 1134, in register_model
    raise RuntimeError(
RuntimeError: Failed to register model, detail: [address=0.0.0.0:43413, pid=85559] Invalid model URI /copydata2/zhaozhizhuo/qwen2-7b-instruct/.

### Expected behavior / 期待表现

希望能够解决如何加载问题，是否是GLIBC版本问题。

**Comment by ChengjieLi28** [comment]
@zhaozhizhuo 升级0.14.0.post1，现在注册与内置model_family一致的模型，可以直接launch时指定model_path。
另外，之前的注册方式的问题是：
```
RuntimeError: Failed to register model, detail: [address=0.0.0.0:43413, pid=85559] Invalid model URI /copydata2/zhaozhizhuo/qwen2-7b-instruct/.
```
这个路径有问题。
