### ISSUE TITLE
embedding模型配置输入长度超过4096会导致显存撑爆，请考虑添加embedding配置页面的参数

### ISSUE THREAD

**Issue by zhangyanbo2007** [xorbitsai/inference#2040]
### System Info / 系統信息

xinference==0.14.0
vllm==0.5.3.post1
torch==2.3.1
cuda==118&123

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 nohup xinference -H 0.0.0.0 --log-level debug --port 9999 >logs/xinference-0.12.3-38.log 2>&1 &

### Reproduction / 复现过程

**输入：**
2024-08-07 09:46:26,807 xinference.core.model 473204 DEBUG    Enter wrapped_func, args: (<xinference.core.model.ModelActor object at 0x7f2bc8a240e0>, ['公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第六章  附则\n第二十八条 各省级公安机关交通管理部门应当在每年年底最后一周将年度本省（区、市）公路交通事故多发点段及严重安全隐患排查工作情况上报公安部交通管理局。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第六章  附则\n第二十六条 公安机关交通管理部门可以聘请专业机构或者人员参与公路交通事故多发点段及严重安全隐患的排查工作，形成消除隐患的综合对策建议。\n\n各级公安机关交通管理部门可以视情况建立本辖区排查工作专家库以及专业机构推荐清单。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第六章  附则\n第二十四条 各级公安机关交通管理部门应当将开展公路交通事故多发点段及严重安全隐患排查的费用纳入经费保障。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第六章  附则\n附录1：公路交通事故多发点段分类参考标准\n\n一、交通事故多发点段划分\n\n道路交通事故多发点、段是指3年内，发生多起交通事故或事故损害后果极其严重，有一定规律特点的道路点、段。\n\n\n\n1、普通公路\n\n普通公路交通事故多发点的范围为：距交叉路口中心点250米（含，下同）范围内或一般路段上500米范围内，及隧道口、接入口等。\n\n普通公路交通事故多发段的范围为：道路上2000米范围内或桥梁、隧道、长大下（上）坡全程。\n\n\n\n2、高速、一级公路\n\n高速公路、一级公路多发点范围为：道路上1000米（含）范围内或收费站、隧道口、匝道口（含加减速车道）、接入口、平面交叉口等点。\n\n高速公路、一级公路交通事故多发段的范围为：道路上4000米范围内（单向）或桥梁、隧道、长大下（上）坡全程。\n\n\n\n二、交通事故多发点段分类\n\n按照公路所发生交通事故的数量及后果（不含毒驾、酒驾等事故），公路交通事故多发点段分为一类、二类、三类三种类型。其中：\n\n\n\n1、一类点、段需符合下列条件之一：\n\n（1）近3年内，发生1起及以上一次死亡5人（含）以上道路交通事故，且事故的发生与道路因素有关的；\n\n（2）近3年内，发生2起及以上一次死亡3人（含）以上道路交通事故的；\n\n（3）近3年内，发生6起以上死亡交通事故的；\n\n（4）公安机关交通管理部门认为存在特别严重安全隐患的其它事故多发点、段。\n\n\n\n2、二类点、段需符合下列条件之一：\n\n（1）近3年内，发生1起一次死亡3-4人道路交通事故，且事故的发生与道路因素有关的；\n\n（2）近3年内，发生3-5起致人死亡的交通事故的；\n\n（3）近3年内，发生6起以上致人伤亡的交通事故的；\n\n（4）公安机关交通管理部门认为存在严重安全隐患的其它事故多发点、段。\n\n\n\n3、三类点、段需符合下列条件之一：\n\n（1）近3年内，发生1-2起死亡交通事故，且事故的发生与道路因素有关的；\n\n（2）近3年内，发生3-5起致人伤亡的交通事故的；\n\n（3）一定时间内，发生道路交通事故（含简易事故）情况突出的；\n\n（4）公安机关交通管理部门认为存在安全隐患的其它事故多发点、段。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第六章  附则\n附录2：公路交通事故多发点段隐患调查分析方法\n\n一、调查方式\n\n\n\n1、 查阅相关图纸、档案、统计数据等资料；\n\n2、 对道路及安全设施实地测量检查；\n\n3、 走访、询问疑似路段途经驾驶人、周边居民等；\n\n4、 侦查实验；\n\n5、 必要时，可以委托有资质的机构进行检验鉴定；\n\n6、 其他调查方法。\n\n\n\n二、确定重点调查分析内容\n\n\n\n根据公路交通事故多发点段历史交通事故形态、原因等分布特点及所占比例，参考附表2.1确定重点调查内容。\n\n附表2.1 公路交通事故多发点段重点调查内容对照表\n\n图片\n\n\n三、常用术语解释\n\n\n\n1、公路技术等级\n\n根据交通量及其使用任务、性质，对公路进行的技术分级。我国现行《公路工程技术标准》中将公路划分为高速公路和一、二、三、四级公路。\n\n\n\n2、纵面线形\n\n公路中线在纵断面上的投影形状。\n\n\n\n3、纵坡\n\n路线纵断面上同一坡段两点间的高差与其水平距离的比值。\n\n\n\n4、平均纵坡\n\n含若干坡段的路段两端点的高差与该路段长度的比值。\n\n\n\n5、竖曲线\n\n在公路纵坡的变坡处设置的竖向曲线。\n\n\n\n6、凹形竖曲线\n\n设于公路纵坡呈凹形转折处的曲线。用以缓冲行车中因运动量变化而产生的冲击和保证夜间汽车前灯视线和汽车在立交桥下行驶时的视线。\n\n\n\n7、凸形竖曲线\n\n设于公路纵坡呈凸形转折处的曲线。用以保证汽车按设计速度行驶时有足够的行车视距。\n\n\n\n8、平面线形\n\n公路中线在水平面上的投影形状。\n\n\n\n9、圆曲线\n\n公路平面走向改变方向或竖向改变坡度时所设置的连接两相邻直线段的圆弧形曲线。\n\n\n\n10、视距三角形\n\n交叉路口处，由一条道路进入路口行驶方向的最外侧的车道中线与相交道路最内侧的车道中线的交点为顶点，两条车道中线各按其规定车速停车视距的长度为两边，所组成的三角形。在视距三角形内不允许有阻碍驾驶员视线的物体和道路设施存在。\n\n\n\n四、公路交通事故多发点段安全隐患排查参考标准\n\n\n\n应当在确定重点调查分析内容的基础上，依次对照下述详细标准分析事故多发点段存在的公路安全隐患，分析项目包含但不限于本部分所述内容。\n\n\n\n1 平面线形\n\n\n\n1、公路平曲线半径小于附表2.1中一般值的路段可以确定为急弯路段。\n\n2、急弯接桥、隧道、涵洞的。\n\n3、急弯接公路收费站、检查站的。\n\n4、急弯接高速公路服务区、停车区的。\n\n5、存在连续回头弯路段的。\n\n\n\n2 纵面线形\n\n\n\n2.1 存在长下坡\n\n1、高速公路、一级公路长下坡，是指特定相对高差，或特定平均坡度条件下，连续坡长大于表附表2.2中限值的路段。其中坡长可以按公路里程估算，相对高差可以采用GPS/北斗等定位设备测算。\n\n2、二级、三级、四级公路长下坡路段，是指相对高差为200m-500m时，平均纵坡大于5.5%的路段；或者相对高差大于500m时，平均纵坡大于5%的路段。还包括，任意连续3km路段的平均纵坡大于5.5%的。\n\n\n\n2.2 存在陡坡\n\n1、根据公路设计速度，纵坡大于附表2.3中最大纵坡的路段可以确定为陡坡路段。\n\n（1）设计速度为120km/h、100km/h、80km/h的高速公路，受地形条件或其他特殊情况限制时，最大纵坡可增加1%；\n\n（2）改扩建公路设计速度为40km/h、30km/h、20km/h的利用原有公路的路段，最大纵坡可增加1%；\n\n（3）四级公路位于海拔2000米以上或积雪冰冻地区的路段，最大纵坡大于8%的可确定为陡坡路段。\n\n2、陡坡接桥梁、隧道的。\n\n3、陡坡接公路收费站、检查站的。\n\n\n\n3 横断面设置\n\n\n\n3.1车道宽度不足\n\n公路车道宽度小于附表2.4的规定的。\n\n1、八车道及以上公路在内侧车道（内侧第1、2车道）仅限小客车通行时，其车道宽度小于3.5m的。\n\n2、以通行中、小型客运车辆为主且设计速度为80km/h及以上的公路，车道宽度小于3.5m的。\n\n3、高速公路和作为干线的一级公路右侧硬路肩小于2.5m时，未设置紧急停车带或紧急停车带宽度小于3.5m的。\n\n4、四级公路采用单行车道时，车道宽度小于3.5m的。\n\n5、设置慢车道的二级公路，慢车道宽度小于3.5m的。\n\n\n\n3.2 车道数或宽度突变\n\n1、在同一路段上，车道数或宽度发生突变，形成交通瓶颈的。\n\n2、桥梁、隧道的车道数与所在公路车道数不一致的。\n\n3、两条相接的道路，车道数一致，但衔接段线形不连续的。\n\n4、道路宽度发生突变的。\n\n5、宽路接窄桥、隧道的。\n\n\n\n4 不良线形组合\n\n\n\n同时存在急弯和陡坡，特别是出现下列情形的：\n\n1、陡坡和急弯接桥梁、隧道的。\n\n2、陡坡和急弯接公路收费站、检查站、服务区、停车区的。\n\n3、陡坡和急弯接临水临崖路段的。\n\n4、纵面线形出现驼峰、暗凹、跳跃、断背、折曲等使驾驶人视觉中断的线形的。\n\n\n\n5公路行车条件\n\n\n\n5.1路侧险要\n\n1、路肩挡墙、陡于1:3的填方边坡、路侧陡崖或深沟高度大于一定值（一般为6-8米）的。\n\n2、路侧一定距离（一般为2-5米）内有常水深0.5m以上的水体（含江河、湖泊、水库、沟渠）、干线公路或铁路等的。\n\n\n\n5.2视距不良\n\n1、行车视线受到标志牌、绿植和房屋等遮挡的。\n\n2、急弯路段弯道内侧为土丘、灌木乔木，且视距不良的。\n\n3、连续弯道末端视距不良的。\n\n4、弯道外侧为深沟、无盖板矩形边沟的。\n\n5、路肩上有巨石、电线杆或大树等的。\n\n6、急弯下坡路段，内侧山体阻挡视线，外侧为深谷的。\n\n7、陡坡路段坡顶处视距不良的。\n\n8、高速公路进出口、服务区进出口引道视距不良的。\n\n9、在平面交叉口视距三角形内有阻碍驾驶员视线的物体和道路设施存在的。\n\n\n\n5.3 路面抗滑性能不足\n\n路面摩擦力不足，明显发光发亮，路面可见车辆侧滑痕迹的。\n\n\n\n6 公路开口及交叉口设置\n\n\n\n6.1 路侧开口设置不当\n\n1、平面交叉口存在冲坡和下坡现象的。\n\n2、平面交叉口隐蔽，不容易被发现的。\n\n3、在弯道、坡道等视距不良的路侧开设路口的。\n\n\n\n6.2 大型交叉口未渠化\n\n四车道及以上多车道交叉路口未渠化设计的。\n\n\n\n6.3 缺乏信号灯控制\n\n当公路无信号控制平交路口出现如下任意一种情况时，可认定缺乏信号灯控制：[5]\n\n1、一级公路与一级公路平交的。\n\n2、两条交通量均大且功能、等级相同的公路相交。\n\n3、两相交公路虽有主次之别，但交通量均较大。\n\n4、次要公路交通量不大，但主要公路交通量相当大。\n\n5、两相交公路的交通量虽未达到上述程度，但由于有相当数量的行人和非机动车穿越交叉。\n\n6、平交路口安全停车视距三角形限界内，有妨碍机动车驾驶人视线的障碍物。\n\n7、根据平交路口交通事故情况，达到以下条件之一未设置信号灯的：\n\na) 3年内平均每年发生5次以上交通事故，事故原因分析表明通过设置信号灯可避免事故发生的。\n\nb) 3年内平均每年发生一次以上死亡交通事故的路口。\n\n8、根据路口综合条件，应当设置信号灯的。\n\n\n\n6.4 信号灯配时等设置严重不合理的。\n\n\n\n7 主要交通安全设施\n\n\n\n7.1 路侧防护栏缺失\n\n当路侧出现如下任意一种情况，且未设置防护栏时，则确定为路侧防护栏缺失：\n\n1、急弯或连续急弯，特别是连续下坡与急弯组合路段的外侧。\n\n2、长直线尽头设置有急弯路段的外侧，尤其是路面抗滑性能不足的急弯路段外侧。\n\n3、曲线段外侧较近范围内有民居、高速公路、高速铁路、高压输电线塔、危险品储存仓库的。\n\n4、桥梁两侧护栏缺失、损毁或者不连续的。\n\n5、符合5.1相关条件的。\n\n\n\n7.2 路侧护栏端头处置不当\n\n1、护栏端头外露的。\n\n2、护栏设置不连续，连续出现护栏端头的。\n\n3、高速公路主线分流端、匝道出口的护栏端头未设置防撞垫的。\n\n4、高速公路、一级公路隧道洞口护栏缺乏连接过渡的。\n\n\n\n7.3 护栏防撞能力不足\n\n1、有车辆冲过防护栏，驶出路外或驶入对向车车道发生事故的。\n\n2、高速公路桥梁、路肩墙未采用混凝土防撞护栏、金属梁柱式护栏或组合式护栏的。\n\n3、护栏有明显破损，或没有螺栓固定、螺栓松动的。\n\n4、高速公路路侧护栏高度低于0.75米的。\n\n\n\n7.4 中央隔离带设置不当\n\n1、中央隔离带开口过密，存在行人、非机动车随意穿行现象的。\n\n2、中央隔离带开口处绿化遮挡严重的。\n\n\n\n7.5 标志标线存在明显错误和缺失\n\n1、公路车道划分线、导流线以及高速公路出入口等导向线施划有矛盾或者错误的。\n\n2、标志和标线表达的内容不一致，甚至出现矛盾的。\n\n3、等级公路未设置交通标志标线的。\n\n4、连接高速公路收费站的公路交叉口未设标志标线的。\n\n5、在平交路口和路侧开口处未设警示标志的。\n\n6、指路标志前后存在矛盾或者错误的。\n\n7、高速公路指路标志被绿化遮挡的。\n\n8、高速公路出口指示标志距离出口过远的。\n\n9、高速公路出口未按标准提供三级预告标志的。\n\n10、高速公路两侧反光标识、标牌缺失的。\n\n11、在急弯、连续弯道、连续坡道等不满足会车视距要求、不宜变道的路段未施划标线或施划虚线的。\n\n12、隧道路段缺少反光标志、反光标线的。\n\n\n\n7.6 穿越村镇路段必要安全设施缺失\n\n1、穿村镇道路临近村庄、集镇且视线不良路段，未设置村庄警告标志的。\n\n2、在行人过街需求频繁的公路路段，未设置人行横道及配套标志标线的。\n\n3、在人流密度大、机非交织密集区域，缺乏必要减速设施、机非隔离设施或警示标志的。\n\n\n\n8 辅助安全设施\n\n\n\n8.1 未设置避险车道或设置不当\n\n1、连续长大下坡路段货车失控事故多发，未设置避险车道的。\n\n2、避险车道和主路角度设置不当，车辆不易驶入避险车道的。\n\n3、避险车道过短，有车辆冲出避险车道发生事故风险的。\n\n4、避险车道因长期缺乏维护，制动效能严重衰减的。\n\n5、避险车道引道入口前未设置“禁止停车”的禁令标志和“失控车辆专用”标记的。\n\n6、高速公路避险车道口未设置照明、监控等管理设施的。\n\n7、避险车道入口存在视线遮挡的。\n\n\n\n8.2 无灯光照明或亮度不足\n\n1、隧道内未亮灯，或未按规定照明的。\n\n2、在城乡结合部交通流量较大或者承担城市功能的公路没有安装照明设施的。\n\n3、因恶劣天气等因素导致存在严重安全隐患，应当安装照明设施的。\n\n\n\n8.3 其它\n\n1、高速公路、一级公路中央隔离带宽度小于9米，且夜间流量较大、大中型客货车占比高的路段未设置防眩设施的。\n\n\n\n[1] 《JTG D20-2017公路路线设计规范》\n\n[2] 《JTG D20-2017公路路线设计规范》\n\n[3] 《JTG D20-2017公路路线设计规范》\n\n[4] 《JTG D20-2017公路路线设计规范》\n\n[5] 详情可参照《GB 14886-2016 道路交通信号灯设置与安装规范》5.1路口的有关规定', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第六章  附则\n第三十条 本规范自下发之日起施行。\n附录3：公路交通事故多发点段排查报告格式\n\n一、排查报告应当包括下列内容：\n\n\n\n1封面；\n\n2著录页；\n\n3目录；\n\n4正文。\n\n\n\n二、排查报告应当采用A4幅面，左侧装订。\n\n\n\n三、封面应当包括下列内容：\n\n\n\n1行政辖区名称；\n\n2标题，统一为“公路交通事故多发点段排查报告”；\n\n3排查单位名称；\n\n4排查报告完成日期。\n\n封面式样如附图3.1所示。\n\n\n\n四、著录页应当包括下列内容：\n\n\n\n1 行政辖区名称；\n\n2 标题，统一为“公路交通事故多发点段排查报告”；\n\n3 本次排查年度；\n\n4 排查单位负责人、排查负责人及主要参加人员姓名；\n\n5 排查单位名称及公章；\n\n6 排查报告完成日期。\n\n著录页式样如附图3.2所示。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第四章 推动整改和治理\n第二十条 公安机关交通管理部门可以对事故多发点段及严重安全隐患路段的治理情况，依据交通事故数据评价治理效果。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第四章 推动整改和治理\n第十七条 公安机关交通管理部门可以根据交通事故多发点段类别或者严重安全隐患治理难度，提请同级人民政府或者道路交通安全工作联席会议等议事协调机构挂牌督办。\n\n      对隐患治理难度较大或者投入超出本地财政承担能力的，可以由上级公安机关交通管理部门提级督办。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第四章 推动整改和治理\n第十九条 公安机关交通管理部门应当定期了解掌握已报告的隐患问题治理进度。对于未及时处理的，应当督促提醒。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第四章 推动整改和治理\n第十八条 公安机关交通管理部门可以联合有关部门对排查出的公路交通事故多发点段及严重安全隐患路段，通过跟踪整改、公布提示、宣传曝光等方式，推动排查发现问题的治理。', '公路交通事故多发点段及严重安全隐患排查工作规范（试行）\n第四章 推动整改和治理\n第十六条 公安机关交通管理部门应当将排查结果书面报告同级人民政府，并抄送同级交通运输、应急管理等行业主管部门及产权单位，同时报上一级公安机关交通管理部门备案。\n\n      对于高速公路，应当将排查结果向有路产管辖权的人民政府报告，并抄送相应层级行业主管部门。', '办理使用伪造变造和挪用机动车号牌案件工作规范（试行）\n第一章 总 则\n第一条为规范使用伪造变造和挪用机动车号牌案件的办理工作，切实保障公安机关交通管理部门依法履行职责，维护公民、法人和其他组织的合法权益，根据《道路交通安全法》及其实施条例、《公安机关办理行政案件程序规定》、《道路交通安全违法行为处理程序规定》、《机动车登记规定》、《交通警察道路执勤执法工作规范》，制定本规范。', '办理使用伪造变造和挪用机动车号牌案件工作规范（试行）\n第一章 总 则\n第三条公安机关交通管理部门办理套牌案件应当以事实为根据，以法律为准绳，遵循公开、便民、高效的原则。', '办理使用伪造变造和挪用机动车号牌案件工作规范（试行）\n第一章 总 则\n第二条本规范所称伪造变造和挪用机动车号牌（以下简称“套牌”）行为，是指机动车所有人、管理人、驾驶人使用伪造、变造的其他机动车号牌或者使用其他机动车号牌的违法行为。', '办理使用伪造变造和挪用机动车号牌案件工作规范（试行）\n第一章 总 则\n第四条省级公安机关交通管理部门应当做好本省（自治区、直辖市）范围内办理套牌案件的指导、协调和检查监督。设区市或者相当于同级的公安机关交通管理部门、县级公安机关交通管理部门应当明确专人负责套牌案件的办理、群众咨询等工作。', '办理使用伪造变造和挪用机动车号牌案件工作规范（试行）\n第七章 附 则\n第三十五条 本规范自发布之日起实施。\n\n\u3000\u3000\n\n \n\n附件：1、套用机动车号牌案件受案登记表\n\n \n\n\u3000\u30002、套用机动车号牌案件受案回执单\n\n \n\n\u3000\u30003、涉嫌套牌机动车协查通知书\n\n \n\n\u3000\u30004、查获套牌违法机动车通知书\n\n \n\n\u3000\u30005、套用机动车号牌案件查处结果通知书\n\n \n\n\u3000\u30006、套用机动车号牌案件终止案件调查通知书\n\n \n\n\u3000\u30007、关于协助鉴别号牌号码为XXXXXX的机动车号牌真伪情况的函\n\n \n\n\u3000\u30008、关于号牌号码为XXXXXX机动车号牌的鉴定结果']), kwargs: {}
**输出：**
2024-08-07 09:46:28,746 xinference.core.model 473204 ERROR    Model actor is out of memory.
Traceback (most recent call last):
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xinference/core/model.py", line 410, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xinference/model/embedding/core.py", line 349, in create_embedding
    all_embeddings, all_token_nums = encode(
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xinference/model/embedding/core.py", line 292, in encode
    out_features = model.forward(features)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/sentence_transformers/models/Transformer.py", line 118, in forward
    output_states = self.auto_model(**trans_features, return_dict=False)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/gte_Qwen2-7B-instruct/modeling_qwen.py", line 1081, in forward
    layer_outputs = decoder_layer(
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/gte_Qwen2-7B-instruct/modeling_qwen.py", line 794, in forward
    hidden_states = self.mlp(hidden_states)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/gte_Qwen2-7B-instruct/modeling_qwen.py", line 186, in forward
    return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.42 GiB. GPU 
2024-08-07 09:46:29,721 xinference.api.restful_api 419621 ERROR    Remote server 0.0.0.0:42700 closed
Traceback (most recent call last):
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xinference/api/restful_api.py", line 1160, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xoscar/backends/context.py", line 106, in _wait
    await asyncio.shield(future)
  File "/root/anaconda3/envs/llm_inference_0.14.0/lib/python3.9/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:42700 closed
2024-08-07 09:46:30,643 xinference.core.worker 419754 WARNING  Process 0.0.0.0:42700 is down.

### Expected behavior / 期待表现

![image](https://github.com/user-attachments/assets/e1d1a62e-cc72-41fc-b4ac-61edf8092979)
embedding这里有个参数配置，可以选配max_model_len参数。类似大模型的配置页面：
![image](https://github.com/user-attachments/assets/e7cb9460-9a19-47c0-a76f-49f01bb11d56)

**Comment by zhangyanbo2007** [comment]
解决一下吧
