### ISSUE TITLE
新版本启动v0.14.0.post1启动sdxl-turbo失败（猜测是代码笔误：text2iamge 应为 text2image）

### ISSUE THREAD

**Issue by nikelius** [xorbitsai/inference#2044]
### System Info / 系統信息

- 操作系统：Windows 10
- nvidia-smi显示：Driver Version: 551.61 | CUDA Version: 12.4     
- nvcc版本显示：Cuda compilation tools, release 12.4, V12.4.99 | Build cuda_12.4.r12.4/compiler.33961263_0
- llama_cpp_python     0.2.82
vllm		无

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Release: v0.14.0.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 10.10.83.104 --port 9997

### Reproduction / 复现过程

操作：加载 sd-turbo 模型
前端错误显示：Server error: 400 - [address=10.10.83.104:52667, pid=8764] Unknown ability: ['text2iamge']
后台错误显示：
2024-08-08 13:01:08,985 xinference.api.restful_api 10936 ERROR    [address=10.10.83.104:52667, pid=8764] Unknown ability: ['text2iamge']
Traceback (most recent call last):
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\api\restful_api.py", line 857, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\pool.py", line 370, in _run_coro
    return await coro
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\supervisor.py", line 990, in launch_builtin_model
    await _launch_model()
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\supervisor.py", line 954, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\supervisor.py", line 933, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\worker.py", line 850, in launch_builtin_model
    await model_ref.load()
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\pool.py", line 370, in _run_coro
    return await coro
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\model.py", line 295, in load
    self._model.load()
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\model\image\stable_diffusion\core.py", line 78, in load
    raise ValueError(f"Unknown ability: {self._abilities}")
ValueError: [address=10.10.83.104:52667, pid=8764] Unknown ability: ['**text2iamge**']

### Expected behavior / 期待表现

正常启动 sdxl-turbo、sd-turbo等服务。

猜测是代码中的笔误导致：text2iamge 应为 text2image

**Comment by AnomeZ** [comment]
碰到相同问题了，有解决方案了吗？

**Comment by AnomeZ** [comment]
我没找到具体哪里写错了，所以偷懒将错就错，把core.py的报错判断改成了` if "text2iamge" in self._abilities or "image2image" in self._abilities:
            from diffusers import AutoPipelineForText2Image as AutoPipelineModel`，可以运行。

**Comment by nikelius** [comment]
更新到v0.14.1后，已可正常启动。
