### ISSUE TITLE
不能自己注册并拉起 FLUX.1-dev

### ISSUE THREAD

**Issue by luckfu** [xorbitsai/inference#2053]
### System Info / 系統信息

registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -d \
  --name xinference \
  --restart=unless-stopped \
  -p 9997:9997 \
  --gpus all \
  -e XINFERENCE_MODEL_SRC=/models \
  -v /nfsdata/models:/models \
  -v /nfsdata/llm-api/xinference/data:/root/.xinference \
  -v /nfsdata/models:/root/.cache/huggingface \
  -v /nfsdata/models:/root/.cache/modelscope \
  xprobe/xinference:v0.14.0 \
  xinference-local -H 0.0.0.0

### Reproduction / 复现过程

我已经下载好模型在`/models/black-forest-labs/FLUX.1-dev` 路径下
通过注册 FLUX.1-dev 模型
```json
{
    "model_name": "FLUX",
    "model_id": null,
    "model_revision": null,
    "model_hub": "huggingface",
    "model_family": "stable_diffusion",
    "abilities": null,
    "controlnet": [],
    "model_uri": "/models/black-forest-labs/FLUX.1-dev/",
    "is_builtin": false
}
```

<img width="1137" alt="截屏2024-08-09 15 57 57" src="https://github.com/user-attachments/assets/67326d14-fef8-4246-88bb-8945c7c7b04a">
启动模型时，报错
<img width="1091" alt="截屏2024-08-09 15 58 39" src="https://github.com/user-attachments/assets/e8498374-7e4d-44e1-bd8a-1031cc68ad8c">
日志显示:

```
2024-08-09 08:11:31,854 xinference.model.utils 76 INFO     Model caching from URI: /models/black-forest-labs/FLUX.1-dev/
2024-08-09 08:11:31,856 xinference.model.utils 76 INFO     cache /models/black-forest-labs/FLUX.1-dev exists
2024-08-09 08:11:31,858 xinference.core.worker 76 ERROR    Failed to load model flux-1-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 838, in launch_builtin_model
    await self.update_cache_status(model_name, model_description)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 719, in update_cache_status
    model_path = version_info[0]["model_file_location"]
IndexError: list index out of range
2024-08-09 08:11:31,900 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:29979, pid=76] list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 850, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 990, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 954, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 933, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 838, in launch_builtin_model
    await self.update_cache_status(model_name, model_description)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 719, in update_cache_status
    model_path = version_info[0]["model_file_location"]
IndexError: [address=0.0.0.0:29979, pid=76] list index out of range
```

### Expected behavior / 期待表现

我哪里做错了吗？

**Comment by luckfu** [comment]
registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.0 这个版本的容器中，模型列表里并没有FLUX.1-dev，我需要自己重新构建一个吗？

**Comment by qinxuye** [comment]
> registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.0 这个版本的容器中，模型列表里并没有FLUX.1-dev，我需要自己重新构建一个吗？

等下会发 0.14.1 会支持。

**Comment by qinxuye** [comment]
已支持。
