### ISSUE TITLE
Xinfernece==0.14报错，笔记本i5核显启动服务报错  RuntimeError: Cluster is not available after multiple attempts

### ISSUE THREAD

**Issue by YiKangMo** [xorbitsai/inference#2058]
### System Info / 系統信息

xinference[transformers]==0.14.1
python== 3.10.14 

设备名称	LAPTOP-J8K4706U
处理器	12th Gen Intel(R) Core(TM) i5-12500H   2.50 GHz
机带 RAM	16.0 GB (15.7 GB 可用)
设备 ID	B6F3C2D0-9369-4C92-830B-EC30F4AEF41A
产品 ID	00330-80000-00000-AA299
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	为 10 触摸点提供触控支持
版本	Windows 11 专业版
版本号	23H2
安装日期	‎2024/‎6/‎19
操作系统版本	22631.3880
体验	Windows Feature Experience Pack 1000.22700.1020.0
制造商	HUAWEI
电话	950800
小时	普通话7*24小时

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Xinference=0.14.1

### The command used to start Xinference / 用以启动 xinference 的命令

(xin) C:\Users\Administrator\Desktop\Langchain-Chatchat\libs\chatchat-server\chatchat>xinference-local --host 0.0.0.0 --port 9997
2024-08-09 23:00:28,557 xinference.core.supervisor 22240 INFO     Xinference supervisor 0.0.0.0:32094 started
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\xin\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\.conda\envs\xin\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xinference\deploy\local.py", line 87, in run
    loop.run_until_complete(task)
  File "C:\Users\Administrator\.conda\envs\xin\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xinference\deploy\local.py", line 51, in _start_local_cluster
    await xo.create_actor(
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xoscar\api.py", line 78, in create_actor
    return await ctx.create_actor(actor_cls, *args, uid=uid, address=address, **kwargs)
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xoscar\backends\context.py", line 143, in create_actor
    return self._process_result_message(result)
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xoscar\backends\pool.py", line 595, in create_actor
    await self._run_coro(message.message_id, actor.__post_create__())
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xinference\core\supervisor.py", line 168, in __post_create__
    from ..model.flexible import (
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xinference\model\flexible\__init__.py", line 35, in <module>
    model_spec = FlexibleModelSpec.parse_obj(json.load(fd))
  File "C:\Users\Administrator\.conda\envs\xin\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\Administrator\.conda\envs\xin\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\.conda\envs\xin\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\.conda\envs\xin\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: [address=0.0.0.0:32094, pid=22240] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\xin\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\.conda\envs\xin\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\.conda\envs\xin\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xinference\deploy\cmdline.py", line 224, in local
    start_local_cluster(
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xinference\deploy\cmdline.py", line 111, in start_local_cluster
    main(
  File "C:\Users\Administrator\.conda\envs\xin\lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts

### Reproduction / 复现过程

步骤1.
pip install xinference[transformers]==0.14.1
步骤2.
xinference-local --host 0.0.0.0 --port 9997
结果.
RuntimeError: Cluster is not available after multiple attempts

### Expected behavior / 期待表现

0.13版本可正常启动服务，升级0.14后启动服务报错，

**Comment by YiKangMo** [comment]
重新换个新环境一样报错，但是安装0.13版本即可正常开启服务

**Comment by lukuanwang-delta** [comment]
> 重新换个新环境conda一样报错，但是安装0.13版本即可正常开启服务

我是0.14.3版本，使用源码执行xinference-local --host 0.0.0.0 --port 9997 也是此错误

**Comment by yuxi9264** [comment]
我也是这样 windows10系统，host都并未使用 0.0.0.0 而是使用的自己ip，同样报这个错误，0.13.0并未有此问题

**Comment by MrWangChong** [comment]
这个问题解决了吗?
