### ISSUE TITLE
v0.14.1 docker 启动失败

### ISSUE THREAD

**Issue by Minamiyama** [xorbitsai/inference#2059]
### System Info / 系統信息

windows 11, docker desktop

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.14.1

### The command used to start Xinference / 用以启动 xinference 的命令

version: '3.8'
name: xinference
services:
  xinference:
    image: registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.1
    ports:
      - "9997:9997"
    restart: always
    volumes:
      - ./root:/root
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
      - HF_ENDPOINT=https://hf-mirror.com
    command: xinference-local --host 0.0.0.0 --port 9997 --log-level debug 
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

### Reproduction / 复现过程

docker compose up -d

2024-08-09 23:51:33 WARNING 08-09 15:51:33 _core_ext.py:175] Failed to import from vllm._core_C with ImportError('/usr/local/lib/python3.10/dist-packages/vllm/_core_C.abi3.so: undefined symbol: _ZNK3c105Error4whatEv')
2024-08-09 23:51:37 WARNING 08-09 15:51:37 _core_ext.py:175] Failed to import from vllm._core_C with ImportError('/usr/local/lib/python3.10/dist-packages/vllm/_core_C.abi3.so: undefined symbol: _ZNK3c105Error4whatEv')
2024-08-09 23:51:37 Traceback (most recent call last):
2024-08-09 23:51:37   File "/usr/local/bin/xinference-local", line 5, in <module>
2024-08-09 23:51:37     from xinference.deploy.cmdline import local
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 37, in <module>
2024-08-09 23:51:37     _install()
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 34, in _install
2024-08-09 23:51:37     install_model()
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/xinference/model/__init__.py", line 19, in _install
2024-08-09 23:51:37     llm_install()
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/__init__.py", line 133, in _install
2024-08-09 23:51:37     from .vllm.core import VLLMChatModel, VLLMModel
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/vllm/core.py", line 85, in <module>
2024-08-09 23:51:37     import vllm  # noqa: F401
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 3, in <module>
2024-08-09 23:51:37     from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 7, in <module>
2024-08-09 23:51:37     from vllm.config import (CacheConfig, DecodingConfig, DeviceConfig,
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 11, in <module>
2024-08-09 23:51:37     from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/__init__.py", line 1, in <module>
2024-08-09 23:51:37     from vllm.model_executor.sampling_metadata import SamplingMetadata
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/sampling_metadata.py", line 11, in <module>
2024-08-09 23:51:37     from vllm.utils import (async_tensor_h2d, is_pin_memory_available,
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 29, in <module>
2024-08-09 23:51:37     from vllm import _custom_ops as ops
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/_custom_ops.py", line 7, in <module>
2024-08-09 23:51:37     from vllm._core_ext import ScalarType
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/vllm/_core_ext.py", line 177, in <module>
2024-08-09 23:51:37     ScalarType = torch.classes._core_C.ScalarType
2024-08-09 23:51:37   File "/usr/local/lib/python3.10/dist-packages/torch/_classes.py", line 12, in __getattr__
2024-08-09 23:51:37     proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
2024-08-09 23:51:37 RuntimeError: Tried to instantiate class '_core_C.ScalarType', but it does not exist! Ensure that it is registered via torch::class_

### Expected behavior / 期待表现

正常启动

**Comment by qinxuye** [comment]
这……镜像又出问题

**Comment by dingqiangit** [comment]
同样的问题

**Comment by luckfu** [comment]
好了吗？

**Comment by CliffHan** [comment]
same error, revert to v0.14.0.
I guess this error may caused by vllm-openai:latest image released several days ago.

**Comment by harryzwh** [comment]
same here

**Comment by Alex-Zuo-One** [comment]
same here

**Comment by FanziSufu** [comment]
same here

**Comment by qinxuye** [comment]
We are about to release new docker image tomorrow.

**Comment by Aaronchannn** [comment]
same same

**Comment by qinxuye** [comment]
各位试下 nightly-main tag 的镜像是否已经修复。

**Comment by Minamiyama** [comment]
> 各位试下 nightly-main tag 的镜像是否已经修复。

实测ok

**Comment by xmlululu** [comment]
是不是阿里云的镜像还没有同步，出现了同样问题

**Comment by Minamiyama** [comment]
亲测v0.14.1.post1已可以正常运行
