### ISSUE TITLE
AutoPipeline can't find a pipeline linked to FluxPipeline for None

### ISSUE THREAD

**Issue by luckfu** [xorbitsai/inference#2063]
### System Info / 系統信息

transformers 4.41.2
torch 2.3.1+cu121

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

v0.14.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference --host 0.0.0.0 --port 9997
/data/miniconda3/lib/python3.10/site-packages/xinference/deploy/cmdline.py:164: DeprecationWarning: Starting a local 'xinference' cluster via the 'xinference' command line is deprecated and will be removed in a future release. Please use the new 'xinference-local' command.
  warnings.warn(
2024-08-11 01:56:18,110 xinference.core.supervisor 3263 INFO     Xinference supervisor 0.0.0.0:36755 started
2024-08-11 01:56:18,527 xinference.core.worker 3263 INFO     Purge cache directory: /root/.xinference/cache
2024-08-11 01:56:18,531 xinference.core.worker 3263 INFO     Connected to supervisor as a fresh worker
2024-08-11 01:56:18,548 xinference.core.worker 3263 INFO     Xinference worker 0.0.0.0:36755 started
2024-08-11 01:56:24,540 xinference.api.restful_api 3195 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997
2024-08-11 01:56:24,696 uvicorn.error 3195 INFO     Uvicorn running on http://0.0.0.0:9997 (Press CTRL+C to quit)

### Reproduction / 复现过程

<img width="771" alt="截屏2024-08-11 10 56 43" src="https://github.com/user-attachments/assets/c2c744be-0a61-4ce5-8f9e-ec7410b6a329">
```
2024-08-11 02:36:58,080 xinference.api.restful_api 3195 ERROR    [address=0.0.0.0:36435, pid=4196] AutoPipeline can't find a pipeline linked to FluxPipeline for None
Traceback (most recent call last):
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/api/restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/core/supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/core/supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/core/worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/miniconda3/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/core/model.py", line 300, in load
    self._model.load()
  File "/data/miniconda3/lib/python3.10/site-packages/xinference/model/image/stable_diffusion/core.py", line 135, in load
    self._model = AutoPipelineModel.from_pretrained(
  File "/data/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 339, in from_pretrained
    text_2_image_cls = _get_task_class(AUTO_TEXT2IMAGE_PIPELINES_MAPPING, orig_class_name)
  File "/data/miniconda3/lib/python3.10/site-packages/diffusers/pipelines/auto_pipeline.py", line 162, in _get_task_class
    raise ValueError(f"AutoPipeline can't find a pipeline linked to {pipeline_class_name} for {model_name}")
ValueError: [address=0.0.0.0:36435, pid=4196] AutoPipeline can't find a pipeline linked to FluxPipeline for None
```

### Expected behavior / 期待表现

希望正常启动FLUX.1.xxx

**Comment by qinxuye** [comment]
Upgrade diffusers to 0.30.0

**Comment by luckfu** [comment]
> Upgrade diffusers to 0.30.0

已更新，有个新问题，我有4块4090，启动的时候始终只用到第一块，报显存不足退出

**Comment by qinxuye** [comment]
参考 https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/image.html#tips-for-large-image-models-including-sd3-medium-flux-1

**Comment by luckfu** [comment]
> 参考 https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/image.html#tips-for-large-image-models-including-sd3-medium-flux-1

请问类似`xinference launch --model-name FLUX.1-dev --model-type image --quantize_text_encoder text_encoder_2` 这样的方式运行，我用什么参数指定本地模型路径呢？  `xinference launch --help` 中似乎没有看到

**Comment by qinxuye** [comment]
目前需要指定 --model_path xxx，后面我们添加成内置的。

**Comment by uid10086** [comment]
大坑，注意需要安装  pip install transformers[sentencepiece]
