### ISSUE TITLE
ConnectionRefusedError: [WinError 10061]

### ISSUE THREAD

**Issue by YinyiE** [xorbitsai/inference#2064]
### System Info / 系統信息

windows11
python(conda)3.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

任意以xinference起始的命令

### Reproduction / 复现过程

当我运行xinference相关指令时出现以下报错
Traceback (most recent call last):
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\connectionpool.py", line 497, in _make_request
    conn.request(
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\connection.py", line 395, in request
    self.endheaders()
  File "D:\cuda3envs\xinference\lib\http\client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\cuda3envs\xinference\lib\http\client.py", line 1038, in _send_output
    self.send(msg)
  File "D:\cuda3envs\xinference\lib\http\client.py", line 976, in send
    self.connect()
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001CF7FB1F1C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\cuda3envs\xinference\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "D:\cuda3envs\xinference\lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/cluster/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF7FB1F1C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\cuda3envs\xinference\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\cuda3envs\xinference\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\cuda3envs\xinference\Scripts\xinference.exe\__main__.py", line 7, in <module>
    sys.exit(cli())
  File "D:\cuda3envs\xinference\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\cuda3envs\xinference\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\cuda3envs\xinference\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\cuda3envs\xinference\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\cuda3envs\xinference\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\cuda3envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 478, in list_model_registrations
    client = RESTfulClient(base_url=endpoint, api_key=api_key)
  File "D:\cuda3envs\xinference\lib\site-packages\xinference\client\restful\restful_client.py", line 870, in __init__
    self._check_cluster_authenticated()
  File "D:\cuda3envs\xinference\lib\site-packages\xinference\client\restful\restful_client.py", line 888, in _check_cluster_authenticated
    response = requests.get(url)
  File "D:\cuda3envs\xinference\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\cuda3envs\xinference\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\cuda3envs\xinference\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\cuda3envs\xinference\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\cuda3envs\xinference\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/cluster/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF7FB1F1C0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

我尝试过关掉所有防火墙等软件但均无效
但是xinference-local相关指令正常

### Expected behavior / 期待表现

xinference指令正常执行

**Comment by jmb123456** [comment]
你先用xinference-local -H 127.0.0.1 -p 9997 启动服务框架，然后再用其他指令试试

**Comment by zhangever** [comment]
最新版本0.15.1依然存在这个问题。
我是在xinference-local进程启动之后，休眠10s，然后开始加载bce-embedding模型。 以前都是没问题的，升级版本后就报上面的连接异常。

通过反复验证，发现只要休眠20s 在加载模型，那就不会报错。
