### ISSUE TITLE
启动FLUX.1-schnell错误：TypeError：load_checkpoint_and_dispatch() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by nikelius** [xorbitsai/inference#2071]
### System Info / 系統信息

Windows 10
Python 3.10.13
Driver Version: 551.61
cuda_12.4.r12.4/compiler.33961263_0
无vllm

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Release: v0.14.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 127.0.0.1 --port 9997

### Reproduction / 复现过程

1，启动FLUX.1-schnell （参数：1副本，GPU，modelscope）

错误信息：
2024-08-13 10:10:40,238 xinference.api.restful_api 20828 ERROR    [address=10.10.83.104:54884, pid=29044] load_checkpoint_and_dispatch() got an unexpected keyword argument 
'strict'
Traceback (most recent call last):
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\api\restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\pool.py", line 370, in _run_coro
    return await coro
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "G:\miniconda\envs\py310\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\core\model.py", line 300, in load
    self._model.load()
  File "G:\miniconda\envs\py310\lib\site-packages\xinference\model\image\stable_diffusion\core.py", line 135, in load
    self._model = AutoPipelineModel.from_pretrained(
  File "G:\miniconda\envs\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "G:\miniconda\envs\py310\lib\site-packages\diffusers\pipelines\auto_pipeline.py", line 382, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "G:\miniconda\envs\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "G:\miniconda\envs\py310\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 876, in from_pretrained
    loaded_sub_model = load_sub_model(
  File "G:\miniconda\envs\py310\lib\site-packages\diffusers\pipelines\pipeline_loading_utils.py", line 700, in load_sub_model
    loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
  File "G:\miniconda\envs\py310\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "G:\miniconda\envs\py310\lib\site-packages\diffusers\models\modeling_utils.py", line 774, in from_pretrained
    accelerate.load_checkpoint_and_dispatch(
TypeError: [address=10.10.83.104:54884, pid=29044] load_checkpoint_and_dispatch() got an unexpected keyword argument 'strict'

### Expected behavior / 期待表现

正常启动

**Comment by qinxuye** [comment]
pip show diffusers 看下版本

**Comment by nikelius** [comment]
pip show diffusers
Name: diffusers
Version: 0.30.0

> pip show diffusers 看下版本

**Comment by qinxuye** [comment]
更新 accelerate 试下。

**Comment by nikelius** [comment]
Successfully installed accelerate-0.33.0 | 替换 accelerate-0.25.0
谢谢秦总，已经解决。
