### ISSUE TITLE
14.1版本

### ISSUE THREAD

**Issue by YSblack** [xorbitsai/inference#2072]
### System Info / 系統信息

docker运行

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

14.1

### The command used to start Xinference / 用以启动 xinference 的命令

WARNING 08-13 02:33:37 _core_ext.py:175] Failed to import from vllm._core_C with ImportError('/usr/local/lib/python3.10/dist-packages/vllm/_core_C.abi3.so: undefined symbol: _ZNK3c105Error4whatEv')
Traceback (most recent call last):
  File "/usr/local/bin/xinference-local", line 5, in <module>
    from xinference.deploy.cmdline import local
  File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 37, in <module>
    _install()
  File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 34, in _install
    install_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/__init__.py", line 19, in _install
    llm_install()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/__init__.py", line 133, in _install
    from .vllm.core import VLLMChatModel, VLLMModel
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/vllm/core.py", line 85, in <module>
    import vllm  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 7, in <module>
    from vllm.config import (CacheConfig, DecodingConfig, DeviceConfig,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 11, in <module>
    from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/__init__.py", line 1, in <module>
    from vllm.model_executor.sampling_metadata import SamplingMetadata
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/sampling_metadata.py", line 11, in <module>
    from vllm.utils import (async_tensor_h2d, is_pin_memory_available,
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 29, in <module>
    from vllm import _custom_ops as ops
  File "/usr/local/lib/python3.10/dist-packages/vllm/_custom_ops.py", line 7, in <module>
    from vllm._core_ext import ScalarType
  File "/usr/local/lib/python3.10/dist-packages/vllm/_core_ext.py", line 177, in <module>
    ScalarType = torch.classes._core_C.ScalarType
  File "/usr/local/lib/python3.10/dist-packages/torch/_classes.py", line 12, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '_core_C.ScalarType', but it does not exist! Ensure that it is registered via torch::class_

### Reproduction / 复现过程

docker compose up -d 运行后报错

WARNING 08-13 02:33:37 _core_ext.py:175] Failed to import from vllm._core_C with ImportError('/usr/local/lib/python3.10/dist-packages/vllm/_core_C.abi3.so: undefined symbol: _ZNK3c105Error4whatEv')
Traceback (most recent call last):
  File "/usr/local/bin/xinference-local", line 5, in <module>
    from xinference.deploy.cmdline import local
  File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 37, in <module>
    _install()
  File "/usr/local/lib/python3.10/dist-packages/xinference/__init__.py", line 34, in _install
    install_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/__init__.py", line 19, in _install
    llm_install()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/__init__.py", line 133, in _install
    from .vllm.core import VLLMChatModel, VLLMModel
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/vllm/core.py", line 85, in <module>
    import vllm  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/vllm/__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "/usr/local/lib/python3.10/dist-packages/vllm/engine/arg_utils.py", line 7, in <module>
    from vllm.config import (CacheConfig, DecodingConfig, DeviceConfig,
  File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 11, in <module>
    from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/__init__.py", line 1, in <module>
    from vllm.model_executor.sampling_metadata import SamplingMetadata
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/sampling_metadata.py", line 11, in <module>
    from vllm.utils import (async_tensor_h2d, is_pin_memory_available,
  File "/usr/local/lib/python3.10/dist-packages/vllm/utils.py", line 29, in <module>
    from vllm import _custom_ops as ops
  File "/usr/local/lib/python3.10/dist-packages/vllm/_custom_ops.py", line 7, in <module>
    from vllm._core_ext import ScalarType
  File "/usr/local/lib/python3.10/dist-packages/vllm/_core_ext.py", line 177, in <module>
    ScalarType = torch.classes._core_C.ScalarType
  File "/usr/local/lib/python3.10/dist-packages/torch/_classes.py", line 12, in __getattr__
    proxy = torch._C._get_custom_class_python_wrapper(self.name, attr)
RuntimeError: Tried to instantiate class '_core_C.ScalarType', but it does not exist! Ensure that it is registered via torch::class_

### Expected behavior / 期待表现

镜像包感觉异常

**Comment by qinxuye** [comment]
Duplicated with #2059 .
