### ISSUE TITLE
视频模型不显示

### ISSUE THREAD

**Issue by YSblack** [xorbitsai/inference#2103]
### System Info / 系統信息

docker14.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

14.2

### The command used to start Xinference / 用以启动 xinference 的命令

docekr compuse up -d

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/bfb4ee17-3b01-4a7f-be7e-3bb95e095798)
其他板块都有可以加载模型，只有视频不能加载模型

### Expected behavior / 期待表现

麻烦修复一下

**Comment by qinxuye** [comment]
强行刷新页面试下。

**Comment by YSblack** [comment]
> 强行刷新页面试下。

还是一样的问题
![image](https://github.com/user-attachments/assets/9dc7fe3c-03be-4cea-9d45-dfa63118ca06)

**Comment by qinxuye** [comment]
版本确认下

**Comment by YSblack** [comment]
> 版本确认下

14.2版本

![image](https://github.com/user-attachments/assets/75989b4d-d70d-4f81-9417-b97cd57fe51e)

**Comment by qinxuye** [comment]
服务端日志有报错吗？

**Comment by YSblack** [comment]
> 服务端日志有报错吗？
这是日志报错信息

![image](https://github.com/user-attachments/assets/6d90051e-ba57-4db2-b691-2862ef4745db)

**Comment by YSblack** [comment]
docker-compose.yml配置信息
version: '3.8'

services:
  xinference:
    container_name: xinference-supervisor
    image: xprobe/xinference:nightly-main
    # xprobe/xinference:v0.14.2
    # swr.cn-east-3.myhuaweicloud.com/kubesre/docker.io/xprobe/xinference:v0.14.0.post1
    #swr.cn-east-3.myhuaweicloud.com/kubesre/docker.io/xprobe/xinference:latest
    restart: always
    ports:
      - "9997:9997"
      - "11111:11111"
#      - "9995:9995"
    network_mode: host
    environment:
      - XINFERENCE_MODEL_SRC=modelscope
    volumes:
      - /public/AI/xinference/.cache/modelscope:/root/.cache/modelscope
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    command: xinference-supervisor -H 192.168.30.186 -p 9997
  
使用集群模式不能显示video模型
使用xinference-local 本地模式可以显示video模型

集群模式：
![image](https://github.com/user-attachments/assets/6099ee29-0a04-49c5-be6c-38fe6d8ad6ef)

集群模式报错
2024-08-20 01:59:18,954 xinference.api.restful_api 1 ERROR    [address=192.168.30.186:18904, pid=1] Unsupported model type: video
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1814, in list_model_registrations
    data = await (await self._get_supervisor_ref()).list_model_registrations(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 546, in list_model_registrations
    ret.extend(await worker.list_model_registrations(model_type, detailed))
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 673, in list_model_registrations
    raise ValueError(f"Unsupported model type: {model_type}")
ValueError: [address=192.168.30.186:18904, pid=1] Unsupported model type: video

本地模式：
![image](https://github.com/user-attachments/assets/aa1c63e2-c308-40cd-a852-34039daca354)
