### ISSUE TITLE
注册自定义的微调后的Embedding模型时报错

### ISSUE THREAD

**Issue by huangjun11** [xorbitsai/inference#2124]
### System Info / 系統信息

CUDA 12.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [x] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 0.14.1.post1

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_MODEL=/data/embedding xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

xinference register --model-type embedding --file bge-embedding-base-sql.json --persist

file内容：
{
    "model_name": "bge-embedding-base-sql",
    "dimensions": 768,
    "max_tokens": 512,
    "language": ["zh"],
    "model_uri": "/data/embedding/bge-embedding-sql-base_v1.1"
}

报错如下：
```
Traceback (most recent call last):
  File "/data/conda-envs/embedding/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/data/conda-envs/embedding/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/conda-envs/embedding/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/conda-envs/embedding/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/conda-envs/embedding/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/conda-envs/embedding/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/data/conda-envs/embedding/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 403, in register_model
    client.register_model(
  File "/data/conda-envs/embedding/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 1148, in register_model
    raise RuntimeError(
RuntimeError: Failed to register model, detail: [address=0.0.0.0:26645, pid=2629120] 1 validation error for CustomEmbeddingModelSpec
__root__
  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=; pos=0; lineno=1; colno=1)
```

### Expected behavior / 期待表现

模型注册成功

**Comment by qinxuye** [comment]
我试了下你的 json，只是报错 uri 不存在（我机器上没这个目录）没碰到你的这个问题。
