### ISSUE TITLE
运行所有的reranker模型，均提示got an unexpected keyword argument 'trust_remote_code'

### ISSUE THREAD

**Issue by chengoak** [xorbitsai/inference#2130]
### System Info / 系統信息

python=3.10
xinference运行在conda环境下，通过pip install "xinference[all]"安装，未安装其他插件。

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

 0.14.2

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/opt/xinference HF_ENDPOINT=https://hf-mirror.com XINFERENCE_MODEL_SRC=modelscope /usr/local/bin/xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1、启用reranker，模型能正常下载
2、下载完成后，打开模型失败，提示信息：
2024-08-20 23:09:43,357 xinference.api.restful_api 28149 ERROR    [address=0.0.0.0:37683, pid=50923] CrossEncoder.__init__() got an unexpected keyword argument 'trust_remote_code'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 300, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/rerank/core.py", line 165, in load
    self._model = CrossEncoder(
TypeError: [address=0.0.0.0:37683, pid=50923] CrossEncoder.__init__() got an unexpected keyword argument 'trust_remote_code'

3、运行embedding模型无此问题，运行所有的reranker模型均如此

### Expected behavior / 期待表现

正常运行reranker模型

**Comment by qinxuye** [comment]
更新 sentence-transformers 到 2.7.0 以上，检查你的版本。

**Comment by ztzheng** [comment]
> 更新 sentence-transformers 到 2.7.0 以上，检查你的版本。

现在版本是2.7.0，如图：
![Snipaste_2024-08-21_17-19-49](https://github.com/user-attachments/assets/ac67f038-b29f-4a47-81c5-eda1a5bda259)

**Comment by utopia2077** [comment]
升级这两个包之后解决了这个问题：
Name: accelerate
Version: 0.33.0

Name: sentence-transformers
Version: 3.0.1

**Comment by ztzheng** [comment]
> 升级这两个包之后解决了这个问题： Name: accelerate Version: 0.33.0
> 
> Name: sentence-transformers Version: 3.0.1

你好，accelerate 版本是0.33.0，sentence-transformers无论是2.7.0或者3.0.1都有这个问题
