### ISSUE TITLE
删除模型缓存失败

### ISSUE THREAD

**Issue by ztzheng** [xorbitsai/inference#2138]
### System Info / 系統信息

python=3.10
xinference运行在conda环境下，通过pip install "xinference[all]"安装，未安装其他插件。

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.14.2

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/opt/xinference HF_ENDPOINT=https://hf-mirror.com/ XINFERENCE_MODEL_SRC=modelscope /usr/local/bin/xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

删除已缓存的大模型，提示信息如下：

```
2024-08-21 18:26:57,952 xinference.api.restful_api 74464 ERROR    [address=0.0.0.0:44068, pid=74570] No module named 'xinference.model.llm.pytorch'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1939, in confirm_and_remove_model
    res = await (await self._get_supervisor_ref()).confirm_and_remove_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 1320, in confirm_and_remove_model
    ret = ret and await worker.confirm_and_remove_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 1094, in confirm_and_remove_model
    paths = await self.list_deletable_models(model_version)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 1084, in list_deletable_models
    from ..model.llm.pytorch.tensorizer_utils import get_tensorizer_dir
ModuleNotFoundError: [address=0.0.0.0:44068, pid=74570] No module named 'xinference.model.llm.pytorch'
```

### Expected behavior / 期待表现

正常删除大模型

**Comment by qinxuye** [comment]
Fixed by #2114 .

会在本周发布版本中包含。
