### ISSUE TITLE
BUG: RuntimeError was raised when launch models simultaneously

### ISSUE THREAD

**Issue by aresnow1** [xorbitsai/inference#214]
### Describe the bug
RuntimeError was raised when launch models simultaneously.

### To Reproduce
```
Traceback (most recent call last):
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/gradio.py", line 301, in select_model
    model_uid = self._create_model(
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/gradio.py", line 61, in _create_model
    return self._api.launch_model(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/api.py", line 108, in launch_model
    return self._isolation.call(_launch_model())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/isolation.py", line 44, in call
    return fut.result()
           ^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/api.py", line 98, in _launch_model
    await supervisor_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 270, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 404, in _handle_actor_result
  File "xoscar/core.pyx", line 447, in _run_actor_async_generator
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x1740fd510 [locked, waiters:1]> is bound to a different event loop
Traceback (most recent call last):
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/routes.py", line 439, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/blocks.py", line 1384, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/blocks.py", line 1089, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/site-packages/gradio/utils.py", line 700, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/gradio.py", line 301, in select_model
    model_uid = self._create_model(
                ^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/gradio.py", line 61, in _create_model
    return self._api.launch_model(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/api.py", line 108, in launch_model
    return self._isolation.call(_launch_model())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/Documents/projects/inference/xinference/isolation.py", line 44, in call
    return fut.result()
           ^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/hekaisheng/Documents/projects/inference/xinference/core/api.py", line 98, in _launch_model
    await supervisor_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 266, in __pyx_actor_method_wrapper
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/Users/hekaisheng/miniconda3/envs/py311/lib/python3.11/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x1740fd510 [unlocked, waiters:1]> is bound to a different event loop
```

**Comment by UranusSeven** [comment]
Fixed by #546
