### ISSUE TITLE
使用文档里的命令，启动embeeding模型，报错

### ISSUE THREAD

**Issue by nowang6** [xorbitsai/inference#2140]
### System Info / 系統信息

帮助文档地址：
https://inference.readthedocs.io/zh-cn/latest/models/builtin/embedding/bge-large-zh-v1.5.html

xinference launch --model-name bge-large-zh-v1.5 --model-type embedding

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference                        0.14.2
xinference-client                 0.13.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference launch --model-name bge-large-zh-v1.5 --model-type embedding

### Reproduction / 复现过程

执行
xinference launch --model-name bge-large-zh-v1.5 --model-type embedding

(chat) ➜  code xinference launch --model-name bge-large-zh-v1.5 --model-type embedding
Launch model name: bge-large-zh-v1.5 with kwargs: {}
Traceback (most recent call last):
  File "/home/niwang/miniconda3/envs/chat/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 902, in model_launch
    model_uid = client.launch_model(
  File "/home/niwang/miniconda3/envs/chat/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 959, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:42028, pid=10331] Model not found in the model list, uid: glm4-chat-1-0

### Expected behavior / 期待表现

启动embeeding模型

**Comment by qinxuye** [comment]
xinference-client 请升级到 0.14.2 和服务端匹配。
