### ISSUE TITLE
llama-3.1-instruct 用docker安装的Xinference无法运行

### ISSUE THREAD

**Issue by yebanliuying** [xorbitsai/inference#2143]
### System Info / 系統信息

<img width="798" alt="image" src="https://github.com/user-attachments/assets/ded14618-f69f-452e-a748-3fca89e86b88">

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

docker版本：registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.14.2
模型：llama-3.1-instruct

### The command used to start Xinference / 用以启动 xinference 的命令

报错：docker logs xinference
2024-08-22 09:47:05,544 xinference.core.supervisor 140 INFO     Xinference supervisor 0.0.0.0:58652 started
2024-08-22 09:47:05,738 xinference.core.worker 140 INFO     Starting metrics export server at 0.0.0.0:None
2024-08-22 09:47:05,743 xinference.core.worker 140 INFO     Checking metrics export server...
2024-08-22 09:47:08,739 xinference.core.worker 140 INFO     Metrics server is started at: http://0.0.0.0:41881
2024-08-22 09:47:08,739 xinference.core.worker 140 INFO     Purge cache directory: /data/work/models/cache
2024-08-22 09:47:08,741 xinference.core.worker 140 INFO     Connected to supervisor as a fresh worker
2024-08-22 09:47:08,769 xinference.core.worker 140 INFO     Xinference worker 0.0.0.0:58652 started
2024-08-22 09:47:12,176 xinference.api.restful_api 1 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997
2024-08-22 09:47:12,334 uvicorn.error 1 INFO     Uvicorn running on http://0.0.0.0:9997 (Press CTRL+C to quit)
2024-08-22 09:47:55,268 xinference.model.llm.llm_family 140 INFO     Caching from Modelscope: LLM-Research/Meta-Llama-3.1-70B-Instruct-AWQ-INT4
2024-08-22 09:47:55,661 xinference.model.llm.sglang.core 158 INFO     Loading llama-3.1-instruct with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tp_size': 1, 'mem_fraction_static': 0.88, 'log_level': 'info', 'attention_reduce_in_fp32': False}
Process Process-1:1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 245, in launch_server
    _set_envs_and_config(server_args)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 383, in _set_envs_and_config
    assert_pkg_version(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/utils.py", line 357, in assert_pkg_version
    raise Exception(
Exception: flashinfer is installed with version 0.1.2+cu121torch2.4, which is less than the minimum required version 0.1.5. Please uninstall the old version and reinstall the latest version by following the instructions at https://docs.flashinfer.ai/installation.html.
2024-08-22 09:48:07,214 xinference.core.worker 140 ERROR    Failed to load model llama-3.1-instruct-1-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 300, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/sglang/core.py", line 120, in load
    self._engine = sgl.Runtime(
  File "/usr/local/lib/python3.10/dist-packages/sglang/api.py", line 40, in Runtime
    return Runtime(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 508, in __init__
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:44555, pid=158] Initialization failed. Please see the error messages above.
2024-08-22 09:48:07,301 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:44555, pid=158] Initialization failed. Please see the error messages above.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 300, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/sglang/core.py", line 120, in load
    self._engine = sgl.Runtime(
  File "/usr/local/lib/python3.10/dist-packages/sglang/api.py", line 40, in Runtime
    return Runtime(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 508, in __init__
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:44555, pid=158] Initialization failed. Please see the error messages above.

### Reproduction / 复现过程

docker run -id --gpus all --ipc=host --name xinference \
-e XINFERENCE_MODEL_SRC=modelscope \
-p 8000:9997 \
xprobe/xinference:latest xinference-local -H 0.0.0.0

### Expected behavior / 期待表现

报错的主要原因是 flashinfer 包的版本不兼容，具体表现为当前安装的 flashinfer 版本过低（0.1.2+cu121torch2.4），而系统要求最低版本为 0.1.5。此外，日志中还提到 sglang 模块的初始化失败，这可能与 flashinfer 版本问题直接相关。

**Comment by PolarPeak** [comment]
我用sglang启动也是报错这个

2024-08-22 13:12:10,910 xinference.model.llm.sglang.core 219 INFO     Loading Qwen1.5-14B-Chat-SFT with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tp_size': 1, 'mem_fraction_static': 0.88, 'log_level': 'info', 'attention_reduce_in_fp32': False}
Process Process-1:1:1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 245, in launch_server
    _set_envs_and_config(server_args)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 383, in _set_envs_and_config
    assert_pkg_version(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/utils.py", line 357, in assert_pkg_version
    raise Exception(
Exception: flashinfer is installed with version 0.1.2+cu121torch2.4, which is less than the minimum required version 0.1.5. Please uninstall the old version and reinstall the latest version by following the instructions at https://docs.flashinfer.ai/installation.html.
2024-08-22 13:12:36,315 xinference.core.worker 28 ERROR    Failed to load model Qwen1.5-14B-Chat-SFT-1-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 300, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/sglang/core.py", line 120, in load
    self._engine = sgl.Runtime(
  File "/usr/local/lib/python3.10/dist-packages/sglang/api.py", line 40, in Runtime
    return Runtime(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 508, in __init__
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:37541, pid=219] Initialization failed. Please see the error messages above.
2024-08-22 13:12:36,464 xinference.core.supervisor 28 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f3e65f20c20>, 'Qwen1.5-14B-Chat-SFT'), kwargs: {'suppress_exception': True}
2024-08-22 13:12:36,489 xinference.core.supervisor 28 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-08-22 13:12:36,543 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:37541, pid=219] Initialization failed. Please see the error messages above.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 300, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/sglang/core.py", line 120, in load
    self._engine = sgl.Runtime(
  File "/usr/local/lib/python3.10/dist-packages/sglang/api.py", line 40, in Runtime
    return Runtime(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 508, in __init__
    raise RuntimeError(
RuntimeError: [address=0.0.0.0:37541, pid=219] Initialization failed. Please see the error messages above.
