### ISSUE TITLE
请问支持华为的npu推理吗？

### ISSUE THREAD

**Issue by cold-eye** [xorbitsai/inference#2150]
### System Info / 系統信息

请问支持华为的npu推理吗？

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

请问支持华为的npu推理吗？

### The command used to start Xinference / 用以启动 xinference 的命令

请问支持华为的npu推理吗？

### Reproduction / 复现过程

请问支持华为的npu推理吗？

### Expected behavior / 期待表现

请问支持华为的npu推理吗？

**Comment by zlpmetyou** [comment]
按照这个教程部署之后，向量化速度贼慢，感觉根本没有调用npu

**Comment by qinxuye** [comment]
> 按照这个教程部署之后，向量化速度贼慢，感觉根本没有调用npu

310p 吗？embedding 模型跑在 310 上确实很慢，企业版支持会快很多。

**Comment by zlpmetyou** [comment]
@qinxuye 是的，310，企业版是不是要收费，收费如何呢

**Comment by cold-eye** [comment]
请问支持 GPTQ 量化版本吗？ Qwen2-7B-Instruct-GPTQ-Int4 版本报错。
```
Server error: 500 - [address=0.0.0.0:43571, pid=2766] No package metadata was found for auto_gptq
```
然后安装auto_gptq又报以下错误，看着是关于cuda的。但是我们是npu，感觉是不是不支持。
```
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9aevh4eb/auto-gptq_d99ddba00db24ad4ab6afd8a02cf459c/setup.py", line 62, in <module>
          CUDA_VERSION = "".join(os.environ.get("CUDA_VERSION", default_cuda_version).split("."))
      AttributeError: 'NoneType' object has no attribute 'split'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

配置如下：
注册：
```
{
    "version": 1,
    "context_length": 2048,
    "model_name": "custom-llm",
    "model_lang": [
        "en",
        "zh"
    ],
    "model_ability": [
        "generate"
    ],
    "model_description": "This is a custom model description.",
    "model_family": "your_custom_model",
    "model_specs": [
        {
            "model_format": "pytorch",
            "model_size_in_billions": 7,
            "quantizations": [
                "none"
            ],
            "model_id": null,
            "model_hub": "huggingface",
            "model_uri": "/app/Qwen2-7B-Instruct-GPTQ-Int4",
            "model_revision": null
        }
    ],
    "chat_template": null,
    "stop_token_ids": null,
    "stop": null,
    "is_builtin": false
}
```


lauching:
![image](https://github.com/user-attachments/assets/8a6f7539-ac12-421e-ac71-747e8f31a214)

这里的选项是n-gpu，没有npu的支持
