### ISSUE TITLE
断网部署本地bge embedding模型报错

### ISSUE THREAD

**Issue by cold-eye** [xorbitsai/inference#2151]
### System Info / 系統信息

正常gpu服务器

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

最新版本

### The command used to start Xinference / 用以启动 xinference 的命令

xinference register --model-type embedding --file custom-bge-large-zh-v1.5.json --persist

xinference launch --model-name custom-bge-large-zh-v1.5 --model-type embedding --model_path /FlagEmbedding/embeddings/bge-large-zh-v1.5

### Reproduction / 复现过程

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 497, in _make_request
    conn.request(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/root/anaconda3/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/anaconda3/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/root/anaconda3/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9a746a1210>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/root/anaconda3/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/cluster/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a746a1210>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/root/anaconda3/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 400, in register_model
    client = RESTfulClient(base_url=endpoint, api_key=api_key)
  File "/root/anaconda3/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 788, in __init__
    self._check_cluster_authenticated()
  File "/root/anaconda3/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 806, in _check_cluster_authenticated
    response = requests.get(url)
  File "/root/anaconda3/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/anaconda3/lib/python3.10/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/cluster/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a746a1210>: Failed to establish a new connection: [Errno 111] Connection refused'))

### Expected behavior / 期待表现

成功启动

**Comment by cold-eye** [comment]
不能理解，模型跟官网一样，也指定了模型文件的位置，为什么还要强制联网。网络环境为局域网

**Comment by cold-eye** [comment]
![image](https://github.com/user-attachments/assets/27bc03a6-8f9f-4432-9dae-b24a9d61db47)

我用xinference-local可以正常启动，可以告知一下 命令吗？顺便给个建议，webUI启动后，如果能返回启动的launch命令就好了

**Comment by oubeichen** [comment]
`xinference launch` 这个命令是要在 `xinference-local` 启动之后才能运行的……就是一个api调用工具，不是真正的CLI。

**Comment by cold-eye** [comment]
就是说，我需要先启动 xinference-local，在web界面配置好后，再xinference launch，暴露端口，供其他应用调借口？

**Comment by oubeichen** [comment]
xinference-local 启动的是整个服务，webui是附带的，你 xinference launch 的操作都需要先启动 xinference-local。本地运行命令也可以的，只要能连接上这个端口， xinference launch -e <your endpoint> [其它参数]

**Comment by cold-eye** [comment]
大致搞明白了。

我现在指定启动端口
xinference-local --host 0.0.0.0 --port 8889

然后launch bge模型，还是报错，请教一下我该怎么设置？

xinference launch --host 0.0.0.0 --port 8889 --model-name bge-large-zh-v1.5 --model-type embedding --model_path /app/FlagEmbedding/bge-large-zh-v1.5

**Comment by cold-eye** [comment]
明白了，谢谢

**Comment by qinxuye** [comment]
Thanks @oubeichen , close first.
