### ISSUE TITLE
运行 CosyVoice-300M-SFT 报错 TypeError: [address=0.0.0.0:42103, pid=64] get_tokenizer() got an unexpected keyword argument 'num_languages'

### ISSUE THREAD

**Issue by maogeigei** [xorbitsai/inference#2154]
### System Info / 系統信息

docker安装的最新版本
NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

latest

### The command used to start Xinference / 用以启动 xinference 的命令

网页上点击运行CosyVoice-300M-SFT

### Reproduction / 复现过程

![image](https://github.com/user-attachments/assets/c0fa0b36-3d3c-48cb-893f-6dcbe7b0dd92)
2024-08-24 01:32:57,606 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:42103, pid=64] get_tokenizer() got an unexpected keyword argument 'num_languages'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 882, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 300, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/cosyvoice.py", line 50, in load
    self._model = CosyVoice(self._model_path)
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/cosyvoice.py", line 30, in __init__
    self.frontend = CosyVoiceFrontEnd(configs['get_tokenizer'],
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/frontend.py", line 46, in __init__
    self.tokenizer = get_tokenizer()
TypeError: [address=0.0.0.0:42103, pid=64] get_tokenizer() got an unexpected keyword argument 'num_languages'

### Expected behavior / 期待表现

正常运行

**Comment by qinxuye** [comment]
pip install --no-deps 'openai-whisper==v20231117'

duplicated with #2095
