### ISSUE TITLE
CosyVoice-300M-SFT  No module named 'ttsfrd' No module named 'tn.english'

### ISSUE THREAD

**Issue by tsiens** [xorbitsai/inference#2161]
### System Info / 系統信息

docker

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

 0.14.3

### The command used to start Xinference / 用以启动 xinference 的命令

compose
```
services:
  xin:
    container_name: xin
    image: 12.1.150.73:18080/xprobe/xinference:latest
    restart: always
    shm_size: 128g
    environment:
      - HF_ENDPOINT=https://hf-mirror.com
      - TZ=Asia/Shanghai
      - XINFERENCE_AUDIO_SPEECH_DEFAULT_STREAM=1
      - CUDA_LAUNCH_BLOCKING=1
    volumes:
      - /data/xinference/xinference:/root/.xinference
      - /data/xinference/huggingface:/root/.cache/huggingface
      - /data/xinference/modelscope:/root/.cache/modelscope
    ports:
      - 9997:9997
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              device_ids: ["0", "1", "2", "3","4", "5"]
              driver: "nvidia"
    command:
      - bash
      - -c
      - |
        sleep 60 && python3 /root/.xinference/start.py &
       xinference-local -H 0.0.0.0
```

### Reproduction / 复现过程

```
2024-08-26 17:06:24,167 xinference.core.worker 142 INFO     You specify to launch the model: CosyVoice-300M-SFT on GPU index: [1] of the worker: 0.0.0.0:45440, xinference will automatically ignore the `n_gpu` option.
2024-08-26 17:06:35,915 xinference.core.worker 142 ERROR    Failed to load model CosyVoice-300M-SFT-1-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/frontend.py", line 26, in <module>
    import ttsfrd
ModuleNotFoundError: No module named 'ttsfrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 888, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 303, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/cosyvoice.py", line 48, in load
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/cosyvoice.py", line 18, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/frontend.py", line 31, in <module>
    from tn.english.normalizer import Normalizer as EnNormalizer
ModuleNotFoundError: [address=0.0.0.0:40967, pid=1345] No module named 'tn.english'
2024-08-26 17:06:36,008 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:40967, pid=1345] No module named 'tn.english'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/frontend.py", line 26, in <module>
    import ttsfrd
ModuleNotFoundError: No module named 'ttsfrd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 888, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 303, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/cosyvoice.py", line 48, in load
    from cosyvoice.cli.cosyvoice import CosyVoice
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/cosyvoice.py", line 18, in <module>
    from cosyvoice.cli.frontend import CosyVoiceFrontEnd
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/cosyvoice/cli/frontend.py", line 31, in <module>
    from tn.english.normalizer import Normalizer as EnNormalizer
ModuleNotFoundError: [address=0.0.0.0:40967, pid=1345] No module named 'tn.english'
```

### Expected behavior / 期待表现

docker 0.14.0 have access to

**Comment by skytodmoon** [comment]
pip install tn can resolve this problem.

**Comment by tsiens** [comment]
> please install WeTextProcessing
![image](https://github.com/user-attachments/assets/9bcfdf19-0c1b-4537-a303-2be792193054)

It's all installed, it's useless

**Comment by tsiens** [comment]
> I met the same problem and pip install tn can resolve this problem.

pip install tn，Still reporting an error

**Comment by wuminghui-coder** [comment]
![image](https://github.com/user-attachments/assets/fcab580f-b17b-42e3-8982-d29ed309bd24)
![image](https://github.com/user-attachments/assets/16cb4cb4-f143-41a5-b3a2-6fc455e27d1d)

**Comment by wuminghui-coder** [comment]
需要去到官方，下载资源包

**Comment by wuminghui-coder** [comment]
![image](https://github.com/user-attachments/assets/e090d4a4-54ab-4ec9-99b9-3fe4e822cfba)

**Comment by sonach** [comment]
> Please try uninstalling tn and force reinstalling WeTextProcessing. WeTextProcessing contains the package `tn.english`: https://github.com/wenet-e2e/WeTextProcessing/tree/master/tn

force reinstalling WeTextProcessing  solved my problem. tks.

**Comment by yu1yu1yu** [comment]
if your machine is linux x86_64. Just do as the guide.Or you can open the file 

> model/audio/../../thirdparty/cosyvoice/cli/frontend.py 

maybe this way and annotate  try and exception
