### ISSUE TITLE
Unable to Launch Custom Embedding Model gte-Qwen2-1.5B-instruct

### ISSUE THREAD

**Issue by danialcheung** [xorbitsai/inference#2176]
### System Info / 系統信息

CUDA  V12.5.82, transformers 4.40.0, Python 3.11.9, Red Hat Enterprise Linux 9.4 (Plow)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference-0.14.13

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1. Install `xinference-0.14.13` via pip
2. Launch `xinference-local --host 0.0.0.0 --port 9997`
3. Register custom model with the following configuration file:
```json
{
    "model_name": "gte-qwen2-1.5b-instruct",
    "dimensions": 1536,
    "max_tokens": 8192,
    "language": ["en", "zh", "multilingual"],
    "model_id": "Alibaba-NLP/gte-Qwen2-1.5B-instruct"
}
```
4. Register the custom model with `xinference register --model-type embedding --file your-configuration-file.json --persist`
5. Launch model with `xinference launch --model-name gte-qwen1.5b-instruct --model-type embedding`
6. Get the following error:
```bash
2024-08-27 17:31:14,154 xinference.core.worker 490315 ERROR    Failed to load model gte-qwen2-1.5b-instruct-1-0
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/worker.py", line 888, in launch_builtin_model
    await model_ref.load()
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 303, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 159, in load
    torch_dtype_str = self._kwargs.get("torch_dtype")
    ^^^^^^^^^^^^^^^^^
AttributeError: [address=0.0.0.0:35197, pid=492409] 'EmbeddingModel' object has no attribute '_kwargs'
2024-08-27 17:31:14,190 xinference.api.restful_api 490137 ERROR    [address=0.0.0.0:35197, pid=492409] 'EmbeddingModel' object has no attribute '_kwargs'
Traceback (most recent call last):
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/api/restful_api.py", line 878, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 1027, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 991, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 970, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/worker.py", line 888, in launch_builtin_model
    await model_ref.load()
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 303, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/home/user1/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/embedding/core.py", line 159, in load
    torch_dtype_str = self._kwargs.get("torch_dtype")
    ^^^^^^^^^^^^^^^^^
AttributeError: [address=0.0.0.0:35197, pid=492409] 'EmbeddingModel' object has no attribute '_kwargs'
```

### Expected behavior / 期待表现

Model is loaded successfully.

**Comment by danialcheung** [comment]
For now, I've rolled back to `xinference-0.13.2` where the model can be loaded successfully.

**Comment by xbl916** [comment]
实际上7b版本也不行

**Comment by qinxuye** [comment]
@Zzzz1111 这个应该和你提交的 PR 有关，能看下吗？

**Comment by Zzzz1111** [comment]
@qinxuye 修复了，提交了一个pr
