### ISSUE TITLE
调用模型报错'NoneType' object is not subscriptable"

### ISSUE THREAD

**Issue by hezixinshellingfordf** [xorbitsai/inference#2233]
### System Info / 系統信息

CUDA Version: 12.4
transformers Version: 4.41.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.14.4.post1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 6006

### Reproduction / 复现过程

1、启动xinference xinference-local --host 0.0.0.0 --port 6006
2、使用ui界面launch model（glm4-chat\chatglm3均尝试过，报同样的错误）
3、执行curl -X 'POST' \
  'http://127.0.0.1:6006/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "glm4-chat",
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant."
        },
        {
            "role": "user",
            "content": "What is the largest animal?"
        }
    ]
  }'
4、
2024-09-06 01:07:24,527 xinference.api.restful_api 1348 ERROR    [address=0.0.0.0:45947, pid=1407] 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1752, in create_chat_completion
    data = await model.chat(
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/model.py", line 90, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/model.py", line 531, in chat
    response = await self._call_wrapper_json(
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/model.py", line 401, in _call_wrapper_json
    return await self._call_wrapper("json", fn, *args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/core/model.py", line 114, in _async_wrapper
    return await fn(*args, **kwargs)

### Expected behavior / 期待表现

正常调用模型

**Comment by hezixinshellingfordf** [comment]
我更换了transformers版本后正常了。
