### ISSUE TITLE
worker启动模型失败

### ISSUE THREAD

**Issue by unsw-luopan** [xorbitsai/inference#2250]
### System Info / 系統信息

docker部署的集群模型，注册模型、查看注册模型情况正常

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.14.0

### The command used to start Xinference / 用以启动 xinference 的命令

集群方式启动

### Reproduction / 复现过程

xinference registrations 可以看到注册了的模型，使用注册的模型name启动，但是下面的命令启动时模型not found

xinference launch -e "http://172.18.10.192:9997" -n qwen2-72b-int4 -en vllm -s 72 -f pytorch -q Int4 --work-ip "172.18.10.182" --model_path /root/.cache/modelscope/hub/qwen/Qwen2-72B-Instruct-GPTQ-Int4/
Launch model name: qwen2-72b-int4 with kwargs: {'work-ip': '172.18.10.182', 'model_path': '/root/.cache/modelscope/hub/qwen/Qwen2-72B-Instruct-GPTQ-Int4/'}
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 903, in model_launch
    model_uid = client.launch_model(
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 1041, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=172.18.10.182:23016, pid=1] Model not found, name: qwen2-72b-int4, format: pytorch, size: 72, quantization: Int4

### Expected behavior / 期待表现

集群模式下怎么启动本地模型，貌似model_path没奏效

**Comment by nan9126** [comment]
请问这个问题解决了么

**Comment by unsw-luopan** [comment]
> 请问这个问题解决了么

解决了，注册模型的时候使用CMD在worker上注册
xinference register -e "Master_IP" -f Path_to_Your_Config_File -w Worker_IP -p

**Comment by unsw-luopan** [comment]
xinference register -e "http://172.18.10.12:9997" -f /root/.xinference/model/llm/qwen2.json -w 172.18.10.11 -p

**Comment by nakroy** [comment]
> > 请问这个问题解决了么
> 
> 解决了，注册模型的时候使用CMD在worker上注册 xinference register -e "Master_IP" -f Path_to_Your_Config_File -w Worker_IP -p

那这也太坑了吧，Supervisor那里注册了跟没注册一样

**Comment by zxx20231119** [comment]
请教下只在一个worker下注册，是不是不能在其他节点运行啊
