### ISSUE TITLE
0.15.0版本xinf启动本地模型报错Model not found

### ISSUE THREAD

**Issue by Shh0718** [xorbitsai/inference#2300]
### System Info / 系統信息

python3.10
Ubuntu22.04

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference

### Reproduction / 复现过程

1. 本地启动xinference，从modelscope下载模型
2. 启动离线模型 xinference launch --model_path /data/liuxw/model/Qwen1.5-7B -n qwen1.57b --model-engine Transformers
xinference launch --model_path /data/liuxw/model/Qwen1.5-7B -n qwen1.57b --model-engine Transformers
Launch model name: qwen1.57b with kwargs: {'model_path': '/data/liuxw/model/Qwen1.5-7B'}
2024-09-13 07:48:45,484 xinference.core.worker 29170 INFO     [request 9aa4e740-71a4-11ef-9b42-e2253a35a188] Enter launch_builtin_model, args: <xinference.core.worker.WorkerActor object at 0x7f54d92fdcb0>, kwargs: model_uid=qwen1.57b-1-0,model_name=qwen1.57b,model_size_in_billions=None,model_format=None,quantization=None,model_engine=Transformers,model_type=LLM,n_gpu=auto,request_limits=None,peft_model_config=None,gpu_idx=None,download_hub=None,model_path=/data/liuxw/model/Qwen1.5-7B,trust_remote_code=True
2024-09-13 07:48:48,922 xinference.core.worker 29170 ERROR    Failed to load model qwen1.57b-1-0
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/worker.py", line 867, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
  File "/root/miniconda3/envs/xinf/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/miniconda3/envs/xinf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/core.py", line 71, in create_model_instance
    return create_llm_model_instance(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/llm/core.py", line 209, in create_llm_model_instance
    raise ValueError(
ValueError: Model not found, name: qwen1.57b, format: None, size: None, quantization: None
2024-09-13 07:48:48,945 xinference.core.worker 29170 WARNING  Process 127.0.0.1:41143 is down.
2024-09-13 07:48:48,945 xinference.core.worker 29170 ERROR    [request 9aa4e740-71a4-11ef-9b42-e2253a35a188] Leave launch_builtin_model, error: Model not found, name: qwen1.57b, format: None, size: None, quantization: None, elapsed time: 3 s
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/worker.py", line 867, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
  File "/root/miniconda3/envs/xinf/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/miniconda3/envs/xinf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/core.py", line 71, in create_model_instance
    return create_llm_model_instance(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/llm/core.py", line 209, in create_llm_model_instance
    raise ValueError(
ValueError: Model not found, name: qwen1.57b, format: None, size: None, quantization: None
2024-09-13 07:48:48,948 xinference.api.restful_api 29154 ERROR    [address=127.0.0.1:55171, pid=29170] Model not found, name: qwen1.57b, format: None, size: None, quantization: None
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/api/restful_api.py", line 876, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1026, in launch_builtin_model
    await _launch_model()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 990, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 969, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/worker.py", line 867, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
  File "/root/miniconda3/envs/xinf/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/root/miniconda3/envs/xinf/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/core.py", line 71, in create_model_instance
    return create_llm_model_instance(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/llm/core.py", line 209, in create_llm_model_instance
    raise ValueError(
ValueError: [address=127.0.0.1:55171, pid=29170] Model not found, name: qwen1.57b, format: None, size: None, quantization: None
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 901, in model_launch
    model_uid = client.launch_model(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 938, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=127.0.0.1:55171, pid=29170] Model not found, name: qwen1.57b, format: None, size: None, quantization: None

![image](https://github.com/user-attachments/assets/4ffa579e-99b7-466c-9392-66ecf3c8cabd)

### Expected behavior / 期待表现

模型正常启动

**Comment by George-TQL** [comment]
遇到相同问题，求解

**Comment by CEfanmin** [comment]
> 遇到相同问题，求解

我也遇到这个问题，CLI命令如下：
xinference launch --model-name "qwen2-instruct" \
                  --n-gpu 4 \
                  --model-engine "vllm" \
                  --model-type "LLM" \
                  --model-uid  "qwen2-instruct"\
                  --model-format "awq" \
                  --size-in-billions "72" \
                  --quantization "4-bit" \
                  --endpoint "http://x.x.x.x:9997"

**Comment by Jarvanen** [comment]
xinference registrations可以看到所有默认的模型名  应该是qwen1.5-chat   然后通过size参数配大小

但是现在还没有qwen2.5   不是说已经支持了吗

**Comment by Valdanitooooo** [comment]
-n qwen1.5-chat -u qwen1.57b

```
xinference launch  --help
  -n, --model-name TEXT           Provide the name of the model to be
  -u, --model-uid TEXT            Specify UID of model, default is None.
```

https://inference.readthedocs.io/zh-cn/latest/models/builtin/llm/qwen1.5-chat.html#model-spec-4-pytorch-7-billion

**Comment by boluoyu** [comment]
这里比较坑，因为页面需要预先注册一个模型，model_name 是随便写的，点击页面部署时，model-uid 和model_name 是一样的，用launch 命令 ，后面的版本不需要预先注册，所以，model_name 必须是系统里已有的标准写法，如qwen2-instruct ，--model-uid 才是你想要起的名字，这里很多人没注意就报这个错了

**Comment by haoyangwang-ai** [comment]
Lunch本地模型，必须用完整命令，带所有参数，才能避免这个错误。在主页面启动模型那里，配置好你要启动的模型，然后右上角复制完整命令，命令行再加入--model_path /*/*/* 本地目录。

**Comment by Joseph513shen** [comment]
> model_name 必须是系统里已有的标准写法

没太明白，所以model_name和model_uid最好不要一样是吗？我的model_name：DeepSeek-R1-Distill-Llama-70B，最后UID总是变成DeepSeek-R1-Distill-Llama-70B-0，导致不匹配，这个是怎么回事？
