### ISSUE TITLE
所有模型都无法下载

### ISSUE THREAD

**Issue by sdytzjp** [xorbitsai/inference#2310]
### System Info / 系統信息

docker部署
latest_cpu

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Release: v0.15.0

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -v /root/fastgpt/xinference_image:/root/xinference_image -e XINFERENCE_HOME=/root/xinference_image -d -p 9997:9997 --name xinference registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:latest-cpu xinference-local -H 0.0.0.0 --log-level debug

### Reproduction / 复现过程

1、在xinf页面下载任何模型
2、docker logs xinference查看日志，都是失败，需要宿主机安装vpn吗
3、

2024-09-14 04:02:17,685 xinference.core.supervisor 23 DEBUG    [request 2218fd8e-724e-11ef-baaf-0242ac110002] Enter list_model_registrations, args: <xinference.core.supervisor.SupervisorActor object at 0x7f451ff2d730>,LLM, kwargs: detailed=True
2024-09-14 04:02:17,831 xinference.core.supervisor 23 DEBUG    [request 2218fd8e-724e-11ef-baaf-0242ac110002] Leave list_model_registrations, elapsed time: 0 s
2024-09-14 04:02:21,515 xinference.core.supervisor 23 DEBUG    [request 246160fe-724e-11ef-baaf-0242ac110002] Enter query_engines_by_model_name, args: <xinference.core.supervisor.SupervisorActor object at 0x7f451ff2d730>,aquila2, kwargs:
2024-09-14 04:02:21,515 xinference.core.worker 23 DEBUG    [request 24617972-724e-11ef-baaf-0242ac110002] Enter query_engines_by_model_name, args: <xinference.core.worker.WorkerActor object at 0x7f451ff10e30>,aquila2, kwargs:
2024-09-14 04:02:21,516 xinference.core.worker 23 DEBUG    [request 24617972-724e-11ef-baaf-0242ac110002] Leave query_engines_by_model_name, elapsed time: 0 s
2024-09-14 04:02:21,516 xinference.core.supervisor 23 DEBUG    [request 246160fe-724e-11ef-baaf-0242ac110002] Leave query_engines_by_model_name, elapsed time: 0 s

2024-09-14 04:02:55,875 xinference.core.supervisor 23 DEBUG    aquila2 exists in xinference. Generate suffix to aquila2 for model_uid.
2024-09-14 04:02:55,876 xinference.core.supervisor 23 DEBUG    Enter launch_builtin_model, model_uid: aquila2-cjPflaCX, model_name: aquila2, model_size: 7, model_format: pytorch, quantization: none, replica: 1, kwargs: {}
2024-09-14 04:02:55,877 xinference.core.worker 23 DEBUG    Enter get_model_count, args: <xinference.core.worker.WorkerActor object at 0x7f451ff10e30>, kwargs:
2024-09-14 04:02:55,877 xinference.core.worker 23 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-09-14 04:02:55,878 xinference.core.worker 23 INFO     [request 38dcc226-724e-11ef-baaf-0242ac110002] Enter launch_builtin_model, args: <xinference.core.worker.WorkerActor object at 0x7f451ff10e30>, kwargs: model_uid=aquila2-cjPflaCX-1-0,model_name=aquila2,model_size_in_billions=7,model_format=pytorch,quantization=none,model_engine=Transformers,model_type=LLM,n_gpu=None,request_limits=None,peft_model_config=None,gpu_idx=None,download_hub=None,model_path=None
2024-09-14 04:02:55,879 xinference.core.worker 23 DEBUG    GPU disabled for model aquila2-cjPflaCX-1-0
2024-09-14 04:03:00,133 xinference.model.llm.core 23 DEBUG    Launching aquila2-cjPflaCX-1-0 with PytorchModel
2024-09-14 04:03:00,134 xinference.model.llm.llm_family 23 INFO     Caching from Hugging Face: BAAI/Aquila2-7B
2024-09-14 04:03:32,852 xinference.model.utils 23 DEBUG    Download failed: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again., download func: <function snapshot_download at 0x7f4574b3d4e0>, download args: ('BAAI/Aquila2-7B',), kwargs: {'revision': '9c76e143c6e9621689ca76e078c465b0dee75eb8'}
2024-09-14 04:03:32,852 xinference.model.utils 23 WARNING  Attempt 3 failed. Remaining attempts: 0
2024-09-14 04:03:32,852 xinference.core.worker 23 ERROR    Failed to load model aquila2-1-0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f457496f590>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/Aquila2-7B/revision/9c76e143c6e9621689ca76e078c465b0dee75eb8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f457496f590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2588, in repo_info
    return method(
           ^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2372, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/Aquila2-7B/revision/9c76e143c6e9621689ca76e078c465b0dee75eb8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f457496f590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 95a61fb7-641f-445c-a174-fa80385cee2a)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 105, in retry_download
    return download_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 241, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 867, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 71, in create_model_instance
    return create_llm_model_instance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/core.py", line 226, in create_llm_model_instance
    model_path = cache(llm_family, llm_spec, quantization)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/llm_family.py", line 298, in cache
    return cache_from_huggingface(llm_family, llm_spec, quantization)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/llm_family.py", line 729, in cache_from_huggingface
    download_dir = retry_download(
                   ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 128, in retry_download
    raise RuntimeError(
RuntimeError: Failed to download model 'aquila2' (size: 7, format: pytorch) after multiple retries
2024-09-14 04:03:32,897 xinference.core.worker 23 ERROR    [request 68e21378-724d-11ef-baaf-0242ac110002] Leave launch_builtin_model, error: Failed to download model 'aquila2' (size: 7, format: pytorch) after multiple retries, elapsed time: 385 s
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f457496f590>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/Aquila2-7B/revision/9c76e143c6e9621689ca76e078c465b0dee75eb8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f457496f590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2588, in repo_info
    return method(
           ^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2372, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 66, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/Aquila2-7B/revision/9c76e143c6e9621689ca76e078c465b0dee75eb8 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f457496f590>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 95a61fb7-641f-445c-a174-fa80385cee2a)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 105, in retry_download
    return download_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 241, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 867, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 71, in create_model_instance
    return create_llm_model_instance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/core.py", line 226, in create_llm_model_instance
    model_path = cache(llm_family, llm_spec, quantization)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/llm_family.py", line 298, in cache
    return cache_from_huggingface(llm_family, llm_spec, quantization)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/llm_family.py", line 729, in cache_from_huggingface
    download_dir = retry_download(
                   ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 128, in retry_download
    raise RuntimeError(
RuntimeError: Failed to download model 'aquila2' (size: 7, format: pytorch) after multiple retries
2024-09-14 04:03:32,904 xinference.core.supervisor 23 DEBUG    [request 4eee8b12-724e-11ef-baaf-0242ac110002] Enter terminate_model, args: <xinference.core.supervisor.SupervisorActor object at 0x7f451ff2d730>,aquila2, kwargs: suppress_exception=True
2024-09-14 04:03:32,904 xinference.core.supervisor 23 DEBUG    [request 4eee8b12-724e-11ef-baaf-0242ac110002] Leave terminate_model, elapsed time: 0 s
2024-09-14 04:03:32,913 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:59589, pid=23] Failed to download model 'aquila2' (size: 7, format: pytorch) after multiple retries
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/api/restful_api.py", line 876, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 1026, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 990, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 969, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 867, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 71, in create_model_instance
    return create_llm_model_instance(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/core.py", line 226, in create_llm_model_instance
    model_path = cache(llm_family, llm_spec, quantization)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/llm_family.py", line 298, in cache
    return cache_from_huggingface(llm_family, llm_spec, quantization)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/llm/llm_family.py", line 729, in cache_from_huggingface
    download_dir = retry_download(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 128, in retry_download
    raise RuntimeError(
    ^^^^^^^^^^^^^^^^^
RuntimeError: [address=0.0.0.0:59589, pid=23] Failed to download model 'aquila2' (size: 7, format: pytorch) after multiple retries

![image](https://github.com/user-attachments/assets/16b45e78-463a-406d-bad4-9301a2d61001)

### Expected behavior / 期待表现

可以下载模型

**Comment by Valdanitooooo** [comment]
可以尝试切换源 https://inference.readthedocs.io/zh-cn/latest/models/sources/sources.html
