### ISSUE TITLE
运行FishSpeech-1.4模型报错Error locating target 'fish_speech.models.vqgan.modules.fsq.DownsampleFiniteScalarQuantize', set env var HYDRA_FULL_ERROR=1 to see chained exception. full_key: quantizer

### ISSUE THREAD

**Issue by githust66** [xorbitsai/inference#2316]
### System Info / 系統信息

OS：WSL2 Ubuntu 22.04.4 LTS
py：3.10.12
transfermers：4.45.0.dev0
vllm：无
torch：2.4.0+rocm6.1
GPU：AMD Radeon RX 7900 XT

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

Xinference version ：0.15.1

### The command used to start Xinference / 用以启动 xinference 的命令

```HF_ENDPOINT=https://hf-mirror.com xinference-local --host 0.0.0.0 --port 9997```

### Reproduction / 复现过程

在Launch Model界面选择FishSpeech-1.4模型下载运行报错：Server error: 500 - [address=0.0.0.0:36475, pid=3230] Error locating target 'fish_speech.models.vqgan.modules.fsq.DownsampleFiniteScalarQuantize', set env var HYDRA_FULL_ERROR=1 to see chained exception. full_key: quantizer
报错日志:
```
2024-09-15 18:52:54,273 xinference.core.worker 2426 ERROR    Failed to load model FishSpeech-1.4-1-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 893, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 309, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/fish_speech.py", line 97, in load
    self._model = load_decoder_model(
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/fish_speech/tools/vqgan/inference.py", line 25, in load_model
    model = instantiate(cfg)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: [address=0.0.0.0:36475, pid=3230] Error locating target 'fish_speech.models.vqgan.modules.fsq.DownsampleFiniteScalarQuantize', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: quantizer
2024-09-15 18:52:54,340 xinference.core.worker 2426 ERROR    [request a3801c24-7350-11ef-a7ba-4b56a88f097b] Leave launch_builtin_model, error: [address=0.0.0.0:36475, pid=3230] Error locating target 'fish_speech.models.vqgan.modules.fsq.DownsampleFiniteScalarQuantize', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: quantizer, elapsed time: 9 s
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 893, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 309, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/fish_speech.py", line 97, in load
    self._model = load_decoder_model(
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/fish_speech/tools/vqgan/inference.py", line 25, in load_model
    model = instantiate(cfg)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: [address=0.0.0.0:36475, pid=3230] Error locating target 'fish_speech.models.vqgan.modules.fsq.DownsampleFiniteScalarQuantize', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: quantizer
2024-09-15 18:52:54,382 xinference.api.restful_api 2323 ERROR    [address=0.0.0.0:36475, pid=3230] Error locating target 'fish_speech.models.vqgan.modules.fsq.DownsampleFiniteScalarQuantize', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: quantizer
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 967, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 1032, in launch_builtin_model
    await _launch_model()
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 996, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/supervisor.py", line 975, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 893, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 309, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/fish_speech.py", line 97, in load
    self._model = load_decoder_model(
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/audio/../../thirdparty/fish_speech/tools/vqgan/inference.py", line 25, in load_model
    model = instantiate(cfg)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/usr/local/lib/python3.10/dist-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: [address=0.0.0.0:36475, pid=3230] Error locating target 'fish_speech.models.vqgan.modules.fsq.DownsampleFiniteScalarQuantize', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: quantizer
2024-09-15 18:52:54,385 uvicorn.access 2323 INFO     192.168.1.3:59611 - "POST /v1/models HTTP/1.1" 500
```

### Expected behavior / 期待表现

正常运行

**Comment by gavin2014** [comment]
pip install vector_quantize_pytorch 我是fsq.py 缺包，表现成你那个报错
