### ISSUE TITLE
docker运行无法下载模型，变量已经更改.宿主机本地启动,就可以下载

### ISSUE THREAD

**Issue by sdytzjp** [xorbitsai/inference#2341]
### System Info / 系統信息

 Driver Version: 535.183.06   CUDA Version: 12.2
py311

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

latest_cpu

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -v /root/fastgpt/xinference_image:/root/xinference_image   -v /root/.cache/huggingface:/root/.cache/huggingface -v /root/.cache/modelscope:/root/.cache/modelscope -e XINFERENCE_HOME=/root/xinference_image -d -p 9997:9997 --name xinference registry.cn-hangzhou.aliyuncs.com/sdytai/xprobe_xinference_cpu xinference-local -H 0.0.0.0 --log-level debug

### Reproduction / 复现过程
容器启动后无法下载模型。
但是宿主机安装0.14.0，本地启动xinference-local -H 0.0.0.0 就可以正常下载

宿主机环境变量
export HF_ENDPOINT=https://hf-mirror.com
export XINFERENCE_MODEL_SRC=modelscope 

容器日志如下：
RuntimeError: [address=0.0.0.0:59644, pid=135] Failed to download model 'MiniCPM-V-2.6' (size: 8, format: pytorch) after multiple retries
2024-09-20 18:43:42,743 xinference.core.supervisor 135 DEBUG    Enter launch_builtin_model, model_uid: MiniCPM-V-2.6, model_name: MiniCPM-V-2.6, model_size: 8, model_format: pytorch, quantization: none, replica: 1, kwargs: {}
2024-09-20 18:43:42,745 xinference.core.worker 135 DEBUG    Enter get_model_count, args: <xinference.core.worker.WorkerActor object at 0x7f4c521bce30>, kwargs:
2024-09-20 18:43:42,745 xinference.core.worker 135 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-09-20 18:43:42,746 xinference.core.worker 135 INFO     [request 42875ea8-7780-11ef-848b-0242ac110004] Enter launch_builtin_model, args: <xinference.core.worker.WorkerActor object at 0x7f4c521bce30>, kwargs: model_uid=MiniCPM-V-2.6-1-0,model_name=MiniCPM-V-2.6,model_size_in_billions=8,model_format=pytorch,quantization=none,model_engine=Transformers,model_type=LLM,n_gpu=None,request_limits=None,peft_model_config=None,gpu_idx=None,download_hub=None,model_path=None
2024-09-20 18:43:42,747 xinference.core.worker 135 DEBUG    GPU disabled for model MiniCPM-V-2.6-1-0
2024-09-20 18:43:46,950 xinference.model.llm.core 135 DEBUG    Launching MiniCPM-V-2.6-1-0 with MiniCPMV26Model
2024-09-20 18:43:46,950 xinference.model.llm.llm_family 135 INFO     Caching from Hugging Face: openbmb/MiniCPM-V-2_6
2024-09-20 18:45:54,348 xinference.model.utils 135 DEBUG    Download failed: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again., download func: <function snapshot_download at 0x7f4dbec7ea20>, download args: ('openbmb/MiniCPM-V-2_6',), kwargs: {'revision': '3f7a8da1b7a8b928b5ee229fae33cf43fd64cf31'}
2024-09-20 18:45:54,348 xinference.model.utils 135 WARNING  Attempt 1 failed. Remaining attempts: 2

### Expected behavior / 期待表现

可以下载

**Comment by sdytzjp** [comment]
更新最新版本ok

**Comment by uu5208** [comment]
已经更新最新版本的image了，还是不可

**Comment by kettly1260** [comment]
@goactiongo 
2025-02-27 14:51:58,166 xinference.core.cache_tracker 32 WARNING  Not record version info for model_name: CogVideoX-2b
2025-02-27 14:51:58,169 xinference.core.cache_tracker 32 WARNING  Not record version info for model_name: CogVideoX-5b
2025-02-27 14:51:58,172 xinference.core.cache_tracker 32 WARNING  Not record version info for model_name: HunyuanVideo
2025-02-27 14:52:08,062 xinference.core.worker 32 INFO     [request 6abee3ba-f51a-11ef-b55a-0242ac150009] Enter launch_builtin_model, args: <xinference.core.worker.WorkerActor object at 0x14913dfd3410>, kwargs: model_uid=ChatTTS-0,model_name=ChatTTS,model_size_in_billions=None,model_format=None,quantization=None,model_engine=None,model_type=audio,n_gpu=None,request_limits=None,peft_model_config=None,gpu_idx=None,download_hub=None,model_path=None,xavier_config=None
2025-02-27 14:54:22,333 xinference.model.utils 32 WARNING  Attempt 1 failed. Remaining attempts: 2
2025-02-27 14:56:37,501 xinference.model.utils 32 WARNING  Attempt 2 failed. Remaining attempts: 1
2025-02-27 14:58:52,669 xinference.model.utils 32 WARNING  Attempt 3 failed. Remaining attempts: 0
2025-02-27 14:58:52,671 xinference.core.worker 32 ERROR    Failed to load model ChatTTS-0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x14916743e3d0>, 'Connection to huggingface.co timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/2Noise/ChatTTS/revision/1a3c04a8b0651689bd9242fbb55b1f4b5a9aef84 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14916743e3d0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 155, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2748, in repo_info
    return method(
           ^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2532, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/2Noise/ChatTTS/revision/1a3c04a8b0651689bd9242fbb55b1f4b5a9aef84 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14916743e3d0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 8aa299b1-d56f-4def-b92f-026861ed0d96)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 115, in retry_download
    return download_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 235, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 894, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 124, in create_model_instance
    return create_audio_model_instance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/core.py", line 186, in create_audio_model_instance
    model_path = cache(model_spec)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/core.py", line 144, in cache
    return cache(model_spec, AudioModelDescription)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 295, in cache
    download_dir = retry_download(
                   ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 144, in retry_download
    raise RuntimeError(
RuntimeError: Failed to download model 'ChatTTS' after multiple retries
2025-02-27 14:58:52,698 xinference.core.worker 32 ERROR    [request 6abee3ba-f51a-11ef-b55a-0242ac150009] Leave launch_builtin_model, error: Failed to download model 'ChatTTS' after multiple retries, elapsed time: 404 s
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x14916743e3d0>, 'Connection to huggingface.co timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/2Noise/ChatTTS/revision/1a3c04a8b0651689bd9242fbb55b1f4b5a9aef84 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14916743e3d0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 155, in snapshot_download
    repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2748, in repo_info
    return method(
           ^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 2532, in model_info
    r = get_session().get(path, headers=headers, timeout=timeout, params=params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/2Noise/ChatTTS/revision/1a3c04a8b0651689bd9242fbb55b1f4b5a9aef84 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x14916743e3d0>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 8aa299b1-d56f-4def-b92f-026861ed0d96)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 115, in retry_download
    return download_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/huggingface_hub/_snapshot_download.py", line 235, in snapshot_download
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/utils.py", line 93, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 894, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 124, in create_model_instance
    return create_audio_model_instance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/core.py", line 186, in create_audio_model_instance
    model_path = cache(model_spec)
                 ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/core.py", line 144, in cache
    return cache(model_spec, AudioModelDescription)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 295, in cache
    download_dir = retry_download(
                   ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 144, in retry_download
    raise RuntimeError(
RuntimeError: Failed to download model 'ChatTTS' after multiple retries
2025-02-27 14:58:52,710 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:49847, pid=32] Failed to download model 'ChatTTS' after multiple retries
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the files on the Hub and we cannot find the appropriate snapshot folder for the specified revision on the local disk. Please check your internet connection and try again.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1002, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 667, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 1190, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 1125, in _launch_model
    subpool_address = await _launch_one_model(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/supervisor.py", line 1083, in _launch_one_model
    subpool_address = await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 667, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/utils.py", line 93, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 894, in launch_builtin_model
    model, model_description = await asyncio.to_thread(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/core.py", line 124, in create_model_instance
    return create_audio_model_instance(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/core.py", line 186, in create_audio_model_instance
    model_path = cache(model_spec)
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/audio/core.py", line 144, in cache
    return cache(model_spec, AudioModelDescription)
      ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 295, in cache
    download_dir = retry_download(
    ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/model/utils.py", line 144, in retry_download
    raise RuntimeError(
    ^^^^^^^^^^^^^^^^^
RuntimeError: [address=0.0.0.0:49847, pid=32] Failed to download model 'ChatTTS' after multiple retries
2025-02-27 15:00:42,018 xinference.core.worker 32 INFO     [request 9d166846-f51b-11ef-b55a-0242ac150009] Enter launch_builtin_model, args: <xinference.core.worker.WorkerActor object at 0x14913dfd3410>, kwargs: model_uid=FishSpeech-1.5-0,model_name=FishSpeech-1.5,model_size_in_billions=None,model_format=None,quantization=None,model_engine=None,model_type=audio,n_gpu=None,request_limits=None,peft_model_config=None,gpu_idx=None,download_hub=modelscope,model_path=None,xavier_config=None
2025-02-27 15:00:42,596 xinference.model.utils 32 WARNING  Attempt 1 failed. Remaining attempts: 2
2025-02-27 15:02:58,429 xinference.model.utils 32 WARNING  Attempt 2 failed. Remaining attempts: 1


换了几个model，都无法下载
