### ISSUE TITLE
0.15.2版本xinference启动本地模型报错Model not found

### ISSUE THREAD

**Issue by wujingbo-web** [xorbitsai/inference#2358]
### System Info / 系統信息

宿主机：cent7.9
cuda:12.4
python3.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.2

### The command used to start Xinference / 用以启动 xinference 的命令

xinference launch --model_path /data1/model/Qwen2.5-72B-Instruct-AWQ --model-engine vllm  -n Qwen2.5-72B-Instruct-AWQ -s 72 -f awq -q int4

### Reproduction / 复现过程

1。手工下载模型权重到本地
2。启动docker，进入docker内部执行命令：
xinference launch --model_path /data1/model/Qwen2.5-72B-Instruct-AWQ --model-engine vllm  -n Qwen2.5-72B-Instruct-AWQ -s 72 -f awq -q int4
3、
Launch model name: Qwen2.5-72B-Instruct-AWQ with kwargs: {'model_path': '/data1/model/Qwen2.5-72B-Instruct-AWQ'}
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 901, in model_launch
    model_uid = client.launch_model(
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 940, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:15216, pid=108] Model not found, name: Qwen2.5-72B-Instruct-AWQ, format: awq, size: 72, quantization: int4

### Expected behavior / 期待表现

期待能正常运行。
目前通过ui界面启动模型运行是正常的，自己下载后就不能启动模型。

**Comment by Valdanitooooo** [comment]
```  
-n, --model-name TEXT           Provide the name of the model to be
-u, --model-uid TEXT            Specify UID of model, default is None.
```
-n 应该是 qwen2.5-instruct
-u Qwen2.5-72B-Instruct-AWQ

参考：
- https://inference.readthedocs.io/zh-cn/latest/models/builtin/llm/qwen2.5-instruct.html#model-spec-21-awq-72-billion
- xinference launch  --help

**Comment by boluoyu** [comment]
这里比较坑，因为UI页面需要预先注册一个模型，model_name 是随便写的，点击UI页面部署时，model-uid 和model_name 是一样的，用launch 命令 ，后面的版本不需要预先注册，所以，model_name 必须是系统里已有的标准写法，如qwen2-instruct ，--model-uid 才是你想要起的名字，这里很多人没注意就报这个错了
