### ISSUE TITLE
0.15.3 不支持qwen2.5的vllm了

### ISSUE THREAD

**Issue by Songjiadong** [xorbitsai/inference#2399]
### System Info / 系統信息

0.15.3 不支持qwen2.5的vllm了

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 8888

### Reproduction / 复现过程

ui无法支持qwen2.5了 而且前版本的添加模型的ui也变了，不支持修改初始prompt了

### Expected behavior / 期待表现

支持qwen2.5 vllm

**Comment by Songjiadong** [comment]
@codingl2k1  vllm 0.4.3，然后主要是ui页面注册模型已经无法注册qwen2.5了

**Comment by qinxuye** [comment]
<img width="816" alt="image" src="https://github.com/user-attachments/assets/b12f0926-686a-4e76-ac18-129640e44b40">

这里输入会自动提示自带的模型，qwen2.5-instruct 没有问题。

**Comment by Songjiadong** [comment]
@qinxuye  我0.15.2版本确实是这样的，但是升级到0.15.3的时候就没有了变成老样式了

**Comment by Songjiadong** [comment]
@qinxuye 而且 只有qwen2的2.5的都没有

**Comment by Songjiadong** [comment]
@qinxuye  还有就是想问一下目前qwen2.5 在咱们xinference中是否支持function call？

**Comment by ZhouqyCH** [comment]
升级之后需要重启一下xinference的服务，才能看到qwen2.5系列模型

**Comment by Songjiadong** [comment]
@ZhouqyCH 我是先通过pip install -U 升级的 然后启动的xinference

**Comment by Songjiadong** [comment]
@qinxuye 我又重新更新了一下，出来了您说的页面，我想问以下升级到0.15.3，为什么我启动qwen2.5 会报错` AsyncEngineArgs.__init__() got an unexpected keyword argument 'limit_mm_per_prompt'
` 0.15.2的时候没有这种情况的

**Comment by Songjiadong** [comment]
@ZhouqyCH 我又重新更新了一下，出来了您说的页面，我想问以下升级到0.15.3，为什么我启动qwen2.5 会报错` AsyncEngineArgs.__init__() got an unexpected keyword argument 'limit_mm_per_prompt'
` 0.15.2的时候没有这种情况的

**Comment by Songjiadong** [comment]
```
Traceback (most recent call last):
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/api/restful_api.py", line 967, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1032, in launch_builtin_model
    await _launch_model()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 996, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 975, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 893, in launch_builtin_model
    await model_ref.load()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 309, in load
    self._model.load()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 251, in load
    engine_args = AsyncEngineArgs(
TypeError: [address=0.0.0.0:38945, pid=39412] AsyncEngineArgs.__init__() got an unexpected keyword argument 'limit_mm_per_prompt'

```

**Comment by qinxuye** [comment]
> @qinxuye 我又重新更新了一下，出来了您说的页面，我想问以下升级到0.15.3，为什么我启动qwen2.5 会报错`AsyncEngineArgs.__init__() got an unexpected keyword argument 'limit_mm_per_prompt'` 0.15.2的时候没有这种情况的

这个是已知问题，0.15.4 会修复。
