### ISSUE TITLE
launch model sd3-medium 报错torch.cuda.OutOfMemoryError，实际上其他卡显存空闲

### ISSUE THREAD

**Issue by turndown** [xorbitsai/inference#2406]
### System Info / 系統信息

操作系统"openEuler 20.03 (LTS-SP3)
Cuda V12.5.40
conda虚拟环境Python 3.11.9 
transformers   4.42.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

V0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/data/inference/.xinference XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 30002 --log-level debug

### Reproduction / 复现过程

点击launch模型，选择sd3，模型下载完成，运行报错cuda内容溢出，但实际其他的卡显存充足：
`(Xinference) [root@ecs-lcdsj inference]# nvidia-smi
Wed Oct  9 12:16:02 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-PCIE-40GB          Off |   00000000:00:06.0 Off |                    0 |
| N/A   27C    P0             34W /  250W |   35611MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA A100-PCIE-40GB          Off |   00000000:00:07.0 Off |                    0 |
| N/A   26C    P0             34W /  250W |   13137MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA A100-PCIE-40GB          Off |   00000000:00:08.0 Off |                    0 |
| N/A   28C    P0             33W /  250W |   13105MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA A100-PCIE-40GB          Off |   00000000:00:09.0 Off |                    0 |
| N/A   28C    P0             37W /  250W |   12667MiB /  40960MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A   1984456      C   .../dlbackend/ComfyUI/venv/bin/python3        578MiB |
|    0   N/A  N/A   2387060      C   python                                      22354MiB |
|    0   N/A  N/A   2807977      C   ...unners/cuda_v11/ollama_llama_server      12658MiB |
|    1   N/A  N/A   2807977      C   ...unners/cuda_v11/ollama_llama_server      13128MiB |
|    2   N/A  N/A   2807977      C   ...unners/cuda_v11/ollama_llama_server      13096MiB |
|    3   N/A  N/A   2807977      C   ...unners/cuda_v11/ollama_llama_server      12658MiB |
+-----------------------------------------------------------------------------------------+
`

log日志部分如下，可以看到加载了GPU0，并后续多处出现显存溢出错误，并卡在最后这个位置：
`2024-10-09 12:10:44,478 xinference.core.supervisor 855988 DEBUG    Worker 0.0.0.0:62743 has been added successfully
2024-10-09 12:10:44,479 xinference.core.supervisor 855988 DEBUG    Leave add_worker, elapsed time: 0 s
2024-10-09 12:10:44,479 xinference.core.worker 855988 INFO     Xinference worker 0.0.0.0:62743 started
2024-10-09 12:10:44,480 xinference.core.worker 855988 INFO     Purge cache directory: /data/inference/.xinference/cache
2024-10-09 12:10:44,491 xinference.core.supervisor 855988 DEBUG    Worker 0.0.0.0:62743 resources: {'cpu': ResourceStatus(usage=0.0, total=32, memory_used=50377650176, memory_available=217142534144, memory_total=270481088512), 'gpu-0': GPUStatus(mem_total=42949672960, mem_free=4945346560, mem_used=38004326400), 'gpu-1': GPUStatus(mem_total=42949672960, mem_free=28510126080, mem_used=14439546880), 'gpu-2': GPUStatus(mem_total=42949672960, mem_free=28543680512, mem_used=14405992448), 'gpu-3': GPUStatus(mem_total=42949672960, mem_free=29002956800, mem_used=13946716160)}
2024-10-09 12:10:48,708 xinference.core.supervisor 855988 DEBUG    Enter get_status, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb973660bf0>,), kwargs: {}
2024-10-09 12:10:48,708 xinference.core.supervisor 855988 DEBUG    Leave get_status, elapsed time: 0 s
2024-10-09 12:10:49,781 xinference.api.restful_api 855815 INFO     Starting Xinference at endpoint: http://0.0.0.0:30002
2024-10-09 12:10:50,167 uvicorn.error 855815 INFO     Uvicorn running on http://0.0.0.0:30002 (Press CTRL+C to quit)
2024-10-09 12:11:09,670 xinference.core.supervisor 855988 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb973660bf0>, 'image'), kwargs: {'detailed': True}
2024-10-09 12:11:09,675 xinference.model.image.core 855988 WARNING  Cannot find builtin image model spec: stable-diffusion-inpainting
2024-10-09 12:11:09,676 xinference.model.image.core 855988 WARNING  Cannot find builtin image model spec: stable-diffusion-2-inpainting
2024-10-09 12:11:09,676 xinference.core.supervisor 855988 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-10-09 12:12:05,774 xinference.core.supervisor 855988 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb973660bf0>, 'LLM'), kwargs: {'detailed': True}
2024-10-09 12:12:05,904 xinference.core.supervisor 855988 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-10-09 12:12:08,092 xinference.core.supervisor 855988 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb973660bf0>, 'image'), kwargs: {'detailed': True}
2024-10-09 12:12:08,096 xinference.model.image.core 855988 WARNING  Cannot find builtin image model spec: stable-diffusion-inpainting
2024-10-09 12:12:08,096 xinference.model.image.core 855988 WARNING  Cannot find builtin image model spec: stable-diffusion-2-inpainting
2024-10-09 12:12:08,096 xinference.core.supervisor 855988 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-10-09 12:12:12,939 xinference.core.supervisor 855988 DEBUG    Enter launch_builtin_model, model_uid: sd3-medium, model_name: sd3-medium, model_size: , model_format: None, quantization: None, replica: 1, kwargs: {}
2024-10-09 12:12:12,940 xinference.core.worker 855988 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7fb9734dddf0>,), kwargs: {}
2024-10-09 12:12:12,940 xinference.core.worker 855988 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-10-09 12:12:12,940 xinference.core.worker 855988 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7fb9734dddf0>,), kwargs: {'model_uid': 'sd3-medium-1-0', 'model_name': 'sd3-medium', 'model_size_in_billions': None, 'model_format': None, 'quantization': None, 'model_engine': None, 'model_type': 'image', 'n_gpu': 'auto', 'request_limits': None, 'peft_model_config': None, 'gpu_idx': None, 'download_hub': 'modelscope'}
2024-10-09 12:12:12,941 xinference.core.worker 855988 DEBUG    GPU selected: [0] for model sd3-medium-1-0
2024-10-09 12:12:18,249 xinference.model.image.core 855988 DEBUG    Image model sd3-medium found in ModelScope.
2024-10-09 12:12:18,250 xinference.model.utils 855988 INFO     Use model cache from a different hub.
2024-10-09 12:12:18,273 xinference.model.image.core 857915 WARNING  Cannot find builtin image model spec: stable-diffusion-inpainting
2024-10-09 12:12:18,273 xinference.model.image.core 857915 WARNING  Cannot find builtin image model spec: stable-diffusion-2-inpainting
2024-10-09 12:12:21,096 xinference.model.image.stable_diffusion.core 857915 DEBUG    Loading model <class 'diffusers.pipelines.auto_pipeline.AutoPipelineForText2Image'>
Keyword arguments {'lora_model_paths': None} are not expected by StableDiffusion3Pipeline and will be ignored.
Loading pipeline components...:   0%|                                                                                  | 0/9 [00:00<?, ?it/s]2024-10-09 12:12:21,098 transformers.configuration_utils 857915 INFO     loading configuration file /data/inference/.xinference/cache/sd3-medium/text_encoder_2/config.json
2024-10-09 12:12:21,099 transformers.configuration_utils 857915 INFO     Model config CLIPTextConfig {
`
报错日志：
`Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████| 9/9 [00:03<00:00,  2.60it/s]
2024-10-09 12:12:26,922 xinference.core.worker 855988 ERROR    Failed to load model sd3-medium-1-0
Traceback (most recent call last):
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/model/image/stable_diffusion/core.py", line 97, in load
    self._model = move_model_to_available_device(self._model)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/device_utils.py", line 74, in move_model_to_available_device
    return model.to(device)
      ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 431, in to
    module.to(device, dtype)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
torch.cuda.OutOfMemoryError: [address=0.0.0.0:33491, pid=857915] CUDA out of memory. Tried to allocate 28.00 MiB. GPU
2024-10-09 12:12:27,346 xinference.core.supervisor 855988 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7fb973660bf0>, 'sd3-medium'), kwargs: {'suppress_exception': True}
2024-10-09 12:12:27,346 xinference.core.supervisor 855988 DEBUG    Leave terminate_model, elapsed time: 0 s
2024-10-09 12:12:27,351 xinference.api.restful_api 855815 ERROR    [address=0.0.0.0:33491, pid=857915] CUDA out of memory. Tried to allocate 28.00 MiB. GPU
Traceback (most recent call last):
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/api/restful_api.py", line 847, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 988, in launch_builtin_model
    await _launch_model()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 952, in _launch_model
    await _launch_one_model(rep_model_uid)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/supervisor.py", line 932, in _launch_one_model
    await worker_ref.launch_builtin_model(
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/worker.py", line 841, in launch_builtin_model
    await model_ref.load()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/core/model.py", line 295, in load
    self._model.load()
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/model/image/stable_diffusion/core.py", line 97, in load
    self._model = move_model_to_available_device(self._model)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/xinference/device_utils.py", line 74, in move_model_to_available_device
    return model.to(device)
      ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/diffusers/pipelines/pipeline_utils.py", line 431, in to
    module.to(device, dtype)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
    ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/envs/Xinference/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
torch.cuda.OutOfMemoryError: [address=0.0.0.0:33491, pid=857915] CUDA out of memory. Tried to allocate 28.00 MiB. GPU

`

### Expected behavior / 期待表现

希望能正常使用文生图模型，调用其他的空闲卡运行，但是我没有找到页面上文生图模型的相关设置，能指定某个gpu运行该模型。希望得到回复及帮助，谢谢。

**Comment by turndown** [comment]
麻烦大佬把这个issue关闭下，我发现我默认用pip安装的xinference的版本不是最新的，是0.13版本的，所以界面和别人安装的也都不一样，后面我用源码安装了才发现这个问题，不好意思了。
