### ISSUE TITLE
集成dify的时候tts出现问题

### ISSUE THREAD

**Issue by Uhao-P** [xorbitsai/inference#2412]
### System Info / 系統信息

cuda和系统
![image](https://github.com/user-attachments/assets/b36b052b-6c80-4d15-8b83-b078762466e8)
python环境
```
Package                           Version
--------------------------------- ------------------
absl-py                           2.1.0
accelerate                        1.0.0
accept-types                      0.4.1
aiofiles                          22.1.0
aiohappyeyeballs                  2.3.5
aiohttp                           3.10.1
aioprometheus                     23.12.0
aiosignal                         1.3.1
aiosqlite                         0.20.0
aliyun-python-sdk-core            2.15.2
aliyun-python-sdk-kms             2.16.5
altair                            5.3.0
anaconda-anon-usage               0.4.4
annotated-types                   0.7.0
ansicolors                        1.1.8
antlr4-python3-runtime            4.9.3
anyio                             4.4.0
archspec                          0.2.3
argcomplete                       3.5.1
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
asttokens                         2.4.1
async-timeout                     4.0.3
attrdict                          2.0.1
attrs                             24.2.0
audioread                         3.0.1
auto_gptq                         0.7.1
autoawq                           0.2.5
autoawq_kernels                   0.0.6
av                                13.1.0
Babel                             2.15.0
bcrypt                            4.2.0
beautifulsoup4                    4.12.3
bitsandbytes                      0.44.1
black                             24.10.0
bleach                            6.1.0
blinker                           1.8.2
boltons                           23.0.0
boto3                             1.28.64
botocore                          1.31.85
Brotli                            1.0.9
cachetools                        5.4.0
cdifflib                          1.2.6
certifi                           2024.7.4
cffi                              1.16.0
charset-normalizer                2.0.4
chattts                           0.1.1
chinese                           0.2.1
click                             8.1.7
cloudpickle                       3.0.0
cmake                             3.30.2
coloredlogs                       15.0.1
comm                              0.2.2
conda                             24.7.1
conda-content-trust               0.2.0
conda-libmamba-solver             24.1.0
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
conformer                         0.3.2
contourpy                         1.2.1
controlnet_aux                    0.0.7
crcmod                            1.7
cryptography                      42.0.5
cycler                            0.12.1
Cython                            3.0.10
datamodel-code-generator          0.26.1
datasets                          2.20.0
debugpy                           1.8.5
decorator                         5.1.1
defusedxml                        0.7.1
diffusers                         0.30.3
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
dlib                              19.24.2
dnspython                         2.7.0
ecdsa                             0.19.0
editdistance                      0.8.1
einops                            0.8.0
einx                              0.3.0
email_validator                   2.2.0
encodec                           0.1.1
entrypoints                       0.4
enum34                            1.1.10
eva-decord                        0.6.1
exceptiongroup                    1.2.2
executing                         2.0.1
fastapi                           0.110.3
fastjsonschema                    2.20.0
ffmpeg-python                     0.2.0
ffmpy                             0.4.0
filelock                          3.15.4
FlagEmbedding                     1.2.11
Flask                             3.0.3
Flask-Cors                        4.0.1
flatbuffers                       24.3.25
fonttools                         4.53.1
fqdn                              1.5.1
frozendict                        2.4.2
frozenlist                        1.4.1
fsspec                            2024.5.0
funasr                            1.1.10
future                            1.0.0
fvcore                            0.1.5.post20221221
gdown                             5.2.0
gekko                             1.2.1
genson                            1.3.0
google-auth                       2.33.0
google-auth-oauthlib              1.0.0
gradio                            4.44.1
gradio_client                     1.3.0
graphviz                          0.20.3
grpcio                            1.65.4
h11                               0.14.0
hiredis                           3.0.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.0
huggingface-hub                   0.24.5
humanfriendly                     10.0
hydra-core                        1.3.2
HyperPyYAML                       1.2.2
idna                              3.7
imageio                           2.34.2
imageio-ffmpeg                    0.5.1
importlib_metadata                8.5.0
importlib_resources               6.4.5
inflect                           5.6.2
interegular                       0.3.3
iopath                            0.1.10
ipykernel                         6.29.5
ipython                           8.26.0
ipython-genutils                  0.2.0
ipywidgets                        8.1.3
isoduration                       20.11.0
isort                             5.13.2
itsdangerous                      2.2.0
jaconv                            0.4.0
jamo                              0.4.1
jedi                              0.19.1
jieba                             0.42.1
Jinja2                            3.1.4
jiter                             0.5.0
jj-pytorchvideo                   0.1.5
jmespath                          0.10.0
joblib                            1.4.2
json5                             0.9.25
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.12.1
jupyter-archive                   3.4.0
jupyter_client                    7.4.9
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter_server                    2.14.2
jupyter_server_fileid             0.9.2
jupyter_server_terminals          0.5.3
jupyter_server_ydoc               0.8.0
jupyter-ydoc                      0.2.5
jupyterlab                        3.6.5
jupyterlab_colab_bridge           0.1.6
jupyterlab-execute-time           2.3.1
jupyterlab-language-pack-zh-CN    4.2.post2
jupyterlab-notifications          0.5.0
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.27.3
jupyterlab_widgets                3.0.11
kaldiio                           2.18.0
kiwisolver                        1.4.5
lark                              1.1.9
lazy_loader                       0.4
libmambapy                        1.5.8
libnacl                           2.1.0
librosa                           0.10.2.post1
lightgbm                          2.3.1
lightning                         2.4.0
lightning-utilities               0.11.7
llama_cpp_python                  0.3.1
llvmlite                          0.43.0
lm-format-enforcer                0.10.3
loguru                            0.7.2
loralib                           0.1.2
Markdown                          3.6
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
matplotlib                        3.9.1
matplotlib-inline                 0.1.7
mdurl                             0.1.2
menuinst                          2.1.1
mistune                           3.0.2
modelscope                        1.18.1
mpmath                            1.3.0
msgpack                           1.0.8
multidict                         6.0.5
multiprocess                      0.70.16
mypy-extensions                   1.0.0
natsort                           8.4.0
nbclassic                         1.1.0
nbclient                          0.10.0
nbconvert                         7.16.4
nbformat                          5.10.4
nemo_text_processing              1.0.2
nest-asyncio                      1.6.0
networkx                          3.3
ninja                             1.11.1.1
notebook                          6.5.7
notebook_shim                     0.2.4
numba                             0.60.0
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.555.43
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.6.20
nvidia-nvtx-cu12                  12.1.105
oauthlib                          3.2.2
omegaconf                         2.3.0
onnx                              1.16.2
onnxruntime                       1.16.0
openai                            1.40.1
openbayes-serving                 0.3.1
openbayestool                     0.3.2
opencv-python                     4.10.0.84
optimum                           1.22.0
orjson                            3.10.7
ormsgpack                         1.5.0
oss2                              2.19.0
outlines                          0.0.46
overrides                         7.7.0
packaging                         24.1
pandas                            2.2.2
pandocfilters                     1.5.1
papermill                         2.6.0
parameterized                     0.9.0
parso                             0.8.4
passlib                           1.7.4
pathspec                          0.12.1
peft                              0.13.0
pexpect                           4.9.0
pillow                            10.4.0
pip                               24.0
platformdirs                      3.10.0
pluggy                            1.0.0
pooch                             1.8.2
portalocker                       2.10.1
pprintpp                          0.4.0
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
prompt_toolkit                    3.0.47
protobuf                          5.27.3
psutil                            6.0.0
ptyprocess                        0.7.0
pure_eval                         0.2.3
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           17.0.0
pyarrow-hotfix                    0.6
pyasn1                            0.6.0
pyasn1_modules                    0.4.0
pybase16384                       0.3.7
pycosat                           0.6.6
pycountry                         24.6.1
pycparser                         2.21
pycryptodome                      3.21.0
pydantic                          2.8.2
pydantic_core                     2.20.1
pydub                             0.25.1
Pygments                          2.18.0
pynini                            2.1.5
PyNLPIR                           0.6.0
pynndescent                       0.5.13
pyparsing                         3.1.2
PySocks                           1.7.1
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-jose                       3.3.0
python-json-logger                2.0.7
python-multipart                  0.0.12
pytorch-lightning                 2.4.0
pytorch-wpe                       0.0.1
pytz                              2024.1
PyYAML                            6.0.2
pyzmq                             26.1.0
quantile-python                   1.1
qwen-vl-utils                     0.0.8
ray                               2.34.0
redis                             5.1.1
referencing                       0.35.1
regex                             2024.7.24
requests                          2.32.3
requests-oauthlib                 2.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.9.2
rouge                             1.0.1
rpds-py                           0.20.0
rsa                               4.9
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruff                              0.6.9
s3transfer                        0.7.0
sacremoses                        0.1.1
safetensors                       0.4.4
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.14.0
seaborn                           0.13.2
semantic-version                  2.10.0
Send2Trash                        1.8.3
sentence-transformers             3.1.1
sentencepiece                     0.2.0
setuptools                        72.1.0
sglang                            0.3.3
shellingham                       1.5.4
simplejson                        3.19.3
six                               1.16.0
sniffio                           1.3.1
soundfile                         0.12.1
soupsieve                         2.5
soxr                              0.4.0
sse-starlette                     2.1.3
stack-data                        0.6.3
starlette                         0.37.2
sympy                             1.13.1
tabulate                          0.9.0
tblib                             3.0.0
tenacity                          9.0.0
tensorboard                       2.14.0
tensorboard-data-server           0.7.2
tensorboardX                      2.6.2.2
tensorizer                        2.9.0
termcolor                         2.5.0
terminado                         0.18.1
threadpoolctl                     3.5.0
tifffile                          2024.7.24
tiktoken                          0.7.0
timm                              1.0.9
tinycss2                          1.3.0
tn                                0.0.4
tokenizers                        0.19.1
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.12.0
toolz                             0.12.1
torch                             2.4.0+cu121
torch-complex                     0.4.4
torch-tb-profiler                 0.4.3
torchaudio                        2.4.0+cu121
torchmetrics                      1.4.2
torchvision                       0.19.0+cu121
tornado                           6.4.1
tqdm                              4.66.4
traitlets                         5.14.3
transformers                      4.44.0
transformers-stream-generator     0.0.5
triton                            3.0.0
truststore                        0.8.0
typer                             0.12.5
types-python-dateutil             2.9.0.20240316
typing_extensions                 4.12.2
tzdata                            2024.1
umap-learn                        0.5.6
uri-template                      1.3.0
urllib3                           2.0.7
uvicorn                           0.30.5
uvloop                            0.16.0
vector-quantize-pytorch           1.17.8
vega-datasets                     0.9.0
vllm                              0.5.4
vllm-flash-attn                   2.6.1
vocos                             0.1.0
watchfiles                        0.23.0
wcwidth                           0.2.13
webcolors                         24.6.0
webencodings                      0.5.1
websocket-client                  1.8.0
websockets                        12.0
Werkzeug                          3.0.3
WeTextProcessing                  1.0.3
wget                              3.2
wheel                             0.43.0
widgetsnbextension                4.0.11
wrapt                             1.16.0
xformers                          0.0.27.post2
xinference                        0.15.3
xinference-client                 0.15.3
xlrd                              2.0.1
xoscar                            0.3.3
xxhash                            3.4.1
y-py                              0.6.2
yacs                              0.1.8
yarl                              1.9.4
ypy-websocket                     0.8.4
zipp                              3.20.2
zstandard                         0.22.0
```

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

![image](https://github.com/user-attachments/assets/aab6f9a9-1371-42c4-b470-4c92cefd6b4c)

### Reproduction / 复现过程

1. 成功启动xinference并且启动CosyVoice-300M-SFT(chatTTS也尝试过了会出现同样的问题)

2. 在dify中添加xinference的tts模型
![image](https://github.com/user-attachments/assets/1cd683b5-cff4-4ca7-9da7-29052e59b8e5)

3.在dify中设置音色
![image](https://github.com/user-attachments/assets/d6773e4e-482f-4205-9486-92250855cec9)

4.问答时报错
![image](https://github.com/user-attachments/assets/e4df55e1-ec2e-48b1-a1a7-f4e851676872)

5.xinference后台报错信息
```
2024-10-09 12:52:32,520 xinference.api.restful_api 14952 ERROR    Handling request http://openbayesalgo-jx7k2ut9ok6m.gear-c1.openbayes.net/v1/audio/speech failed: unhandled errors in a TaskGroup (1 sub-exception)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 289, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 278, in wrap
    await func()
  File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 228, in listen_for_disconnect
    message = await receive()
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 553, in receive
    await self.message_event.wait()
  File "/usr/local/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fc39494e950

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/lib/python3.10/site-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
  |     await self.asgi_callable(scope, receive, wrapped_send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
  |     await route.handle(scope, receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 275, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 278, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.10/site-packages/sse_starlette/sse.py", line 258, in stream_response
    |     async for data in self.body_iterator:
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/api.py", line 340, in __anext__
    |     return await self._actor_ref.__xoscar_next__(self._uid)
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    |     return self._process_result_message(result)
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    |     raise message.as_instanceof_cause()
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    |     result = await self._run_coro(message.message_id, coro)
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    |     return await coro
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    |     return await super().__on_receive__(message)  # type: ignore
    |   File "xoscar/core.pyx", line 558, in __on_receive__
    |     raise ex
    |   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    |     async with self._lock:
    |   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    |     with debug_async_timeout('actor_lock_timeout',
    |   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    |     result = await result
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/api.py", line 431, in __xoscar_next__
    |     raise e
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/api.py", line 417, in __xoscar_next__
    |     r = await asyncio.to_thread(_wrapper, gen)
    |   File "/usr/local/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    |     return await loop.run_in_executor(None, func_call)
    |   File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    |     result = self.fn(*self.args, **self.kwargs)
    |   File "/usr/local/lib/python3.10/site-packages/xoscar/api.py", line 402, in _wrapper
    |     return next(_gen)
    |   File "/usr/local/lib/python3.10/site-packages/xinference/core/model.py", line 332, in _to_generator
    |     for v in gen:
    |   File "/usr/local/lib/python3.10/site-packages/xinference/model/audio/cosyvoice.py", line 108, in _generator_stream
    |     writer = torchaudio.io.StreamWriter(out, format=response_format)
    |   File "/usr/local/lib/python3.10/site-packages/torio/io/_streaming_media_encoder.py", line 197, in __init__
    |     self._s = ffmpeg_ext.StreamingMediaEncoderFileObj(dst, format, buffer_size)
    |   File "/usr/local/lib/python3.10/site-packages/torio/_extension/utils.py", line 25, in __getattr__
    |     self._import_once()
    |   File "/usr/local/lib/python3.10/site-packages/torio/_extension/utils.py", line 39, in _import_once
    |     self.module = self.import_func()
    |   File "/usr/local/lib/python3.10/site-packages/torio/_extension/utils.py", line 143, in _init_ffmpeg
    |     ext = _find_ffmpeg_extension(ffmpeg_vers)
    |   File "/usr/local/lib/python3.10/site-packages/torio/_extension/utils.py", line 122, in _find_ffmpeg_extension
    |     raise ImportError(
    | ImportError: [address=0.0.0.0:34763, pid=17228] Failed to intialize FFmpeg extension. Tried versions: ['6', '5', '4', '']. Enable DEBUG logging to see more details about the error.
    +------------------------------------
```

### Expected behavior / 期待表现

无

**Comment by Uhao-P** [comment]
重新源码安装ffmpeg后解决问题

**Comment by 948024326** [comment]
哥你dify是什么版本的？ 为啥我没得播放这个功能

**Comment by kfchandsome** [comment]
> 重新源码安装ffmpeg后解决问题

 我在window安装了ffmpeg，我是通过docker部署Xinference，请问我要怎么处理
