### ISSUE TITLE
0.15.3版本qwen2.5模型AsyncEngineArgs.__init__() got an unexpected keyword argument 'limit_mm_per_prompt'报错

### ISSUE THREAD

**Issue by Songjiadong** [xorbitsai/inference#2430]
### System Info / 系統信息

python 3.10
vllm 0.4.3

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.3

### The command used to start Xinference / 用以启动 xinference 的命令

. xinference/bin/activate
xinference-local --host 0.0.0.0 --port 8888

### Reproduction / 复现过程

我是从0.15.2版本升级到0.15.3版本的
然后我配置了qwen2.5-32b的chat版本，然后发现以下bug
```
Traceback (most recent call last):
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/api/restful_api.py", line 967, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1032, in launch_builtin_model
    await _launch_model()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 996, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 975, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 893, in launch_builtin_model
    await model_ref.load()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
    return await coro
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 309, in load
    self._model.load()
  File "/data/galileo/models/xinference/xinference/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 251, in load
    engine_args = AsyncEngineArgs(
TypeError: [address=0.0.0.0:38945, pid=39412] AsyncEngineArgs.__init__() got an unexpected keyword argument 'limit_mm_per_prompt'
```
又尝试了以下qwen2.0版本也同样会出现这个问题

### Expected behavior / 期待表现

正常启动qwen

**Comment by qinxuye** [comment]
已经有 PR 修复了，今天发版会解决。
