### ISSUE TITLE
0.15.4启动jina-embedding-v3报错

### ISSUE THREAD

**Issue by linhao622** [xorbitsai/inference#2436]
### System Info / 系統信息

python==3.10.13
xinference==0.15.4
sentence-transformers         3.2.0
transformers                  4.45.2
transformers-stream-generator 0.0.5

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference==0.15.4

### The command used to start Xinference / 用以启动 xinference 的命令

命令行启动命令如下：
xinference launch -t embedding -n jina-embeddings-v3-local -u jina-embeddings-v3-local
PS：在webui启动也报同样的错误

### Reproduction / 复现过程

1、启动xinference
XINFERENCE_HOME=~/1506/models/xinference XINFERENCE_MODEL_SRC=modelscope XINFERENCE_DISABLE_HEALTH_CHECK=1 xinference-local -H 0.0.0.0
2、注册模型（通过webui注册）
3、启动模型，如上所述不管通过webui还是命令行xinference launch -t embedding -n jina-embeddings-v3-local -u jina-embeddings-v3-local
都报错
### 报错如下：
2024-10-12 22:50:48,650 xinference.api.restful_api 2042 ERROR    [address=0.0.0.0:49649, pid=2345] Transformer.__init__() got an unexpected keyword argument 'backend'
Traceback (most recent call last):
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/api/restful_api.py", line 977, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1040, in launch_builtin_model
    await _launch_model()
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1004, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/supervisor.py", line 983, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/utils.py", line 69, in wrapped
    ret = await func(*args, **kwargs)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/worker.py", line 894, in launch_builtin_model
    await model_ref.load()
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/core/model.py", line 335, in load
    self._model.load()
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/xinference/model/embedding/core.py", line 198, in load
    self._model = SentenceTransformer(
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 306, in __init__
    modules, self.module_kwargs = self._load_sbert_model(
  File "/Users/tsuyoshidomoto/.pyenv/versions/3.10.13/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 1722, in _load_sbert_model
    module = module_class(model_name_or_path, cache_dir=cache_folder, backend=self.backend, **kwargs)
TypeError: [address=0.0.0.0:49649, pid=2345] Transformer.__init__() got an unexpected keyword argument 'backend'

### Expected behavior / 期待表现

模型正常启动

**Comment by linhao622** [comment]
通过docker镜像0.15.4-cpu和本地pip install启动都报同样的错误

**Comment by wangbo6886** [comment]
> 测试了：docker镜像0.15.4-cpu和本地pip install两种方式部署，命令行或者webui启动都报同样的错误

我降级sentence-transformers到3.1.0就可以了

**Comment by linhao622** [comment]
试了，把sentence-transformers降到3.2.0以下，比如3.1.1，3.1.0都行，看来版本高了也不行。。。

**Comment by songleipu123** [comment]
我把sentence-transformers降到3.1.0了，还是不行啊，大佬们还有啥办法吗？
