### ISSUE TITLE
pip部署模式升级到0.16.0无法分布式启动

### ISSUE THREAD

**Issue by sarsmlee** [xorbitsai/inference#2460]
### System Info / 系統信息

python 3.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

 Xinference = 0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-supervisor -H "192.168.x.x"

### Reproduction / 复现过程

1.pip install 'xinference==0.16.0’
2.使用分布式模式启动 xinference-supervisor -H "192.168.x.x"

3.Traceback (most recent call last):
  File ".conda/envs/xinference/bin/xinference-supervisor", line 8, in <module>
    sys.exit(supervisor())
  File ".conda/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File ".conda/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File ".conda/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".conda/envs/xinference/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File ".conda/envs/xinference/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 274, in supervisor
    from ..deploy.supervisor import main
  File ".conda/envs/xinference/lib/python3.10/site-packages/xinference/deploy/supervisor.py", line 34, in <module>
    from ..model import _install as install_model
ImportError: cannot import name '_install' from 'xinference.model' (.conda/envs/xinference/lib/python3.10/site-packages/xinference/model/__init__.py)

### Expected behavior / 期待表现

0.15.4版本没有这个问题

0.16.0能够正常启动

**Comment by qinxuye** [comment]
在 #2457 里修复了，下个版本会修复。

**Comment by cnjack** [comment]
Workaround: apply the same change(#2457 ) to `./miniconda3/envs/xinference/lib/python3.11/site-packages/xinference/deploy/supervisor.py` and restart the serivce.
