### ISSUE TITLE
Running Xinference with Docker  has ImportError

### ISSUE THREAD

**Issue by DavidSche** [xorbitsai/inference#2500]
### System Info / 系統信息

cuda  12.4 ,ubuntu 20.4 

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.16.0 

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -it --name xinference-master -d -p 9997:9997  -e XINFERENCE_HOME=/data -e XINFERENCE_MODEL_SRC=modelscope -v /data/xinference/cluster/data:/data --gpus all --net=host xprobe/xinference:latest xinference-supervisor -H 192.168.31.25

### Reproduction / 复现过程

目的是构建集群，结果   启动容器报错，提示错误
     
Traceback (most recent call last):

  File "/usr/local/bin/xinference-supervisor", line 8, in <module>

    sys.exit(supervisor())

  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke

    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 274, in supervisor

    from ..deploy.supervisor import main

  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/supervisor.py", line 34, in <module>

    from ..model import _install as install_model

ImportError: cannot import name '_install' from 'xinference.model' (/usr/local/lib/python3.10/dist-packages/xinference/model/__init__.py)

### Expected behavior / 期待表现

正常启动

**Comment by qinxuye** [comment]
v0.16.1 released last week should have solved this issue, close first, feel free to reopen if the problem exists still.
