### ISSUE TITLE
qwen2.5 用vllm引擎报错failed to infer device type

### ISSUE THREAD

**Issue by kevinchi8781** [xorbitsai/inference#2511]
### System Info / 系統信息

![微信图片_20241104172619](https://github.com/user-attachments/assets/3aa4d394-71aa-43a8-a923-5dc1548372a9)
![微信图片_20241104172637](https://github.com/user-attachments/assets/c863ee2a-f885-40a1-9567-886693422e87)
![微信图片_20241104172646](https://github.com/user-attachments/assets/c4d69968-97bc-4767-9132-0e9e846e8f94)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

1

### The command used to start Xinference / 用以启动 xinference 的命令

1

### Reproduction / 复现过程

1111

### Expected behavior / 期待表现

111

**Comment by kevinchi8781** [comment]
![微信图片_20241104173642](https://github.com/user-attachments/assets/1741c934-af2e-4866-8e0a-2e036e40e16a)
补充VLLM版本

**Comment by githust66** [comment]
我也遇到了同样的问题，vllm版本号0.6.4+rocm624。错误日志
`2024-11-22 11:45:14,432 xinference.api.restful_api 98471 ERROR    [address=0.0.0.0:43751, pid=110660] Failed to infer device type
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/api/restful_api.py", line 992, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1041, in launch_builtin_model
    await _launch_model()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1005, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 984, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/utils.py", line 90, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/worker.py", line 897, in launch_builtin_model
    await model_ref.load()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 399, in load
    self._model.load()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 262, in load
    self._engine = AsyncLLMEngine.from_engine_args(engine_args)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/vllm-0.6.4+rocm624-py3.10-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 683, in from_engine_args
    engine_config = engine_args.create_engine_config()
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/vllm-0.6.4+rocm624-py3.10-linux-x86_64.egg/vllm/engine/arg_utils.py", line 948, in create_engine_config
    device_config = DeviceConfig(device=self.device)
  File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/vllm-0.6.4+rocm624-py3.10-linux-x86_64.egg/vllm/config.py", line 1222, in __init__
    raise RuntimeError("Failed to infer device type")
RuntimeError: [address=0.0.0.0:43751, pid=110660] Failed to infer device type
2024-11-22 11:45:14,432 uvicorn.access 98471 INFO     192.168.0.105:53633 - "POST /v1/models HTTP/1.1" 503
`

**Comment by githust66** [comment]
> 我也遇到了同样的问题。 模型：目前试过了qwen2.5-instruct和llama3.1-instruct都是如此 vllm版本：0.6.4+rocm624 安装方式：pip install xinf版本：1.0.0 ![image](https://private-user-images.githubusercontent.com/53259654/388793843-fbb090cb-9a74-4dc2-866b-8fadf4eefc4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MDE4MzEsIm5iZiI6MTczMjcwMTUzMSwicGF0aCI6Ii81MzI1OTY1NC8zODg3OTM4NDMtZmJiMDkwY2ItOWE3NC00ZGMyLTg2NmItOGZhZGY0ZWVmYzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA5NTg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNGM3MDAyOGE1MWNhY2FkNzExMzg1OWY5OTRhMzY1Y2M0NzVhYTZmZGQ0NDMzY2Y4ZjIxODE0MGMyOTc5MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.AFFTZCQTk_4uknpYnayQSk89u58-97RXz9Ew06rZoFQ) 错误日志： 2024-11-22 11:45:14,432 xinference.api.restful_api 98471 ERROR [address=0.0.0.0:43751, pid=110660] Failed to infer device type Traceback (most recent call last): File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/api/restful_api.py", line 992, in launch_model model_uid = await (await self._get_supervisor_ref()).launch_builtin_model( File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send return self._process_result_message(result) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message raise message.as_instanceof_cause() File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send result = await self._run_coro(message.message_id, coro) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro return await coro File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in **on_receive** return await super().**on_receive**(message) # type: ignore File "xoscar/core.pyx", line 558, in **on_receive** raise ex File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.**on_receive** async with self._lock: File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.**on_receive** with debug_async_timeout('actor_lock_timeout', File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.**on_receive** result = await result File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1041, in launch_builtin_model await _launch_model() File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 1005, in _launch_model await _launch_one_model(rep_model_uid) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/supervisor.py", line 984, in _launch_one_model await worker_ref.launch_builtin_model( File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send return self._process_result_message(result) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message raise message.as_instanceof_cause() File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send result = await self._run_coro(message.message_id, coro) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro return await coro File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in **on_receive** return await super().**on_receive**(message) # type: ignore File "xoscar/core.pyx", line 558, in **on_receive** raise ex File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.**on_receive** async with self._lock: File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.**on_receive** with debug_async_timeout('actor_lock_timeout', File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.**on_receive** result = await result File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/utils.py", line 90, in wrapped ret = await func(*args, **kwargs) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/worker.py", line 897, in launch_builtin_model await model_ref.load() File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 231, in send return self._process_result_message(result) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message raise message.as_instanceof_cause() File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send result = await self._run_coro(message.message_id, coro) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro return await coro File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xoscar/api.py", line 384, in **on_receive** return await super().**on_receive**(message) # type: ignore File "xoscar/core.pyx", line 558, in **on_receive** raise ex File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.**on_receive** async with self._lock: File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.**on_receive** with debug_async_timeout('actor_lock_timeout', File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.**on_receive** result = await result File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/core/model.py", line 399, in load self._model.load() File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/xinference/model/llm/vllm/core.py", line 262, in load self._engine = AsyncLLMEngine.from_engine_args(engine_args) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/vllm-0.6.4+rocm624-py3.10-linux-x86_64.egg/vllm/engine/async_llm_engine.py", line 683, in from_engine_args engine_config = engine_args.create_engine_config() File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/vllm-0.6.4+rocm624-py3.10-linux-x86_64.egg/vllm/engine/arg_utils.py", line 948, in create_engine_config device_config = DeviceConfig(device=self.device) File "/root/miniconda3/envs/xinf/lib/python3.10/site-packages/vllm-0.6.4+rocm624-py3.10-linux-x86_64.egg/vllm/config.py", line 1222, in **init** raise RuntimeError("Failed to infer device type") RuntimeError: [address=0.0.0.0:43751, pid=110660] Failed to infer device type 2024-11-22 11:45:14,432 uvicorn.access 98471 INFO 192.168.0.105:53633 - "POST /v1/models HTTP/1.1" 503

vllm使用了amdsmi，但是amdsmi不支持在wsl上工作导致的。请忽略
