### ISSUE TITLE
无法安装FishSpeech

### ISSUE THREAD

**Issue by zg9uagfv** [xorbitsai/inference#2517]
### System Info / 系統信息

ubuntu20.04
python3.8
CUDA Version: 12.4 

安装命令:
pip install "xinference[all]"

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.16.2

### The command used to start Xinference / 用以启动 xinference 的命令

HF_ENDPOINT=https://hf-mirror.com xinference --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

1.启动HF_ENDPOINT=https://hf-mirror.com xinference --host 0.0.0.0 --port 9997
2.在另一个终端上启动FishSpeech后，就会报如下错误：
`(base) hs@hs-A800:~/.cache/huggingface/hub$ xinference launch --model-name FishSpeech-1.4 --model-type audio

Launch model name: FishSpeech-1.4 with kwargs: {}
Traceback (most recent call last):
  File "/home/hs/.local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/home/hs/.local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/hs/.local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/hs/.local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hs/.local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hs/.local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/hs/.local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hs/.local/lib/python3.8/site-packages/xinference/deploy/cmdline.py", line 901, in model_launch
    model_uid = client.launch_model(
  File "/home/hs/.local/lib/python3.8/site-packages/xinference/client/restful/restful_client.py", line 959, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:46619, pid=2908576] invalid syntax (llama.py, line 79)`

### Expected behavior / 期待表现

正常加载FishSpeech并跑起来

**Comment by zg9uagfv** [comment]
> The fish speech source code is written in Python 3.10: https://peps.python.org/pep-0622/

Thanks a lot
