### ISSUE TITLE
[vllm] got an unexpected keyword argument '--gpu-memory-utilization'

### ISSUE THREAD

**Issue by jizusun** [xorbitsai/inference#2525]
### System Info / 系統信息
```
NVIDIA-SMI 550.120                Driver Version: 550.120        CUDA Version: 12.4
Python 3.10.12
(.venv) ➜  vllm-ray cat /etc/*release
DISTRIB_ID=Ubuntu
22.04

(.venv) ➜  vllm-ray pip list | grep vllm
vllm                              0.6.3.post1
```
### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.16.0

### The command used to start Xinference / 用以启动 xinference 的命令

```
 XINFERENCE_MODEL_SRC=modelscope  xinference-local --host 0.0.0.0 --port 9997
```

### Reproduction / 复现过程

```
➜  xinference launch --model-engine vllm --model-name qwen2.5-instruct --size-in-billions 7 --model-format pytorch --quantization none --gpu-memory-utilization 0.6

Launch model name: qwen2.5-instruct with kwargs: {'gpu-memory-utilization': 0.6}
Traceback (most recent call last):
  File "/home/jizu/vllm-ray/.venv/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 901, in model_launch
    model_uid = client.launch_model(
  File "/home/jizu/vllm-ray/.venv/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 940, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:40577, pid=2495685] AsyncEngineArgs.__init__() got an unexpected keyword argument 'gpu-memory-utilization'
```

### Expected behavior / 期待表现

Should accept the argument 'gpu-memory-utilization'
according to this: https://docs.vllm.ai/en/stable/models/engine_args.html

**Comment by jizusun** [comment]
https://inference.readthedocs.io/en/latest/getting_started/using_xinference.html

**Comment by lywy233** [comment]
请问一下这个问题解决了吗，这种参数我传入后也是提示AsyncEngineArgs.__init__() got an unexpected keyword argument ，希望能够修改vllm引擎的参数应当如何设置
