### ISSUE TITLE
libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Yanhuanjin** [xorbitsai/inference#2535]
### System Info / 系統信息

conda/24.1.2 
CPython/3.11.7
Linux/3.10.0-1160.114.2.el7.x86_6
centos/7.9.2009
glibc/2.17

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.2

### The command used to start Xinference / 用以启动 xinference 的命令

使用xinference --version报错

### Reproduction / 复现过程

1、pip install "xinference[all]==0.15.2"安装完毕后，执行任意xinference名令报错
具体错误如下：
Traceback (most recent call last):
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/llama_cpp/_ctypes_extensions.py", line 67, in load_shared_library
    return ctypes.CDLL(str(lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/xinference/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anaconda3/envs/xinference/bin/xinference", line 5, in <module>
    from xinference.deploy.cmdline import cli
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/__init__.py", line 37, in <module>
    _install()
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/__init__.py", line 34, in _install
    install_model()
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/__init__.py", line 17, in _install
    from .audio import _install as audio_install
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/audio/__init__.py", line 22, in <module>
    from .core import (
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/audio/core.py", line 20, in <module>
    from ..core import CacheableModelSpec, ModelDescription
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/core.py", line 19, in <module>
    from ..types import PeftModelConfig
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/types.py", line 386, in <module>
    from llama_cpp import Llama
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/llama_cpp/llama_cpp.py", line 38, in <module>
    _lib = load_shared_library(_lib_base_name, _base_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anaconda3/envs/xinference/lib/python3.11/site-packages/llama_cpp/_ctypes_extensions.py", line 69, in load_shared_library
    raise RuntimeError(f"Failed to load shared library '{lib_path}': {e}")
RuntimeError: Failed to load shared library '/home/anaconda3/envs/xinference/lib/python3.11/site-packages/llama_cpp/lib/libllama.so': libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory

### Expected behavior / 期待表现

之前在ubuntu系统都能正常启动，这次更换centos报错，麻烦看下是什么问题导致?

**Comment by Yanhuanjin** [comment]
solved

**Comment by trackcan** [comment]
> solved

请问怎么解决的，我也碰到这个问题
