### ISSUE TITLE
命令行启动总是提示 You must specify extra kwargs with `--` prefix.

### ISSUE THREAD

**Issue by luckfu** [xorbitsai/inference#2539]
### System Info / 系統信息

registry.cn-hangzhou.aliyuncs.com/xprobe_xinference/xinference:v0.15.4

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.15.4

### The command used to start Xinference / 用以启动 xinference 的命令

webui 上启动服务正常，但命令行总是提示 `You must specify extra kwargs with `--` prefix.`
```bash
root@gpuserver04:/opt/inference# xinference launch \
>     --model-name qwen2.5 \
>     --model-type LLM \
>     --model-uid  \
>     --model_path /models/TableGPT2-7B_1 \
>     --model-engine 'Transformers' \
>     --model-format 'pytorch' \
>     --quantization None \
>     --n-gpu '1' \
>     --gpu-idx '1'

root@gpuserver04:/opt/inference# xinference launch \
>     --model-name qwen2.5 \
>     --model-type LLM \
>     --model-uid \
>     --model_path /models/TableGPT2-7B_1 \
>     --model-engine 'vllm' \
>     --model-format 'pytorch' \
>     --quantization None \
>     --n-gpu '1' \
>     --gpu-idx '1'

```

### Reproduction / 复现过程

```bash
root@gpuserver04:/opt/inference# xinference launch \
>     --model-name qwen2.5 \
>     --model-type LLM \
>     --model-uid \
>     --model_path /models/TableGPT2-7B_1 \
>     --model-engine 'vllm' \
>     --model-format 'pytorch' \
>     --quantization None \
>     --n-gpu '1' \
>     --gpu-idx '1'
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 844, in model_launch
    raise ValueError("You must specify extra kwargs with `--` prefix.")
ValueError: You must specify extra kwargs with `--` prefix.
```

### Expected behavior / 期待表现

希望能从命令行启动

**Comment by luckfu** [comment]
0.16.3 也有这个问题哈
```
xinference launch \
>     --model-name qwen2.5 \
>      --model-type LLM \
>      --model-uid  \
>      --model_path /models/TableGPT2-7B_1 \
>      --model-engine 'Transformers' \
>      --model-format 'pytorch' \
>      --quantization None \
>      --n-gpu '1' \
>      --gpu-idx '1'
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 849, in model_launch
    raise ValueError("You must specify extra kwargs with `--` prefix.")
ValueError: You must specify extra kwargs with `--` prefix.


```

**Comment by namecd** [comment]
take

**Comment by qinxuye** [comment]
@luckfu 问题解决了吗？

**Comment by luckfu** [comment]
> @luckfu 问题解决了吗？

解决了，还是我的问题。。。。`--model-uid  \`  后没有写uid的参数

**Comment by qinxuye** [comment]
OK，报错不是很清楚，没有把有问题的字段抛出来。

不过你如果没有提供值的话应该也要提示。@namecd 可以优化下。
