### ISSUE TITLE
black-forest-labs/FLUX.1-dev 模型启动失败：You are trying to load the model files of the `variant=fp16`, but no such modeling files are available

### ISSUE THREAD

**Issue by majestichou** [xorbitsai/inference#2545]
### System Info / 系統信息

CUDA Version: 12.2，centos 7.9

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

v0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

docker run -d -v /home/llm-test/embedding_and_rerank_model:/root/models -p 9998:9997 --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0

### Reproduction / 复现过程

1. 到hugging face上下载模型 black-forest-labs/FLUX.1-dev， 把所有文件下载到目录/home/llm-test/embedding_and_rerank_model下
2. 采用如下命令启动Xinference
`docker run -d -v /home/llm-test/embedding_and_rerank_model:/root/models -p 9998:9997 --gpus all xprobe/xinference:latest xinference-local -H 0.0.0.0`
3. 浏览器访问Xinference的启动界面
4. 选择Launch Model，选中模型FLUX.1-dev，模型路径选择/root/models/FLUX.1-dev，其他参数采用默认参数，点击启动模型
5. 运行报错，报错如下：
```
2024-11-13 07:49:52,158 transformers.modeling_utils 1437 INFO     All the weights of T5EncoderModel were initialized from the model checkpoint at /root/models/FLUX.1-dev.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5EncoderModel for predictions without further training.
All the weights of T5EncoderModel were initialized from the model checkpoint at /root/models/FLUX.1-dev.
If your task is similar to the task the model of the checkpoint was trained on, you can already use T5EncoderModel for predictions without further training.
2024-11-13 07:49:52,313 xinference.core.worker 289 ERROR    Failed to load model FLUX.1-dev-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/worker.py", line 897, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 231, in send
    return self._process_result_message(result)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/usr/local/lib/python3.10/dist-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/usr/local/lib/python3.10/dist-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/usr/local/lib/python3.10/dist-packages/xinference/core/model.py", line 398, in load
    self._model.load()
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/image/stable_diffusion/core.py", line 252, in load
    self._model = AutoPipelineModel.from_pretrained(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/auto_pipeline.py", line 404, in from_pretrained
    return text_2_image_cls.from_pretrained(pretrained_model_or_path, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py", line 772, in from_pretrained
    raise ValueError(error_message)
ValueError: [address=0.0.0.0:39822, pid=1437] You are trying to load the model files of the `variant=fp16`, but no such modeling files are available.
2024-11-13 07:49:52,580 xinference.core.worker 289 ERROR    [request de545d1a-a1d6-11ef-ac7f-0242ac110002] Leave launch_builtin_model, error: [address=0.0.0.0:39822, pid=1437] You are trying to load the model files of the `variant=fp16`, but no such modeling files are available., elapsed time: 22 s
```

### Expected behavior / 期待表现

正常启动模型

**Comment by majestichou** [comment]
@qinxuye 我按照修复bug的commit修改了一个文件代码，发现还是启动不起来。镜像用的是latest，容器改了修复bug的commit的几行代码，stop，然后start，之后启动模型失败
