### ISSUE TITLE
在windows系统的conda中启动系统，提示错误信息。

### ISSUE THREAD

**Issue by cns-cash** [xorbitsai/inference#2550]
### System Info / 系統信息

OS:WINDOWS10+CONDA
xinference：0.16.3
python：3.10.15
cpu运行，无GPU

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference：0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local.exe -H 127.0.0.1 -p 9997 --log-level DEBUG

### Reproduction / 复现过程

使用以下命令启动时，提示“远程计算机拒绝网络连接。”
xinference-local.exe -H 127.0.0.1 -p 9997 --log-level DEBUG
--------------------------------------------------------------------------------------
2024-11-14 14:03:30,783 xinference.deploy.utils 11296 DEBUG    Error while checking cluster: [WinError 1225] 远程计算机拒绝网络连接。
2024-11-14 14:03:30,784 xinference.deploy.utils 11296 DEBUG    Cluster not available, will try 4 more times
Detected accelerate version: 1.1.1
Detected bitsandbytes version: 0.44.1
Detected coloredlogs version: 15.0.1
Detected datasets version: 2.19.0
Detected jieba version: 0.42.1
Detected jinja2 version: 3.1.4
Detected librosa version: 0.10.2.post1
Detected openai version: 1.54.4
Detected optimum version: 1.23.3
Detected auto_gptq version: 0.7.1
Detected pandas version: 2.2.3
Detected peft version: 0.13.2
Detected psutil version: 6.1.0
Detected pygments version: 2.18.0
Detected sacremoses version: 0.1.1
Detected safetensors version: 0.4.5
Detected scipy version: 1.14.1
Detected sentencepiece version: 0.2.0
Detected soundfile version: 0.12.1
Detected timm version: 1.0.11
Detected tokenizers version: 0.19.1
Detected torchaudio version: 2.5.1
Detected torchvision version: 0.20.1
Detected torch version: 2.5.1
Detected PIL version 10.4.0
2024-11-14 14:03:37,834 xinference.deploy.utils 11296 DEBUG    Error while checking cluster: [WinError 1225] 远程计算机拒绝网络连接。
2024-11-14 14:03:37,834 xinference.deploy.utils 11296 DEBUG    Cluster not available, will try 3 more times
2024-11-14 14:03:44,877 xinference.deploy.utils 11296 DEBUG    Error while checking cluster: [WinError 1225] 远程计算机拒绝网络连接。
2024-11-14 14:03:44,878 xinference.deploy.utils 11296 DEBUG    Cluster not available, will try 2 more times
2024-11-14 14:03:51,937 xinference.deploy.utils 11296 DEBUG    Error while checking cluster: [WinError 1225] 远程计算机拒绝网络连接。
2024-11-14 14:03:51,937 xinference.deploy.utils 11296 DEBUG    Cluster not available, will try 1 more times
2024-11-14 14:03:58,976 xinference.deploy.utils 11296 DEBUG    Error while checking cluster: [WinError 1225] 远程计算机拒绝网络连接。
Traceback (most recent call last):
  File "C:\Users\14790\.conda\envs\xinference\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\14790\.conda\envs\xinference\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\14790\.conda\envs\xinference\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "C:\Users\14790\.conda\envs\xinference\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\14790\.conda\envs\xinference\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\14790\.conda\envs\xinference\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\14790\.conda\envs\xinference\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\14790\.conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 226, in local
    start_local_cluster(
  File "C:\Users\14790\.conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 113, in start_local_cluster
    main(
  File "C:\Users\14790\.conda\envs\xinference\lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts
2024-11-14 14:04:13,631 xinference.core.supervisor 18672 INFO     Xinference supervisor 127.0.0.1:11892 started
2024-11-14 14:04:13,656 xinference.core.worker 18672 INFO     Starting metrics export server at 127.0.0.1:None
2024-11-14 14:04:13,660 xinference.core.worker 18672 INFO     Checking metrics export server...
2024-11-14 14:04:19,828 xinference.core.worker 18672 INFO     Metrics server is started at: http://127.0.0.1:31129
2024-11-14 14:04:19,831 xinference.core.worker 18672 INFO     Purge cache directory: C:\Users\14790\.xinference\cache
2024-11-14 14:04:19,838 xinference.core.supervisor 18672 DEBUG    [request 49a3959d-a24e-11ef-ac54-00f48dd18ca4] Enter add_worker, args: <xinference.core.supervisor.SupervisorActor object at 0x000002364630CCC0>,127.0.0.1:11892, kwargs:
2024-11-14 14:04:19,839 xinference.core.supervisor 18672 DEBUG    Worker 127.0.0.1:11892 has been added successfully
2024-11-14 14:04:19,840 xinference.core.supervisor 18672 DEBUG    [request 49a3959d-a24e-11ef-ac54-00f48dd18ca4] Leave add_worker, elapsed time: 0 s
2024-11-14 14:04:19,841 xinference.core.worker 18672 INFO     Connected to supervisor as a fresh worker
2024-11-14 14:04:19,861 xinference.core.worker 18672 INFO     Xinference worker 127.0.0.1:11892 started
2024-11-14 14:04:19,867 xinference.core.supervisor 18672 DEBUG    Worker 127.0.0.1:11892 resources: {'cpu': ResourceStatus(usage=0.0, total=8, memory_used=9018257408, memory_available=3690369024, memory_total=12708626432)}

### Expected behavior / 期待表现

能正确启动系统，并能够访问

**Comment by XXXE88** [comment]
一样的问题
