### ISSUE TITLE
qwen2-instruct chat failed if set stop parameter

### ISSUE THREAD

**Issue by liunux4odoo** [xorbitsai/inference#2556]
### System Info / 系統信息

system: win10
python: 3.10
transformers: 4.46.2

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local.exe

### Reproduction / 复现过程

1. start `xinference-local.exe`
2. launch qwen2-instruct model in webui
3. do request
```
import openai
client = openai.Client(xxx)
messages = [{'role': 'user', 'content': "Answer the following questions as best you can. You have access to the following APIs:\n\nTool Name: search_santi\nTool Arguments: {'arg':
 {'description': None, 'type': 'str'}}\nTool Description: 查找三体小说中的内容\n\nUse the following format:\n\nQuestion: the input question you must answer\nThought: you should al
 ways think about what to do\nAction: the action to take, should be one of [search_santi]\nAction Input: the input to the action\nObservation: the result of the action\n... (this T
hought/Action/Action Input/Observation can be repeated zero or more times)\nThought: I now know the final answer\nFinal Answer: the final answer to the original input question\n\n
Format the Action Input as a JSON object.\n\nBegin!\n\nQuestion: 在三体小说中找出所有云天明与程心的共同经历"}]
client.chat.completions.create(messages=messages, model="qwen2-instruct", stream=False, temperature=0.01,stop=["Observation:"])
```
this throws exception:
```
Traceback (most recent call last):
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xinference\api\restful_api.py", line 1998, in create_chat_completion
    data = await model.chat(
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xoscar\backends\pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xoscar\backends\pool.py", line 370, in _run_coro
    return await coro
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xinference\core\model.py", line 101, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xoscar\api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xinference\core\utils.py", line 78, in wrapped
    ret = await func(*args, **kwargs)
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xinference\core\model.py", line 723, in chat
    return await self.handle_batching_request(
  File "D:\chatglm\app\anaconda3\envs\lite\lib\site-packages\xinference\core\model.py", line 706, in handle_batching_request
    result = await fut
ValueError: [address=192.168.8.68:63919, pid=36388] <xinference.core.scheduler.InferenceRequest object at 0x00000284D6D0D780>
```
request successes if remove the `stop` parameter.
 

### Expected behavior / 期待表现

make tool call of qwen2 model with `stop` parameter

**Comment by qinxuye** [comment]
We may have not considered too much about the `stop` param, we will try to address the issue.

**Comment by 948024326** [comment]
同样报错了这个  Transformer启动qwen2.5-7b模型 请问解决了吗
