### ISSUE TITLE
When Dify is connected to CosyVoice-300M-SFT of Xinference for text-to-speech conversion, an error is reported.

### ISSUE THREAD

**Issue by peterliang5678** [xorbitsai/inference#2606]
### System Info / 系統信息

ubuntu20

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

new

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_HOME=/home/zhdk_admin/ai/xinference XINFERENCE_MODEL_SRC=modelscope xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

 ERROR    stream encountered an error.
Traceback (most recent call last):
  File "/home/zhdk_admin/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 533, in _handle_pending_requests
    r = await asyncio.to_thread(_wrapper, gen)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhdk_admin/anaconda3/envs/xinference/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhdk_admin/anaconda3/envs/xinference/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zhdk_admin/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 526, in _wrapper
    return next(_gen)
           ^^^^^^^^^^
  File "/home/zhdk_admin/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 437, in _to_generator
    for v in gen:
  File "/home/zhdk_admin/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/audio/cosyvoice.py", line 109, in _generator_stream
    writer.add_audio_stream(sample_rate=22050, num_channels=1)
  File "/home/zhdk_admin/anaconda3/envs/xinference/lib/python3.11/site-packages/torio/io/_streaming_media_encoder.py", line 278, in add_audio_stream
    self._s.add_audio_stream(
RuntimeError: Encoder not found for codec: mp3

### Expected behavior / 期待表现

Resolve the problem

**Comment by qinxuye** [comment]
本地安装下 ffmpeg 试下。

```
conda install -c conda-forge "ffmpeg<7"
```
