### ISSUE TITLE
How to set up xinference behind proxy-server ?

### ISSUE THREAD

**Issue by wan2355** [xorbitsai/inference#2608]
I have to use xinference docker image **behind proxy.** 
But  **xinference can not go through our proxy-server**, and can not launch any models.

**Q1.  How can I set up xinference behind proxy-server and lauch models ?**
**Q2.  if $http_proxy can work for xinference,  it seems that some python script might have bugs, or model-server might have change json format?** 

Read all contes of  the below at the end of this post.
```
xinference  registrations
...

  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 481, in list_model_registrations
    client = RESTfulClient(base_url=endpoint, api_key=api_key)
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 789, in __init__
    self._check_cluster_authenticated()
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 814, in _check_cluster_authenticated
    f"Failed to get cluster information, detail: {response.json()['detail']}"
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

---
1. After setting proxy env. like follows, **curl can  go through my proxy server.**

```
## set proxy env. for docker by follwoing file & run systemd at host PC.
cat /etc/systemd/system/docker.service.d/proxy.conf

Environment="HTTP_PROXY=http://ID:PASS:PORT
Environment="HTTPS_PROXY=http://ID:PASS:PORT
Environment="http_proxy=http://ID:PASS:PORT
Environment="http_proxy=http://ID:PASS:PORT
```

```
## run image
docker run -d \
  -e XINFERENCE_HOME=/data \
  -v  data:/data
  -p 9997:9997 \
  --gpus all \
  --name xinference \
  xprobe/xinference:latest \
  xinference-local -H 0.0.0.0

## log in docker
docker exec -it  xinference bash

## set proxy env.
export http_proxy=http://ID:PASS:PORT

## test curl using proxy
curl https://inference.readthedocs.io/en/latest/development/contributing_environment.html -x $http_proxy | head -n10

## seems to get contens of the page.
...
<p>Before proceeding with any code modifications, it<E2><80><99>s essential to set up the necessary envi
ronment for Xinference development,
which includes familiarizing yourself with Git usage, establishing an isolated environment, installing X
inference, and compiling the frontend.</p>
<section id="getting-started-with-git">
...
```

---
2. xinference, not go through proxy-server?

```
xinference  registrations

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 481, in list_model_registrations
    client = RESTfulClient(base_url=endpoint, api_key=api_key)
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 789, in __init__
    self._check_cluster_authenticated()
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 814, in _check_cluster_authenticated
    f"Failed to get cluster information, detail: {response.json()['detail']}"
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

**Comment by zachary-zheng** [comment]
unset http_proxy
unset https_proxy

Don't set proxy!
