### ISSUE TITLE
接入SenseVoice模型时发生权限错误

### ISSUE THREAD

**Issue by terryoyty** [xorbitsai/inference#2618]
### System Info / 系統信息

Python 3.10.15
anaconda Command line client (version 1.12.3)

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference, version 0.16.3

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 192.168.1.209

### Reproduction / 复现过程

1.启动xinference服务
![image](https://github.com/user-attachments/assets/ee1e418b-adc2-401f-9df7-1484e07863f1)

2.加载SenseVoice模型
![image](https://github.com/user-attachments/assets/5fb7dce3-fce1-42ae-b022-8423bcf33469)

![image](https://github.com/user-attachments/assets/31d1fbae-4232-49c5-923d-e142820b495c)

3.使用dify接入xinference模型
![image](https://github.com/user-attachments/assets/165afc0f-ba19-44ef-85d9-6b33975a5a41)

4.点保存发生报错
![image](https://github.com/user-attachments/assets/18771be4-67e2-4331-ba47-41113965b45f)

  0%|                                                                                            | 0/1 [00:00<?, ?it/s]2024-12-02 11:25:42,460 xinference.core.model 21868 ERROR    [request 1c414af2-b05d-11ef-b60b-0a6225165260] Leave transcriptions, error: Failed to load audio: ffmpeg version 2024-11-28-git-bc991ca048-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59. 47.101 / 59. 47.101
  libavcodec     61. 26.100 / 61. 26.100
  libavformat    61.  9.100 / 61.  9.100
  libavdevice    61.  4.100 / 61.  4.100
  libavfilter    10.  6.101 / 10.  6.101
  libswscale      8. 12.100 /  8. 12.100
  libswresample   5.  4.100 /  5.  4.100
  libpostproc    58.  4.100 / 58.  4.100
[in#0 @ 00000183e4a00240] Error opening input: Permission denied
Error opening input file C:\Users\Terry\AppData\Local\Temp\tmph19eo8gi.
Error opening input files: Permission denied
, elapsed time: 0 s
Traceback (most recent call last):
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\utils\load_utils.py", line 95, in load_audio_text_image_video
    data_or_path_or_list, audio_fs = torchaudio.load(data_or_path_or_list)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\torchaudio\_backend\utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\torchaudio\_backend\soundfile.py", line 27, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 221, in load
    with soundfile.SoundFile(filepath, "r") as file_:
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\soundfile.py", line 658, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\soundfile.py", line 1216, in _open
    raise LibsndfileError(err, prefix="Error opening {0!r}: ".format(self.name))
soundfile.LibsndfileError: Error opening 'C:\\Users\\Terry\\AppData\\Local\\Temp\\tmph19eo8gi': System error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\utils\load_utils.py", line 242, in _load_audio_ffmpeg
    out = run(cmd, capture_output=True, check=True).stdout
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', 'C:\\Users\\Terry\\AppData\\Local\\Temp\\tmph19eo8gi', '-f', 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 4294967283.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\xinference\core\utils.py", line 78, in wrapped
    ret = await func(*args, **kwargs)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\xinference\core\model.py", line 832, in transcriptions
    return await self._call_wrapper_json(
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\xinference\core\model.py", line 549, in _call_wrapper_json
    return await self._call_wrapper("json", fn, *args, **kwargs)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\xinference\core\model.py", line 125, in _async_wrapper
    return await fn(*args, **kwargs)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\xinference\core\model.py", line 573, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\xinference\model\audio\funasr.py", line 99, in transcriptions
    result = self._model.generate(  # type: ignore
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\auto\auto_model.py", line 304, in generate
    return self.inference_with_vad(input, input_len=input_len, **cfg)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\auto\auto_model.py", line 377, in inference_with_vad
    res = self.inference(
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\auto\auto_model.py", line 343, in inference
    res = model.inference(**batch, **kwargs)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\models\fsmn_vad_streaming\model.py", line 676, in inference
    audio_sample_list = load_audio_text_image_video(
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\utils\load_utils.py", line 74, in load_audio_text_image_video
    return [
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\utils\load_utils.py", line 75, in <listcomp>
    load_audio_text_image_video(
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\utils\load_utils.py", line 99, in load_audio_text_image_video
    data_or_path_or_list = _load_audio_ffmpeg(data_or_path_or_list, sr=fs)
  File "C:\Environments\anaconda3\envs\ASRServiceEnv\lib\site-packages\funasr\utils\load_utils.py", line 244, in _load_audio_ffmpeg
    raise RuntimeError(f"Failed to load audio: {e.stderr.decode()}") from e
RuntimeError: Failed to load audio: ffmpeg version 2024-11-28-git-bc991ca048-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 14.2.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libopenjpeg --enable-libquirc --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-libqrencode --enable-librav1e --enable-libsvtav1 --enable-libvvenc --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-liblc3 --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59. 47.101 / 59. 47.101
  libavcodec     61. 26.100 / 61. 26.100
  libavformat    61.  9.100 / 61.  9.100
  libavdevice    61.  4.100 / 61.  4.100
  libavfilter    10.  6.101 / 10.  6.101
  libswscale      8. 12.100 /  8. 12.100
  libswresample   5.  4.100 /  5.  4.100
  libpostproc    58.  4.100 / 58.  4.100
[in#0 @ 00000183e4a00240] Error opening input: Permission denied
Error opening input file C:\Users\Terry\AppData\Local\Temp\tmph19eo8gi.
Error opening input files: Permission denied

### Expected behavior / 期待表现

可以正常使用SenseVoice模型

**Comment by terryoyty** [comment]
已解决，经查是生成临时文件时发生了问题，我是在win11上部署的Xinference，可以看到官方文档中已给出提示：
![image](https://github.com/user-attachments/assets/fc81d4d4-32da-4413-aee7-79c82d09863f)
delete改为False后可正常运行

**Comment by nayaku** [comment]
我也出现这个问题，这个要在哪改？

**Comment by justwangweimin** [comment]
同样的问题，改哪个文件

**Comment by restron** [comment]
https://docs.python.org/zh-cn/3/library/tempfile.html
tempfile.NamedTemporaryFile 
Lib\tempfile.py

**Comment by pjkpjpk** [comment]
First, confirm your virtual environment.
Within the virtual environment, execute python -c "import tempfile; print(tempfile.__file__)" to locate the path of the tempfile.py file.
Open the tempfile.py file, and around line 539, find the method named NamedTemporaryFile, then modify the delete parameter to False.

![Image](https://github.com/user-attachments/assets/8c94f8ed-2e8c-4010-a94f-8e8725ba0748)

**Comment by robin12jbj** [comment]
亲测可行，藏的太隐蔽了😂
