### ISSUE TITLE
launch失败

### ISSUE THREAD

**Issue by Readyou123** [xorbitsai/inference#2633]
### System Info / 系統信息

linux环境
conda安装python环境3.10

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

1.0.1

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 127.0.0.1 --port 9997

### Reproduction / 复现过程

xinference-local --host 127.0.0.1 --port 9997
xinference launch --model-name CosyVoice-300M-SFT --model-type audio --gpu-idx 1

Launch model name: CosyVoice-300M-SFT with kwargs: {}
Traceback (most recent call last):
  File "/root/anaconda3/envs/xinference/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 906, in model_launch
    model_uid = client.launch_model(
  File "/root/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 999, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=127.0.0.1:14812, pid=234656] unexpected EOF

### Expected behavior / 期待表现

成功launch

**Comment by qinxuye** [comment]
需要看服务端日志。
