### ISSUE TITLE
Xinference v1.0.1，无法使用guided_json

### ISSUE THREAD

**Issue by 780966854** [xorbitsai/inference#2636]
### System Info / 系統信息

torch                             2.5.1
torch-complex                     0.4.4
torchaudio                        2.5.1
torchmetrics                      1.6.0
torchvision                       0.20.1
tornado                           6.4.2
transformers                      4.47.0
transformers-stream-generator     0.0.5
triton                            3.1.0
typing_extensions                 4.12.2
urllib3                           2.0.7
vector-quantize-pytorch           1.20.11
verovio                           4.4.0
vllm                              0.6.4.post1
vllm-flash-attn                   2.6.1
xformers                          0.0.28.post3
xinference                        1.0.1

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinferene                        1.0.1

### The command used to start Xinference / 用以启动 xinference 的命令

XINFERENCE_MODEL_SRC=modelscope XINFERENCE_HOME=/root/data1/XinIntefence/ xinference-local --host 0.0.0.0 --port 17000

### Reproduction / 复现过程

所有环境安装包均已更新到最新版本
import openai, json
client = openai.Client(api_key="not empty", base_url="http://0.0.0.0:17001/v1")
sample_json_schema = sample_json_schemas()
messages = [
    {"role": "system", "content": "you are a helpful assistant"},
    {"role": "user", "content": "Give an example JSON for an employee profile that fits this schema: {sample_json_schema}"}
]
completion = client.chat.completions.create(
    model="qwen2.5-instruct",
    messages = messages,
    extra_body={
        "guided_json": sample_json_schema,
        "guided_decoding_backend": "outlines"
    }
)
response = completion.choices[0].message.content
print(response)

报错：
InternalServerError                       Traceback (most recent call last)
Cell In[10], [line 11](vscode-notebook-cell:?execution_count=10&line=11)
      [4](vscode-notebook-cell:?execution_count=10&line=4) sample_json_schema = sample_json_schemas()
      [6](vscode-notebook-cell:?execution_count=10&line=6) messages = [
      [7](vscode-notebook-cell:?execution_count=10&line=7)     {"role": "system", "content": "you are a helpful assistant"},
      [8](vscode-notebook-cell:?execution_count=10&line=8)     {"role": "user", "content": "Give an example JSON for an employee profile that fits this schema: {sample_json_schema}"}
      [9](vscode-notebook-cell:?execution_count=10&line=9) ]
---> [11](vscode-notebook-cell:?execution_count=10&line=11) completion = client.chat.completions.create(
     [12](vscode-notebook-cell:?execution_count=10&line=12)     model="qwen2.5-instruct",
     [13](vscode-notebook-cell:?execution_count=10&line=13)     messages = messages,
     [14](vscode-notebook-cell:?execution_count=10&line=14)     extra_body={
     [15](vscode-notebook-cell:?execution_count=10&line=15)         "guided_json": sample_json_schema,
     [16](vscode-notebook-cell:?execution_count=10&line=16)         "guided_decoding_backend": "outlines"
     [17](vscode-notebook-cell:?execution_count=10&line=17)     }
     [18](vscode-notebook-cell:?execution_count=10&line=18) )
     [20](vscode-notebook-cell:?execution_count=10&line=20) response = completion.choices[0].message.content
     [21](vscode-notebook-cell:?execution_count=10&line=21) print(response)

File d:\miniconda\envs\doc\lib\site-packages\openai\_utils\_utils.py:277, in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    [275](file:///D:/miniconda/envs/doc/lib/site-packages/openai/_utils/_utils.py:275)             msg = f"Missing required argument: {quote(missing[0])}"
    [276](file:///D:/miniconda/envs/doc/lib/site-packages/openai/_utils/_utils.py:276)     raise TypeError(msg)
--> [277](file:///D:/miniconda/envs/doc/lib/site-packages/openai/_utils/_utils.py:277) return func(*args, **kwargs)

File d:\miniconda\envs\doc\lib\site-packages\openai\resources\chat\completions.py:643, in Completions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, parallel_tool_calls, presence_penalty, response_format, seed, service_tier, stop, stream, stream_options, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
...
InternalServerError: Internal Server Error: 2 validation errors for CreateChatCompletion
guided_decoding_backend
  extra fields not permitted (type=value_error.extra)
guided_json
  extra fields not permitted (type=value_error.extra)

服务器报错：
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/xinference/api/restful_api.py", line 1967, in create_chat_completion
    body = CreateChatCompletion.parse_obj(raw_body)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for CreateChatCompletion
guided_decoding_backend
  extra fields not permitted (type=value_error.extra)
guided_json
  extra fields not permitted (type=value_error.extra)

### Expected behavior / 期待表现

completion = client.chat.completions.create(
    model="qwen2.5-instruct",
    messages = messages,
    extra_body={
        "guided_json": sample_json_schema,
        "guided_decoding_backend": "outlines"
    }
)

这里这可以像直接用VLLM启动模型一样，可以调用这几个参数 guided_json guided_decoding_backend

**Comment by qinxuye** [comment]
@wxiwnd 能帮忙看下吗？

**Comment by wxiwnd** [comment]
之前没做OpenAI client的兼容支持，只对xinference client 以及 本身的 restful api 做了支持。我会发一个commit增加对 OpenAI client的支持
