### ISSUE TITLE
在版本1.0.1中，无法运行qwen2_vl大模型，报告xinference.core.worker Leave launch_builtin_model, error: [address=0.0.0.0:42695, pid=88] cannot import name 'Qwen2VLForConditionalGeneration' from 'transformers' (/opt/conda/lib/python3.11/site-packages/transformers/__init__.py),

### ISSUE THREAD

**Issue by zhudemiao** [xorbitsai/inference#2642]
### System Info / 系統信息

v1.0.1，cpu版本

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [X] docker / docker
- [ ] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

1.0.1

### The command used to start Xinference / 用以启动 xinference 的命令

用容器启动

### Reproduction / 复现过程

1、直接使用xprobe/xinference:v1.0.1-cpu，运行qwen2_vl大模型，报告xinference.core.worker Leave launch_builtin_model, error: [address=0.0.0.0:42695, pid=88] cannot import name 'Qwen2VLForConditionalGeneration' from 'transformers' (/opt/conda/lib/python3.11/site-packages/transformers/__init__.py),
2、更新pip install --upgrade --force-reinstall transformers==v4.45.2，报兼容性问题；

### Expected behavior / 期待表现

成功运行

**Comment by qinxuye** [comment]
1.0.1 镜像的 transformers 版本应该已经更新了。

**Comment by zhudemiao** [comment]
刚才重新下载了xprobe/xinference:v1.0.1-cpu，进入容器，查看transformers，还是旧的版本。也无法升级，在容器中如何升级，才能不导致版本冲突。
#pip show transformers
Name: transformers
Version: 4.44.2


================================================================
#pip install --upgrade --force-reinstall transformers==v4.45.2
报兼容性问题。
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.26.3
    Uninstalling huggingface-hub-0.26.3:
      Successfully uninstalled huggingface-hub-0.26.3
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.19.1
    Uninstalling tokenizers-0.19.1:
      Successfully uninstalled tokenizers-0.19.1
  Attempting uninstall: transformers
    Found existing installation: transformers 4.44.2
    Uninstalling transformers-4.44.2:
      Successfully uninstalled transformers-4.44.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
conda 23.10.0 requires ruamel-yaml<0.18,>=0.11.14, but you have ruamel-yaml 0.18.6 which is incompatible.
flagembedding 1.3.2 requires transformers==4.44.2, but you have transformers 4.45.2 which is incompatible.
botocore 1.31.85 requires urllib3<2.1,>=1.25.4; python_version >= "3.10", but you have urllib3 2.2.3 which is incompatible.
chattts 0.2.1 requires numpy<2.0.0, but you have numpy 2.2.0 which is incompatible.
datasets 2.19.0 requires fsspec[http]<=2024.3.1,>=2023.1.0, but you have fsspec 2024.10.0 which is incompatible.
gradio 4.26.0 requires numpy~=1.0, but you have numpy 2.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.2.0 which is incompatible.
Successfully installed certifi-2024.8.30 charset-normalizer-3.4.0 filelock-3.16.1 fsspec-2024.10.0 huggingface-hub-0.26.5 idna-3.10 numpy-2.2.0 packaging-24.2 pyyaml-6.0.2 regex-2024.11.6 requests-2.32.3 safetensors-0.4.5 tokenizers-0.20.3 tqdm-4.67.1 transformers-4.45.2 typing-extensions-4.12.2 urllib3-2.2.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

**Comment by qinxuye** [comment]
哦？你是 CPU 版本？

我们只升级了 GPU 版本，用 CPU 跑 qwen2-vl 吗，能跑得动吗？

**Comment by zhudemiao** [comment]
还没有跑起来就有问题了，服务器是32核，64G内存，试试看。能升级cpu版本吗？

**Comment by zjuyzj** [comment]
我这两天也遇到了类似的问题，原因在 #2649 里有提及，上面的报错信息中也有反映：
> flagembedding 1.3.2 requires transformers==4.44.2, but you have transformers 4.45.2 which is incompatible.

目前`FlagEmbedding`这个上游包严格限制`transformers`的版本为4.44.2，而恰好Qwen2-VL在这个版本的`transformers`下无法工作。很不幸，Docker镜像在构建时安装了所有依赖，猜测是`FlagEmbedding`在依赖解析的过程中把新版的`transformers`顶替掉了，所以升级无效。
`FlagEmbedding`包是rerank模型的必须依赖，是embedding模型的可选依赖。如果只需要使用Qwen2-VL这类视觉模型，可以把`FlagEmbedding`移除了，再升级`transformers`。也可以在干净环境中使用`pip install xinference[transformers]`把Xinference重新装一遍。

**Comment by zhudemiao** [comment]
> FlagEmbedding

按照这个方法，先卸载FlagEmbedding，然后安装transformers，安装时没有报错，但是，在xinference加载运行（点击火箭）时报错：
2024-12-10 23:38:37,855 transformers.modeling_utils 86 INFO     loading weights file /root/.xinference/cache/qwen2-vl-instruct-pytorch-72b/model.safetensors.index.json
loading weights file /root/.xinference/cache/qwen2-vl-instruct-pytorch-72b/model.safetensors.index.json
2024-12-10 23:38:37,858 transformers.generation.configuration_utils 86 INFO     Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645
}

Generate config GenerationConfig {
  "bos_token_id": 151643,
  "eos_token_id": 151645
}

2024-12-10 23:38:37,859 transformers.modeling_utils 86 INFO     Instantiating Qwen2VisionTransformerPretrainedModel model under default dtype torch.float32.
Instantiating Qwen2VisionTransformerPretrainedModel model under default dtype torch.float32.
2024-12-10 23:38:37,936 transformers.models.qwen2_vl.modeling_qwen2_vl 86 WARNING  `Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
`Qwen2VLRotaryEmbedding` can now be fully parameterized by passing the model config through the `config` argument. All other arguments will be removed in v4.46
Loading checkpoint shards:  11%|█▋              | 4/38 [01:39<14:08, 24.95s/it]2024-12-10 23:40:39,862 xinference.core.supervisor 71 ERROR    Worker timeout. address: 0.0.0.0:41607, check count remaining 4...
2024-12-10 23:40:39,866 xinference.core.worker 71 ERROR    Report status got error.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 1030, in report_status
    status = await asyncio.to_thread(gather_node_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 1029, in report_status
    async with timeout(2):
  File "/opt/conda/lib/python3.11/asyncio/timeouts.py", line 111, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
2024-12-10 23:40:41,518 xinference.core.worker 71 ERROR    Failed to load model qwen2-vl-instruct-0
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 897, in launch_builtin_model
    await model_ref.load()
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/core.py", line 87, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server unixsocket:///9306112 closed: 0 bytes read on a total of 11 expected bytes
2024-12-10 23:40:41,522 xinference.core.worker 71 ERROR    [request dc533fa2-b74f-11ef-9989-0242c0a85009] Leave launch_builtin_model, error: Remote server unixsocket:///9306112 closed: 0 bytes read on a total of 11 expected bytes, elapsed time: 131 s
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/utils.py", line 90, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xinference/core/worker.py", line 897, in launch_builtin_model
    await model_ref.load()
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/xoscar/backends/core.py", line 87, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server unixsocket:///9306112 closed: 0 bytes read on a total of 11 expected bytes
2024-12-10 23:40:41,524 xinference.core.supervisor 71 DEBUG    [request 2acee492-b750-11ef-9989-0242c0a85009] Enter terminate_model, args: <xinference.core.supervisor.SupervisorActor object at 0x7fa0c1adc530>,qwen2-vl-instruct, kwargs: suppress_exception=True
2024-12-10 23:40:41,524 xinference.core.supervisor 71 DEBUG    [request 2acee492-b750-11ef-9989-0242c0a85009] Leave terminate_model, elapsed time: 0 s
2024-12-10 23:40:41,548 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:41607, pid=71] Remote server unixsocket:///9306112 closed: 0 bytes read on a total of 11 expected bytes
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1002, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(

**Comment by qinxuye** [comment]
显存够吗？选n-gpu了没

**Comment by zhudemiao** [comment]
> 显存够吗？选n-gpu了没

是基于cpu的。
