### ISSUE TITLE
报错 : 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by hsoftxl** [xorbitsai/inference#2643]
### System Info / 系統信息

macos , mac studio ultral,  pip 安装   。  使用的模型 qwen2-audio

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [x] installation from source / 从源码安装

### Version info / 版本信息

pip 安装最新版

### The command used to start Xinference / 用以启动 xinference 的命令

qwen2-audio模型自带的web页 对话框输入问题， 提交后报错
Traceback (most recent call last):
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/queueing.py", line 624, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/route_utils.py", line 323, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/blocks.py", line 2043, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/blocks.py", line 1602, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/utils.py", line 710, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/utils.py", line 815, in asyncgen_wrapper
    response = await iterator.__anext__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/chat_interface.py", line 727, in _stream_fn
    first_response = await utils.async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/utils.py", line 710, in async_iteration
    return await anext(iterator)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/utils.py", line 704, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/gradio/utils.py", line 687, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/xinference/core/chat_interface.py", line 126, in generate_wrapper
    for chunk in model.chat(
  File "/Users/rays/xinterface/myenv/lib/python3.11/site-packages/xinference/client/common.py", line 51, in streaming_response_iterator
    raise Exception(str(error))
Exception: [address=0.0.0.0:54357, pid=12196] 'NoneType' object is not iterable

### Reproduction / 复现过程

启动服务后， qwen2-audio模型自带的页面提交文本，报错

### Expected behavior / 期待表现

推理出结果

**Comment by qinxuye** [comment]
mac 上可能没有适配。目前应该适配的是 GPU。
