### ISSUE TITLE
xinference显存溢出后llm还在运行状态但api不可用

### ISSUE THREAD

**Issue by YiLin198** [xorbitsai/inference#2648]
### System Info / 系統信息

Ubuntu 22.04.05LTS，CUDA11.8.0，Python3.11，安装的xinference[transformers] 1.0.1，transformers 4.46.3

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference[transformers] 1.0.1，transformers 4.46.3

### The command used to start Xinference / 用以启动 xinference 的命令

nohup xinference-local --host 0.0.0.0 --port 9997 > "$log_file" 2>&1 &

### Reproduction / 复现过程

下载Qwen\Qwen2.5-7B-Instruct，以pytorch、Transformers的方式在单卡4090服务器上运行
为了模拟生产环境，测试显存溢出后，xinference运行的表现，我用paddleOCR结合gunicorn占满了显存。此时运行xinference进行推理报错：
```
2024-12-10 13:55:57,426 - INFO - 请求 f8281099-fa52-45da-b1fb-9c09af36ae75: LLM 处理开始...
2024-12-10 13:55:57,673 - ERROR - 请求 f8281099-fa52-45da-b1fb-9c09af36ae75: 处理失败: Failed to generate completion, detail: Remote server 0.0.0.0:44311 closed: 0 bytes read on a total of 11 expected bytes
Traceback (most recent call last):
  File "/data/app/llm/ocr_app/app/services/ocr_service.py", line 65, in process_id_card_ocr
    llm_response = query_llm(prompt, model_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/llm/ocr_app/app/services/llm_service.py", line 10, in query_llm
    result = model.generate(prompt, generate_config={"max_tokens": 200, "temperature": 0.1})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/anaconda/anaconda3/envs/py311cuda118/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 515, in generate
    raise RuntimeError(
RuntimeError: Failed to generate completion, detail: Remote server 0.0.0.0:44311 closed: 0 bytes read on a total of 11 expected bytes
2024-12-10 13:55:57,676 - ERROR - 请求 f8281099-fa52-45da-b1fb-9c09af36ae75: 处理失败: 请求 f8281099-fa52-45da-b1fb-9c09af36ae75: OCR 流程失败: Failed to generate completion, detail: Remote server 0.0.0.0:44311 closed: 0 bytes read on a total of 11 expected bytes
Traceback (most recent call last):
  File "/data/app/llm/ocr_app/app/services/ocr_service.py", line 65, in process_id_card_ocr
    llm_response = query_llm(prompt, model_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/llm/ocr_app/app/services/llm_service.py", line 10, in query_llm
    result = model.generate(prompt, generate_config={"max_tokens": 200, "temperature": 0.1})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/anaconda/anaconda3/envs/py311cuda118/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 515, in generate
    raise RuntimeError(
RuntimeError: Failed to generate completion, detail: Remote server 0.0.0.0:44311 closed: 0 bytes read on a total of 11 expected bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/app/llm/ocr_app/app/routes.py", line 37, in ocr_id_card
    response = process_id_card_ocr(file1_path, model_name, file2_path=file2_path, request_id=request_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/llm/ocr_app/app/services/ocr_service.py", line 99, in process_id_card_ocr
    raise ValueError(f"请求 {request_id}: OCR 流程失败: {str(e)}")
ValueError: 请求 f8281099-fa52-45da-b1fb-9c09af36ae75: OCR 流程失败: Failed to generate completion, detail: Remote server 0.0.0.0:44311 closed: 0 bytes read on a total of 11 expected bytes
```

此时前端页面上Running Models中模型还存在，且页面上可以生成回答：
![1733811383434](https://github.com/user-attachments/assets/400747b2-92bb-4cb2-b9f4-1a67b2f7ee1a)

但调用后台的api连接返回报错：
```
Traceback (most recent call last):
  File "/data/app/llm/xinference/xinference_test.py", line 77, in <module>
    main(prompt_word)
  File "/data/app/llm/xinference/xinference_test.py", line 33, in main
    response = model.generate(prompt, generate_config={"max_tokens": 5000, "temperature": 0})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/app/anaconda/anaconda3/envs/py311cuda118/lib/python3.11/site-packages/xinference/client/restful/restful_client.py", line 515, in generate
    raise RuntimeError(
RuntimeError: Failed to generate completion, detail: 500 Server Error: Internal Server Error for url: http://127.0.0.1:9997/v1/completions

```

### Expected behavior / 期待表现

期望能有个机制能告诉我（或者能自动修复这个问题）这个模型不再可用了，需要重新launch

**Comment by qinxuye** [comment]
应该是模型状态同步存在问题。我们看下。
