### ISSUE TITLE
qwen2.5-7B-instruct-AWQ 推理报错 __pydantic_core_schema__

### ISSUE THREAD

**Issue by hqm19** [xorbitsai/inference#2666]
### System Info / 系統信息

```
# pip list | grep -E 'torch|cuda|transformers|vllm|llama|pydantic|gradio|fastapi'
fastapi                           0.115.6
gradio                            4.26.0
gradio_client                     0.15.1
jj-pytorchvideo                   0.1.5
llama_cpp_python                  0.3.4
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
prometheus-fastapi-instrumentator 7.0.0
pydantic                          2.10.3
pydantic_core                     2.27.1
pytorch-lightning                 2.4.0
pytorch-wpe                       0.0.1
sentence-transformers             3.3.1
torch                             2.5.1+cu121
torch-complex                     0.4.4
torchaudio                        2.5.1+cu121
torchdiffeq                       0.2.5
torchelastic                      0.2.2
torchmetrics                      1.6.0
torchvision                       0.20.1+cu121
transformers                      4.47.0
transformers-stream-generator     0.0.5
vector-quantize-pytorch           1.20.11
vllm                              0.6.4.post1
x-transformers                    1.42.26
```

```
# python --version
Python 3.11.10
# uname -a
Linux xinference-supervisor-69d77d8494-cfl4h 5.15.0-97-generic #107~20.04.1-Ubuntu SMP Fri Feb 9 14:20:11 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

# nvidia-smi
Fri Dec 13 07:29:23 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
```

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [ ] pip install / 通过 pip install 安装
- [X] installation from source / 从源码安装

### Version info / 版本信息

xinference 版本：
```
commit 609b8257007519b73dd5857d1cb1a3b64d9d0b26 (HEAD -> main, origin/main, origin/HEAD)
Author: Second222None <second222none@163.com>
Date:   Thu Dec 12 23:51:29 2024 +0800
```
以这个 git commit 版本构建的docker镜像，在k8s容器中运行

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-supervisor:
```
root           1  0.4  0.1 11058936 596200 ?     Ssl  03:44   0:57 /opt/conda/bin/python3.11 /opt/conda/bin/xinference-supervisor --port 9997 --host 10.196.84.47 --supervisor-port 9999 --log-level debug --auth-config /etc/xinference/auth-config.json
root         136  0.0  0.1 9342184 648212 ?      Sl   03:44   0:11 /opt/conda/bin/python3.11 /opt/conda/bin/xinference-supervisor --port 9997 --host 10.196.84.47 --supervisor-port 9999 --log-level debug --auth-config /etc/xinference/auth-config.json

```

xinference-worker:
```
# # ps auxww
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.3  0.1 15419204 825636 ?     Ssl  03:44   0:50 /opt/conda/bin/python3.11 /opt/conda/bin/xinference-worker -e http://xinference-supervisor:9997 --host 10.196.84.42 --worker-port 30001 --log-level debug
root         147  0.0  0.0  16552 12952 ?        S    03:52   0:00 /opt/conda/bin/python3.11 -c from multiprocessing.resource_tracker import main;main(38)
root         148  0.0  0.0  17304 14448 ?        S    03:52   0:00 /opt/conda/bin/python3.11 -c from multiprocessing.forkserver import main; main(38, 40, ['__main__'], **{'sys_path': ['/opt/conda/lib/python3.11/site-packages/ray/thirdparty_files', '/opt/conda/bin', '/opt/conda/lib/python311.zip', '/opt/conda/lib/python3.11', '/opt/conda/lib/python3.11/lib-dynload', '/opt/conda/lib/python3.11/site-packages', '__editable__.flashinfer-0.1.6.finder.__path_hook__', '/opt/conda/lib/python3.11/site-packages/setuptools/_vendor', '/tmp/tmpaicyr4lj']})
root        1402  0.0  0.0   8592  7840 pts/0    Ss   06:50   0:00 bash
root        1549  3.8  1.6 47390340 8958768 ?    Sl   06:59   1:18 Model: qwen2.5-instruct-0
```

### Reproduction / 复现过程

在 xinference 中选择 qwen2.5-instruct 卡片，在随后表达中填入(选择)：
* Model Engine: vLLM
* Model Format：awq
* Model Size： 7
* Quantization： int4
* N-GPU：auto
* Replica：1 

启动后，web网页上发起推理请求，后台 xinference-supervisor 报错：
```
2024-12-13 06:25:46,052 xinference.core.supervisor 136 DEBUG    [request 16430c48-b91b-11ef-ab99-3e1134eb1ddd] Enter list_models, args: <xinference.core.supervisor.SupervisorActor object at 0x7f3f655a2f90>, kwargs:
2024-12-13 06:25:46,055 xinference.core.supervisor 136 DEBUG    [request 16430c48-b91b-11ef-ab99-3e1134eb1ddd] Leave list_models, elapsed time: 0 s
2024-12-13 06:26:03,596 xinference.api.restful_api 1 ERROR    Handling request http://xinference.aidc.lccomputing.com:31591/qwen2.5-instruct/run/predict failed: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.10/u/schema-for-unknown-type
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 271, in _init_core_attrs
    self.core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 55, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.11/site-packages/aioprometheus/asgi/middleware.py", line 184, in __call__
    await self.asgi_callable(scope, receive, wrapped_send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/conda/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 460, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/opt/conda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/opt/conda/lib/python3.11/site-packages/gradio/route_utils.py", line 695, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/conda/lib/python3.11/site-packages/gradio/route_utils.py", line 711, in simple_response
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/opt/conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/conda/lib/python3.11/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/fastapi/routing.py", line 291, in app
    solved_result = await solve_dependencies(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 666, in solve_dependencies
    ) = await request_body_to_args(  # body_params checked above
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/fastapi/dependencies/utils.py", line 891, in request_body_to_args
    fields_to_extract = get_cached_model_fields(first_field.type_)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/fastapi/_compat.py", line 659, in get_cached_model_fields
    return get_model_fields(model)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/fastapi/_compat.py", line 285, in get_model_fields
    return [
           ^
  File "/opt/conda/lib/python3.11/site-packages/fastapi/_compat.py", line 286, in <listcomp>
    ModelField(field_info=field_info, name=name)
  File "<string>", line 6, in __init__
  File "/opt/conda/lib/python3.11/site-packages/fastapi/_compat.py", line 111, in __post_init__
    self._type_adapter: TypeAdapter[Any] = TypeAdapter(
                                           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 228, in __init__
    self._init_core_attrs(
  File "/opt/conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 290, in _init_core_attrs
    core_schema = schema_generator.generate_schema(self._type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 865, in _generate_schema_inner
    return self._annotated_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1983, in _annotated_schema
    schema = self._apply_annotations(source_type, annotations)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2062, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2137, in new_handler
    schema = metadata_get_schema(source, get_inner_schema)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2133, in <lambda>
    lambda source, handler: handler(source)
                            ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 84, in __call__
    schema = self._handler(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 2043, in inner_handler
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 988, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1016, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1327, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 612, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 886, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 997, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 515, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.10/u/schema-for-unknown-type
2024-12-13 06:26:03,605 xinference.api.restful_api 1 ERROR    Handling request http://xinference.aidc.lccomputing.com:31591/qwen2.5-instruct/run/predict failed: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.10/u/schema-for-unknown-type
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 271, in _init_core_attrs
    self.core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pydantic/type_adapter.py", line 55, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:
。。。
```

xinference-worker 没有日志

### Expected behavior / 期待表现

正常返回推理结果

**Comment by hqm19** [comment]
基于最新代码：
```
commit 609b8257007519b73dd5857d1cb1a3b64d9d0b26 (HEAD -> main, origin/main, origin/HEAD)
Author: Second222None <second222none@163.com>
Date:   Thu Dec 12 23:51:29 2024 +0800

    FEAT: Add support for CLIP model (#2637)

    Signed-off-by: Song Wei <weis28@chinaunicom.cn>
```
重新构建镜像，在最后加上 pip install gradio==4.44.1 强制升级 gradio 到 4.x 最新版本，推理正常返回，问题解决。
