### ISSUE TITLE
GOT-OCR2.0模型运行出现问题

### ISSUE THREAD

**Issue by zjx140** [xorbitsai/inference#2679]
### System Info / 系統信息

cuda 11.8
python 3.10
torch 2.4.0

### Running Xinference with Docker? / 是否使用 Docker 运行 Xinfernece？

- [ ] docker / docker
- [X] pip install / 通过 pip install 安装
- [ ] installation from source / 从源码安装

### Version info / 版本信息

xinference 1.1.0

### The command used to start Xinference / 用以启动 xinference 的命令

xinference-local --host 0.0.0.0 --port 9997

### Reproduction / 复现过程

点击GOT-OCR2.0加载后点击webUI报错
内容如下
`
2024-12-17 00:05:53,490 xinference.core.model 1263 INFO     ModelActor(GOT-OCR2_0-0) loaded
2024-12-17 00:05:53,492 xinference.core.worker 1082 INFO     [request 180155f4-bbc7-11ef-9402-00ffaabbccdd] Leave launch_builtin_model, elapsed time: 228 s
2024-12-17 00:05:56,294 xinference.api.restful_api 1037 ERROR
Traceback (most recent call last):
  File "/home/zjx140/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1180, in build_gradio_images_interface
    ).build()
  File "/home/zjx140/anaconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/image_interface.py", line 59, in build
    assert "stable_diffusion" in self.model_family
AssertionError
`

### Expected behavior / 期待表现

希望能够打开webUI

**Comment by qinxuye** [comment]
目前 image 的 web UI 是给文生图/图生图用的，OCR 还不能用。

**Comment by xiaocode337317439** [comment]
> 目前 image 的 web UI 是给文生图/图生图用的，OCR 还不能用。

如何调用GOT-OCR, 代码上面

**Comment by qinxuye** [comment]
> > 目前 image 的 web UI 是给文生图/图生图用的，OCR 还不能用。
> 
> 如何调用GOT-OCR, 代码上面

参考：https://inference.readthedocs.io/zh-cn/latest/models/model_abilities/image.html#ocr
