### ISSUE TITLE
BUG:cant't depoy supervisor-worker mode

### ISSUE THREAD

**Issue by touchtop** [xorbitsai/inference#369]
### Describe the bug
I have two machine in the same local newwork, operation system are all win10 professional. Start one machine as supervisor normally, but when start other machine as worker node, echo socket error [WinError 1214]: The format of the specified network name is invalid.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version: Python 3.10 on both machine
2. The version of xinference you use：Xinference 0.2.0 on both machine
3. Versions of crucial packages: all the same as requiements with xinference.
4. Full stack of the error. 
On the machine as supervisor:
(llm) C:\WINDOWS\system32>xinference-supervisor -H "192.168.1.101"
INFO:xinference:Xinference successfully started. Endpoint: http://192.168.1.101:9997

On the machine as worker endpoints:
(llm) C:\WINDOWS\system32>xinference-worker -e "http://192.168.1.101:9997"
Traceback (most recent call last):
  File "D:\anaconda\envs\llm\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\llm\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\llm\Scripts\xinference-worker.exe\__main__.py", line 7, in <module>
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\cmdline.py", line 159, in worker
    main(
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\worker.py", line 61, in main
    loop.run_until_complete(task)
  File "D:\anaconda\envs\llm\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\worker.py", line 50, in _start_worker
    await start_worker_components(
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\worker.py", line 34, in start_worker_components
    await xo.create_actor(
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\api.py", line 59, in create_actor
    return await ctx.create_actor(actor_cls, *args, uid=uid, address=address, **kwargs)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 143, in create_actor
    return self._process_result_message(result)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 596, in create_actor
    await self._run_coro(message.message_id, actor.__post_create__())
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\core\worker.py", line 57, in __post_create__
    await self._supervisor_ref.add_worker(self.address)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\core.pyx", line 545, in __on_receive__
  File "xoscar\core.pyx", line 515, in xoscar.core._BaseActor.__on_receive__
  File "xoscar\core.pyx", line 516, in xoscar.core._BaseActor.__on_receive__
  File "xoscar\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
  File "D:\ANACONDA\envs\llm\lib\site-packages\xinference\core\utils.py", line 25, in wrapped
    ret = await func(*args, **kwargs)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xinference\core\supervisor.py", line 245, in add_worker
    worker_ref = await xo.actor_ref(address=worker_address, uid=WorkerActor.uid())
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\api.py", line 106, in actor_ref
    return await ctx.actor_ref(*args, **kwargs)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\context.py", line 196, in actor_ref
    future = await self._call(actor_ref.address, message, wait=False)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\context.py", line 77, in _call
    return await self._caller.call(
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\core.py", line 180, in call
    client = await self.get_client(router, dest_address)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\core.py", line 68, in get_client
    client = await router.get_client(dest_address, from_who=self)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\router.py", line 143, in get_client
    client = await self._create_client(client_type, address, **kw)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\router.py", line 157, in _create_client
    return await client_type.connect(address, local_address=local_address, **kw)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\communication\socket.py", line 254, in connect
    (reader, writer) = await asyncio.open_connection(host=host, port=port, **kwargs)
  File "D:\ANACONDA\envs\llm\lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "D:\ANACONDA\envs\llm\lib\asyncio\base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "D:\ANACONDA\envs\llm\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "D:\ANACONDA\envs\llm\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\ANACONDA\envs\llm\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\ANACONDA\envs\llm\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "D:\ANACONDA\envs\llm\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
OSError: [address=192.168.1.101:32048, pid=17484] [WinError 1214] 指定的网络名格式无效。

(llm) C:\WINDOWS\system32>xinference-worker -e "http://192.168.1.101:9997"
Traceback (most recent call last):
  File "D:\anaconda\envs\llm\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\llm\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\llm\Scripts\xinference-worker.exe\__main__.py", line 7, in <module>
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\anaconda\envs\llm\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\cmdline.py", line 159, in worker
    main(
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\worker.py", line 61, in main
    loop.run_until_complete(task)
  File "D:\anaconda\envs\llm\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\worker.py", line 50, in _start_worker
    await start_worker_components(
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\deploy\worker.py", line 34, in start_worker_components
    await xo.create_actor(
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\api.py", line 59, in create_actor
    return await ctx.create_actor(actor_cls, *args, uid=uid, address=address, **kwargs)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 143, in create_actor
    return self._process_result_message(result)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 596, in create_actor
    await self._run_coro(message.message_id, actor.__post_create__())
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "D:\anaconda\envs\llm\lib\site-packages\xinference\core\worker.py", line 57, in __post_create__
    await self._supervisor_ref.add_worker(self.address)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "D:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\core.pyx", line 545, in __on_receive__
  File "xoscar\core.pyx", line 515, in xoscar.core._BaseActor.__on_receive__
  File "xoscar\core.pyx", line 516, in xoscar.core._BaseActor.__on_receive__
  File "xoscar\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
  File "D:\ANACONDA\envs\llm\lib\site-packages\xinference\core\utils.py", line 25, in wrapped
    ret = await func(*args, **kwargs)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xinference\core\supervisor.py", line 245, in add_worker
    worker_ref = await xo.actor_ref(address=worker_address, uid=WorkerActor.uid())
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\api.py", line 106, in actor_ref
    return await ctx.actor_ref(*args, **kwargs)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\context.py", line 196, in actor_ref
    future = await self._call(actor_ref.address, message, wait=False)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\context.py", line 77, in _call
    return await self._caller.call(
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\core.py", line 180, in call
    client = await self.get_client(router, dest_address)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\core.py", line 68, in get_client
    client = await router.get_client(dest_address, from_who=self)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\router.py", line 143, in get_client
    client = await self._create_client(client_type, address, **kw)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\router.py", line 157, in _create_client
    return await client_type.connect(address, local_address=local_address, **kw)
  File "D:\ANACONDA\envs\llm\lib\site-packages\xoscar\backends\communication\socket.py", line 254, in connect
    (reader, writer) = await asyncio.open_connection(host=host, port=port, **kwargs)
  File "D:\ANACONDA\envs\llm\lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
  File "D:\ANACONDA\envs\llm\lib\asyncio\base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "D:\ANACONDA\envs\llm\lib\asyncio\base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "D:\ANACONDA\envs\llm\lib\asyncio\base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "D:\ANACONDA\envs\llm\lib\asyncio\proactor_events.py", line 709, in sock_connect
    return await self._proactor.connect(sock, address)
  File "D:\ANACONDA\envs\llm\lib\asyncio\windows_events.py", line 826, in _poll
    value = callback(transferred, key, ov)
  File "D:\ANACONDA\envs\llm\lib\asyncio\windows_events.py", line 613, in finish_connect
    ov.getresult()
OSError: [address=192.168.1.101:25909, pid=10436] [WinError 1214]

6. Minimized code to reproduce the error.

### Expected behavior
when start xinference as worker.

**Comment by pangyoki** [comment]
Thanks for your feedback.

Will you have the same problem if you only use xinference-supervisor and xinference-worker on one machine?

Can you provide a screenshot of your `ipconfig`?
Will there be an error if using this command?
```
xinference-supervisor -H "0.0.0.0"
xinference-worker -e "http://192.168.1.101:[port]"
(`[port]` is the port of the endpoint when the supervisor starts)
```

**Comment by touchtop** [comment]
> 

thanks for your quick response. 
Yes, when I run xinference-supervisor and xinference-worker on one machine, get the same issue. and here is my ipconfig on supervisor machine, just one network adapter.

(llm) C:\Users\shen>ipconfig

Windows IP 配置


以太网适配器 以太网:

   连接特定的 DNS 后缀 . . . . . . . :
   本地链接 IPv6 地址. . . . . . . . : fe80::eebf:33f4:22c3:2108%3
   IPv4 地址 . . . . . . . . . . . . : 192.168.1.101
   子网掩码  . . . . . . . . . . . . : 255.255.255.0
   默认网关. . . . . . . . . . . . . : 192.168.1.1

(llm) C:\Users\shen>xinference-supervisor -H "0.0.0.0"
INFO:xinference:Xinference successfully started. Endpoint: http://0.0.0.0:9997

**Comment by pangyoki** [comment]
You can try to start the `xinference` command directly on a machine, this command will start both supervisor and worker, you can see if there is any problem.

**Comment by pangyoki** [comment]
In addition, I inquired about "[WinError 1214] The format of the specified network name is invalid." related issues, you can try this method to solve it?
https://stackoverflow.com/questions/19095769/simple-web-server-the-format-of-the-specified-network-name-is-invalid
```
netsh http add iplisten 192.168.1.101
```

**Comment by touchtop** [comment]
start only xinference normally, get:
(llm) C:\WINDOWS\system32>xinference
2023-08-22 14:46:16,327 xinference   11712 INFO     Xinference successfully
started. Endpoint: http://127.0.0.1:9997
2023-08-22 14:46:16,328 xinference.core.supervisor 11712 INFO     Worker
127.0.0.1:12492 has been added successfully
2023-08-22 14:46:16,328 xinference.deploy.worker 11712 INFO     Xinference
worker successfully started.

Adding listening IP still can't solve the problem, so I temporarily give up
the multi-node service. :)
Many thanks for your help.



pangyoki ***@***.***> 于2023年8月22日周二 11:09写道：
