### ISSUE TITLE
BUG: Launching a model raises a Type error 

### ISSUE THREAD

**Issue by onesuper** [xorbitsai/inference#436]
### Describe the bug

Fail to launch a model with cli: 

```
xinference launch --model-name "llama-2-chat" --model-format ggmlv3 --size-in-billions 13 -e ${XINFERENCE_SERVER_ENDPOINT}
```

### To Reproduce

0.4.0

```
pdf-chatbot-with-local-llm-app-1  | Traceback (most recent call last):
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/bin/xinference", line 8, in <module>
pdf-chatbot-with-local-llm-app-1  |     sys.exit(cli())
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
pdf-chatbot-with-local-llm-app-1  |     return self.main(*args, **kwargs)
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
pdf-chatbot-with-local-llm-app-1  |     rv = self.invoke(ctx)
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1635, in invoke
pdf-chatbot-with-local-llm-app-1  |     rv = super().invoke(ctx)
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
pdf-chatbot-with-local-llm-app-1  |     return ctx.invoke(self.callback, **ctx.params)
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
pdf-chatbot-with-local-llm-app-1  |     return __callback(*args, **kwargs)
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
pdf-chatbot-with-local-llm-app-1  |     return f(get_current_context(), *args, **kwargs)
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/xinference/deploy/cmdline.py", line 127, in cli
pdf-chatbot-with-local-llm-app-1  |     from .local import main
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/xinference/deploy/local.py", line 19, in <module>
pdf-chatbot-with-local-llm-app-1  |     from .supervisor import start_supervisor_components
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/xinference/deploy/supervisor.py", line 24, in <module>
pdf-chatbot-with-local-llm-app-1  |     from ..core.restful_api import RESTfulAPIActor
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/xinference/core/restful_api.py", line 121, in <module>
pdf-chatbot-with-local-llm-app-1  |     class CreateCompletionRequest(BaseModel):
pdf-chatbot-with-local-llm-app-1  |   File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
pdf-chatbot-with-local-llm-app-1  |   File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
pdf-chatbot-with-local-llm-app-1  |   File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
pdf-chatbot-with-local-llm-app-1  |   File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
pdf-chatbot-with-local-llm-app-1  |   File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
pdf-chatbot-with-local-llm-app-1  |   File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/typing.py", line 852, in __subclasscheck__
pdf-chatbot-with-local-llm-app-1  |     return issubclass(cls, self.__origin__)
pdf-chatbot-with-local-llm-app-1  | TypeError: issubclass() arg 1 must be a class
pdf-chatbot-with-local-llm-app-1  | Traceback (most recent call last):
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
pdf-chatbot-with-local-llm-app-1  |     conn = connection.create_connection(
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
pdf-chatbot-with-local-llm-app-1  |     raise err
pdf-chatbot-with-local-llm-app-1  |   File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
pdf-chatbot-with-local-llm-app-1  |     sock.connect(sa)
pdf-chatbot-with-local-llm-app-1  | ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by onesuper** [comment]
resolved by upgrading to 0.4.1
