### ISSUE TITLE
QUESTION: `ServerClosed: Remote server unixsocket:///1312817152 closed`

### ISSUE THREAD

**Issue by jarvisaoieong** [xorbitsai/inference#458]
### Describe the bug
Can't launch any LLM model with version 0.4.3

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Python version 3.10.13.
1. Xinference version 0.4.3
1. Full stack of the error.
```
$ xinference                          
2023-09-17 14:01:45,161 xinference   10016 INFO     Xinference successfully started. Endpoint: http://127.0.0.1:9997
2023-09-17 14:01:46,394 xinference.core.supervisor 10016 INFO     Worker 127.0.0.1:41695 has been added successfully
2023-09-17 14:01:46,396 xinference.deploy.worker 10016 INFO     Xinference worker successfully started.
tcgetpgrp failed: Not a tty
2023-09-17 14:32:39,700 xinference.model.llm.llm_family 10016 INFO     Caching from Hugging Face: baichuan-inc/Baichuan2-7B-Chat
Fetching 16 files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 18.29it/s]2023-09-17 14:32:45,555 torch.distributed.nn.jit.instantiator 14070 INFO     Created a temporary directory at /tmp/tmp8ypzo0z4
2023-09-17 14:32:45,555 torch.distributed.nn.jit.instantiator 14070 INFO     Writing /tmp/tmp8ypzo0z4/_remote_module_non_scriptable.py
2023-09-17 14:33:10,536 xinference.core.restful_api 10016 ERROR    Remote server unixsocket:///1312817152 closed
Traceback (most recent call last):
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/restful_api.py", line 408, in launch_model
    model_uid = await self._supervisor_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 288, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/supervisor.py", line 221, in launch_builtin_model
    yield _launch_one_model(rep_model_uid)
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/supervisor.py", line 200, in _launch_one_model
    yield worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 396, in _handle_actor_result
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/worker.py", line 180, in launch_builtin_model
    await model_ref.load()
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server unixsocket:///1312817152 closed
2023-09-17 14:33:10,956 xinference.core.restful_api 10016 ERROR    Model not found in the model list, uid: ffae1880-5523-11ee-a211-3b066ebf7ef0
Traceback (most recent call last):
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/restful_api.py", line 365, in describe_model
    return await self._supervisor_ref.describe_model(model_uid)
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/supervisor.py", line 294, in describe_model
    raise ValueError(f"Model not found in the model list, uid: {model_uid}")
ValueError: Model not found in the model list, uid: ffae1880-5523-11ee-a211-3b066ebf7ef0
2023-09-17 14:33:11,005 xinference.core.restful_api 10016 ERROR    Failed to get the model description, detail: Model not found in the model list, uid: ffae1880-5523-11ee-a211-3b066ebf7ef0
Traceback (most recent call last):
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/restful_api.py", line 457, in build_interface
    gr.mount_gradio_app(self._app, interface.build(), f"/{model_uid}")
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/core/chat_interface.py", line 36, in build
    model = self.client.get_model(self.model_uid)
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xinference/client.py", line 877, in get_model
    raise RuntimeError(
RuntimeError: Failed to get the model description, detail: Model not found in the model list, uid: ffae1880-5523-11ee-a211-3b066ebf7ef0
2023-09-17 14:33:12,425 xoscar.backends.pool 10016 ERROR    Monitor sub pool 127.0.0.1:36041 failed
Traceback (most recent call last):
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xoscar/backends/pool.py", line 1402, in monitor_sub_pools
    await self.recover_sub_pool(address)
  File "/home/jarvisaoieong/www/xinference/env/lib/python3.10/site-packages/xoscar/backends/indigen/pool.py", line 436, in recover_sub_pool
    for _, message in self._allocated_actors[address].values():
KeyError: '127.0.0.1:36041'
```
1. Minimized code to reproduce the error.
```
$ python3.10 -m venv env
$ source env/bin/activate
$ pip install "xinference[all]"
$ xinference
```
then launch the `baichuan-2-chat` model with 7B model size and 4bit q from the web ui.

### Expected behavior
Successfully launch the baichuan-2-chat model

**Comment by UranusSeven** [comment]
Hi! The message `Remote server unixsocket:///1312817152 closed` indicates that the subprocess running the model encountered an issue and crashed. This kind of crash is often a result of Out Of Memory (OOM) errors.

For 7B models, ensure there is 13GB of **main memory** available during model loading and 4GB of **GPU memory** for inference.

Also, could you share details of your OS and GPU to help diagnose the issue?
