### ISSUE TITLE
BUG: failed to load models 

### ISSUE THREAD

**Issue by zysno1** [xorbitsai/inference#496]
### Describe the bug
I have built a Docker image myself and deployed xinference on k8s. The homepage can be accessed normally. However, loading the model failed, and the error message is 'not found'. This error is consistently reproducible, making xinference basically unusable.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version. 
3.10
3. The version of xinference you use. 
latest
6. Versions of crucial packages.
7. Full stack of the error.
8. Minimized code to reproduce the error.

### Additional context

dockerfile

FROM python:3.10

ENV XINFERENCE_MODEL_SRC=xorbits

RUN pip install --upgrade pip setuptools -i https://pypi.tuna.tsinghua.edu.cn/simple/

RUN pip install "xinference[all]" -i https://pypi.tuna.tsinghua.edu.cn/simple/

EXPOSE 9997

CMD ["/usr/local/bin/xinference","-H 0.0.0.0", "-p 9997"]

<img width="1389" alt="image" src="https://github.com/xorbitsai/inference/assets/8028258/28f20220-b9ef-49ca-82e8-7dd838f44f11">
<img width="322" alt="image" src="https://github.com/xorbitsai/inference/assets/8028258/da26ad3d-c40e-4be7-8062-cab5425b6f84">
<img width="1114" alt="image" src="https://github.com/xorbitsai/inference/assets/8028258/1740511a-b483-4ea6-8246-61c08c937617">

**Comment by UranusSeven** [comment]
Hi, thanks for reporting this issue!

The error message `Not found` on the webpage indicates there's something wrong when loading the model. I see you have attached part of the server side logs, could you attach the full logs?

**Comment by UranusSeven** [comment]
The problem seems to be relavent to `XINFERENCE_MODEL_SRC=xorbits`. This env var force xinference downloading models from our s3 bucket, which is not accessible right now.

We've added support of downloading from modelscope, and you can enable this feature by`XINFERENCE_MODEL_SRC=modelscope`.

**Comment by Bojun-Feng** [comment]
I also encountered this issue, in my case the issue originates from launching the model in the Supervisor

<details>
  <summary>Log from DEBUG mode</summary>
  
  ```
2023-09-28 09:19:53,235 xinference.core.supervisor 62053 DEBUG    Enter launch_builtin_model, model_uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf, model_name: gpt-2, model_size: 1, model_format: ggmlv3, quantization: none, replica: 1
2023-09-28 09:19:53,236 xinference.core.worker 62053 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x14b40e570>,), kwargs: {}
2023-09-28 09:19:53,236 xinference.core.worker 62053 DEBUG    Leave get_model_count, elapsed time: 0 ms
2023-09-28 09:19:53,236 xinference.core.worker 62053 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x14b40e570>,), kwargs: {'model_uid': '1783edb0-5e0a-11ee-8b3d-af674e7ac1bf-1-0', 'model_name': 'gpt-2', 'model_size_in_billions': 1, 'model_format': 'ggmlv3', 'quantization': 'none', 'model_type': 'LLM', 'n_gpu': 'auto'}
2023-09-28 09:19:53,237 xinference.core.supervisor 62053 DEBUG    Enter is_local_deployment, args: (<xinference.core.supervisor.SupervisorActor object at 0x14b40c290>,), kwargs: {}
2023-09-28 09:19:53,237 xinference.core.supervisor 62053 DEBUG    Leave is_local_deployment, elapsed time: 0 ms
2023-09-28 09:19:53,245 xinference.model.llm.llm_family 62053 INFO     Caching from Hugging Face: marella/gpt-2-ggml
2023-09-28 09:19:53,296 urllib3.connectionpool 62053 DEBUG    Starting new HTTPS connection (1): huggingface.co:443
2023-09-28 09:19:53,357 urllib3.connectionpool 62053 DEBUG    https://huggingface.co:443 "HEAD /marella/gpt-2-ggml/resolve/main/ggml-model.bin HTTP/1.1" 302 0
2023-09-28 09:19:53,381 xinference.model.llm.core 62053 DEBUG    Launching 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf-1-0 with CtransformersModel
2023-09-28 09:19:53,386 xinference.core.supervisor 62053 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x14b40c290>, '1783edb0-5e0a-11ee-8b3d-af674e7ac1bf'), kwargs: {'suppress_exception': True}
2023-09-28 09:19:53,386 xinference.core.supervisor 62053 DEBUG    Leave terminate_model, elapsed time: 0 ms
2023-09-28 09:19:53,386 xinference.core.restful_api 62053 ERROR    'MainActorPool' object has no attribute 'append_sub_pool'
Traceback (most recent call last):
  File "/Users/bojunfeng/cs/inference/xinference/core/restful_api.py", line 408, in launch_model
    model_uid = await self._supervisor_ref.launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 288, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/Users/bojunfeng/cs/inference/xinference/core/supervisor.py", line 227, in launch_builtin_model
    yield _launch_one_model(rep_model_uid)
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/Users/bojunfeng/cs/inference/xinference/core/supervisor.py", line 206, in _launch_one_model
    yield worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 396, in _handle_actor_result
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/Users/bojunfeng/cs/inference/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 182, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(model_uid, n_gpu=n_gpu)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 111, in _create_subpool
    sub_pool_address = await self._main_pool.append_sub_pool(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainActorPool' object has no attribute 'append_sub_pool'
2023-09-28 09:19:53,442 urllib3.connectionpool 62053 DEBUG    Starting new HTTP connection (1): 127.0.0.1:9997
2023-09-28 09:19:53,443 xinference.core.supervisor 62053 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x14b40c290>, '1783edb0-5e0a-11ee-8b3d-af674e7ac1bf'), kwargs: {}
2023-09-28 09:19:53,443 xinference.core.restful_api 62053 ERROR    Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf
Traceback (most recent call last):
  File "/Users/bojunfeng/cs/inference/xinference/core/restful_api.py", line 365, in describe_model
    return await self._supervisor_ref.describe_model(model_uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/Users/bojunfeng/cs/inference/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/supervisor.py", line 300, in describe_model
    raise ValueError(f"Model not found in the model list, uid: {model_uid}")
ValueError: Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf
2023-09-28 09:19:53,443 urllib3.connectionpool 62053 DEBUG    http://127.0.0.1:9997 "GET /v1/models/1783edb0-5e0a-11ee-8b3d-af674e7ac1bf HTTP/1.1" 400 89
2023-09-28 09:19:53,443 xinference.core.restful_api 62053 ERROR    Failed to get the model description, detail: Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf
Traceback (most recent call last):
  File "/Users/bojunfeng/cs/inference/xinference/core/restful_api.py", line 457, in build_interface
    gr.mount_gradio_app(self._app, interface.build(), f"/{model_uid}")
                                   ^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/chat_interface.py", line 36, in build
    model = self.client.get_model(self.model_uid)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/client.py", line 877, in get_model
    raise RuntimeError(
RuntimeError: Failed to get the model description, detail: Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf

  ```
</details>

The core issue seems to be in the launch model part of the code:
```
  File "/Users/bojunfeng/cs/inference/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 182, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(model_uid, n_gpu=n_gpu)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 111, in _create_subpool
    sub_pool_address = await self._main_pool.append_sub_pool(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainActorPool' object has no attribute 'append_sub_pool'
```

Since the model is not launched, later requests to create a gradio page for the model also fails, resulting in a "model not found" error page instead of the gradio interface as expected.

**Comment by YinSonglin1997** [comment]
> The problem seems to be relavent to `XINFERENCE_MODEL_SRC=xorbits`. This env var force xinference downloading models from our s3 bucket, which is not accessible right now.
> 
> We've added support of downloading from modelscope, and you can enable this feature by`XINFERENCE_MODEL_SRC=modelscope`.

我在constants.py中设置参数XINFERENCE_MODEL_SRC=“modelscope”，但是Xinference的界面似乎并没有按照llm_family_modelscope.json改变，请问还需要设置什么参数吗？
