### ISSUE TITLE
BUG: Failed to launch model

### ISSUE THREAD

**Issue by Bojun-Feng** [xorbitsai/inference#501]
### Describe the bug
Unable to use Dashboard to launch model, using api also fails

### To Reproduce
Python 3.11.4
Newest version of Xinference

### Expected behavior
When launching model from dashboard, new Gradio page should start

### Additional context

<details>
  <summary>Log from DEBUG mode</summary>
  
  ```
2023-09-28 09:19:53,235 xinference.core.supervisor 62053 DEBUG    Enter launch_builtin_model, model_uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf, model_name: gpt-2, model_size: 1, model_format: ggmlv3, quantization: none, replica: 1
2023-09-28 09:19:53,236 xinference.core.worker 62053 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x14b40e570>,), kwargs: {}
2023-09-28 09:19:53,236 xinference.core.worker 62053 DEBUG    Leave get_model_count, elapsed time: 0 ms
2023-09-28 09:19:53,236 xinference.core.worker 62053 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x14b40e570>,), kwargs: {'model_uid': '1783edb0-5e0a-11ee-8b3d-af674e7ac1bf-1-0', 'model_name': 'gpt-2', 'model_size_in_billions': 1, 'model_format': 'ggmlv3', 'quantization': 'none', 'model_type': 'LLM', 'n_gpu': 'auto'}
2023-09-28 09:19:53,237 xinference.core.supervisor 62053 DEBUG    Enter is_local_deployment, args: (<xinference.core.supervisor.SupervisorActor object at 0x14b40c290>,), kwargs: {}
2023-09-28 09:19:53,237 xinference.core.supervisor 62053 DEBUG    Leave is_local_deployment, elapsed time: 0 ms
2023-09-28 09:19:53,245 xinference.model.llm.llm_family 62053 INFO     Caching from Hugging Face: marella/gpt-2-ggml
2023-09-28 09:19:53,296 urllib3.connectionpool 62053 DEBUG    Starting new HTTPS connection (1): huggingface.co:443
2023-09-28 09:19:53,357 urllib3.connectionpool 62053 DEBUG    https://huggingface.co:443 "HEAD /marella/gpt-2-ggml/resolve/main/ggml-model.bin HTTP/1.1" 302 0
2023-09-28 09:19:53,381 xinference.model.llm.core 62053 DEBUG    Launching 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf-1-0 with CtransformersModel
2023-09-28 09:19:53,386 xinference.core.supervisor 62053 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x14b40c290>, '1783edb0-5e0a-11ee-8b3d-af674e7ac1bf'), kwargs: {'suppress_exception': True}
2023-09-28 09:19:53,386 xinference.core.supervisor 62053 DEBUG    Leave terminate_model, elapsed time: 0 ms
2023-09-28 09:19:53,386 xinference.core.restful_api 62053 ERROR    'MainActorPool' object has no attribute 'append_sub_pool'
Traceback (most recent call last):
  File "/Users/bojunfeng/cs/inference/xinference/core/restful_api.py", line 408, in launch_model
    model_uid = await self._supervisor_ref.launch_builtin_model(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 288, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/Users/bojunfeng/cs/inference/xinference/core/supervisor.py", line 227, in launch_builtin_model
    yield _launch_one_model(rep_model_uid)
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/Users/bojunfeng/cs/inference/xinference/core/supervisor.py", line 206, in _launch_one_model
    yield worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 396, in _handle_actor_result
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/Users/bojunfeng/cs/inference/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 182, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(model_uid, n_gpu=n_gpu)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 111, in _create_subpool
    sub_pool_address = await self._main_pool.append_sub_pool(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainActorPool' object has no attribute 'append_sub_pool'
2023-09-28 09:19:53,442 urllib3.connectionpool 62053 DEBUG    Starting new HTTP connection (1): 127.0.0.1:9997
2023-09-28 09:19:53,443 xinference.core.supervisor 62053 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x14b40c290>, '1783edb0-5e0a-11ee-8b3d-af674e7ac1bf'), kwargs: {}
2023-09-28 09:19:53,443 xinference.core.restful_api 62053 ERROR    Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf
Traceback (most recent call last):
  File "/Users/bojunfeng/cs/inference/xinference/core/restful_api.py", line 365, in describe_model
    return await self._supervisor_ref.describe_model(model_uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/Users/bojunfeng/cs/inference/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/supervisor.py", line 300, in describe_model
    raise ValueError(f"Model not found in the model list, uid: {model_uid}")
ValueError: Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf
2023-09-28 09:19:53,443 urllib3.connectionpool 62053 DEBUG    http://127.0.0.1:9997 "GET /v1/models/1783edb0-5e0a-11ee-8b3d-af674e7ac1bf HTTP/1.1" 400 89
2023-09-28 09:19:53,443 xinference.core.restful_api 62053 ERROR    Failed to get the model description, detail: Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf
Traceback (most recent call last):
  File "/Users/bojunfeng/cs/inference/xinference/core/restful_api.py", line 457, in build_interface
    gr.mount_gradio_app(self._app, interface.build(), f"/{model_uid}")
                                   ^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/chat_interface.py", line 36, in build
    model = self.client.get_model(self.model_uid)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/client.py", line 877, in get_model
    raise RuntimeError(
RuntimeError: Failed to get the model description, detail: Model not found in the model list, uid: 1783edb0-5e0a-11ee-8b3d-af674e7ac1bf

  ```
</details>

The core issue seems to be in the launch model part of the code:
```
  File "/Users/bojunfeng/cs/inference/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 182, in launch_builtin_model
    subpool_address, devices = await self._create_subpool(model_uid, n_gpu=n_gpu)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bojunfeng/cs/inference/xinference/core/worker.py", line 111, in _create_subpool
    sub_pool_address = await self._main_pool.append_sub_pool(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainActorPool' object has no attribute 'append_sub_pool'
```

Since the model is not launched, later requests to create a gradio page for the model also fails, resulting in a "model not found" page instead of the gradio interface as expected.

**Comment by Bojun-Feng** [comment]
Just realized this is a duplicate for #496, closing down
