### ISSUE TITLE
BUG: 'BaichuanTokenizer' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by glfruit** [xorbitsai/inference#505]
### Describe the bug
property 'sp_model' is used in its parent class PreTrainedTokenizer's init method before it's initialized

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version: 3.9.18
2. The version of xinference you use: 0.5.2
3. Versions of crucial packages.
4. Full stack of the error.
```
2023-10-05 21:03:27,278 xinference.core.restful_api 94357 ERROR    [address=0.0.0.0:63187, pid=94412] 'BaichuanTokenizer' object has no attribute 'sp_model'
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/restful_api.py", line 404, in launch_model
    model_uid = await self._supervisor_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 288, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/supervisor.py", line 227, in launch_builtin_model
    yield _launch_one_model(rep_model_uid)
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 422, in _handle_actor_result
  File "xoscar/core.pyx", line 465, in _run_actor_async_generator
  File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/supervisor.py", line 206, in _launch_one_model
    yield worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
  File "xoscar/core.pyx", line 396, in _handle_actor_result
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/worker.py", line 187, in launch_builtin_model
    await model_ref.load()
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/model.py", line 117, in load
    self._model.load()
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/model/llm/pytorch/core.py", line 193, in load
    self._model, self._tokenizer = load_compress_model(
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/model/llm/pytorch/compression.py", line 113, in load_compress_model
    tokenizer = AutoTokenizer.from_pretrained(
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
    return cls._from_pretrained(
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/Users/glfruit/.cache/huggingface/modules/transformers_modules/baichuan-2-chat-pytorch-7b/tokenization_baichuan.py", line 75, in __init__
    super().__init__(
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 366, in __init__
    self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
    current_vocab = self.get_vocab().copy()
  File "/Users/glfruit/.cache/huggingface/modules/transformers_modules/baichuan-2-chat-pytorch-7b/tokenization_baichuan.py", line 109, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
  File "/Users/glfruit/.cache/huggingface/modules/transformers_modules/baichuan-2-chat-pytorch-7b/tokenization_baichuan.py", line 105, in vocab_size
    return self.sp_model.get_piece_size()
AttributeError: [address=0.0.0.0:63187, pid=94412] 'BaichuanTokenizer' object has no attribute 'sp_model'
2023-10-05 21:03:27,288 xinference.core.restful_api 94357 ERROR    Model not found in the model list, uid: 9115de70-637f-11ee-a91b-95113f049f98
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/restful_api.py", line 361, in describe_model
    return await self._supervisor_ref.describe_model(model_uid)
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/llm-lab/lib/python3.9/site-packages/xinference/core/supervisor.py", line 300, in describe_model
    raise ValueError(f"Model not found in the model list, uid: {model_uid}")
ValueError: Model not found in the model list, uid: 9115de70-637f-11ee-a91b-95113f049f98
2023-10-05 21:03:27,289 xinference.core.restful_api 94357 ERROR    Failed to get the model description, detail: Model not found in the model list, uid: 9115de70-637f-11ee-a91b-95113f049f98
```

5. Minimized code to reproduce the error.

### Expected behavior
baichun-2-model should be loaded successfully.

### Additional context
After looking into source code in tokenization_baichuan.py, I think this problem is caused by an initialization sequence error in class BaichuanTokenizer's __init__method:
```python3
def __init__(
        self,
        vocab_file,
        unk_token="<unk>",
        bos_token="<s>",
        eos_token="</s>",
        pad_token=None,
        sp_model_kwargs: Optional[Dict[str, Any]] = None,
        add_bos_token=True,
        add_eos_token=False,
        clean_up_tokenization_spaces=False,
        **kwargs,
    ):
        self.sp_model_kwargs = {} if sp_model_kwargs is None else sp_model_kwargs
        bos_token = AddedToken(bos_token, lstrip=False, rstrip=False) if isinstance(bos_token, str) else bos_token
        eos_token = AddedToken(eos_token, lstrip=False, rstrip=False) if isinstance(eos_token, str) else eos_token
        unk_token = AddedToken(unk_token, lstrip=False, rstrip=False) if isinstance(unk_token, str) else unk_token
        pad_token = AddedToken(pad_token, lstrip=False, rstrip=False) if isinstance(pad_token, str) else pad_token
        super().__init__(
            bos_token=bos_token,
            eos_token=eos_token,
            unk_token=unk_token,
            pad_token=pad_token,
            add_bos_token=add_bos_token,
            add_eos_token=add_eos_token,
            sp_model_kwargs=self.sp_model_kwargs,
            clean_up_tokenization_spaces=clean_up_tokenization_spaces,
            **kwargs,
        )
        self.vocab_file = vocab_file
        self.add_bos_token = add_bos_token
        self.add_eos_token = add_eos_token
        self.sp_model = spm.SentencePieceProcessor(**self.sp_model_kwargs)
        self.sp_model.Load(vocab_file)
```

from the code above, we can see BaichuanTokenizer's parent class PretrainedTokenizer's __init__ is called before property sp_model is initialized, but PretrainedTrokenizer's __init__ method uses sp_model in its implementation, so the code crashes and an AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model' is reported.

**Comment by UranusSeven** [comment]
Hi! Thanks for reporting this issue. The error seems to be inside of `transformers`. Could you provide your version of `transformers` so we can reproduce this problem?

**Comment by glfruit** [comment]
my transformers version is 4.34.0

<img width="1241" alt="image" src="https://github.com/xorbitsai/inference/assets/3939154/54f011dc-bf88-42e1-a751-754a4bbb730b">

**Comment by Cyrusky** [comment]
I got the same issue. did you figure it out?

**Comment by Cyrusky** [comment]
@glfruit I figure it out when I downgrade the transformers to `4.33.1`. Good luck to you.

**Comment by Cyrusky** [comment]
You can also see: https://github.com/huggingface/transformers/issues/26340#issuecomment-1731394278

**Comment by glfruit** [comment]
@Cyrusky I did as what you said, but got another error: "TypeError: [address=0.0.0.0:55168, pid=20573] Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype."

**Comment by UranusSeven** [comment]
Baichuan models uses fp16, which is not supported on macOS. The error `Trying to convert BFloat16 to the MPS backend but it does not have support for that dtype.` is expected.

Check out the xinference's doc about built-in models: https://inference.readthedocs.io/en/latest/models/builtin/baichuan-2.html#models-builtin-baichuan-2

It is suggested to use GGML models on macOS. For example, [vicuna-v1.3](https://inference.readthedocs.io/en/latest/models/builtin/vicuna-v1.3.html) and [chatglm2](https://inference.readthedocs.io/en/latest/models/builtin/chatglm2.html) are great choices.

If the model you need is not built-in, you can download it and register it as a new model. You can do it via the web UI or using xinference client: https://inference.readthedocs.io/en/latest/models/custom.html
