### ISSUE TITLE
BUG: Unable to list or load embedding models

### ISSUE THREAD

**Issue by iguy0** [xorbitsai/inference#511]
### Describe the bug
When attempting to list models as like in https://inference.readthedocs.io/en/latest/models/builtin/index.html#embedding-models
using: 
`xinference registrations`
No embedding models are listed, just models of type "LLM" 

The embedding models are also not listed in the GUI.

When trying to launch an embedding model using:
`xinference launch --model-name bge-base-en --model-type embedding`

The following error occurs:
```
$ xinference launch --model-name bge-base-en   --model-type embedding
Traceback (most recent call last):
  File "/home/v2/miniconda3/envs/inference/bin/xinference", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/v2/miniconda3/envs/inference/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v2/miniconda3/envs/inference/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/v2/miniconda3/envs/inference/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v2/miniconda3/envs/inference/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v2/miniconda3/envs/inference/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/v2/miniconda3/envs/inference/lib/python3.11/site-packages/xinference/deploy/cmdline.py", line 413, in model_launch
    model_uid = client.launch_model(
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/v2/miniconda3/envs/inference/lib/python3.11/site-packages/xinference/client.py", line 816, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: EmbeddingModel.__init__() got an unexpected keyword argument 'trust_remote_code'
```

 
### To Reproduce
To help us to reproduce this bug, please provide information below:

```
conda create -n inference python=3.11.4
conda activate inference
pip install "xinference[all]"
xinference -H 0.0.0.0
xinference launch --model-name bge-base-en --model-type embedding
```

### Expected behavior

1 - Models of type "EMBEDDING" be listed when running: xinference registrations and also via GUI
2 - The embedding models listed in the webpage start properly without the error.

**Comment by aresnow1** [comment]
I've reproduced this issue and will fix it soon.
