### ISSUE TITLE
BUG: After downloaded, always show "Not found"

### ISSUE THREAD

**Issue by Minamiyama** [xorbitsai/inference#526]
the logs shown as below: 
2023-10-11 11:44:55 2023-10-11 03:44:55,093 xinference.core.restful_api 1 ERROR    [address=0.0.0.0:37531, pid=200] 'BaichuanTokenizer' object has no attribute 'sp_model'
2023-10-11 11:44:55 Traceback (most recent call last):
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/restful_api.py", line 404, in launch_model
2023-10-11 11:44:55     model_uid = await self._supervisor_ref.launch_builtin_model(
2023-10-11 11:44:55   File "xoscar/core.pyx", line 288, in __pyx_actor_method_wrapper
2023-10-11 11:44:55   File "xoscar/core.pyx", line 422, in _handle_actor_result
2023-10-11 11:44:55   File "xoscar/core.pyx", line 465, in _run_actor_async_generator
2023-10-11 11:44:55   File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
2023-10-11 11:44:55   File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/supervisor.py", line 227, in launch_builtin_model
2023-10-11 11:44:55     yield _launch_one_model(rep_model_uid)
2023-10-11 11:44:55   File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
2023-10-11 11:44:55   File "xoscar/core.pyx", line 422, in _handle_actor_result
2023-10-11 11:44:55   File "xoscar/core.pyx", line 465, in _run_actor_async_generator
2023-10-11 11:44:55   File "xoscar/core.pyx", line 466, in xoscar.core._BaseActor._run_actor_async_generator
2023-10-11 11:44:55   File "xoscar/core.pyx", line 471, in xoscar.core._BaseActor._run_actor_async_generator
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/supervisor.py", line 206, in _launch_one_model
2023-10-11 11:44:55     yield worker_ref.launch_builtin_model(
2023-10-11 11:44:55   File "xoscar/core.pyx", line 476, in xoscar.core._BaseActor._run_actor_async_generator
2023-10-11 11:44:55   File "xoscar/core.pyx", line 396, in _handle_actor_result
2023-10-11 11:44:55   File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
2023-10-11 11:44:55   File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/utils.py", line 27, in wrapped
2023-10-11 11:44:55     ret = await func(*args, **kwargs)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/worker.py", line 187, in launch_builtin_model
2023-10-11 11:44:55     await model_ref.load()
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
2023-10-11 11:44:55     return self._process_result_message(result)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
2023-10-11 11:44:55     raise message.as_instanceof_cause()
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
2023-10-11 11:44:55     result = await self._run_coro(message.message_id, coro)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
2023-10-11 11:44:55     return await coro
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xoscar/api.py", line 306, in __on_receive__
2023-10-11 11:44:55     return await super().__on_receive__(message)  # type: ignore
2023-10-11 11:44:55   File "xoscar/core.pyx", line 558, in __on_receive__
2023-10-11 11:44:55   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
2023-10-11 11:44:55   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
2023-10-11 11:44:55   File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/model.py", line 117, in load
2023-10-11 11:44:55     self._model.load()
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 205, in load
2023-10-11 11:44:55     self._model, self._tokenizer = self._load_model(kwargs)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/model/llm/pytorch/baichuan.py", line 54, in _load_model
2023-10-11 11:44:55     tokenizer = AutoTokenizer.from_pretrained(
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 738, in from_pretrained
2023-10-11 11:44:55     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2045, in from_pretrained
2023-10-11 11:44:55     return cls._from_pretrained(
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
2023-10-11 11:44:55     tokenizer = cls(*init_inputs, **init_kwargs)
2023-10-11 11:44:55   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-chat-pytorch-13b/tokenization_baichuan.py", line 75, in __init__
2023-10-11 11:44:55     super().__init__(
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 366, in __init__
2023-10-11 11:44:55     self._add_tokens(self.all_special_tokens_extended, special_tokens=True)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/transformers/tokenization_utils.py", line 462, in _add_tokens
2023-10-11 11:44:55     current_vocab = self.get_vocab().copy()
2023-10-11 11:44:55   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-chat-pytorch-13b/tokenization_baichuan.py", line 109, in get_vocab
2023-10-11 11:44:55     vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
2023-10-11 11:44:55   File "/root/.cache/huggingface/modules/transformers_modules/baichuan-2-chat-pytorch-13b/tokenization_baichuan.py", line 105, in vocab_size
2023-10-11 11:44:55     return self.sp_model.get_piece_size()
2023-10-11 11:44:55 AttributeError: [address=0.0.0.0:37531, pid=200] 'BaichuanTokenizer' object has no attribute 'sp_model'
2023-10-11 11:44:55 2023-10-11 03:44:55,102 xinference.core.restful_api 1 ERROR    Model not found in the model list, uid: 88d2e420-67e8-11ee-989a-75cb3bc35c4e
2023-10-11 11:44:55 Traceback (most recent call last):
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/restful_api.py", line 361, in describe_model
2023-10-11 11:44:55     return await self._supervisor_ref.describe_model(model_uid)
2023-10-11 11:44:55   File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
2023-10-11 11:44:55   File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/utils.py", line 27, in wrapped
2023-10-11 11:44:55     ret = await func(*args, **kwargs)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/supervisor.py", line 300, in describe_model
2023-10-11 11:44:55     raise ValueError(f"Model not found in the model list, uid: {model_uid}")
2023-10-11 11:44:55 ValueError: Model not found in the model list, uid: 88d2e420-67e8-11ee-989a-75cb3bc35c4e
2023-10-11 11:44:55 2023-10-11 03:44:55,103 xinference.core.restful_api 1 ERROR    Failed to get the model description, detail: Model not found in the model list, uid: 88d2e420-67e8-11ee-989a-75cb3bc35c4e
2023-10-11 11:44:55 Traceback (most recent call last):
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/restful_api.py", line 453, in build_interface
2023-10-11 11:44:55     gr.mount_gradio_app(self._app, interface.build(), f"/{model_uid}")
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/core/chat_interface.py", line 36, in build
2023-10-11 11:44:55     model = self.client.get_model(self.model_uid)
2023-10-11 11:44:55   File "/usr/local/lib/python3.10/site-packages/xinference/client.py", line 883, in get_model
2023-10-11 11:44:55     raise RuntimeError(
2023-10-11 11:44:55 RuntimeError: Failed to get the model description, detail: Model not found in the model list, uid: 88d2e420-67e8-11ee-989a-75cb3bc35c4e

the browser show as: 
![image](https://github.com/xorbitsai/inference/assets/918617/97a20d22-f7f0-48ec-8fc8-e595e43a5cd0)

**Comment by UranusSeven** [comment]
Hi! Thanks for reporting this issue.

This is an known problem caused by `transformers`. You can solve this by downgrading the `transformers` to `4.33.1`.

See #505 for more details.

**Comment by Minamiyama** [comment]
> Hi! Thanks for reporting this issue.
> 
> This is an known problem caused by `transformers`. You can solve this by downgrading the `transformers` to `4.33.1`.
> 
> See #505 for more details.

thank you, the problem is solved ^_^
