### ISSUE TITLE
BUG: deallocating on web UI errored.

### ISSUE THREAD

**Issue by qinxuye** [xorbitsai/inference#541]
### Describe the bug

I launched two models, and I deallocated one model, an error happends.

```
2023-10-16 14:12:22,105 xinference.core.restful_api 64171 ERROR    Task <Task pending name='Task-195' coro=<RequestResponseCycle.run_asgi() running at /Users/xuyeqin/miniconda3/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py:428> cb=[set.discard()]> got Future <Future pending> attached to a different loop
Traceback (most recent call last):
  File "/Users/xuyeqin/Workspace/inference/xinference/core/restful_api.py", line 369, in list_models
    return await self._supervisor_ref.list_models()
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
  File "/Users/xuyeqin/miniconda3/lib/python3.9/asyncio/locks.py", line 14, in __aenter__
    await self.acquire()
  File "/Users/xuyeqin/miniconda3/lib/python3.9/asyncio/locks.py", line 120, in acquire
    await fut
RuntimeError: Task <Task pending name='Task-195' coro=<RequestResponseCycle.run_asgi() running at /Users/xuyeqin/miniconda3/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py:428> cb=[set.discard()]> got Future <Future pending> attached to a different loop
```

**Comment by aresnow1** [comment]
Closed by #546
