### ISSUE TITLE
BUG: Yi-200k model deploy error

### ISSUE THREAD

**Issue by waltcow** [xorbitsai/inference#633]
### Describe the bug

```





2023-11-10 10:31:03,333 xinference.core.supervisor 2833164 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f4699fffd80>, 'LLM'), kwargs: {'detailed': True}
2023-11-10 10:31:03,337 xinference.model.llm.llm_family 2833164 WARNING  Cache /root/.xinference/cache/Yi-200k-pytorch-6b exists, but it was from modelscope
2023-11-10 10:31:03,337 xinference.model.llm.llm_family 2833164 WARNING  Cache /root/.xinference/cache/Yi-200k-pytorch-34b exists, but it was from modelscope
2023-11-10 10:31:03,338 xinference.core.supervisor 2833164 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2023-11-10 10:31:16,962 xinference.core.supervisor 2833164 DEBUG    Enter launch_builtin_model, model_uid: 3994f740-7f71-11ee-abb4-d35f488c61a0, model_name: Yi-200k, model_size: 34, model_format: pytorch, quantization: 4-bit, replica: 1
2023-11-10 10:31:16,962 xinference.core.worker 2833164 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7f4699fffd30>,), kwargs: {}
2023-11-10 10:31:16,962 xinference.core.worker 2833164 DEBUG    Leave get_model_count, elapsed time: 0 s
2023-11-10 10:31:16,962 xinference.core.worker 2833164 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7f4699fffd30>,), kwargs: {'model_uid': '3994f740-7f71-11ee-abb4-d35f488c61a0-1-0', 'model_name': 'Yi-200k', 'model_size_in_billions': 34, 'model_format': 'pytorch', 'quantization': '4-bit', 'model_type': 'LLM', 'n_gpu': 'auto', 'request_limits': None}
2023-11-10 10:31:16,962 xinference.core.worker 2833164 DEBUG    GPU selected: [0] for model 3994f740-7f71-11ee-abb4-d35f488c61a0-1-0
2023-11-10 10:31:18,051 - modelscope - INFO - PyTorch version 2.1.0 Found.
2023-11-10 10:31:18,051 - modelscope - INFO - Loading ast index from /root/.cache/modelscope/ast_indexer
2023-11-10 10:31:18,063 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 5ce6449a40b865d4f6545992938fd560 and a total number of 945 components indexed
2023-11-10 10:31:18,076 xinference.model.llm.llm_family 2833164 INFO     Caching from Hugging Face: 01-ai/Yi-34B-200K
2023-11-10 10:31:18,076 xinference.model.llm.llm_family 2833164 WARNING  Cache /root/.xinference/cache/Yi-200k-pytorch-34b exists, but it was from modelscope
2023-11-10 10:31:18,076 xinference.model.llm.core 2833164 DEBUG    Launching 3994f740-7f71-11ee-abb4-d35f488c61a0-1-0 with PytorchModel
Loading checkpoint shards:   0%|                                                     | 0/7 [00:00<?, ?it/s]
2023-11-10 10:31:20,606 xinference.core.worker 2833164 ERROR    Failed to load model 3994f740-7f71-11ee-abb4-d35f488c61a0-1-0
Traceback (most recent call last):
  File "/opt/inference/xinference/core/worker.py", line 316, in launch_builtin_model
    await model_ref.load()
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/opt/inference/xinference/core/model.py", line 166, in load
    self._model.load()
  File "/opt/inference/xinference/model/llm/pytorch/core.py", line 182, in load
    self._model, self._tokenizer = self._load_model(**kwargs)
  File "/opt/inference/xinference/model/llm/pytorch/core.py", line 101, in _load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3548, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/modeling_utils.py", line 467, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
FileNotFoundError: [address=0.0.0.0:35755, pid=2833244] No such file or directory: "/root/.xinference/cache/Yi-200k-pytorch-34b/model-00001-of-00007.safetensors"
2023-11-10 10:31:20,886 xinference.core.supervisor 2833164 DEBUG    Enter terminate_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7f4699fffd80>, '3994f740-7f71-11ee-abb4-d35f488c61a0'), kwargs: {'suppress_exception': True}
2023-11-10 10:31:20,887 xinference.core.supervisor 2833164 DEBUG    Leave terminate_model, elapsed time: 0 s
2023-11-10 10:31:20,888 xinference.api.restful_api 2833071 ERROR    [address=0.0.0.0:35755, pid=2833244] No such file or directory: "/root/.xinference/cache/Yi-200k-pytorch-34b/model-00001-of-00007.safetensors"
Traceback (most recent call last):
  File "/opt/inference/xinference/api/restful_api.py", line 408, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/opt/inference/xinference/core/supervisor.py", line 398, in launch_builtin_model
    await _launch_one_model(rep_model_uid)
  File "/opt/inference/xinference/core/supervisor.py", line 367, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/opt/inference/xinference/core/utils.py", line 27, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/inference/xinference/core/worker.py", line 316, in launch_builtin_model
    await model_ref.load()
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/opt/inference/xinference/core/model.py", line 166, in load
    self._model.load()
  File "/opt/inference/xinference/model/llm/pytorch/core.py", line 182, in load
    self._model, self._tokenizer = self._load_model(**kwargs)
  File "/opt/inference/xinference/model/llm/pytorch/core.py", line 101, in _load_model
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3175, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3548, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/root/miniconda3/envs/infer/lib/python3.10/site-packages/transformers/modeling_utils.py", line 467, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
FileNotFoundError: [address=0.0.0.0:35755, pid=2833244] No such file or directory: "/root/.xinference/cache/Yi-200k-pytorch-34b/model-00001-of-00007.safetensors"
```

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by qinxuye** [comment]
@aresnow1 could you help the user to address this issue?

**Comment by aresnow1** [comment]
How did you download your models?

**Comment by waltcow** [comment]
modelscope do not provide models list is not same as huggingface

**Comment by aresnow1** [comment]
Yi-200k is supported with modelscope, have you tested set environment `XINFERENCE_MODEL_SRC=modelscope` before starting xinfernece?

**Comment by waltcow** [comment]
> Yi-200k is supported with modelscope, have you tested set environment `XINFERENCE_MODEL_SRC=modelscope` before starting xinfernece?

environment var is already set

**Comment by aresnow1** [comment]
Could you provide your command for launching Yi-200k?
