### ISSUE TITLE
QUESTION： How can I register and run a embedding model

### ISSUE THREAD

**Issue by gqchen-dz** [xorbitsai/inference#664]
I am new for infercne.
I want to regist a custom embedding model ( I downloaded it  from modelscop.cn) and run it from the web UI.
But I cannt register it from the "register model" page . 
And I try to do it  from CLI :  xinference register -t embedding -f /llm/bge-large-zh-v1.5/config.json -p , then , I get  error like this :
**************************************************************************
2023-11-17 22:14:17,498 - modelscope - INFO - PyTorch version 2.0.1 Found.
2023-11-17 22:14:17,501 - modelscope - INFO - Loading ast index from /root/.cach                   e/modelscope/ast_indexer
2023-11-17 22:14:17,540 - modelscope - INFO - Loading done! Current index file v                   ersion is 1.9.4, with md5 b542cb69632ed25605a7646a09b9831c and a total number of                    945 components indexed
Traceback (most recent call last):
  File "/root/miniconda3/envs/xinference_env/bin/xinference", line 8, in <module                   >
    sys.exit(cli())
  File "/root/miniconda3/envs/xinference_env/lib/python3.10/site-packages/click/                   core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/envs/xinference_env/lib/python3.10/site-packages/click/                   core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/envs/xinference_env/lib/python3.10/site-packages/click/                   core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/envs/xinference_env/lib/python3.10/site-packages/click/                   core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/envs/xinference_env/lib/python3.10/site-packages/click/                   core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/envs/xinference_env/lib/python3.10/site-packages/xinfer                   ence/deploy/cmdline.py", line 281, in register_model
    client.register_model(
  File "/root/miniconda3/envs/xinference_env/lib/python3.10/site-packages/xinfer                   ence/client/restful/restful_client.py", line 701, in register_model
    raise RuntimeError(
RuntimeError: Failed to register model, detail: [address=0.0.0.0:23986, pid=1830                   76] Unsupported model type: embedding
**************************************************************
I searched in Issues and "https://inference.readthedocs.io/" ,  but it has not been resolved .

**Comment by aresnow1** [comment]
Thanks for your report, customized embedding model hasn't been supported, it will be available in the next version.

**Comment by gqchen-dz** [comment]
thanks ,  wait for the release.
