### ISSUE TITLE
QUESTIONAttributeError: [address=0.0.0.0:33767, pid=5848] Model model_format='pytorch' model_size_in_billions=13 quantizations=['4-bit', '8-bit', 'none'] model_id='FlagAlpha/Llama2-Chinese-13b-Chat' model_hub='huggingface' model_uri='file:///root/chinese-llama2' model_revision=None is not for chat.

### ISSUE THREAD

**Issue by ghkl98** [xorbitsai/inference#685]
我想部署自己的本地模型，写的model.json如下
{
    "version": 1,
    "context_length": 2048,
    "model_name": "customer-llama-2",
    "model_lang": [
      "en",
      "zh"
    ],
    "model_ability": [
      "chat"
    ],
    "model_specs": [
      {
        "model_format": "pytorch",
        "model_size_in_billions": 13,
        "quantizations": [
          "4-bit",
          "8-bit",
          "none"
        ],
        "model_id": "FlagAlpha/Llama2-Chinese-13b-Chat",
        "model_uri": "file:///root/chinese-llama2"
      }
    ]
  }
在xinference可以运行：
![image](https://github.com/xorbitsai/inference/assets/105712475/cc1d4605-6e21-46a5-bbc5-4c722810d702)

但是在dify上就会报错AttributeError: [address=0.0.0.0:33767, pid=5848] Model model_format='pytorch' model_size_in_billions=13 quantizations=['4-bit', '8-bit', 'none'] model_id='FlagAlpha/Llama2-Chinese-13b-Chat' model_hub='huggingface' model_uri='file:///root/chinese-llama2' model_revision=None is not for chat.

**Comment by ghkl98** [comment]
Traceback (most recent call last):
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xinference/api/restful_api.py", line 353, in describe_model
    data = await (await self._get_supervisor_ref()).describe_model(model_uid)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xinference/core/utils.py", line 30, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xinference/core/supervisor.py", line 474, in describe_model
    raise ValueError(f"Model not found in the model list, uid: {model_uid}")
ValueError: [address=0.0.0.0:48099, pid=44353] Model not found in the model list, uid: 1e3681f8-8c14-11ee-a696-b36a74d71b49
2023-11-26 04:56:03,922 xinference.api.restful_api 44285 ERROR    [address=0.0.0.0:35837, pid=44729] Model model_format='pytorch' model_size_in_billions=13 quantizations=['none'] model_id='FlagAlpha/Llama2-Chinese-13b-Chat' model_hub='huggingface' model_uri='file:///root/chinese-llama2' model_revision=None is not for chat.
Traceback (most recent call last):
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xinference/api/restful_api.py", line 791, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xinference/core/utils.py", line 30, in wrapped
    ret = await func(*args, **kwargs)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xinference/core/model.py", line 67, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/root/miniconda3/envs/py39_mhy/lib/python3.9/site-packages/xinference/core/model.py", line 236, in chat
    raise AttributeError(f"Model {self._model.model_spec} is not for chat.")
AttributeError: [address=0.0.0.0:35837, pid=44729] Model model_format='pytorch' model_size_in_billions=13 quantizations=['none'] model_id='FlagAlpha/Llama2-Chinese-13b-Chat' model_hub='huggingface' model_uri='file:///root/chinese-llama2' model_revision=None is not for chat.

**Comment by aresnow1** [comment]
确定注册的时候选的是 chat 吗，看上去是模型只有 generate 能力，没有 chat 能力。

**Comment by faroasis** [comment]
我也遇到这个问题，model_ability只保留chat就好了

**Comment by faroasis** [comment]
不过现在有个问题是中文会乱码...
![image](https://github.com/xorbitsai/inference/assets/245267/077f25fb-b853-4619-aac2-fb84ff2ef638)

**Comment by faroasis** [comment]
> 这个模型的链接发一下？ @faroasis

https://huggingface.co/FlagAlpha/Llama2-Chinese-7b-Chat

**Comment by aresnow1** [comment]
roles 改成 ["Human", "Assistant"] 这个试一下

**Comment by faroasis** [comment]
> roles 改成 ["Human", "Assistant"] 这个试一下 @faroasis

问题不在这里，应该是LlamaTokenizer词表太小，中文被切分了，如果是对整个output_ids做decode就是完整的中文字符。目前按照stream_interval输出的方式就是会把中文字符切碎。
`
 LlamaTokenizer(name_or_path='C:\llama2\cn_chat', vocab_size=32000, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False), 'eos_token': AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False), 'unk_token': AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False)}, clean_up_tokenization_spaces=False)
`


另外，我想要以4bit加载模型的话，需要修改model/llm/pytorch/core.py 384行
`
if self._device == "cuda":# and self._is_linux():
`
至少在我的机器上是没问题的，win10 pro，torch201+cuda 117。

@aresnow1

**Comment by xiaolibuzai-ovo** [comment]
> > roles 改成 ["Human", "Assistant"] 这个试一下 @faroasis
> 
> 问题不在这里，应该是LlamaTokenizer词表太小，中文被切分了，如果是对整个output_ids做decode就是完整的中文字符。目前按照stream_interval输出的方式就是会把中文字符切碎。 `LlamaTokenizer(name_or_path='C:\llama2\cn_chat', vocab_size=32000, model_max_length=1000000000000000019884624838656, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'bos_token': AddedToken("<s>", rstrip=False, lstrip=False, single_word=False, normalized=False), 'eos_token': AddedToken("</s>", rstrip=False, lstrip=False, single_word=False, normalized=False), 'unk_token': AddedToken("<unk>", rstrip=False, lstrip=False, single_word=False, normalized=False)}, clean_up_tokenization_spaces=False)`
> 
> 另外，我想要以4bit加载模型的话，需要修改model/llm/pytorch/core.py 384行 `if self._device == "cuda":# and self._is_linux():` 至少在我的机器上是没问题的，win10 pro，torch201+cuda 117。
> 
> @aresnow1

请问在哪里配置LlamaTokenizer呢？我在Xinference自定义模型配置中并没有找到，我也遇到了中文乱码的问题🥹

**Comment by xiaolibuzai-ovo** [comment]
> LlamaTokenizer

请问下是哪里的源码呢

**Comment by aresnow1** [comment]
谢谢分享，如果愿意的话可以提个 PR 帮忙修复下吗？

faroasis ***@***.***>于2023年12月1日 周五20:27写道：
