### ISSUE TITLE
BUG: expected mat1 and mat2 to have the same dtype, but got: c10::Half != signed char

### ISSUE THREAD

**Issue by codingl2k1** [xorbitsai/inference#737]
### Describe the bug

torch: 2.1.1
model: llama-2-chat 13b 8bit 
```python
RuntimeError: [address=0.0.0.0:37195, pid=525824] expected mat1 and mat2 to have the same dtype, but got: c10::Half != signed char
Traceback (most recent call last):
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/utils.py", line 512, in async_iteration
    return await iterator.__anext__()
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/utils.py", line 612, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/chat_interface.py", line 438, in _stream_fn
    first_response = await async_iteration(generator)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/utils.py", line 512, in async_iteration
    return await iterator.__anext__()
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/utils.py", line 505, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/gradio/utils.py", line 488, in run_sync_iterator_async
    return next(iterator)
  File "/home/codingl2k1/inference/xinference/core/chat_interface.py", line 111, in generate_wrapper
    for chunk in model.chat(
  File "/home/codingl2k1/inference/xinference/client/common.py", line 49, in streaming_response_iterator
    raise Exception(str(error))
Exception: [address=0.0.0.0:37195, pid=525824] expected mat1 and mat2 to have the same dtype, but got: c10::Half != signed char
```

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by playmobil** [comment]
we encountered the same problem
