### ISSUE TITLE
BUG: ChatGLM3 function call not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by codingl2k1** [xorbitsai/inference#770]
### To Reproduce
To help us to reproduce this bug, please provide information below:

```python
Traceback (most recent call last):
  File "/home/codingl2k1/inference/xinference/api/restful_api.py", line 825, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/home/codingl2k1/inference/xinference/core/utils.py", line 33, in wrapped
    ret = await func(*args, **kwargs)
  File "/home/codingl2k1/inference/xinference/core/model.py", line 77, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/home/codingl2k1/inference/xinference/core/model.py", line 274, in chat
    return await self._call_wrapper(_wrapper)
  File "/home/codingl2k1/inference/xinference/core/model.py", line 211, in _call_wrapper
    return await asyncio.to_thread(_wrapper)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/codingl2k1/inference/xinference/core/model.py", line 262, in _wrapper
    getattr(self._model, "chat")(prompt, *args, **kwargs)
  File "/home/codingl2k1/inference/xinference/model/llm/pytorch/chatglm.py", line 120, in chat
    msg = self._model.chat(self._tokenizer, prompt, [tools], **kwargs)
  File "/home/codingl2k1/.pyenv/versions/3.9.18/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/codingl2k1/.cache/huggingface/modules/transformers_modules/chatglm3-pytorch-6b/modeling_chatglm.py", line 1039, in chat
    response, history = self.process_response(response, history)
  File "/home/codingl2k1/.cache/huggingface/modules/transformers_modules/chatglm3-pytorch-6b/modeling_chatglm.py", line 1003, in process_response
    metadata, content = response.split("\n", maxsplit=1)
ValueError: [address=localhost:36161, pid=648444] not enough values to unpack (expected 2, got 1)
```

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

**Comment by shendepuren** [comment]
1. python version: 3.10.6
2. xinference version: 0.12.3
3.  
![image](https://github.com/xorbitsai/inference/assets/8724079/1296d560-4760-41db-99e0-3fd5beedb000)
4. 
![image](https://github.com/xorbitsai/inference/assets/8724079/a70b15ff-aa42-4e3f-885e-7a85a1ca543e)
`{
    "version": 1,
    "context_length": 2048,
    "model_name": "chatglm3-6b-base",
    "model_lang": [
        "en",
        "zh"
    ],
    "model_ability": [
        "generate",
        "chat"
    ],
    "model_description": "This is a custom model description.",
    "model_family": "chatglm3",
    "model_specs": [
        {
            "model_format": "pytorch",
            "model_size_in_billions": 6,
            "quantizations": [
                "none"
            ],
            "model_id": null,
            "model_hub": "huggingface",
            "model_uri": "/data/ai_server/hub/chatglm3-6b-base",
            "model_revision": null
        }
    ],
    "prompt_style": {
        "style_name": "CHATGLM3",
        "system_prompt": "",
        "roles": [
            "user",
            "assistant"
        ],
        "intra_message_sep": "",
        "inter_message_sep": "",
        "stop": [
            "<|user|>",
            "<|observation|>"
        ],
        "stop_token_ids": [
            64795,
            64797,
            2
        ]
    },
    "is_builtin": false
}`
