### ISSUE TITLE
BUG: chat command line failed for qwen model

### ISSUE THREAD

**Issue by qinxuye** [xorbitsai/inference#789]
### Describe the bug

Chat command line failed for qwen model.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

```shell
xinference chat --model-uid qwen
```

Output

```
2023-12-19 17:07:02,753 - modelscope - INFO - PyTorch version 2.2.0.dev20231204 Found.
2023-12-19 17:07:02,754 - modelscope - INFO - Loading ast index from /Users/xuyeqin/.cache/modelscope/ast_indexer
2023-12-19 17:07:02,782 - modelscope - INFO - Loading done! Current index file version is 1.9.4, with md5 70c2815eaedd8c3a09b7ad23c82b8c1c and a total number of 945 components indexed
User: 42这个数字有啥特别的
Assistant: Traceback (most recent call last):
  File "/Users/xuyeqin/miniconda3/bin/xinference", line 33, in <module>
    sys.exit(load_entry_point('xinference', 'console_scripts', 'xinference')())
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/xuyeqin/Workspace/inference/xinference/deploy/cmdline.py", line 770, in model_chat
    loop.run_until_complete(task)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/xuyeqin/Workspace/inference/xinference/deploy/cmdline.py", line 740, in chat_internal
    async for chunk in model.chat(
  File "/Users/xuyeqin/Workspace/inference/xinference/client/oscar/actor_client.py", line 189, in chat
    return self._isolation.call(coro)
  File "/Users/xuyeqin/Workspace/inference/xinference/isolation.py", line 44, in call
    return fut.result()
  File "/Users/xuyeqin/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/Users/xuyeqin/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/Users/xuyeqin/miniconda3/lib/python3.9/site-packages/xoscar/api.py", line 306, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
  File "/Users/xuyeqin/Workspace/inference/xinference/core/utils.py", line 33, in wrapped
    ret = await func(*args, **kwargs)
  File "/Users/xuyeqin/Workspace/inference/xinference/core/model.py", line 77, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/Users/xuyeqin/Workspace/inference/xinference/core/model.py", line 274, in chat
    return await self._call_wrapper(_wrapper)
  File "/Users/xuyeqin/Workspace/inference/xinference/core/model.py", line 214, in _call_wrapper
    return await asyncio.to_thread(_wrapper)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/Users/xuyeqin/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/xuyeqin/Workspace/inference/xinference/core/model.py", line 262, in _wrapper
    getattr(self._model, "chat")(prompt, *args, **kwargs)
TypeError: [address=127.0.0.1:49793, pid=61755] chat() takes from 2 to 4 positional arguments but 5 were given
```

**Comment by qinxuye** [comment]
This issue can be addressed after switching to llamacpp for qwen.
