### ISSUE TITLE
RuntimeError: Cluster is not available after multiple attempts

### ISSUE THREAD

**Issue by weipeng008005** [xorbitsai/inference#799]
### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
2. The version of xinference you use.
3. Versions of crucial packages.
4. Full stack of the error.
5. Minimized code to reproduce the error.

### Additional context

以使用pip install "xinference[all]"配置环境
运行xinference-local报错如下：
2023-12-22 16:03:51,162 xinference.core.supervisor 25692 INFO     Xinference supervisor 127.0.0.1:36225 started
2023-12-22 16:03:51,166 xinference.core.worker 25692 INFO     Xinference worker 127.0.0.1:36225 started
2023-12-22 16:03:51,167 xinference.core.worker 25692 INFO     Purge cache directory: C:\Users\weipeng\.xinference\cache
Process Process-1:
Traceback (most recent call last):
  File "D:\Anaconda\envs\xinf\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "D:\Anaconda\envs\xinf\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda\envs\xinf\lib\site-packages\xinference\deploy\local.py", line 71, in run
    loop.run_until_complete(task)
  File "D:\Anaconda\envs\xinf\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "D:\Anaconda\envs\xinf\lib\site-packages\xinference\deploy\local.py", line 52, in _start_local_cluster
    await start_worker_components(
  File "D:\Anaconda\envs\xinf\lib\site-packages\xinference\deploy\worker.py", line 39, in start_worker_components
    await xo.create_actor(
  File "D:\Anaconda\envs\xinf\lib\site-packages\xoscar\api.py", line 59, in create_actor
    return await ctx.create_actor(actor_cls, *args, uid=uid, address=address, **kwargs)
  File "D:\Anaconda\envs\xinf\lib\site-packages\xoscar\backends\context.py", line 143, in create_actor
    return self._process_result_message(result)
  File "D:\Anaconda\envs\xinf\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Anaconda\envs\xinf\lib\site-packages\xoscar\backends\pool.py", line 596, in create_actor
    await self._run_coro(message.message_id, actor.__post_create__())
  File "D:\Anaconda\envs\xinf\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "D:\Anaconda\envs\xinf\lib\site-packages\xinference\core\worker.py", line 114, in __post_create__
    loop.add_signal_handler(
  File "D:\Anaconda\envs\xinf\lib\asyncio\events.py", line 553, in add_signal_handler
    raise NotImplementedError
NotImplementedError: [address=127.0.0.1:36225, pid=25692]
Traceback (most recent call last):
  File "D:\Anaconda\envs\xinf\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda\envs\xinf\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\xinf\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda\envs\xinf\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "D:\Anaconda\envs\xinf\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "D:\Anaconda\envs\xinf\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Anaconda\envs\xinf\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "D:\Anaconda\envs\xinf\lib\site-packages\xinference\deploy\cmdline.py", line 167, in local
    start_local_cluster(log_level=log_level, host=host, port=port)
  File "D:\Anaconda\envs\xinf\lib\site-packages\xinference\deploy\cmdline.py", line 80, in start_local_cluster
    main(
  File "D:\Anaconda\envs\xinf\lib\site-packages\xinference\deploy\local.py", line 91, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts

**Comment by ChengjieLi28** [comment]
@weipeng008005 更改这两个环境变量，默认都是3，可以调大一点，例如这样启动：
```
XINFERENCE_HEALTH_CHECK_INTERVAL=10 XINFERENCE_HEALTH_CHECK_ATTEMPTS=6 xinference-local
```

**Comment by weipeng008005** [comment]
> @weipeng008005 更改这两个环境变量，默认都是3，可以调大一点，例如这样启动：
> 
> ```
> XINFERENCE_HEALTH_CHECK_INTERVAL=10 XINFERENCE_HEALTH_CHECK_ATTEMPTS=6 xinference-local
> ```

'XINFERENCE_HEALTH_CHECK_INTERVAL' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by weipeng008005** [comment]
> @weipeng008005 更改这两个环境变量，默认都是3，可以调大一点，例如这样启动：
> 
> ```
> XINFERENCE_HEALTH_CHECK_INTERVAL=10 XINFERENCE_HEALTH_CHECK_ATTEMPTS=6 xinference-local
> ```

windows10
python版本3.10
xinference版本0.7.3

**Comment by ChengjieLi28** [comment]
> > @weipeng008005 更改这两个环境变量，默认都是3，可以调大一点，例如这样启动：
> > ```
> > XINFERENCE_HEALTH_CHECK_INTERVAL=10 XINFERENCE_HEALTH_CHECK_ATTEMPTS=6 xinference-local
> > ```
> 
> 'XINFERENCE_HEALTH_CHECK_INTERVAL' 不是内部或外部命令，也不是可运行的程序 或批处理文件。

Windows环境设置这两个环境变量，我发的这个是Linux的使用方式，Windows如下：
```
set XINFERENCE_HEALTH_CHECK_INTERVAL=10
set XINFERENCE_HEALTH_CHECK_ATTEMPTS=6
xinference-local
```

**Comment by weipeng008005** [comment]
> xinference-local

嗯，我意识到了。按照这个方式启动依然报一样的错

**Comment by ChengjieLi28** [comment]
> > xinference-local
> 
> 嗯，我意识到了。按照这个方式启动依然报一样的错

是我们的一个bug，我们稍后发个hotfix 版本，多谢反馈。

**Comment by weipeng008005** [comment]
> > > xinference-local
> > 
> > 
> > 嗯，我意识到了。按照这个方式启动依然报一样的错
> 
> 是我们的一个bug，我们稍后发个hotfix 版本，多谢反馈。

好的，谢谢

**Comment by weipeng008005** [comment]
> > > xinference-local
> > 
> > 
> > 嗯，我意识到了。按照这个方式启动依然报一样的错
> 
> 是我们的一个bug，我们稍后发个hotfix 版本，多谢反馈。

请问我可以怎么使用这个版本？

**Comment by ChengjieLi28** [comment]
> > > > xinference-local
> > > 
> > > 
> > > 嗯，我意识到了。按照这个方式启动依然报一样的错
> > 
> > 
> > 是我们的一个bug，我们稍后发个hotfix 版本，多谢反馈。
> 
> 请问我可以怎么使用这个版本？

等我们发布版本，届时`pip install -U xinference`即可

**Comment by ChengjieLi28** [comment]
@weipeng008005 你可以更新xinference了：
```
pip install -U xinference
```

**Comment by elepherai** [comment]
@ChengjieLi28 你好，我用的是最新的0.8.0，windows 11，python3.11.7，也会出现这个问题，请问如何解决？

**Comment by jingyaogong** [comment]
@ChengjieLi28 我用的是最新的0.8.2，windows 11，python3.10，也会出现这个问题，请问如何解决？

**Comment by hao203** [comment]
wsl2 ,也是同样的问题。

**Comment by Victor94-king** [comment]
请问下作者解决了这个问题吗。。。 同样在wins上不行

**Comment by nanggn** [comment]
win10也是报同样的错，请问怎么解决？

**Comment by Friman04** [comment]
一样的

**Comment by zaoqishibing** [comment]
win11，Python3.10.11  同样问题:
(xinference) C:\Users\Admin>xinference-local --host 0.0.0.0 --port 9997
2024-07-07 18:59:46,003 xinference.core.supervisor 23192 INFO     Xinference supervisor 0.0.0.0:33311 started
2024-07-07 18:59:46,049 xinference.core.worker 23192 INFO     Starting metrics export server at 0.0.0.0:None
2024-07-07 18:59:46,049 xinference.core.worker 23192 INFO     Checking metrics export server...
2024-07-07 18:59:50,987 xinference.core.worker 23192 INFO     Metrics server is started at: http://0.0.0.0:51445
2024-07-07 18:59:50,987 xinference.core.worker 23192 INFO     Xinference worker 0.0.0.0:33311 started
2024-07-07 18:59:50,987 xinference.core.worker 23192 INFO     Purge cache directory: E:\xinference\cache
Traceback (most recent call last):
  File "E:\conda\envs\xinference\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\conda\envs\xinference\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\conda\envs\xinference\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "E:\conda\envs\xinference\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "E:\conda\envs\xinference\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "E:\conda\envs\xinference\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\conda\envs\xinference\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "E:\conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 225, in local
    start_local_cluster(
  File "E:\conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 112, in start_local_cluster
    main(
  File "E:\conda\envs\xinference\lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts

**Comment by qinxuye** [comment]
Windows 上不支持用 0.0.0.0 启动，请使用 IP。

**Comment by wangsen1110** [comment]
将 0.0.0.0 改成 127.0.0.1    即可正常启动，如下所示：
 xinference-local  --host 127.0.0.1 --port 9997

**Comment by colorfulandcjy0806** [comment]
如果是Windows系统，用这个命令启动就可以了
`xinference-local --host 127.0.0.1 --port 9997`

**Comment by fengyunzaidushi** [comment]
> 如果是Windows系统，用这个命令启动就可以了 `xinference-local --host 127.0.0.1 --port 9997`

确实能解决。
环境：
win11
conda 3.10.14

**Comment by Weishaoya** [comment]
我建议作者解决windows电脑不能0.0.0.0启动这个bug, 因为相当一部分人都是windows电脑办公，而他们的linux系统基本都是windows电脑通过vmware分出来的，无法使用gpu。当把项目如ragflow部署到lvmware的linux上时，为了使用windows上的gpu时，可以通过0.0.0.0在windows上启动，ragflow便可以使用gpu进行推理。而然，由于这个bug的存在，这将不能实现

**Comment by 824562329** [comment]
(xinference) F:\>xinference-local --host 127.0.0.1 --port 9997
Traceback (most recent call last):
  File "C:\Users\Administrator\.conda\envs\xinference\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\.conda\envs\xinference\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\.conda\envs\xinference\Scripts\xinference-local.exe\__main__.py", line 7, in <module>
    sys.exit(local())
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 224, in local
    start_local_cluster(
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\xinference\deploy\cmdline.py", line 111, in start_local_cluster
    main(
  File "C:\Users\Administrator\.conda\envs\xinference\lib\site-packages\xinference\deploy\local.py", line 122, in main
    raise RuntimeError("Cluster is not available after multiple attempts")
RuntimeError: Cluster is not available after multiple attempts
2024-09-04 16:31:28,532 xinference.core.supervisor 15280 INFO     Xinference supervisor 127.0.0.1:43731 started
2024-09-04 16:31:28,555 xinference.core.worker 15280 INFO     Starting metrics export server at 127.0.0.1:None
2024-09-04 16:31:28,559 xinference.core.worker 15280 INFO     Checking metrics export server...
2024-09-04 16:31:30,984 xinference.core.worker 15280 INFO     Metrics server is started at: http://127.0.0.1:22015
2024-09-04 16:31:30,985 xinference.core.worker 15280 INFO     Purge cache directory: C:\Users\Administrator\.xinference\cache
2024-09-04 16:31:30,986 xinference.core.worker 15280 INFO     Connected to supervisor as a fresh worker
2024-09-04 16:31:31,137 xinference.core.worker 15280 INFO     Xinference worker 127.0.0.1:43731 started
