### ISSUE TITLE
BUG: launch method exception

### ISSUE THREAD

**Issue by auxpd** [xorbitsai/inference#807]
### Describe the bug
The `launch` method of XInference encounters an error when loading embeddings, images, and reranking because it does not account for the scenario where `size_in_billions` is `None`.

### To Reproduce
$ xinference launch --model-name bge-reranker-large --model-type rerank -u af828dd0-8e0a-1101-93cf-437b86dbc17b
Traceback (most recent call last):
  File "/home/auxpd/miniconda3/envs/xinference/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/home/auxpd/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/auxpd/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/auxpd/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/auxpd/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/auxpd/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/auxpd/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 501, in model_launch
    size_in_billions if "_" in size_in_billions else int(size_in_billions)
TypeError: argument of type 'NoneType' is not iterable

### Expected behavior
successful loading

**Comment by auxpd** [comment]
I'm a bit curious, why is there a need to perform type conversion here?

**Comment by ChengjieLi28** [comment]
@auxpd . Thanks for reporting. This is a bug for registering non-LLM models. We will fix for the next release. For now, you can specify any value for this option.
