### ISSUE TITLE
自定义模型Launch后无法在控制台删除，命令行也无法删除

### ISSUE THREAD

**Issue by guyfar** [xorbitsai/inference#870]
### Describe the bug
自定义模型Launch后无法在控制台删除，命令行也无法删除且报错

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Python 3.10.12
2. xinference, version 0.7.5
3.命令行执行xinference list命令信息如下：
root@ai-gpu:/opt/devlop# xinference list
UID              Type    Name             Format      Size (in billions)  Quantization
---------------  ------  ---------------  --------  --------------------  --------------
baichuan-2-chat  LLM     baichuan-2-chat  pytorch                     13  8-bit
UID                                             Type       Name                                         Dimensions
----------------------------------------------  ---------  -----------------------------------------  ------------
text2vec-large-chinese                          embedding  text2vec-large-chinese                             1024
bge-base-zh-v1.5                                embedding  bge-base-zh-v1.5                                    768
damo/nlp_corom_sentence-embedding_chinese-base  embedding  nlp_corom_sentence-embedding_chinese-base           768

4.命令行执行停止命令报错如下：
root@ai-gpu:/opt/devlop# xinference terminate --model-uid "damo/nlp_corom_sentence-embedding_chinese-base"
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xinference/deploy/cmdline.py", line 631, in model_terminate
    client.terminate_model(model_uid=model_uid)
  File "/usr/local/lib/python3.10/dist-packages/xinference/client/restful/restful_client.py", line 771, in terminate_model
    raise RuntimeError(
RuntimeError: Failed to terminate model, detail: Not Found 

### Additional context
服务器日志没有任何异常

### 原因猜测
可能是我的uid中有/引起的，我的uid是`damo/nlp_corom_sentence-embedding_chinese-base  embedding`

**Comment by HelloBroTan** [comment]
It‘s still A PROBLEM!问题依旧存在

root@1b7180fa8866:/opt/inference# xinference terminate --endpoint http://0.0.0.0:9997 --model-uid 'Qwen/Qwen3.5-35B-A3B'
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/xinference/deploy/cmdline.py", line 1217, in model_terminate
    client.terminate_model(model_uid=model_uid)
  File "/usr/local/lib/python3.12/dist-packages/xinference/client/restful/restful_client.py", line 1328, in terminate_model
    raise RuntimeError(
RuntimeError: Failed to terminate model, detail: Not Found
root@1b7180fa8866:/opt/inference# xinference terminate --endpoint http://0.0.0.0:41295 --model-uid 'Qwen/Qwen3.5-35B-A3B'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1450, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 336, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 305, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 644, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/urllib3/connection.py", line 461, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 1450, in getresponse
    response.begin()
  File "/usr/lib/python3.12/http/client.py", line 336, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/http/client.py", line 305, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/xinference/deploy/cmdline.py", line 1214, in model_terminate
    client = RESTfulClient(base_url=endpoint, api_key=api_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/xinference/client/restful/restful_client.py", line 1085, in __init__
    self._check_cluster_authenticated()
  File "/usr/local/lib/python3.12/dist-packages/xinference/client/restful/restful_client.py", line 1115, in _check_cluster_authenticated
    response = self.session.get(url)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/requests/adapters.py", line 659, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
root@1b7180fa8866:/opt/inference# xinference list
UID                   Type    Name     Format      Size (in billions)  Quantization
--------------------  ------  -------  --------  --------------------  --------------
Qwen/Qwen3.5-35B-A3B  LLM     qwen3.5  pytorch                    397  none

root@1b7180fa8866:/opt/inference# xinference list
UID                   Type    Name     Format      Size (in billions)  Quantization
--------------------  ------  -------  --------  --------------------  --------------
Qwen/Qwen3.5-35B-A3B  LLM     qwen3.5  pytorch                    397  none

root@1b7180fa8866:/opt/inference# curl -X 'POST' 'http://0.0.0.0:9997/v1/completions' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{ "model": "Qwen/Qwen3.5-35B-A3B", "prompt":"世界上最大的动物是什么？","max_tokens": 128,"temperature": 0.7}'
{"id":"001447ca-39ad-11f1-af01-aaafc711df1d","object":"text_completion","created":1776355062,"model":"Qwen/Qwen3.5-35B-A3B","choices":[{"text":"\n\nA. 蓝鲸\nB. 大象\nC. 长颈鹿\n\n<think>\n\n</think>\n\n目前已知地球上**最大**的动物是**蓝鲸**（Blue Whale）。\n\n蓝鲸不仅是现存最大的动物，也是地球历史上已知存在过的最庞大的生物。成年蓝鲸的体长可达 30 米以上，体重可达 150 至 180 吨。相比之下，陆地上的动物如大象（最大约 6-8 吨）和长颈鹿（最高但体重仅约 1-2 吨）在体型和重量上都远不及蓝鲸","index":0,"logprobs":null,"finish_reason":"length"}],"usage":{"prompt_tokens":4,"completion_tokens":128,"total_tokens":132}}root@1b7180fa8866:/opt/inference# 
root@1**6:/opt/inference# pip show xinference
Name: xinference
Version: 2.4.0
Summary: Model Serving Made Easy
Home-page: https://github.com/xorbitsai/inference
Author: Qin Xuye
Author-email: qinxuye@xprobe.io
License: Apache License 2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: aiohttp, aioprometheus, async-timeout, bcrypt, click, fastapi, gradio, huggingface-hub, modelscope, nvidia-ml-py, openai, peft, pillow, pydantic, pynvml, python-jose, requests, setproctitle, sse_starlette, tabulate, timm, torch, tqdm, typing_extensions, uv, uvicorn, xoscar
Required-by: 
root@1**6:/opt/inference# pip show vllm      
Name: vllm
Version: 0.17.1
Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
Home-page: https://github.com/vllm-project/vllm
Author: vLLM Team
Author-email: 
License-Expression: Apache-2.0
Location: /usr/local/lib/python3.12/dist-packages
Requires: aiohttp, anthropic, blake3, cachetools, cbor2, cloudpickle, compressed-tensors, depyf, diskcache, einops, fastapi, filelock, flashinfer-python, gguf, grpcio, grpcio-reflection, ijson, kaldi-native-fbank, lark, llguidance, lm-format-enforcer, mcp, mistral_common, model-hosting-container-standards, msgspec, ninja, numba, numpy, nvidia-cudnn-frontend, nvidia-cutlass-dsl, openai, openai-harmony, opencv-python-headless, opentelemetry-api, opentelemetry-exporter-otlp, opentelemetry-sdk, opentelemetry-semantic-conventions-ai, outlines_core, partial-json-parser, pillow, prometheus-fastapi-instrumentator, prometheus_client, protobuf, psutil, py-cpuinfo, pybase64, pydantic, python-json-logger, pyyaml, pyzmq, quack-kernels, ray, regex, requests, sentencepiece, setproctitle, setuptools, six, tiktoken, tokenizers, torch, torchaudio, torchvision, tqdm, transformers, typing_extensions, watchfiles, xgrammar
Required-by: 
root@1**6:/opt/inference# pip show torch
Name: torch
Version: 2.10.0+cu129
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org
Author: 
Author-email: PyTorch Team <packages@pytorch.org>
License: BSD-3-Clause
Location: /usr/local/lib/python3.12/dist-packages
Requires: cuda-bindings, filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-cufile-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvshmem-cu12, nvidia-nvtx-cu12, setuptools, sympy, triton, typing-extensions
Required-by: accelerate, autoawq, bitsandbytes, chattts, compressed-tensors, conformer, controlnet_aux, curated-transformers, DeepCache, ema-pytorch, encodec, FlagEmbedding, flash_attn, flashinfer-python, julius, kokoro, lightning, lmcache, nixl-cu12, optimum, outlines, peft, pytorch-lightning, quack-kernels, runai-model-streamer, sentence-transformers, sglang, silero-vad, spacy-curated-transformers, tensorizer, timm, torch_c_dlpack_ext, torchaudio, torchdiffeq, torchmetrics, torchvision, vector-quantize-pytorch, vllm, vocos, x-transformers, xgrammar, xinference
root@1**6:/opt/inference# xinference terminate --endpoint http://0.0.0.0:9997 --model-uid ["Qwen/Qwen3.5-35B-A3B"]
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/xinference/deploy/cmdline.py", line 1217, in model_terminate
    client.terminate_model(model_uid=model_uid)
  File "/usr/local/lib/python3.12/dist-packages/xinference/client/restful/restful_client.py", line 1328, in terminate_model
    raise RuntimeError(
RuntimeError: Failed to terminate model, detail: Not Found
root@1**6:/opt/inference# xinference terminate --endpoint http://0.0.0.0:9997 --model-uid ["Qwen/Qwen3.5-35B-A3B"]
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/xinference/deploy/cmdline.py", line 1217, in model_terminate
    client.terminate_model(model_uid=model_uid)
  File "/usr/local/lib/python3.12/dist-packages/xinference/client/restful/restful_client.py", line 1328, in terminate_model
    raise RuntimeError(
RuntimeError: Failed to terminate model, detail: Not Found
root@1**6:/opt/inference# xinference terminate --endpoint http://0.0.0.0:9997 --model-uid ["Qwen/Qwen3.5-35B-A3B"]
Traceback (most recent call last):
  File "/usr/local/bin/xinference", line 6, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1485, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1406, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1873, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 1269, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/click/core.py", line 824, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/xinference/deploy/cmdline.py", line 1217, in model_terminate
    client.terminate_model(model_uid=model_uid)
  File "/usr/local/lib/python3.12/dist-packages/xinference/client/restful/restful_client.py", line 1328, in terminate_model
    raise RuntimeError(
RuntimeError: Failed to terminate model, detail: Not Found
