### ISSUE TITLE
BUG: Deployment on k8s pod results in an error

### ISSUE THREAD

**Issue by Bojun-Feng** [xorbitsai/inference#873]
### Describe the bug
Can not load model on k8s pod

### To Reproduce
```
from xinference.client import Client
model_name = "openhermes-2.5"
model_format = "ggufv2"
client = Client("http://localhost:9997")
model_uid = client.launch_model(
    model_name=model_name,
    model_format=model_format,
)
```
this is on k8s pod with 32GB RAM.
```
This code crashes with:
2024-01-08 16:21:41,325 xinference.model.llm.llm_family 146 INFO     Caching from Hugging Face: TheBloke/OpenHermes-2.5-Mistral-7B-GGUF
openhermes-2.5-mistral-7b.Q2_K.gguf: 100%|████████████████████████████████████████████████████████████████████████████| 3.08G/3.08G [00:12<00:00, 255MB/s]
2024-01-08 16:21:54,100 xinference.core.worker 146 ERROR    Failed to load model openhermes-2.5-1-0
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/xinference/core/worker.py", line 381, in launch_builtin_model
    await model_ref.load()
  File "/usr/local/lib/python3.11/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server unixsocket:///19136512 closed
```

### Expected behavior
Model should be loaded properly. Any suggestion on what might have caused the error would be much appreciated.

**Comment by aresnow1** [comment]
Any other error messages? looks like an OOM error.

**Comment by Bojun-Feng** [comment]
This is the only error message. I also thought it is OOM but the model is a 7B Q_2K, so it should have plenty of space. Any suggestion on other potential sources of error would be appreciated.

**Comment by aresnow1** [comment]
- Check the version of llama-cpp-python
- Does the k8s cluster have monitoring? Check the memory usage when crash occurs.

**Comment by Bojun-Feng** [comment]
It seems like some of the settings in k8s may interfere with xinference. We solved the issue by switching out from k8s.

**Comment by WangxuP** [comment]
> It seems like some of the settings in k8s may interfere with xinference. We solved the issue by switching out from k8s.

help me ! How did you set k8s up?
