### ISSUE TITLE
模型已经下载完成，启动时出现ServerClosed错误

### ISSUE THREAD

**Issue by flyemagz** [xorbitsai/inference#887]
在http://127.0.0.1:9997/ui/页面中下载了chatglm2模型，但是一运行就会出现错误：
xoscar.errors.ServerClosed: [address=127.0.0.1:41671, pid=8096] Remote server 127.0.0.1:50110 closed
试了另外的模型也会出现同样的问题，请帮助解决，谢谢！

下面是比较完整的错误信息：
xoscar.errors.ServerClosed: Remote server 127.0.0.1:50110 closed
2024-01-11 21:41:43,446 xinference.core.worker 8096 WARNING  Process 127.0.0.1:50110 is down, create model.
2024-01-11 21:41:43,957 xinference.core.worker 8096 WARNING  Process 127.0.0.1:50110 is down, create model.
2024-01-11 21:41:44,468 xinference.core.worker 8096 WARNING  Process 127.0.0.1:50110 is down, create model.
2024-01-11 21:41:44,906 xinference.api.restful_api 4900 ERROR    [address=127.0.0.1:41671, pid=8096] Remote server 127.0.0.1:50110 closed
Traceback (most recent call last):
  File "F:\anaconda\envs\llm\lib\site-packages\xinference\api\restful_api.py", line 444, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 227, in send
    return self._process_result_message(result)
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\pool.py", line 368, in _run_coro
    return await coro
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "F:\anaconda\envs\llm\lib\site-packages\xinference\core\supervisor.py", line 573, in launch_builtin_model
    await _launch_one_model(rep_model_uid)
  File "F:\anaconda\envs\llm\lib\site-packages\xinference\core\supervisor.py", line 542, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "F:\anaconda\envs\llm\lib\site-packages\xinference\core\utils.py", line 35, in wrapped
    ret = await func(*args, **kwargs)
  File "F:\anaconda\envs\llm\lib\site-packages\xinference\core\worker.py", line 381, in launch_builtin_model
    await model_ref.load()
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 115, in _wait
    return await future
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\context.py", line 106, in _wait
    await asyncio.shield(future)
  File "F:\anaconda\envs\llm\lib\site-packages\xoscar\backends\core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: [address=127.0.0.1:41671, pid=8096] Remote server 127.0.0.1:50110 closed

**Comment by aresnow1** [comment]
大概率是模型超出显存了

**Comment by flyemagz** [comment]
> 大概率是模型超出显存了

谢谢回复！请问这个对硬件的最低要求是什么？如果没有gpu，是不是没法用了啊？

**Comment by Zxy1414** [comment]
我也有同样的问题 3080ti 16g 运行glm4-9b 报错

**Comment by zxr-Cr7** [comment]
2024-08-14 19:56:23,598 xinference.core.supervisor 4336 INFO     Xinference supervisor 127.0.0.1:27746 started
2024-08-14 19:56:23,668 xinference.model.image.core 4336 WARNING  Cannot find builtin image model spec: stable-diffusion-inpainting
2024-08-14 19:56:23,670 xinference.model.image.core 4336 WARNING  Cannot find builtin image model spec: stable-diffusion-2-inpainting
2024-08-14 19:56:23,671 xinference.model.image.core 4336 WARNING  Cannot find builtin image model spec: stable-diffusion-xl-inpainting
2024-08-14 19:56:23,698 xinference.core.worker 4336 INFO     Starting metrics export server at 127.0.0.1:None
2024-08-14 19:56:23,709 xinference.core.worker 4336 INFO     Checking metrics export server...
2024-08-14 19:56:29,175 xinference.core.worker 4336 INFO     Metrics server is started at: http://127.0.0.1:57096
2024-08-14 19:56:29,177 xinference.core.worker 4336 INFO     Xinference worker 127.0.0.1:27746 started
2024-08-14 19:56:29,181 xinference.core.worker 4336 INFO     Purge cache directory: C:\Users\zxr\.xinference\cache
2024-08-14 19:56:33,330 xinference.api.restful_api 22132 INFO     Starting Xinference at endpoint: http://127.0.0.1:9997
2024-08-14 19:56:33,611 uvicorn.error 22132 INFO     Started server process [22132]
2024-08-14 19:56:33,611 uvicorn.error 22132 INFO     Waiting for application startup.
2024-08-14 19:56:33,612 uvicorn.error 22132 INFO     Application startup complete.
2024-08-14 19:56:33,613 uvicorn.error 22132 INFO     Uvicorn running on http://127.0.0.1:9997 (Press CTRL+C to quit)
2024-08-14 19:56:35,538 uvicorn.access 22132 INFO     127.0.0.1:57108 - "GET / HTTP/1.1" 307
2024-08-14 19:56:35,983 uvicorn.access 22132 INFO     127.0.0.1:57108 - "GET /v1/cluster/auth HTTP/1.1" 200
2024-08-14 19:56:36,028 uvicorn.access 22132 INFO     127.0.0.1:57109 - "GET /v1/cluster/devices HTTP/1.1" 200
2024-08-14 19:56:36,088 uvicorn.access 22132 INFO     127.0.0.1:57111 - "GET /ui/manifest.json HTTP/1.1" 404
2024-08-14 19:56:37,229 uvicorn.access 22132 INFO     127.0.0.1:57108 - "GET /v1/model_registrations/LLM?detailed=true HTTP/1.1" 200
2024-08-14 19:56:44,722 uvicorn.access 22132 INFO     127.0.0.1:57123 - "GET /v1/engines/glm4-chat HTTP/1.1" 200
2024-08-14 19:57:28,756 xinference.model.llm.llm_family 4336 INFO     Caching from Modelscope: ZhipuAI/glm-4-9b-chat
2024-08-14 19:57:30,668 xinference.model.llm.llm_family 4336 INFO     Cache C:\Users\zxr\.xinference\cache\glm4-chat-pytorch-9b exists
2024-08-14 19:57:30,730 xinference.core.worker 4336 ERROR    Failed to load model glm4-chat-1-0
Traceback (most recent call last):
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\worker.py", line 850, in launch_builtin_model
    await model_ref.load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\model.py", line 295, in load
    self._model.load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\model\llm\pytorch\core.py", line 768, in load
    super().load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\model\llm\pytorch\core.py", line 302, in load
    raise ValueError(
ValueError: [address=127.0.0.1:57157, pid=12712] Only 8-bit quantization is supported if it is not linux system or cuda device
2024-08-14 19:57:30,774 xinference.api.restful_api 22132 ERROR    [address=127.0.0.1:57157, pid=12712] Only 8-bit quantization is supported if it is not linux system or cuda device
Traceback (most recent call last):
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\api\restful_api.py", line 857, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\supervisor.py", line 990, in launch_builtin_model
    await _launch_model()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\supervisor.py", line 954, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\supervisor.py", line 933, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\worker.py", line 850, in launch_builtin_model
    await model_ref.load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\model.py", line 295, in load
    self._model.load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\model\llm\pytorch\core.py", line 768, in load
    super().load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\model\llm\pytorch\core.py", line 302, in load
    raise ValueError(
ValueError: [address=127.0.0.1:57157, pid=12712] Only 8-bit quantization is supported if it is not linux system or cuda device
2024-08-14 19:57:30,781 uvicorn.access 22132 INFO     127.0.0.1:57134 - "POST /v1/models HTTP/1.1" 400
2024-08-14 19:58:19,322 xinference.model.llm.llm_family 4336 INFO     Caching from Modelscope: ZhipuAI/glm-4-9b-chat
2024-08-14 19:58:19,324 xinference.model.llm.llm_family 4336 INFO     Cache C:\Users\zxr\.xinference\cache\glm4-chat-pytorch-9b exists
2024-08-14 19:58:19,407 transformers.tokenization_utils_base 428 INFO     loading file tokenizer.model
2024-08-14 19:58:19,408 transformers.tokenization_utils_base 428 INFO     loading file added_tokens.json
2024-08-14 19:58:19,408 transformers.tokenization_utils_base 428 INFO     loading file special_tokens_map.json
2024-08-14 19:58:19,409 transformers.tokenization_utils_base 428 INFO     loading file tokenizer_config.json
2024-08-14 19:58:19,409 transformers.tokenization_utils_base 428 INFO     loading file tokenizer.json
2024-08-14 19:58:20,001 transformers.tokenization_utils_base 428 INFO     Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-08-14 19:58:20,003 transformers.configuration_utils 428 INFO     loading configuration file C:\Users\zxr\.xinference\cache\glm4-chat-pytorch-9b\config.json
2024-08-14 19:58:20,007 transformers.configuration_utils 428 INFO     loading configuration file C:\Users\zxr\.xinference\cache\glm4-chat-pytorch-9b\config.json
2024-08-14 19:58:20,008 transformers.configuration_utils 428 INFO     Model config ChatGLMConfig {
  "_name_or_path": "C:\\Users\\zxr\\.xinference\\cache\\glm4-chat-pytorch-9b",
  "add_bias_linear": false,
  "add_qkv_bias": true,
  "apply_query_key_layer_scaling": true,
  "apply_residual_connection_post_layernorm": false,
  "architectures": [
    "ChatGLMModel"
  ],
  "attention_dropout": 0.0,
  "attention_softmax_in_fp32": true,
  "auto_map": {
    "AutoConfig": "configuration_chatglm.ChatGLMConfig",
    "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
    "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
  },
  "bias_dropout_fusion": true,
  "classifier_dropout": null,
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "ffn_hidden_size": 13696,
  "fp32_residual_connection": false,
  "hidden_dropout": 0.0,
  "hidden_size": 4096,
  "kv_channels": 128,
  "layernorm_epsilon": 1.5625e-07,
  "model_type": "chatglm",
  "multi_query_attention": true,
  "multi_query_group_num": 2,
  "num_attention_heads": 32,
  "num_hidden_layers": 40,
  "num_layers": 40,
  "original_rope": true,
  "pad_token_id": 151329,
  "padded_vocab_size": 151552,
  "post_layer_norm": true,
  "rmsnorm": true,
  "rope_ratio": 500,
  "seq_length": 131072,
  "tie_word_embeddings": false,
  "torch_dtype": "float32",
  "transformers_version": "4.43.4",
  "use_cache": true,
  "vocab_size": 151552
}

2024-08-14 19:58:20,879 transformers.generation.configuration_utils 428 INFO     Generate config GenerationConfig {
  "eos_token_id": [
    151329,
    151336,
    151338
  ],
  "pad_token_id": 151329
}

2024-08-14 19:58:30,896 xinference.core.worker 4336 ERROR    Failed to load model glm4-chat-1-0
Traceback (most recent call last):
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\worker.py", line 850, in launch_builtin_model
    await model_ref.load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 115, in _wait
    return await future
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 127.0.0.1:57212 closed
2024-08-14 19:58:31,441 xinference.core.worker 4336 WARNING  Process 127.0.0.1:57212 is down.
2024-08-14 19:58:32,952 xinference.api.restful_api 22132 ERROR    [address=127.0.0.1:27746, pid=4336] Remote server 127.0.0.1:57212 closed
Traceback (most recent call last):
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\api\restful_api.py", line 857, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 231, in send
    return self._process_result_message(result)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 656, in send
    result = await self._run_coro(message.message_id, coro)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\pool.py", line 367, in _run_coro
    return await coro
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar\\core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar\\core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar\\core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar\\core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\supervisor.py", line 990, in launch_builtin_model
    await _launch_model()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\supervisor.py", line 954, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\supervisor.py", line 933, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar\\core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar\\core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xinference\core\worker.py", line 850, in launch_builtin_model
    await model_ref.load()
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 230, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\context.py", line 115, in _wait
    return await future
  File "D:\Anaconda_a\envs\xinference\lib\site-packages\xoscar\backends\core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: [address=127.0.0.1:27746, pid=4336] Remote server 127.0.0.1:57212 closed
2024-08-14 19:58:32,958 uvicorn.access 22132 INFO     127.0.0.1:57186 - "POST /v1/models HTTP/1.1" 500
请问我这是怎么回事？
