### ISSUE TITLE
chatglm3-32k 不能使用

### ISSUE THREAD

**Issue by kukuze** [xorbitsai/inference#900]
### Describe the bug
A100 80G python 3.11.7 使用web ui进行对话 报错

Traceback (most recent call last):
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xinference/api/restful_api.py", line 984, in stream_results
    async for item in iterator:
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/api.py", line 340, in __anext__
    return await self._actor_ref.__xoscar_next__(self._uid)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
    ^^^^^^^^^^^^^^^^^
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/api.py", line 431, in __xoscar_next__
    raise e
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/api.py", line 417, in __xoscar_next__
    r = await asyncio.to_thread(_wrapper, gen)
    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
      ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xoscar/api.py", line 402, in _wrapper
    return next(_gen)
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xinference/core/model.py", line 182, in _to_json_generator
    for v in gen:
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xinference/model/llm/utils.py", line 406, in _to_chat_completion_chunks
    for i, chunk in enumerate(chunks):
    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xinference/model/llm/pytorch/core.py", line 236, in generator_wrapper
    for completion_chunk, _ in generate_stream_chatglm(
    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
    ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xinference/model/llm/pytorch/utils.py", line 532, in generate_stream_chatglm
    eos_token_id.append(tokenizer.eos_token_id)
      ^^^^^^^^^^^^^^^^^
AttributeError: [address=0.0.0.0:40353, pid=106209] 'NoneType' object has no attribute 'append'
Traceback (most recent call last):
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/utils.py", line 623, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/chat_interface.py", line 437, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/gradio/utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xinference/core/chat_interface.py", line 124, in generate_wrapper
    for chunk in model.chat(
  File "/root/miniconda3/envs/python-3-11/lib/python3.11/site-packages/xinference/client/common.py", line 49, in streaming_response_iterator
    raise Exception(str(error))
Exception: [address=0.0.0.0:40353, pid=106209] 'NoneType' object has no attribute 'append'

**Comment by aresnow1** [comment]
这个已经修复合进主分支了，如果需要测试，可以通过以下命令安装：`pip install git+https://github.com/xorbitsai/inference.git `

**Comment by kukuze** [comment]
多谢回复

**Comment by hkshimotiong** [comment]
一样，今天遇到的
