### ISSUE TITLE
BUG: model exited abnormally

### ISSUE THREAD

**Issue by auxpd** [xorbitsai/inference#912]
### Describe the bug
(With LLM, embeddingModel, and RerankModel loaded) Whenever I make a call using dify, I always encounter the following error:

### To Reproduce

  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 649, in describe_model
    raise ValueError(f"Model not found in the model list, uid: {model_uid}")
ValueError: [address=0.0.0.0:64202, pid=35028] Model not found in the model list, uid: f593ad50-8e69-11ee-93cf-437b86dbc17b
2024-01-18 21:27:53,300 xinference.core.model 35043 ERROR    Model actor is out of memory.
Traceback (most recent call last):
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 99, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 215, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/model/rerank/core.py", line 109, in rerank
    similarity_scores = self._model.predict(sentence_combinations)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 272, in predict
    self.model.to(self._target_device)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2460, in to
    return super().to(*args, **kwargs)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1160, in to
    return self._apply(convert)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/nn/modules/module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/nn/modules/module.py", line 833, in _apply
    param_applied = fn(param)
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 16.00 MiB. GPU 0 has a total capacty of 23.69 GiB of which 6.94 MiB is free. Including non-PyTorch memory, this process has 2.13 GiB memory in use. Process 35123 has 21.54 GiB memory in use. Of the allocated memory 1.46 GiB is allocated by PyTorch, and 12.85 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
2024-01-18 21:27:53,362 xinference.api.restful_api 35010 ERROR    Remote server 0.0.0.0:43973 closed
Traceback (most recent call last):
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xinference/api/restful_api.py", line 776, in rerank
    scores = await model.rerank(
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 226, in send
    result = await self._wait(future, actor_ref.address, send_message)  # type: ignore
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 115, in _wait
    return await future
  File "/home/ml/miniconda3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/core.py", line 84, in _listen
    raise ServerClosed(
xoscar.errors.ServerClosed: Remote server 0.0.0.0:43973 closed
2024-01-18 21:27:53,582 xinference.core.worker 35028 WARNING  Process 0.0.0.0:43973 is down, create model.

**Comment by aresnow1** [comment]
CUDA out of memory, there's no enough VRAM for models.
