### ISSUE TITLE
chat_interface.py中修改"stream": False会报错.要如何取消stream?

### ISSUE THREAD

**Issue by c20000532** [xorbitsai/inference#922]
我要调用工具,所以要取消stream,修改的是131行.是应该从其他地方修改吗?

Traceback (most recent call last):
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\queueing.py", line 407, in call_prediction
    output = await route_utils.call_process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\blocks.py", line 1199, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\utils.py", line 623, in asyncgen_wrapper
    async for response in f(*args, **kwargs):
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\chat_interface.py", line 437, in _stream_fn
    first_response = await async_iteration(generator)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\utils.py", line 519, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\utils.py", line 512, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\gradio\utils.py", line 495, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "D:\miniconda3\envs\LLM\Lib\site-packages\xinference\core\chat_interface.py", line 135, in generate_wrapper
    assert isinstance(chunk, dict)

**Comment by codingl2k1** [comment]
建议调用工具使用RESTful API：
https://inference.readthedocs.io/en/latest/user_guide/client_api.html#openai-client-tool-calls
https://github.com/xorbitsai/inference/blob/main/examples/FunctionCall.ipynb

如果一定要改chat_interface.py的话，当stream is False时，model.chat返回的是一个completion result，并不是一个迭代器了。build_chat_vl_interface使用的就不是stream模式，具体可以参考：https://github.com/xorbitsai/inference/blob/main/xinference/core/chat_interface.py#L199

**Comment by codingl2k1** [comment]
如果有疑问，可以再打开这个issue。
