### ISSUE TITLE
执行 bge-large-zh-v1.5 失败，执行 bge-large-zh 成功

### ISSUE THREAD

**Issue by golangpkg** [xorbitsai/inference#950]
执行命令 embedding 报错了：

参考这个文档：
https://inference.readthedocs.io/zh-cn/latest/models/builtin/embedding/bge-large-zh-v1.5.html
 
执行命令报错，模型也下载完成了：
# xinference launch --model-name bge-large-zh-v1.5 --model-format pytorch --model-type embedding
Traceback (most recent call last):
  File "/root/miniconda3/bin/xinference", line 8, in <module>
    sys.exit(cli())
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/miniconda3/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/deploy/cmdline.py", line 624, in model_launch
    model_uid = client.launch_model(
  File "/root/miniconda3/lib/python3.10/site-packages/xinference/client/restful/restful_client.py", line 816, in launch_model
    raise RuntimeError(
RuntimeError: Failed to launch model, detail: [address=0.0.0.0:37369, pid=2424] Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/root/autodl-tmp/cache/bge-large-zh-v1.5'. Use `repo_type` argument if needed.

执行这个命令就没有问题：

xinference launch --model-name bge-large-zh --model-type embedding

**Comment by qinxuye** [comment]
@codingl2k1 这个是包版本的问题吗？

**Comment by aresnow1** [comment]
sentence-transformers 最新版本有 break change，需要安装小于 2.3.0 的版本，pip install "sentence-transformers<2.3.0"

**Comment by codingl2k1** [comment]
> @codingl2k1 这个是包版本的问题吗？

好像是一样的问题。最新的已经pin住了sentence-transformers版本号

**Comment by codingl2k1** [comment]
这个PR https://github.com/xorbitsai/inference/pull/941 中修复了，发版本前可以手动安装 pip install "sentence-transformers<2.3.0" 解决。

**Comment by qinxuye** [comment]
Should be addressed in v0.8.4.
