### ISSUE TITLE
 expected scalar type Half but found Float

### ISSUE THREAD

**Issue by 143heyan** [xorbitsai/inference#953]
use 4bit quantization，aquilachat2-34b and chatglm3-6b can be used ，but qwen-14b-chat error。

![image](https://github.com/xorbitsai/inference/assets/143150794/43670f14-fc63-4324-ac44-f113b6b17a93)
![image](https://github.com/xorbitsai/inference/assets/143150794/08712a81-02a5-4004-8ac7-a371a55b5f35)
![image](https://github.com/xorbitsai/inference/assets/143150794/0da0f0dd-bfe0-4aac-ae87-075f01e93b9d)
2024-01-31 02:43:11,531 xinference.api.restful_api 48158 ERROR    [address=0.0.0.0:44655, pid=58721] expected scalar type Half but found Float
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1207, in create_chat_completion
    data = await model.chat(prompt, system_prompt, chat_history, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/utils.py", line 43, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 78, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 462, in _wrapper
    r = await func(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 369, in chat
    response = await self._call_wrapper(
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 102, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 326, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 466, in chat
    c = self.generate(full_prompt, generate_config)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/core.py", line 267, in generate
    for completion_chunk, completion_usage in generate_stream(
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/llm/pytorch/utils.py", line 155, in generate_stream
    out = model(torch.as_tensor([input_ids], device=device), use_cache=True)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-pytorch-14b/modeling_qwen.py", line 1108, in forward
    transformer_outputs = self.transformer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-pytorch-14b/modeling_qwen.py", line 938, in forward
    outputs = block(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-pytorch-14b/modeling_qwen.py", line 639, in forward
    attn_outputs = self.attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-pytorch-14b/modeling_qwen.py", line 564, in forward
    attn_output, attn_weight = self._attn(
  File "/root/.cache/huggingface/modules/transformers_modules/qwen-14b-chat-pytorch-14b/modeling_qwen.py", line 319, in _attn
    attn_weights = torch.matmul(query, key.transpose(-1, -2))
RuntimeError: [address=0.0.0.0:44655, pid=58721] expected scalar type Half but found Float

**Comment by qinxuye** [comment]
We are investigating qwen 14b related issue.

**Comment by simmoncn** [comment]
+1, also meet the same issue.
