### ISSUE TITLE
Builtin model, LLaMA2 Chat 70B fails to load: tensor has wrong shape

### ISSUE THREAD

**Issue by slobentanzer** [xorbitsai/inference#971]
### Describe the bug
Trying to start any of the 70B builtin LLaMA2 models (ggmlv3) through the Python client leads to the `llama_model_load: error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape; expected  8192,  8192, got  8192,  1024,     1,     1` error. I tried with most quantisations, same result. I am on Apple Silicon (M3 Pro Max) if that matters. The other LLaMA2 Chat sizes work as expected.

### To Reproduce
To help us to reproduce this bug, please provide information below:

1. Your Python version.
3.10

3. The version of xinference you use.
xinference, version 0.8.1

6. Full stack of the error.
```
2024-02-02 11:21:29,691 xinference.core.supervisor 77077 INFO     Xinference supervisor 127.0.0.1:29744 started
2024-02-02 11:21:29,697 xinference.core.worker 77077 INFO     Starting metrics export server at 127.0.0.1:None
2024-02-02 11:21:29,697 xinference.core.worker 77077 INFO     Checking metrics export server...
2024-02-02 11:21:31,103 xinference.core.worker 77077 INFO     Metrics server is started at: http://127.0.0.1:60390
2024-02-02 11:21:31,104 xinference.core.worker 77077 INFO     Xinference worker 127.0.0.1:29744 started
2024-02-02 11:21:31,104 xinference.core.worker 77077 INFO     Purge cache directory: /Users/slobentanzer/.xinference/cache
2024-02-02 11:21:32,147 xinference.api.restful_api 77072 INFO     Starting Xinference at endpoint: http://127.0.0.1:9997
2024-02-02 11:21:57,790 xinference.model.llm.llm_family 77077 INFO     Caching from Hugging Face: TheBloke/Llama-2-70B-Chat-GGML
llama_model_loader: loaded meta data with 19 key-value pairs and 723 tensors from /Users/slobentanzer/.xinference/cache/llama-2-chat-ggufv2-70b/llama-2-chat.q4_K_M.ggufv2 (version GGUF V2)
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = llama-2-70b-chat.ggmlv3.q4_K_M.bin
llama_model_loader: - kv   2:                        general.description str              = converted from legacy GGJTv3 MOSTLY_Q...
llama_model_loader: - kv   3:                          general.file_type u32              = 15
llama_model_loader: - kv   4:                       llama.context_length u32              = 2048
llama_model_loader: - kv   5:                     llama.embedding_length u32              = 8192
llama_model_loader: - kv   6:                          llama.block_count u32              = 80
llama_model_loader: - kv   7:                  llama.feed_forward_length u32              = 28672
llama_model_loader: - kv   8:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   9:                 llama.attention.head_count u32              = 64
llama_model_loader: - kv  10:              llama.attention.head_count_kv u32              = 64
llama_model_loader: - kv  11:     llama.attention.layer_norm_rms_epsilon f32              = 0.000005
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama
llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32000]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...
llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32000]   = [0.000000, 0.000000, 0.000000, 0.0000...
llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32000]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:            tokenizer.ggml.unknown_token_id u32              = 0
llama_model_loader: - kv  17:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  18:                tokenizer.ggml.eos_token_id u32              = 2
llama_model_loader: - type  f32:  161 tensors
llama_model_loader: - type q4_K:  481 tensors
llama_model_loader: - type q6_K:   81 tensors
llm_load_vocab: special tokens definition check successful ( 259/32000 ).
llm_load_print_meta: format           = GGUF V2
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = SPM
llm_load_print_meta: n_vocab          = 32000
llm_load_print_meta: n_merges         = 0
llm_load_print_meta: n_ctx_train      = 2048
llm_load_print_meta: n_embd           = 8192
llm_load_print_meta: n_head           = 64
llm_load_print_meta: n_head_kv        = 64
llm_load_print_meta: n_layer          = 80
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 1
llm_load_print_meta: n_embd_k_gqa     = 8192
llm_load_print_meta: n_embd_v_gqa     = 8192
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 5.0e-06
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: n_ff             = 28672
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 10000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 2048
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: model type       = 65B
llm_load_print_meta: model ftype      = Q4_K - Medium
llm_load_print_meta: model params     = 68.98 B
llm_load_print_meta: model size       = 38.54 GiB (4.80 BPW) 
llm_load_print_meta: general.name     = llama-2-70b-chat.ggmlv3.q4_K_M.bin
llm_load_print_meta: BOS token        = 1 '<s>'
llm_load_print_meta: EOS token        = 2 '</s>'
llm_load_print_meta: UNK token        = 0 '<unk>'
llm_load_print_meta: LF token         = 13 '<0x0A>'
llm_load_tensors: ggml ctx size =    0.55 MiB
llama_model_load: error loading model: create_tensor: tensor 'blk.0.attn_k.weight' has wrong shape; expected  8192,  8192, got  8192,  1024,     1,     1
llama_load_model_from_file: failed to load model
AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | 
2024-02-02 11:21:57,829 xinference.core.worker 77077 ERROR    Failed to load model e471d00e-c1b4-11ee-b83a-7ef57b5cf78c-1-0
Traceback (most recent call last):
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/ggml/llamacpp.py", line 191, in load
    self._llm = Llama(
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/llama_cpp/llama.py", line 318, in __init__
    self._n_vocab = self.n_vocab()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/llama_cpp/llama.py", line 1655, in n_vocab
    return self._model.n_vocab()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/llama_cpp/_internals.py", line 67, in n_vocab
    assert self.model is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 476, in launch_builtin_model
    await model_ref.load()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 238, in load
    self._model.load()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/ggml/llamacpp.py", line 197, in load
    raise RuntimeError(f"Load model {self.model_family.model_name} failed")
RuntimeError: [address=127.0.0.1:60404, pid=77106] Load model llama-2-chat failed
2024-02-02 11:21:57,841 xinference.api.restful_api 77072 ERROR    [address=127.0.0.1:60404, pid=77106] Load model llama-2-chat failed
Traceback (most recent call last):
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/ggml/llamacpp.py", line 191, in load
    self._llm = Llama(
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/llama_cpp/llama.py", line 318, in __init__
    self._n_vocab = self.n_vocab()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/llama_cpp/llama.py", line 1655, in n_vocab
    return self._model.n_vocab()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/llama_cpp/_internals.py", line 67, in n_vocab
    assert self.model is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/api/restful_api.py", line 603, in launch_model
    model_uid = await (await self._get_supervisor_ref()).launch_builtin_model(
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 611, in launch_builtin_model
    await _launch_model()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 576, in _launch_model
    await _launch_one_model(rep_model_uid)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/supervisor.py", line 560, in _launch_one_model
    await worker_ref.launch_builtin_model(
  File "xoscar/core.pyx", line 284, in __pyx_actor_method_wrapper
    async with lock:
  File "xoscar/core.pyx", line 287, in xoscar.core.__pyx_actor_method_wrapper
    result = await result
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/utils.py", line 35, in wrapped
    ret = await func(*args, **kwargs)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/worker.py", line 476, in launch_builtin_model
    await model_ref.load()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 657, in send
    result = await self._run_coro(message.message_id, coro)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/backends/pool.py", line 368, in _run_coro
    return await coro
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 524, in xoscar.core._BaseActor.__on_receive__
    result = func(*args, **kwargs)
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/core/model.py", line 238, in load
    self._model.load()
  File "/Users/slobentanzer/miniforge3/envs/xinference/lib/python3.10/site-packages/xinference/model/llm/ggml/llamacpp.py", line 197, in load
    raise RuntimeError(f"Load model {self.model_family.model_name} failed")
RuntimeError: [address=127.0.0.1:60404, pid=77106] Load model llama-2-chat failed
```
7. Minimized code to reproduce the error.

```
from xinference.client import Client

client = Client(base_url="http://localhost:9997")

client.launch_model(
            model_name="llama-2-chat",
            model_size_in_billions=70,
            model_format="ggmlv3",
            quantization="q4_K_M",
        )
```

Thanks!

**Comment by aresnow1** [comment]
We download legacy format ggmlv3 format which may not compatible with latest llamacpp, will update next version.
