### ISSUE TITLE
custom need support tool calls

### ISSUE THREAD

**Issue by xs818818** [xorbitsai/inference#976]
I lora a qwen-chat to support tool calls,can i help you to result openai.BadRequestError: Error code: 400 - {'detail': "Only ['chatglm3', 'gorilla-openfunctions-v1', 'qwen-chat'] support tool calls"}

**Comment by aresnow1** [comment]
Could you paste all error messages or logs?

**Comment by xs818818** [comment]
Traceback (most recent call last):
  File "test_tools.py", line 80, in <module>
    result = client.chat.completions.create(messages=messages, model="tools",temperature=0.75, tools=tools,tool_choice="auto")
  File "/home/xs/.local/lib/python3.8/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/home/xs/.local/lib/python3.8/site-packages/openai/resources/chat/completions.py", line 648, in create
    return self._post(
  File "/home/xs/.local/lib/python3.8/site-packages/openai/_base_client.py", line 1179, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/xs/.local/lib/python3.8/site-packages/openai/_base_client.py", line 868, in request
    return self._request(
  File "/home/xs/.local/lib/python3.8/site-packages/openai/_base_client.py", line 959, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'detail': "Only ['chatglm3', 'gorilla-openfunctions-v1', 'qwen-chat'] support tool calls"}

**Comment by aresnow1** [comment]
Any logs of xinference service?

**Comment by aresnow1** [comment]
Have you chosen qwen-chat when register model?

**Comment by xs818818** [comment]
2024-02-03 15:17:13,533 xinference.model.llm.llm_family 45 INFO     Caching from URI: /root/llm_models/tools
2024-02-03 15:17:13,533 xinference.model.llm.llm_family 45 INFO     Cache /root/llm_models/tools exists
2024-02-03 15:17:13,537 xinference.model.llm.vllm.core 148 INFO     Loading tools with following model config: {'tokenizer_mode': 'auto', 'trust_remote_code': True, 'tensor_parallel_size': 1, 'block_size': 16, 'swap_space': 4, 'gpu_memory_utilization': 0.9, 'max_num_seqs': 256, 'quantization': None}
INFO 02-03 15:17:13 llm_engine.py:70] Initializing an LLM engine with config: model='/root/llm_models/tools', tokenizer='/root/llm_models/tools', tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, enforce_eager=False, seed=0)
WARNING 02-03 15:17:14 tokenizer.py:62] Using a slow tokenizer. This might cause a significant slowdown. Consider using a fast tokenizer instead.
INFO 02-03 15:17:17 llm_engine.py:275] # GPU blocks: 620, # CPU blocks: 1365
INFO 02-03 15:17:18 model_runner.py:501] Capturing the model for CUDA graphs. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI.
INFO 02-03 15:17:18 model_runner.py:505] CUDA graphs can take additional 1~3 GiB memory per GPU. If you are running out of memory, consider decreasing `gpu_memory_utilization` or enforcing eager mode.
INFO 02-03 15:17:23 model_runner.py:547] Graph capturing finished in 5 secs.

**Comment by xs818818** [comment]
{"version": 1, "context_length": 2048, "model_name": "tools", "model_lang": ["en", "zh"], "model_ability": ["chat"], "model_description": "This is a custom model description.", "model_family": "qwen-chat", "model_specs": [{"model_format": "pytorch", "model_size_in_billions": 2, "quantizations": ["4-bit", "8-bit", "none"], "model_id": "", "model_hub": "huggingface", "model_uri": "/root/llm_models/tools", "model_revision": null}], "prompt_style": {"style_name": "QWEN", "system_prompt": "You are a helpful assistant.", "roles": ["user", "assistant"], "intra_message_sep": "\n", "inter_message_sep": "", "stop": ["<|endoftext|>", "<|im_start|>", "<|im_end|>"], "stop_token_ids": [151643, 151644, 151645]}}

**Comment by aresnow1** [comment]
Try to disable vllm and test again with command `XINFERENCE_DISABLE_VLLM=1 xinference-local -H 0.0.0.0 --log-level=debug`.

**Comment by xs818818** [comment]
How to use docker to set XINFERENCE_DISABLE_VLLM=1

**Comment by xs818818** [comment]
docker run --rm --name test -v /home/xs/xinference/date:/root/.xinference -v /home/xs/xinference/huggingface:/root/.cache/huggingface -v /home/xs/xinference/modelscope:/root/.cache/modelscope -v /home/xs/AI/llm_models:/root/llm_models -p 9997:9997 --gpus all xprobe/xinference:latest xinference-local XINFERENCE_DISABLE_VLLM=1 -H 0.0.0.0 --log-level=debug
Got unexpected extra argument (XINFERENCE_DISABLE_VLLM=1)

**Comment by aresnow1** [comment]
refer to https://inference.readthedocs.io/en/latest/getting_started/using_docker_image.html#image-usage.
`docker run -e XINFERENCE_DISABLE_VLLM =1 ...`

**Comment by xs818818** [comment]
2024-02-03 15:32:02,831 xinference.core.supervisor 45 DEBUG    Enter get_status, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>,), kwargs: {}
2024-02-03 15:32:02,832 xinference.core.supervisor 45 DEBUG    Leave get_status, elapsed time: 0 s
2024-02-03 15:32:04,129 xinference.api.restful_api 1 INFO     Starting Xinference at endpoint: http://0.0.0.0:9997
2024-02-03 15:32:04,506 xinference.core.supervisor 45 DEBUG    Enter list_models, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>,), kwargs: {}
2024-02-03 15:32:04,506 xinference.core.worker 45 DEBUG    Enter list_models, args: (<xinference.core.worker.WorkerActor object at 0x7ff7053d4a90>,), kwargs: {}
2024-02-03 15:32:04,507 xinference.core.worker 45 DEBUG    Leave list_models, elapsed time: 0 s
2024-02-03 15:32:04,507 xinference.core.supervisor 45 DEBUG    Leave list_models, elapsed time: 0 s
2024-02-03 15:32:06,245 xinference.core.supervisor 45 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>, 'LLM'), kwargs: {'detailed': True}
2024-02-03 15:32:06,285 xinference.core.supervisor 45 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-02-03 15:32:07,039 xinference.core.supervisor 45 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>, 'rerank'), kwargs: {'detailed': False}
2024-02-03 15:32:07,040 xinference.core.supervisor 45 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-02-03 15:32:07,045 xinference.core.supervisor 45 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>, 'embedding'), kwargs: {'detailed': False}
2024-02-03 15:32:07,045 xinference.core.supervisor 45 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-02-03 15:32:07,050 xinference.core.supervisor 45 DEBUG    Enter list_model_registrations, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>, 'LLM'), kwargs: {'detailed': False}
2024-02-03 15:32:07,050 xinference.core.supervisor 45 DEBUG    Leave list_model_registrations, elapsed time: 0 s
2024-02-03 15:32:07,058 xinference.core.supervisor 45 DEBUG    Enter get_model_registration, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>, 'LLM', 'tools'), kwargs: {}
2024-02-03 15:32:07,058 xinference.core.supervisor 45 DEBUG    Leave get_model_registration, elapsed time: 0 s
2024-02-03 15:32:15,697 xinference.core.supervisor 45 DEBUG    Enter launch_builtin_model, model_uid: tools, model_name: tools, model_size: 2, model_format: pytorch, quantization: none, replica: 1
2024-02-03 15:32:15,697 xinference.core.worker 45 DEBUG    Enter get_model_count, args: (<xinference.core.worker.WorkerActor object at 0x7ff7053d4a90>,), kwargs: {}
2024-02-03 15:32:15,698 xinference.core.worker 45 DEBUG    Leave get_model_count, elapsed time: 0 s
2024-02-03 15:32:15,698 xinference.core.worker 45 DEBUG    Enter launch_builtin_model, args: (<xinference.core.worker.WorkerActor object at 0x7ff7053d4a90>,), kwargs: {'model_uid': 'tools-1-0', 'model_name': 'tools', 'model_size_in_billions': 2, 'model_format': 'pytorch', 'quantization': 'none', 'model_type': 'LLM', 'n_gpu': 'auto', 'request_limits': None}
2024-02-03 15:32:15,698 xinference.core.worker 45 DEBUG    GPU selected: [0] for model tools-1-0
2024-02-03 15:32:18,331 xinference.model.llm.llm_family 45 INFO     Caching from URI: /root/llm_models/tools
2024-02-03 15:32:18,331 xinference.model.llm.llm_family 45 INFO     Cache /root/llm_models/tools exists
2024-02-03 15:32:18,331 xinference.model.llm.core 45 DEBUG    Launching tools-1-0 with PytorchChatModel
Loading checkpoint shards: 100%|█████████████████| 2/2 [00:00<00:00,  2.19it/s]
2024-02-03 15:32:22,609 xinference.model.llm.pytorch.core 64 DEBUG    Model Memory: 3675230336
2024-02-03 15:32:22,610 xinference.core.worker 45 DEBUG    Leave launch_builtin_model, elapsed time: 6 s
2024-02-03 15:32:22,656 xinference.core.supervisor 45 DEBUG    Enter list_models, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>,), kwargs: {}
2024-02-03 15:32:22,656 xinference.core.worker 45 DEBUG    Enter list_models, args: (<xinference.core.worker.WorkerActor object at 0x7ff7053d4a90>,), kwargs: {}
2024-02-03 15:32:22,656 xinference.core.worker 45 DEBUG    Leave list_models, elapsed time: 0 s
2024-02-03 15:32:22,656 xinference.core.supervisor 45 DEBUG    Leave list_models, elapsed time: 0 s
2024-02-03 15:32:36,533 xinference.core.supervisor 45 DEBUG    Enter get_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>, 'tools'), kwargs: {}
2024-02-03 15:32:36,534 xinference.core.worker 45 DEBUG    Enter get_model, args: (<xinference.core.worker.WorkerActor object at 0x7ff7053d4a90>,), kwargs: {'model_uid': 'tools-1-0'}
2024-02-03 15:32:36,534 xinference.core.worker 45 DEBUG    Leave get_model, elapsed time: 0 s
2024-02-03 15:32:36,534 xinference.core.supervisor 45 DEBUG    Leave get_model, elapsed time: 0 s
2024-02-03 15:32:36,535 xinference.core.supervisor 45 DEBUG    Enter describe_model, args: (<xinference.core.supervisor.SupervisorActor object at 0x7ff7053d4ae0>, 'tools'), kwargs: {}
2024-02-03 15:32:36,535 xinference.core.worker 45 DEBUG    Enter describe_model, args: (<xinference.core.worker.WorkerActor object at 0x7ff7053d4a90>,), kwargs: {'model_uid': 'tools-1-0'}
2024-02-03 15:32:36,535 xinference.core.worker 45 DEBUG    Leave describe_model, elapsed time: 0 s
2024-02-03 15:32:36,535 xinference.core.supervisor 45 DEBUG    Leave describe_model, elapsed time: 0 s
